Repository opencrvs/opencrvs-core, pull requests merged in 2020-03, with the labels that each got.

#1517 [ocrvs-2689] Fix for null issues of missing names on workqueues
  packages/client/src/utils/data-formatting.ts
Labels: 👌LGTM

#1516 [ocrvs 2684 & 2685] Adding meaningful columns on registration export
  README.md
  infrastructure/export-registrations.sh
  packages/gateway/src/routes/registrations/export-route.ts
Labels: 👌LGTM

#1521 Updated registration home query for external validation work queue data
  packages/client/src/ListSyncController.ts
  packages/client/src/applications/index.ts
  packages/client/src/views/RegistrationHome/queries.ts
  packages/client/src/views/RegistrationHome/tabs/review/reviewTab.test.tsx
  packages/client/typings/window.d.ts
Labels: :nail_care:Waiting For Review, 👌LGTM

#1524 Ocrvs 2700 fix location search performance
  packages/client/src/views/Performance/MonthlyReports.test.tsx
  packages/client/src/views/Performance/MonthlyReports.tsx
  packages/client/src/views/Performance/ReportList.test.tsx
  packages/client/src/views/Performance/ReportList.tsx
Labels: :nail_care:Waiting For Review

#1522 Ocrvs 2697 External validation tab
  packages/client/src/applications/index.test.ts
  packages/client/src/applications/index.ts
  packages/client/src/i18n/messages/views/registrarHome.ts
  packages/client/src/setupTests.ts
  packages/client/src/views/RegistrationHome/RegistrationHome.test.tsx
  packages/client/src/views/RegistrationHome/RegistrationHome.tsx
  packages/client/src/views/RegistrationHome/tabs/externalValidation/externalValidationTab.test.tsx
  packages/client/src/views/RegistrationHome/tabs/externalValidation/externalValidationTab.tsx
  packages/client/src/views/RegistrationHome/tabs/print/printTab.test.tsx
  packages/client/src/views/RegistrationHome/tabs/reject/rejectTab.test.tsx
  packages/client/src/views/RegistrationHome/tabs/review/reviewTab.test.tsx
  packages/components/src/components/buttons/ListItemAction.tsx
  packages/components/src/components/icons/StatusWaitingValidation.md
  packages/components/src/components/icons/StatusWaitingValidation.tsx
  packages/components/src/components/icons/index.ts
Labels: :nail_care:Waiting For Review

#1527 Fixed export registrations count issues
  infrastructure/export-registrations.sh
  packages/gateway/src/features/registration/root-resolvers.ts
Labels: :boom: Hot Fixes

#1529 Ocrvs 2710 BulletList library component
  packages/components/src/components/typography/BulletList.md
  packages/components/src/components/typography/BulletList.tsx
  packages/components/src/components/typography/index.ts
Labels: :hourglass_flowing_sand: Waiting for CI, :nail_care:Waiting For Review

#1518 Bootstrap chatbot user & mediator
  docker-compose.dev-deps.yml
  infrastructure/openhim-base-config.json
  packages/auth/src/constants.ts
  packages/auth/src/features/authenticate/handler.ts
  packages/client/src/i18n/messages/user.ts
  packages/client/src/tests/languages.json
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/utils/userUtils.ts
Labels: :nail_care:Waiting For Review

#1542 Ocrvs 2556 update BRN validation
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/utils/validate.test.ts
  packages/client/src/utils/validate.ts
Labels: :hourglass_flowing_sand: Waiting for CI, :nail_care:Waiting For Review

#1530 Ocrvs 2711 Create eventinfo component
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/views/eventInfo.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/EventInfo/EventInfo.test.tsx
  packages/client/src/views/EventInfo/EventInfo.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.test.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/components/src/components/typography/BulletList.tsx
Labels: :nail_care:Waiting For Review

#1546 [OCRVS-2714] Load user form definition
  packages/client/src/forms/user/fieldDefinitions/user-section.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/offline/selectors.ts
  packages/client/src/tests/register.json
  packages/client/src/tests/util.tsx
  packages/client/src/user/userReducer.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SysAdmin/tabs/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/tabs/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/tabs/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/tabs/user/userCreation/UserForm.test.tsx
  packages/client/src/views/SysAdmin/tabs/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/tabs/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/SysAdmin/utils.ts
Labels: :hourglass_flowing_sand: Waiting for CI, :nail_care:Waiting For Review

#1526 Added security header on nginx config
  infrastructure/nginx-default.conf
Labels: :nail_care:Waiting For Review

#1548 [ocrvs-2524 & 2525 & 2761] Birth estimation table in performance ui, related backend changes and updated estimation formula
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/Performance/Report.test.tsx
  packages/client/src/views/Performance/Report.tsx
  packages/client/src/views/Performance/metricsQuery.ts
  packages/client/src/views/Performance/reports/Estimated45DayRegistrationReports.tsx
  packages/client/src/views/Performance/reports/index.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/metrics/root-resolvers.test.ts
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/metrics/package.json
  packages/metrics/src/features/metrics/constants.ts
  packages/metrics/src/features/metrics/handler.test.ts
  packages/metrics/src/features/metrics/handler.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/metrics/utils.test.ts
  packages/metrics/src/features/metrics/utils.ts
  yarn.lock
Labels: 👌LGTM

#1549 [ocrvs-2716] update user mutation, user-management endpoint and notification sms for new username
  .travis.yml
  packages/client/src/forms/user/fieldDefinitions/mutation/mutations.ts
  packages/client/src/views/SysAdmin/tabs/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/SysAdmin/utils.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/notification/src/config/routes.ts
  packages/notification/src/features/sms/user-handler.test.ts
  packages/notification/src/features/sms/user-handler.ts
  packages/notification/src/i18n/locales/bn.json
  packages/notification/src/i18n/locales/en.json
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/updateUser/handler.test.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
Labels: 👌LGTM
