Repository opencrvs/opencrvs-core, pull requests merged in 2020-02, with the labels that each got.

#1512 [ocrvs 2682 & 2683] added timeLogged type resolver and adjusted export query
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/routes/registrations/export-route.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/getTimeLogged/constants.ts
  packages/metrics/src/features/getTimeLogged/handler.test.ts
  packages/metrics/src/features/getTimeLogged/handler.ts
  packages/metrics/src/features/getTimeLogged/utils.ts
Labels: :hourglass_flowing_sand: Waiting for CI, :nail_care:Waiting For Review, 👌LGTM

#1509 Ocrvs 2681 Attachment link in preview page
  packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentPreview.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/components/src/components/interface/ViewData/DataSection.tsx
Labels: :hourglass_flowing_sand: Waiting for CI, 👌LGTM

#1506 [OCRVS-2621] Validation queue cleaner
  infrastructure/openhim-base-config.json
Labels: :hourglass_flowing_sand: Waiting for CI, :nail_care:Waiting For Review

#1510 Fixes OCRVS-2590 and issue with no external validation setup
  packages/workflow/src/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.ts
Labels: :hourglass_flowing_sand: Waiting for CI, :nail_care:Waiting For Review

#1513 Ocrvs 2371 save confirmation modal
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/register.ts
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: :nail_care:Waiting For Review

#1514 Setup e2e on zambia
  .travis.yml
  Dockerfile
  README.md
  deploy.sh
  dev.sh
  docker-compose.ci.yml
  docker-compose.deploy.yml
  docker-compose.dev.yml
  docker-compose.yml
  infrastructure/build-and-test-e2e-on-staging.sh
  infrastructure/build-and-test-e2e.sh
  infrastructure/server-setup/README.md
  infrastructure/server-setup/bgd-prod.ini
  infrastructure/server-setup/example.ini
  infrastructure/server-setup/pen.ini
  infrastructure/server-setup/stg.ini
  infrastructure/server-setup/zmb-staging.ini
  infrastructure/traefik.toml
  package.json
  packages/e2e/.gitignore
  packages/e2e/README.md
  packages/e2e/cypress.json
  packages/e2e/cypress/fixtures/example.json
  packages/e2e/cypress/integration/birth.spec.ts
  packages/e2e/cypress/integration/certificate.spec.ts
  packages/e2e/cypress/integration/death.spec.ts
  packages/e2e/cypress/integration/menu.spec.ts
  packages/e2e/cypress/integration/performance.spec.ts
  packages/e2e/cypress/integration/reports.spec.ts
  packages/e2e/cypress/integration/search.spec.ts
  packages/e2e/cypress/integration/user.spec.ts
  packages/e2e/cypress/plugins/index.js
  packages/e2e/cypress/support/commands.js
  packages/e2e/cypress/support/fetch_to_xhr.js
  packages/e2e/cypress/support/index.d.ts
  packages/e2e/cypress/support/index.js
  packages/e2e/package.json
  packages/e2e/tsconfig.json
  yarn.lock
Labels: :nail_care:Waiting For Review
