Repository opencrvs/opencrvs-core, pull requests merged in 2020-06, with the labels that each got.

#1741 Ocrvs 1694 Location picker
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/components/LocationPicker.tsx
  packages/client/src/tests/util.tsx
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/Performance/FieldAgentList.test.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/Performance/RegistrationRates.test.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/client/src/views/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/Performance/WorkflowStatus.tsx
Labels: 💅 Waiting For Review

#1745 Export csv from month wise report list
  packages/client/src/views/Performance/MonthlyReports.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
  packages/gateway/src/routes/metrics/export-all-route.ts
  packages/gateway/src/routes/metrics/montly-export-route.ts
  packages/metrics/package.json
  packages/metrics/src/api.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/export/handler.ts
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1748 Ocvrs 1692 ListTable mouse over effect
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/Performance/WorkflowStatus.tsx
  packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: ⏳ Waiting for CI, 💅 Waiting For Review

#1747 Filtered report list based month picker value
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/utils.ts
Labels: 💅 Waiting For Review

#1759 Ocrvs 1716 Operational dashboard style amends
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/PerformanceContentWrapper.tsx
  packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.tsx
  packages/client/src/views/Performance/utils.ts
Labels: ⏳ Waiting for CI, 💅 Waiting For Review

#1761 Ocrvs 1733 Father DoB validation fixes
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#1749 Bug fixes
  packages/client/src/components/form/FetchButton.tsx
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 💅 Waiting For Review

#1765 Hotfix: Subpage content width and list table height
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 💅 Waiting For Review, 💥 Hot Fixes

#1766 [OCRVS-1706] Plain time duration tool-tip
  packages/client/src/DateUtils.test.ts
  packages/client/src/DateUtils.ts
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: ⏳ Waiting for CI, 💅 Waiting For Review

#1767 UI changes to OpsDash Reg Rate Widget as per issue 1715
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/RegistrationRatesReport.tsx
  packages/components/src/components/fonts.ts
Labels: 💅 Waiting For Review

#1774 [OCRVS-1758] Registration line chart mobile view
  packages/client/src/components/charts/RegRatesLineChart.tsx
  packages/client/src/views/SysAdmin/Performance/RegistrationRates.test.tsx
  packages/components/src/components/charts/TriLineChart.tsx
Labels: 💅 Waiting For Review

#1773 Ocrvs 1750 Responsive location picker
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/components/LocationPicker.tsx
Labels: 💅 Waiting For Review

#1764 [OCRVS-1719] Status window responsiveness
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
Labels: 💅 Waiting For Review

#1779 [OCRVS-1758] Report filter mobile view
  packages/client/src/views/SysAdmin/Performance/utils.ts
Labels: 💅 Waiting For Review

#1780 Ocrvs 1640 Responsive time picker
  packages/client/src/components/DateRangePicker.test.tsx
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/components/LocationPicker.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/SysAdmin/Performance/OperationalReport.test.tsx
  packages/client/src/views/SysAdmin/Performance/RegistrationRates.test.tsx
Labels: 💅 Waiting For Review

#1782 [1698, 1670, 1701 & 1702] Performance and Team screen for registrar and registration agents
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/offline/selectors.ts
  packages/client/src/tests/register.json
  packages/client/src/tests/util.tsx
  packages/client/src/utils/locationUtils.test.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/ApplicationsStartedReport.test.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/StatusWiseApplicationCountView.test.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/StatusWiseApplicationCountView.tsx
  packages/client/src/views/SysAdmin/Team/TeamSearch.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.test.tsx
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/utils/index.ts
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1781 ListTable fixed width and other Subpage / misc fixes
  infrastructure/server-setup/README.md
  infrastructure/server-setup/playbook.yml
  packages/client/src/components/interface/ApplicationStatusWindow.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/RegistrationRates.tsx
  packages/client/src/views/SysAdmin/Performance/Report.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/reports/CertificationPaymentReports.tsx
  packages/client/src/views/SysAdmin/Performance/reports/Estimated45DayRegistrationReports.tsx
  packages/client/src/views/SysAdmin/Performance/reports/GenderBasisReports.tsx
  packages/client/src/views/SysAdmin/Performance/reports/TimeFrameReports.tsx
  packages/client/src/views/SysAdmin/Performance/reports/registrationRates/Within45DaysTable.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 💅 Waiting For Review

#1784 Ocrvs 1676 1689 1708 bug fixes
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/components/form/SearchField.test.tsx
  packages/client/src/components/form/SearchField.tsx
  packages/client/src/components/form/__snapshots__/SearchField.test.tsx.snap
  packages/client/src/forms/index.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/child-mappings.test.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/tests/register.json
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
Labels: 💅 Waiting For Review

#1785 1760 - Updated user creation flow to skip the selected office
  packages/client/src/App.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/tests/register.json
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
Labels: 💅 Waiting For Review

#1797 [OCRVS-1739] Fix application case tracker copy
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/tests/languages.json
  packages/client/src/views/Home/Details.tsx
  packages/client/src/views/RegistrationHome/RowHistoryView.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review
