Repository opencrvs/opencrvs-core, pull requests merged in 2020-12, with the labels that each got.

#2061 Ocrvs 2060 Fixes for UI issues
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
Labels: 👌LGTM

#2043 Ocrvs 1786 Dropdown fixes
  packages/client/src/views/SysAdmin/Performance/PerformanceSelect.tsx
Labels: 👌LGTM

#2058 Ocrvs 2054 Section to section transition indicator
  packages/client/src/applications/index.ts
  packages/client/src/tests/util.tsx
  packages/client/src/views/RegisterForm/ApplicationForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 👌LGTM

#2064 Hot fix for name formatting
  packages/client/src/utils/validate.ts
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: 💅 Waiting For Review, 💥 Hot Fixes

#2065 Showing hospital name on started by column in workstatus list
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💥 Hot Fixes

#2066 Hot fix from QA feedback
  packages/client/src/SubmissionController.test.ts
  packages/client/src/SubmissionController.ts
  packages/client/src/applications/index.ts
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/interface/ApplicationStatusWindow.tsx
  packages/client/src/utils/draftUtils.ts
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegistrationHome/NotificationToast.tsx
  packages/components/src/components/interface/ExpandableNotification/ExpandableNotification.tsx
  packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx
  packages/components/src/components/interface/Header/Mobile/MobileHeader.tsx
Labels: 💥 Hot Fixes, 🔧Waiting for fixes, 🙏 forgive coverage

#2071 Ocrvs 1825 Resend sms invite flow
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/user/mutations.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/resendSMSInvite/handler.test.ts
  packages/user-mgnt/src/features/resendSMSInvite/handler.ts
Labels: 💅 Waiting For Review

#2068 Ocrvs 1619 Forgotten pin flow
  packages/client/src/components/ProtectedPage.tsx
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/user/queries.ts
  packages/client/src/views/SecureAccount/SecureAccountView.tsx
  packages/client/src/views/Unlock/ForgotPIN.test.tsx
  packages/client/src/views/Unlock/ForgotPIN.tsx
  packages/client/src/views/Unlock/Unlock.test.tsx
  packages/client/src/views/Unlock/Unlock.tsx
  packages/components/src/components/interface/PINKeypad.tsx
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/verifyPasswordById/handler.test.ts
  packages/user-mgnt/src/features/verifyPasswordById/handler.ts
Labels: 👌LGTM

#2063 Fix for duplicate history issue
  packages/search/src/elasticsearch/utils.test.ts
  packages/search/src/elasticsearch/utils.ts
Labels: 👌LGTM

#2070 Content management with Contentful
  README.md
  deploy.sh
  docker-compose.yml
  packages/client/extract-translations.sh
  packages/client/package.json
  packages/client/src/extract-translations.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/user.ts
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/i18n/messages/views/confirmationScreen.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/i18n/messages/views/pin.ts
  packages/client/src/i18n/messages/views/registrarHome.ts
  packages/client/src/i18n/messages/views/reject.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/i18n/messages/views/session.ts
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/i18n/messages/views/userSetup.ts
  packages/client/src/tests/languages.json
  packages/client/src/tests/register.json
  packages/client/src/utils/referenceApi.ts
  packages/client/src/utils/validate.test.ts
  packages/client/src/views/RegistrationHome/NotificationToast.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
  packages/client/src/views/Unlock/ForgotPIN.tsx
  packages/login/src/i18n/locales/bn.ts
  packages/login/src/i18n/locales/en.ts
  packages/login/src/views/resetCredentialsForm/resetCredentialsForm.ts
  packages/notification/extract-translations.sh
  packages/notification/package.json
  packages/notification/src/config/plugins.ts
  packages/notification/src/config/routes.ts
  packages/notification/src/constants.ts
  packages/notification/src/extract-translations.ts
  packages/notification/src/features/sms/birth-handler.test.ts
  packages/notification/src/features/sms/birth-handler.ts
  packages/notification/src/features/sms/death-handler.test.ts
  packages/notification/src/features/sms/death-handler.ts
  packages/notification/src/features/sms/handler.test.ts
  packages/notification/src/features/sms/handler.ts
  packages/notification/src/features/sms/service.ts
  packages/notification/src/features/sms/user-handler.test.ts
  packages/notification/src/features/sms/user-handler.ts
  packages/notification/src/features/sms/utils.ts
  packages/notification/src/i18n/locales/bn.json
  packages/notification/src/i18n/locales/en.json
  packages/notification/src/i18n/locales/en_ZA:en.json
  packages/notification/src/i18n/messages.ts
  packages/notification/src/index.test.ts
  packages/notification/src/tests/util.ts
  yarn.lock
Labels: 💅 Waiting For Review
