Repository opencrvs/opencrvs-core, pull requests merged in 2020-10, with the labels that each got.

#2008 1890 - Fix for date time range issue on registration rate page
  packages/client/src/views/SysAdmin/Performance/RegistrationRates.tsx
Labels: 💅 Waiting For Review

#2009 1911 - Fixed timings for workflow status grid
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/features/search/type-resolvers.ts
  packages/metrics/src/api.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/getEventDuration/handler.test.ts
  packages/metrics/src/features/getEventDuration/handler.ts
  packages/metrics/src/features/getTimeLogged/handler.ts
  packages/metrics/src/features/legacy/handler.ts
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/registration/test-data/mark-validated-request.json
  packages/metrics/src/features/registration/test-data/mark-waiting-validation-request.json
  packages/metrics/src/features/registration/test-data/new-in-progress-request copy.json
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#2013 2012 - Fix for user audit data visibility issue
  packages/client/src/user/queries.ts
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
Labels: 💅 Waiting For Review

#2022 2020 - Updated event form definitions for existing testcases
  packages/client/src/tests/register.json
Labels: 💅 Waiting For Review

#2019 2018 - Updating fetched workqueue items with existing application data
  packages/client/src/applications/index.ts
Labels: 🙋Question

#2011 2010 - Added scope for registration agent to print certificate
  packages/user-mgnt/src/utils/userUtils.ts
Labels: 🙋Question

#2026 Ocrvs 1787 Make header sticky
  packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx
  packages/components/src/components/interface/Header/Mobile/MobileHeader.tsx
Labels: 💅 Waiting For Review

#2027 Ocrvs 1928 Fix for processing application in offline mode
  packages/client/src/applications/index.ts
Labels: 💅 Waiting For Review

#2028 Ocrvs 1992 Fix reject comment issue
  packages/search/src/features/registration/birth/service.ts
Labels: 💅 Waiting For Review

#2029 Ocrvs 1955 Fix for radio button and view group mismatch issue
  packages/client/src/applications/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#2030 Ocrvs 1956 Work queue table column related fixes
  packages/client/src/views/RegistrationHome/tabs/inProgress/inProgressTab.tsx
  packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/components/buttons/ListItemAction.tsx
  packages/components/src/components/interface/GridTable/GridTable.tsx
Labels: 💅 Waiting For Review

#2031 Ocrvs 1943 Copy changes
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/tests/languages.json
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
Labels: 💅 Waiting For Review
