Repository opencrvs/opencrvs-core, pull requests merged in 2020-09, with the labels that each got.

#1976 Websub updates and signing
  packages/user-mgnt/src/features/system/handler.ts
  packages/webhooks/src/config/routes.ts
  packages/webhooks/src/features/event/handler.ts
  packages/webhooks/src/features/event/service.ts
  packages/webhooks/src/features/manage/handler.test.ts
  packages/webhooks/src/features/manage/handler.ts
  packages/webhooks/src/features/manage/service.ts
  packages/webhooks/src/features/test/utils.ts
  packages/webhooks/src/model/webhook.ts
  packages/webhooks/src/processor.ts
Labels: 🚧 work in progress

#1972 #1938-Copy fix
  packages/client/src/views/SysAdmin/Performance/utils.ts
Labels: 💅 Waiting For Review

#1973 #1926-Login error message
  packages/login/src/App.test.tsx
  packages/login/src/i18n/locales/bn.ts
  packages/login/src/i18n/locales/en.ts
  packages/login/src/views/StepOne/StepOneForm.tsx
Labels: 💅 Waiting For Review

#1974 #1799-Update x-axis label
  packages/client/src/views/SysAdmin/Performance/RegistrationRates.tsx
  packages/components/src/components/charts/TriLineChart.tsx
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1983 1978 & 1880
  packages/client/src/applications/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegistrationHome/RegistrationHome.test.tsx
  packages/client/src/views/RegistrationHome/RegistrationHome.tsx
  packages/notification/src/i18n/locales/bn.json
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1985 #1982 - Fix for comment mutation and query related mapping issues
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
Labels: 💅 Waiting For Review

#1987 1986 - Fix for load more issue of print tab
  packages/client/src/views/RegistrationHome/RegistrationHome.test.tsx
  packages/client/src/views/RegistrationHome/RegistrationHome.tsx
Labels: 💅 Waiting For Review

#1991 1990 - fix for fetchRegistrationMetrics query issue
  packages/gateway/src/features/fhir/utils.ts
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1996 1910 - Fixed application started time issue on workflow status list
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 👌LGTM

#1998 1951 - Logout user from current session in-case of deactivation or role change
  packages/auth/src/features/authenticate/handler.test.ts
  packages/auth/src/features/authenticate/handler.ts
  packages/client/src/utils/apolloClient.ts
  packages/gateway/src/graphql/config.test.ts
  packages/gateway/src/graphql/config.ts
  packages/login/src/i18n/locales/bn.ts
  packages/login/src/i18n/locales/en.ts
  packages/login/src/utils/authUtils.ts
  packages/login/src/views/StepOne/StepOneForm.tsx
  packages/user-mgnt/src/features/updateUser/handler.ts
Labels: 👌LGTM

#2005 1952 - Fix for started column values on search result screen
  packages/client/src/applications/index.ts
  packages/client/src/search/transformer.ts
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/RegistrationHome/RowHistoryView.tsx
  packages/client/src/views/RegistrationHome/tabs/approvals/approvalTab.tsx
  packages/client/src/views/RegistrationHome/tabs/externalValidation/externalValidationTab.tsx
  packages/client/src/views/RegistrationHome/tabs/print/printTab.tsx
  packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 👌LGTM

#2006 2003 - Adjusted the sorting order for sent for update tab
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/identity.test.ts
  packages/client/src/forms/identity.ts
  packages/client/src/forms/index.ts
  packages/client/src/views/RegistrationHome/RowHistoryView.tsx
  packages/client/src/views/RegistrationHome/queries.ts
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/types.ts
Labels: 👌LGTM
