Repository opencrvs/opencrvs-core, pull requests merged in 2020-04, with the labels that each got.

#1553 "Added security header on nginx config""
  infrastructure/nginx-default.conf
Labels: 🔧Waiting for fixes

#1555 [ocrvs-2762] Backend for operational performance dashboard data
  docker-compose.yml
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/metrics/root-resolvers.test.ts
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/metrics/src/api.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/constants.ts
  packages/metrics/src/features/eventEstimations/handler.test.ts
  packages/metrics/src/features/eventEstimations/handler.ts
  packages/metrics/src/features/metrics/constants.ts
  packages/metrics/src/features/metrics/handler.test.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/metrics/utils.test.ts
  packages/metrics/src/features/metrics/utils.ts
  packages/metrics/test/setupJest.ts
Labels: :nail_care:Waiting For Review

#1550 [OCRVS-2715] Edit user details
  packages/client/src/App.tsx
  packages/client/src/components/Notification.test.tsx
  packages/client/src/components/Notification.tsx
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/sysadmin/user/queries.ts
  packages/client/src/tests/register.json
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/tabs/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/tabs/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/tabs/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/tabs/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/SysAdmin/tabs/user/userTab.test.tsx
  packages/client/src/views/SysAdmin/tabs/user/userTab.tsx
  packages/client/src/views/SysAdmin/utils.ts
  packages/gateway/src/features/location/schema.graphql
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/type-resolvers.test.ts
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
Labels: 👌LGTM

#1557 Applications started metrics
  .dockerignore
  .gitignore
  docker-compose.dev-deps.yml
  infrastructure/license-config.json
  infrastructure/openhim-base-config.json
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/metrics/constants.ts
  packages/metrics/src/features/registration/fhirUtils.test.ts
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/influxdb/client.ts
  packages/workflow/src/features/events/handler.ts
Labels: :nail_care:Waiting For Review

#1556 [OCRVS-2738, OCRVS-2739, OCRVS-2742] Performance pages for system user
  packages/client/src/App.tsx
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/PerformanceContentWrapper.test.tsx
  packages/client/src/views/Performance/PerformanceContentWrapper.tsx
  packages/client/src/views/Performance/PerformanceHome.test.tsx
  packages/client/src/views/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/SysAdminHome.test.tsx
  packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
Labels: :hourglass_flowing_sand: Waiting for CI, 👌LGTM

#1447 [OCRVS-2154] Setup testing environment for device testing
  README.md
  infrastructure/ngrok.conf
  package.json
  packages/client/package.json
  packages/client/serve-static.js
  packages/client/src/registerServiceWorker.ts
  packages/client/src/setupProxy.js
  packages/mobile-proxy/index.ts
  packages/mobile-proxy/package.json
  yarn.lock
Labels: :hourglass_flowing_sand: Waiting for CI

#1559 Metrics handler and GQL query for applications started
  packages/gateway/src/features/metrics/root-resolvers.test.ts
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/applicationsStarted/handler.test.ts
  packages/metrics/src/features/applicationsStarted/handler.ts
Labels: :raising_hand:Question, 👌LGTM

#1564 Update user fixes
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/tabs/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/utils.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
Labels: :boom: Hot Fixes

#1566 Fix for QA server build issue
  infrastructure/nginx-default.conf
Labels: :boom: Hot Fixes

#1561 [OCRVS-2744] Event registration rates report
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/reports/RegistrationRatesReport.test.tsx
  packages/client/src/views/Performance/reports/RegistrationRatesReport.tsx
  packages/client/src/views/Performance/utils.ts
Labels: :nail_care:Waiting For Review

#1563 Added proper content security prolicy on nginx config
  infrastructure/nginx-default.conf
Labels: :hourglass_flowing_sand: Waiting for CI, :nail_care:Waiting For Review

#1567 [ocrvs-2778 & 2782] Showed no data if location does not have estimation data
  packages/client/src/views/Performance/reports/Estimated45DayRegistrationReports.tsx
  packages/gateway/src/features/metrics/schema.graphql
Labels: :nail_care:Waiting For Review, :pray:forgive coverage

#1562 Applications started UI, font and metrics query fixes
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/metricsQuery.ts
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.test.tsx
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.test.tsx
  packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.tsx
  packages/client/src/views/Performance/utils.ts
  packages/components/src/components/fonts.ts
  packages/metrics/src/features/applicationsStarted/handler.test.ts
  packages/metrics/src/features/applicationsStarted/handler.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
Labels: :nail_care:Waiting For Review

#1565 Ocrvs 2768 Copy change
  packages/login/src/i18n/locales/en.ts
Labels: 💅 Waiting For Review

#1632 Fixed some minor ui bugs on operational dashboard screen
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.tsx
Labels: 💥 Hot Fixes, 🙏 forgive coverage

#1637 Ocrvs 2751 RegistrationRates bootstrap
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/Performance/OperationalReport.test.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/PerformanceContentWrapper.tsx
  packages/client/src/views/Performance/PerformanceSelect.tsx
  packages/client/src/views/Performance/RegistrationRates.test.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/client/src/views/Performance/queries.ts
  packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.test.tsx
  packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.tsx
  packages/client/src/views/Performance/utils.test.ts
  packages/client/src/views/Performance/utils.ts
  packages/gateway/src/features/location/root-resolvers.test.ts
  packages/gateway/src/features/location/root-resolvers.ts
  packages/gateway/src/features/location/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
Labels: 👌LGTM

#1673 Introduced time range to estimation metrics
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/metrics/utils.test.ts
  packages/metrics/src/features/metrics/utils.ts
Labels: 👌LGTM

#1674 Fixed Upaliza typo
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/tests/languages.json
  packages/client/src/views/Performance/NoResultMessage.tsx
  packages/client/src/views/Performance/PerformanceHome.tsx
Labels: 💅 Waiting For Review

#1677 [#1606 & #1672] Showing registration rates for different administrative areas
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/views/Performance/PerformanceSelect.test.tsx
  packages/client/src/views/Performance/PerformanceSelect.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/client/src/views/Performance/queries.ts
  packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.test.tsx
  packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/metrics/root-resolvers.test.ts
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/metrics/src/api.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/locationWiseEventEstimations/handler.test.ts
  packages/metrics/src/features/locationWiseEventEstimations/handler.ts
  packages/metrics/test/setupJest.ts
Labels: 💅 Waiting For Review

#1664 Import legacy metrics for applications started
  docker-compose.yml
  packages/metrics/src/api.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/constants.ts
  packages/metrics/src/features/applicationsStarted/handler.ts
  packages/metrics/src/features/legacy/handler.test.ts
  packages/metrics/src/features/legacy/handler.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/test/setupJest.ts
  packages/search/src/config/routes.ts
  packages/search/src/features/search/handler.ts
Labels: 👌LGTM, 🙏 forgive coverage

#1678 Sys Admin reports
  packages/client/src/navigation/index.ts
  packages/client/src/views/Performance/OperationalReport.test.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/PerformanceHome.test.tsx
  packages/client/src/views/Performance/PerformanceHome.tsx
  packages/client/src/views/Performance/PerformanceSelect.tsx
  packages/client/src/views/Performance/RegistrationRates.test.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
Labels: 💅 Waiting For Review

#1683 Check count of Elastic before returning all
  packages/search/src/features/search/handler.ts
Labels: 💅 Waiting For Review, 💥 Hot Fixes

#1684 Applications Started: Query was incorrect for API users
  packages/metrics/src/features/applicationsStarted/handler.ts
Labels: 💅 Waiting For Review, 💥 Hot Fixes
