Repository opencrvs/opencrvs-core, pull requests merged in 2020-05, with the labels that each got.

#1681 maxWidth 1140px and RegistrationRates / Reports UI amends
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/PerformanceContentWrapper.tsx
  packages/client/src/views/Performance/PerformanceSelect.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx
  packages/client/src/views/Performance/utils.ts
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/client/src/views/SysAdmin/tabs/user/userTab.tsx
  packages/components/src/components/fonts.ts
  packages/components/src/components/interface/GridTable/types.ts
  packages/components/src/components/interface/ListTable/ListTable.tsx
  packages/components/src/components/layout/Content.tsx
  packages/metrics/src/features/legacy/handler.ts
Labels: 💅 Waiting For Review

#1682 Ocrvs 1569 date range picker
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/Performance/OperationalReport.test.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/utils.ts
  packages/components/src/components/buttons/CircleButton.tsx
  packages/components/src/components/colors.ts
  packages/components/src/components/icons/Calendar.md
  packages/components/src/components/icons/Calendar.tsx
  packages/components/src/components/icons/CalendarGrey.md
  packages/components/src/components/icons/CalendarGrey.tsx
  packages/components/src/components/icons/ChevronLeft.md
  packages/components/src/components/icons/ChevronLeft.tsx
  packages/components/src/components/icons/ChevronRight.md
  packages/components/src/components/icons/ChevronRight.tsx
  packages/components/src/components/icons/index.ts
Labels: 💅 Waiting For Review

#1688 Check the ID of the primary caregiver, rather than just create a new one
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/search/src/features/search/handler.ts
Labels: 💅 Waiting For Review

#1703 [OCRVS-1667] Application status window
  packages/client/src/components/interface/ApplicationStatusWindow.tsx
  packages/client/src/views/Performance/OperationalReport.test.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/components/src/components/icons/Activity.tsx
Labels: 👌LGTM

#1680 [OCRVS-1578] Registration rates line chart
  packages/client/src/components/charts/RegRatesLineChart.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/components/src/components/charts/Line.md
  packages/components/src/components/charts/Line.tsx
  packages/components/src/components/charts/TriLineChart.md
  packages/components/src/components/charts/TriLineChart.tsx
  packages/components/src/components/charts/index.ts
  packages/components/src/components/colors.ts
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1685 Application status UI updates and related backend changes
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/queries.ts
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.tsx
  packages/client/src/views/Performance/reports/operational/StatusWiseApplicationCountView.test.tsx
  packages/client/src/views/Performance/reports/operational/StatusWiseApplicationCountView.tsx
  packages/client/src/views/RegistrationHome/RegistrationHome.tsx
  packages/components/package.json
  packages/components/src/components/colors.ts
  packages/components/src/components/forms/ProgressBar.md
  packages/components/src/components/forms/ProgressBar.tsx
  packages/components/src/components/forms/index.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/search/src/config/routes.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/composition.test.ts
  packages/search/src/features/registration/birth/noParents.test.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/handler.test.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/search/handler.test.ts
  packages/search/src/features/search/handler.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.test.ts
  packages/search/src/features/search/utils.ts
  packages/search/src/test/utils.ts
  yarn.lock
Labels: 👌LGTM

#1721 Metrics time logged and started by measurement changes
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1720 Ocrvs 1707 Operational dashboard subpage header
  packages/client/src/App.tsx
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/PerformanceContentWrapper.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/client/src/views/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/Performance/WorkflowStatus.tsx
  packages/client/src/views/Performance/reports/operational/StatusWiseApplicationCountView.tsx
Labels: 💅 Waiting For Review

#1725 Applications started percentage and query errors
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/metrics/src/features/applicationsStarted/handler.ts
Labels: 💅 Waiting For Review, 💥 Hot Fixes

#1726 [OCRVS-1704] Performance error handler
  packages/client/src/components/charts/RegRatesLineChart.tsx
  packages/client/src/components/interface/ToastNotification.test.tsx
  packages/client/src/components/interface/ToastNotification.tsx
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/views/Performance/OperationalReport.test.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/RegistrationRates.test.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.tsx
  packages/client/src/views/Performance/reports/operational/StatusWiseApplicationCountView.tsx
  packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx
  packages/components/src/components/icons/Alert.md
  packages/components/src/components/icons/Alert.tsx
  packages/components/src/components/icons/index.ts
  packages/components/src/components/interface/ErrorToastNotification.md
  packages/components/src/components/interface/ErrorToastNotification.tsx
  packages/components/src/components/interface/index.ts
Labels: 💅 Waiting For Review

#1722 Track rejected application
  infrastructure/openhim-base-config.json
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/fhirUtils.test.ts
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/registration/test-data/rejected.json
  packages/metrics/src/features/registration/test-data/task-history.json
  packages/metrics/src/influxdb/client.ts
Labels: 👌LGTM

#1728 Fixes for hierarchical location generation issue for legacy indexes
  packages/search/src/features/search/handler.test.ts
  packages/search/src/features/search/handler.ts
Labels: 💥 Hot Fixes

#1727 Updated reports header in performance
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/Performance/MonthlyReports.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/PerformanceContentWrapper.test.tsx
  packages/client/src/views/Performance/PerformanceContentWrapper.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/client/src/views/Performance/Report.test.tsx
  packages/client/src/views/Performance/Report.tsx
  packages/client/src/views/Performance/ReportList.test.tsx
  packages/client/src/views/Performance/ReportList.tsx
Labels: 👌LGTM, 💅 Waiting For Review

#1729 Restricting application & field agent links using config var
  packages/client/public/config.js
  packages/client/src/setupTests.ts
  packages/client/src/utils/locationUtils.test.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.test.tsx
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/client/src/views/Performance/reports/operational/StatusWiseApplicationCountView.test.tsx
  packages/client/src/views/Performance/reports/operational/StatusWiseApplicationCountView.tsx
  packages/client/typings/window.d.ts
  packages/components/src/components/forms/ProgressBar.tsx
Labels: 💅 Waiting For Review

#1730 GraphQL query, metrics endpoint, user-mgnt endpoint and UI component for field agent list
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/features/user/utils/index.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/applicationsStarted/handler.test.ts
  packages/metrics/src/features/applicationsStarted/handler.ts
  packages/metrics/src/features/applicationsStarted/service.ts
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/fhirUtils.test.ts
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/influxdb/client.ts
Labels: 👌LGTM, 🚧 work in progress

#1735 [OCRVS-1691] Application progress tracker back-end
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/utils/index.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/getTimeLogged/handler.ts
  packages/metrics/src/features/getTimeLogged/utils.ts
  packages/search/src/config/routes.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
Labels: 💅 Waiting For Review

#1738 UI: List of field agents along with their performance data for selected offices
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/Performance/FieldAgentList.test.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/PerformanceSelect.tsx
  packages/client/src/views/Performance/WorkflowStatus.tsx
  packages/client/src/views/Performance/queries.ts
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.test.tsx
  packages/client/src/views/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx
  packages/client/src/views/Performance/utils.ts
  packages/components/src/components/colors.ts
  packages/components/src/components/forms/Select.tsx
  packages/components/src/components/icons/KeyboardArrowDown.md
  packages/components/src/components/icons/KeyboardArrowDown.tsx
  packages/components/src/components/interface/GridTable/LoadMore.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
  packages/gateway/src/features/user/root-resolvers.ts
Labels: 👌LGTM

#1734 Ocrvs 1691 Applications table viewpage
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/registrarHome.ts
  packages/client/src/navigation/index.ts
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/Performance/OperationalReport.tsx
  packages/client/src/views/Performance/RegistrationRates.tsx
  packages/client/src/views/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/Performance/WorkflowStatus.tsx
  packages/client/src/views/Performance/queries.ts
  packages/client/src/views/Performance/reports/operational/StatusWiseApplicationCountView.test.tsx
  packages/client/src/views/Performance/reports/operational/StatusWiseApplicationCountView.tsx
  packages/components/src/components/buttons/CircleButton.tsx
  packages/components/src/components/forms/ProgressBar.tsx
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
Labels: 💅 Waiting For Review
