Repository opencrvs/opencrvs-core, pull requests merged in 2020-07, with the labels that each got.

#1843 [OCRVS-1768] User audit backend
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/utils/index.ts
  packages/gateway/src/graphql/config.test.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/getUser/handler.test.ts
  packages/user-mgnt/src/features/userAudit/handler.test.ts
  packages/user-mgnt/src/features/userAudit/handler.ts
  packages/user-mgnt/src/model/user.ts
  packages/user-mgnt/src/utils/userUtils.ts
Labels: 💅 Waiting For Review

#1851 [OCRVS-1772] User under investigation tag
  packages/client/src/user/queries.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/components/src/components/icons/SearchRed.md
  packages/components/src/components/icons/SearchRed.tsx
  packages/components/src/components/icons/index.ts
  packages/components/src/components/interface/ListTable/ListTable.tsx
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/type-resolvers.test.ts
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1844 Ocrvs 1768 User audit frontend
  packages/client/src/components/Notification.test.tsx
  packages/client/src/components/Notification.tsx
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/notification/actions.ts
  packages/client/src/notification/reducer.ts
  packages/client/src/user/queries.ts
  packages/client/src/user/user-audit.ts
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/components/src/components/interface/ResponsiveModal.tsx
Labels: 💅 Waiting For Review

#1852 Ocrvs 1771 User audit frontend (reactivation)
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/forms/validation.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/user/user-audit.ts
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
Labels: ⏳ Waiting for CI, 💅 Waiting For Review

#1854 [OCRVS-1744] Search page design update
  packages/client/src/search/queries.ts
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/SearchResult/SearchResultExpansion.test.tsx
  packages/components/src/components/buttons/ExpansionButton.tsx
  packages/components/src/components/icons/Download.tsx
Labels: 👌LGTM, 💅 Waiting For Review

#1857 Fixed legacy user audit data issue
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserAuditList.tsx
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💥 Hot Fixes

#1858 Fixed double line table row height
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: 💅 Waiting For Review

#1860 Fixed scroller width and visibility issue
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 💅 Waiting For Review

#1859 Name in ready for review workqueue
  packages/client/src/views/RegistrationHome/RowHistoryView.tsx
  packages/client/src/views/RegistrationHome/tabs/approvals/approvalTab.test.tsx
  packages/client/src/views/RegistrationHome/tabs/approvals/approvalTab.tsx
  packages/client/src/views/RegistrationHome/tabs/review/reviewTab.test.tsx
  packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx
Labels: 💅 Waiting For Review

#1862 Register, deactivate and reactivate a system client
  packages/user-mgnt/package.json
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/model/system.ts
  packages/user-mgnt/src/model/user.ts
  packages/user-mgnt/src/utils/token.ts
  packages/user-mgnt/src/utils/userUtils.ts
Labels: 💅 Waiting For Review

#1864 System client authentication
  packages/auth/src/constants.ts
  packages/auth/src/features/authenticate/handler.ts
  packages/auth/src/features/authenticate/service.ts
  packages/auth/src/features/system/handler.test.ts
  packages/auth/src/features/system/handler.ts
  packages/auth/src/index.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/system/handler.ts
Labels: 💅 Waiting For Review

#1867 Fixed death event location issue on elastic index
  packages/search/src/features/registration/death/service.ts
Labels: 💅 Waiting For Review

#1868 nginx configuration for dynamic hostname
  infrastructure/nginx-default.conf
  infrastructure/setup-deploy-config.sh
Labels: 💅 Waiting For Review

#1865 Updated person identifier with birth/death registration number
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/legacy/handler.test.ts
  packages/workflow/src/features/legacy/handler.ts
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/test/utils.ts
Labels: 👌LGTM

#1869 Hot fixes
  Dockerfile
  docker-compose.deploy.yml
  infrastructure/nginx-default.conf
  infrastructure/nginx-deploy-config.sh
  infrastructure/setup-deploy-config.sh
  packages/client/Dockerfile
  packages/gateway/src/graphql/config.ts
  packages/login/Dockerfile
Labels: 💅 Waiting For Review, 💥 Hot Fixes
