Repository opencrvs/opencrvs-core, pull requests merged in 2020-08, with the labels that each got.

#1916 #1876-Redirecting to appropriate team list
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 👌LGTM, 💅 Waiting For Review, 🙏 forgive coverage

#1922 #1900-Error message for no option selection in event selection screen
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.test.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
Labels: 👌LGTM, 💅 Waiting For Review

#1918 #1886-Activate pilot list on empty report screen
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/tests/languages.json
  packages/client/src/views/SysAdmin/Performance/NoResultMessage.test.tsx
  packages/client/src/views/SysAdmin/Performance/NoResultMessage.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: 💅 Waiting For Review

#1927 #1898-Adjusted phone number search to support with or without country code
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/forms/utils.ts
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 👌LGTM, 💅 Waiting For Review

#1923 #1885-Fix for date picker initial value issue on operational dashboard
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
Labels: 👌LGTM, 💅 Waiting For Review

#1919 #1895-Show 8px scrollbar when applicable for ListTable
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 💅 Waiting For Review

#1920 #1889 & 1892 - Fix for table list alignment issues, removed sort functionality from report list
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/MonthlyReports.tsx
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/reports/CertificationPaymentReports.tsx
  packages/client/src/views/SysAdmin/Performance/reports/Estimated45DayRegistrationReports.tsx
  packages/client/src/views/SysAdmin/Performance/reports/GenderBasisReports.tsx
  packages/client/src/views/SysAdmin/Performance/reports/TimeFrameReports.tsx
  packages/client/src/views/SysAdmin/Performance/reports/registrationRates/Within45DaysTable.tsx
Labels: 💅 Waiting For Review

#1917 #1906-Changed the column header to Started in search result
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#1921 #1890-Removed console error on registration rate screen
  packages/client/src/components/charts/RegRatesLineChart.tsx
  packages/client/src/views/SysAdmin/Performance/RegistrationRates.tsx
Labels: 💅 Waiting For Review, 🙏 forgive coverage

#1947 #1912-Replaced trackingid with name in search result list
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#1935 #1894-Returns empty array in getEventsWithProgress query for invalid location
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
Labels: 💅 Waiting For Review

#1950 Fixed municipality related issues
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/ApplicationsStartedReport.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/StatusWiseApplicationCountView.tsx
  packages/client/src/views/SysAdmin/Performance/utils.ts
  packages/client/src/views/UserSetup/SetupReviewPage.tsx
Labels: 💥 Hot Fixes

#1866 Webhook microservice and webhook subscription
  Dockerfile
  docker-compose.ci.yml
  docker-compose.deploy.yml
  docker-compose.dev.yml
  docker-compose.prod-deploy.yml
  docker-compose.qa-deploy.yml
  docker-compose.yml
  infrastructure/traefik.toml
  packages/auth/src/constants.ts
  packages/auth/src/features/system/handler.ts
  packages/auth/src/index.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/model/system.ts
  packages/webhooks/.dockerignore
  packages/webhooks/.gitignore
  packages/webhooks/Dockerfile
  packages/webhooks/README.md
  packages/webhooks/package.json
  packages/webhooks/src/config/plugins.ts
  packages/webhooks/src/config/routes.ts
  packages/webhooks/src/constants.ts
  packages/webhooks/src/database.ts
  packages/webhooks/src/features/webhooks/handler.test.ts
  packages/webhooks/src/features/webhooks/handler.ts
  packages/webhooks/src/features/webhooks/service.ts
  packages/webhooks/src/index.test.ts
  packages/webhooks/src/index.ts
  packages/webhooks/src/logger.ts
  packages/webhooks/src/model/webhook.ts
  packages/webhooks/test/cert.key.pub
  packages/webhooks/test/setupJest.ts
  packages/webhooks/tsconfig.json
  packages/webhooks/tslint.json
  packages/webhooks/typings/hapi-sentry.d.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/user/utils.ts
Labels: 💅 Waiting For Review

#1964 Webhook queue and broadcast
  docker-compose.yml
  infrastructure/openhim-base-config.json
  packages/webhooks/Dockerfile
  packages/webhooks/package.json
  packages/webhooks/src/config/routes.ts
  packages/webhooks/src/constants.ts
  packages/webhooks/src/features/event/handler.ts
  packages/webhooks/src/features/manage/handler.test.ts
  packages/webhooks/src/features/manage/handler.ts
  packages/webhooks/src/features/manage/service.ts
  packages/webhooks/src/index.ts
  packages/webhooks/src/processor.ts
  packages/webhooks/src/queue.ts
  packages/webhooks/typings/short-uid.d.ts
  yarn.lock
Labels: 🏥 Failing Tests, 👌LGTM
