Repository opencrvs/opencrvs-core, pull requests merged in 2021-12, with the labels that each got.

#2306 Updates to be able to run compose
  Dockerfile
  packages/client/package.json
  packages/commons/package.json
  packages/components/Dockerfile
  packages/gateway/Dockerfile
  packages/gateway/package.json
  packages/gateway/src/index.ts
  packages/integration/package.json
  packages/metrics/Dockerfile
  packages/notification/Dockerfile
  packages/search/Dockerfile
  packages/user-mgnt/Dockerfile
  packages/webhooks/Dockerfile
  packages/workflow/Dockerfile
  yarn.lock
Labels: 💅 Waiting For Review

#2307 ocrvs-1789: Fix font size and styling for registration rate widget
  packages/client/src/views/SysAdmin/Performance/reports/operational/RegistrationRatesReport.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2309 ocrvs-2130 fixed widths in date of birth fields and fixed margin between date of…
  packages/components/src/components/forms/DateField.tsx
Labels: 💅 Waiting For Review

#2313 ocrvs-1794 Sorting implemented in field agent details view
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/reports/registrationRates/Within45DaysTable.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserAuditList.tsx
  packages/components/src/components/interface/GridTable/types.ts
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2317 ocrvs-2129 weight at birth input field fixed to 78px and padding and label fixed
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/components/src/components/forms/InputField/InputField.tsx
  packages/components/src/components/forms/TextInput.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2310 ocrvs-2296 Added New National System Admin User
  docker-compose.dev-deps.yml
  infrastructure/openhim-base-config.json
  packages/auth/src/constants.ts
  packages/auth/src/features/system/handler.ts
  packages/client/src/App.tsx
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/user.ts
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/tests/languages.json
  packages/client/src/utils/constants.ts
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/SysAdmin/Config/ConfigHome.tsx
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/utils/userUtils.ts
Labels: 🔧Waiting for fixes

#2330 ocrvs-1967 Changed pending UI Pill bg colour to amber light
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: 👌LGTM

#2326 back button colored to deepsea
  packages/components/src/components/icons/BackArrowDeepBlue.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2323 ocrvs-1937 device was saved as deviceId in gateway and in user mgnt, this is fixed
  packages/client/src/user/queries.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/model/user.ts
Labels: 💅 Waiting For Review, 👌LGTM

#2332 ocrvs-1963: newfont created, pill fontStyle changed as 12px semibold, padding: 4px 8px, border-radius: 2px
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/components/src/components/fonts.ts
Labels: 💅 Waiting For Review

#2322 ocrvs-1908 NID validation moved from core to contry-wise config
  packages/client/src/utils/validate.ts
  packages/client/typings/window.d.ts
Labels: 💅 Waiting For Review
