Repository opencrvs/opencrvs-core, pull requests merged in 2022-01, with the labels that each got.

#2315 ocrvs-2299 Fixed location name generation
  packages/client/src/components/LocationPicker.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/index.ts
  packages/client/src/i18n/messages/location.ts
  packages/client/src/tests/languages.json
  packages/client/src/tests/util.tsx
  packages/client/src/utils/constants.ts
  packages/client/src/utils/locationUtils.test.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/utils/validate.ts
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Performance/MonthlyReports.tsx
  packages/client/src/views/SysAdmin/Performance/NoResultMessage.tsx
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: 👌LGTM

#2345 ocrvs-2337 Fixed the z-index for status window
  packages/client/src/components/interface/ApplicationStatusWindow.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2334 ocrvs-1904 Fixed add file feature for registrar
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2347 ocrvs-2318 showing all available type on update user
  packages/client/src/user/userReducer.ts
Labels: 💅 Waiting For Review, 👌LGTM

#2349 ocrvs-2128: input field max width set to 344px
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/components/src/components/forms/InputField/InputField.tsx
  packages/components/src/components/forms/Select.tsx
  packages/components/src/components/forms/TextArea.tsx
  packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2361 ocrvs-1962: hover and active state on download button made circle same as expand button.
  packages/client/src/components/interface/DownloadButton.tsx
Labels: 👌LGTM

#2374 ocrvs 1944 Fixed rejected application long comment truncated issue and set maxLength to 500
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/review/reject-registration.ts
  packages/client/src/views/RegistrationHome/RowHistoryView.tsx
  packages/components/src/components/forms/TextArea.tsx
Labels: 👌LGTM

#2385 Ocrvs 1939 Fix lock screen name issue
  packages/client/src/views/Unlock/Unlock.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2388 ocrvs-1981: fix duplicate icon
  packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2389 ocrvs-1989:scrolbar height for sent incomplete modal
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/components/src/components/interface/ResponsiveModal.tsx
Labels: 👌LGTM

#2396 Ocrvs 1873 Make sure handled error in redux loop is not logged
  packages/client/src/store.ts
Labels: 💅 Waiting For Review, 👌LGTM

#2390 ocrvs-2195: *.sentry.io/ whitelisted on nginx-default-conf
  infrastructure/nginx-default.conf
Labels: 💅 Waiting For Review

#2348 ocrvs-2308 Fixed back button not working
  packages/client/src/views/SysAdmin/Performance/Report.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2329 Ocrvs 1965
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 💅 Waiting For Review

#2333 ocrvs-1969: ui bug fix on userProfile
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserAuditList.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
Labels: 💅 Waiting For Review

#2344 ocrvs-2316 Added the required other field in {select} format messages
  packages/login/src/i18n/locales/bn.ts
  packages/login/src/i18n/locales/en.ts
  packages/login/src/views/resetCredentialsForm/resetCredentialsForm.ts
Labels: 👌LGTM

#2351 ocrvs-2336 Added message descriptor for DNRPC type
  packages/client/src/i18n/messages/user.ts
Labels: 💅 Waiting For Review

#2384 ocrvs-1936: time period represented using '-'
  packages/client/src/i18n/messages/constants.ts
Labels: 💅 Waiting For Review

#2369 Ocrvs 1871: Validation implemented on Performance and team tab search
  packages/client/src/i18n/messages/views/search.ts
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Team/TeamSearch.tsx
  packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
Labels: 👌LGTM

#2367 ocrvs-2331 Fixed MANNER_UNDETERMINED as death manner and TRADITIONAL_BIRTH_ATTENDANT as birth attendant application submission
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: ✋On Hold, 👌LGTM

#2368 ocrvs 1929 Added hh:mm on details application view
  packages/client/src/views/Home/Details.tsx
Labels: 👌LGTM

#2383 ocrvs 1883 Fixed login UI issue after verification code timeout and back to login page
  packages/login/src/views/StepOne/StepOneForm.tsx
Labels: 👌LGTM

#2387 Ocrvs 1905: Validation showing when remove the location from user edit page
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/tests/register.json
  packages/client/src/utils/validate.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
Labels: 💅 Waiting For Review

#2395 ocrvs-1872: rejected birth/death application is not visible in sent for review tab
  packages/client/src/applications/index.ts
Labels: 💅 Waiting For Review, 👌LGTM

#2398 ocrvs-2397 Fixed the gen:types script
  package.json
  packages/components/src/components/forms/DateField.tsx
  packages/gateway/package.json
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/features/getRoles/handler.ts
  packages/user-mgnt/src/features/searchUsers/handler.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/user/utils.ts
  yarn.lock
Labels: ☕️ Discussion

#2453 Fix the react-error-overlay not showing up and hot reload
  package.json
  yarn.lock
Labels: 💅 Waiting For Review

#2291 ocrvs-2290 Fixed the types used in ApplicationForm and RegisterForm
  packages/client/src/views/RegisterForm/ApplicationForm.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review, ☕️ Discussion

#2293 ocrvs-2292 Fixed previously visited sections/groups not updating
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review, 👌LGTM, ☕️ Discussion

#2370 ocrvs 1946 Set overflow:auto for date range picker
  packages/client/src/components/DateRangePicker.tsx
Labels: 💅 Waiting For Review

#2418 New installation docs and demo script
  .gitignore
  README.md
  dev.sh
  docker-compose.demo-deps.yml
  infrastructure/server-setup/README.md
  package.json
  packages/components/package.json
  packages/gateway/package.json
  packages/mobile-proxy/README.md
  setup-scripts/setup-resources.sh
  setup-scripts/summary.sh
  setup.sh
Labels: 🚧 work in progress

#2484 Documentation update and Elasticsearch config fix
  docker-compose.dev-deps.yml
  infrastructure/server-setup/README.md
Labels: 👌LGTM

#2452 ocrvs-2379 - Added new Content component
  packages/components/src/components/interface/Content.stories.tsx
  packages/components/src/components/interface/Content.tsx
Labels: 👌LGTM

#2413 Ocrvs 1905: Validation showing when remove the location from user edit page
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/tests/register.json
  packages/client/src/utils/validate.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
Labels: 👌LGTM

#2487 ocrvs-2393: default value added for documentForWhom json
  packages/client/src/i18n/messages/views/review.ts
  packages/components/src/components/interface/DocumentViewer.tsx
Labels: 👌LGTM
