Repository opencrvs/opencrvs-core, pull requests merged in 2022-12, with the labels that each got.

#4343 Birth Archive, Birth Reinstate, Death Archive and Death Reinstate |…
  packages/client/src/i18n/messages/views/userSetup.ts
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/audit/service.ts
  packages/metrics/src/features/registration/handler.ts
  packages/workflow/src/features/events/handler.ts
Labels: 💅 Waiting For Review

#4284 Audit the username reminder and password reset events
  packages/client/src/i18n/messages/views/userSetup.ts
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/user-mgnt/src/features/changePhone/handler.ts
  packages/user-mgnt/src/features/resetPassword/handler.test.ts
  packages/user-mgnt/src/features/resetPassword/handler.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.ts
Labels: 💅 Waiting For Review

#4334 ocrvs-4117 Advanced Search Bookmark Feature
  docker-compose.deploy.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.yml
  packages/client/graphql.schema.json
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/i18n/messages/views/search.ts
  packages/client/src/profile/mutations.ts
  packages/client/src/profile/queries.ts
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.test.tsx
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/AdvancedSearch/BookmarkAdvancedSearchResult.tsx
  packages/client/src/views/AdvancedSearch/RemoveBookmarkModal.tsx
  packages/client/src/views/AdvancedSearch/SaveBookmarkModal.tsx
  packages/client/src/views/ViewRecord/ViewRecord.tsx
  packages/components/src/Icon/Icon.tsx
  packages/components/src/ToggleIcon/ToggleIcon.stories.tsx
  packages/components/src/ToggleIcon/ToggleIcon.tsx
  packages/components/src/ToggleIcon/index.ts
  packages/gateway/src/features/advanceSearch/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/search/utils.ts
  packages/user-mgnt/src/features/userSearchRecord/handler.ts
  packages/user-mgnt/src/model/user.ts
Labels: 💅 Waiting For Review

#4352 ocrvs- 4160: Webhook client integration
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Systems/DeleteSystemModal.tsx
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/client/src/views/SysAdmin/Config/Systems/WebhookModal.tsx
  packages/client/src/views/SysAdmin/Config/Systems/mutations.ts
  packages/client/src/views/SysAdmin/Config/Systems/useSystems.ts
  packages/client/src/views/Unlock/ForgotPIN.tsx
  packages/components/src/Checkbox/CheckboxGroup.tsx
  packages/components/src/CopyButton/CopyButton.stories.tsx
  packages/components/src/CopyButton/CopyButton.tsx
  packages/components/src/CopyButton/index.ts
  packages/gateway/src/features/systems/root-resolvers.test.ts
  packages/gateway/src/features/systems/root-resolvers.ts
  packages/gateway/src/features/systems/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/model/system.ts
  packages/user-mgnt/src/utils/userUtils.ts
  packages/webhooks/src/features/event/handler.ts
  packages/webhooks/src/features/event/service.ts
  packages/webhooks/src/features/manage/handler.ts
  packages/webhooks/src/features/manage/service.ts
Labels: 🔧Waiting for fixes

#4378 ocrvs-4311 Reinstated action name fix
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RecordAudit/utils.ts
Labels: ✅ Ready for merging

#4345 ocrvs-4319 vsExport generator and UI fix
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/views/SysAdmin/Vsexports/VSExport.tsx
  packages/client/src/views/SysAdmin/Vsexports/queries.ts
  packages/components/src/ListViewSimplified/ListViewSimplified.tsx
  packages/metrics/src/constants.ts
  packages/metrics/src/scripts/VSExportGenerator.ts
Labels: 👌LGTM, ✅ Ready for merging

#4369 ocrvs-4119-fix on update view record fixed
  packages/client/src/views/ViewRecord/ViewRecord.tsx
Labels: ✅ Ready for merging

#4417 Bump up vitest version to 0.25.5
  packages/client/package.json
  packages/login/package.json
  yarn.lock
Labels: ✅ Ready for merging

#4399 Fixed UserAudit test fix
  packages/client/src/views/UserAudit/UserAudit.test.tsx
Labels: 💅 Waiting For Review

#4303 Fixed bug for system crashing if back arrow is clicked after printing or correcting a record
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
Labels: 💅 Waiting For Review

#4411 Ocrvs 3852 fixed
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/SectionNavigation.tsx
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/components/formConfig/formTools/components.tsx
  packages/search/src/features/registration/death/service.ts
Labels: 💅 Waiting For Review, ✅ Ready for merging

#4316 ocrvs-4184 Support system initiated events
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/History.tsx
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/config.test.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
Labels: 👌LGTM

#4390 ocrvs-4309-fix Fixed messages id for common content keys
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/forms/advancedSearch/fieldDefinitions/Birth.ts
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/register/fieldMappings/birth/staticLabel.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/advancedSearchForm.ts
  packages/client/src/profile/queries.ts
  packages/client/src/tests/default.json
  packages/client/src/tests/languages.json
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
Labels: 💅 Waiting For Review, ✅ Ready for merging

#4407 OCRVS-3990: Custom Select in form config
  docker-compose.yml
  packages/client/graphql.schema.json
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/configuration/formConfig/reducer.ts
  packages/client/src/forms/configuration/formConfig/utils/index.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/i18n/messages/views/customFieldForm.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/utils/apolloClient.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/query.ts
  packages/client/src/views/SysAdmin/Config/Forms/mutations.ts
  packages/components/src/DateField/DateField.tsx
  packages/components/src/FileSelectLink/FileSelectLink.stories.tsx
  packages/components/src/FileSelectLink/FileSelectLink.tsx
  packages/components/src/FileSelectLink/index.ts
  packages/components/src/FormConfigElementCard/FormConfigElementCard.tsx
  packages/components/src/Icon/Icon.tsx
  packages/config/package.json
  packages/config/src/config/constants.ts
  packages/config/src/config/routes.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/handlers/formDataset/handler.test.ts
  packages/config/src/handlers/formDataset/handler.ts
  packages/config/src/handlers/question/createQuestion/handler.ts
  packages/config/src/handlers/question/getQuestions/handler.ts
  packages/config/src/models/formDataset.ts
  packages/config/src/models/question.ts
  packages/config/src/services/formDatasetService.ts
  packages/config/src/utils/csvHelper.ts
  packages/config/src/utils/verifyToken.ts
  packages/gateway/src/features/formDataset/root-resolver.ts
  packages/gateway/src/features/formDataset/schema.graphql
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/migrate-mongo-config-application-config.js
  packages/migration/migrations/application-config/20221205071415-add_health_facility_to_formdataset.js
  packages/migration/runMigrations.sh
  yarn.lock
Labels: 👌LGTM

#4439 Advanced Search Fixed
  packages/client/src/App.tsx
  packages/client/src/components/Header/Header.tsx
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/gateway/src/features/bookmarkAdvancedSearch/root-resolvers.test.ts
  packages/gateway/src/features/bookmarkAdvancedSearch/root-resolvers.ts
  packages/gateway/src/features/bookmarkAdvancedSearch/schema.graphql
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/search/utils.ts
Labels: 💅 Waiting For Review

#4351 ocrvs-4087 Minio migration
  docker-compose.deploy.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.yml
  packages/migration/migrations/hearth/20221128065238-migrate-documents-to-minio.js
  packages/migration/package.json
  packages/migration/utils/minio-helper.js
Labels: 💅 Waiting For Review, ✅ Ready for merging

#4459 Fixes to Webhook & RecrdSearch integration
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/graphql/config.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/webhooks/src/features/event/handler.ts
  packages/webhooks/src/features/event/service.ts
  packages/workflow/src/features/user/utils.test.ts
  packages/workflow/src/features/user/utils.ts
Labels: 💅 Waiting For Review

#4450 OCRVS-4265: IP Addresses are now correct for Audit Actions
  docker-compose.deploy.yml
  packages/gateway/src/graphql/config.ts
  packages/metrics/src/features/searchMetrics/handler.ts
Labels: ✅ Ready for merging

#4463 Ocrvs-4393 Adds changed for advanced search e2e test . Also contains some fixes for bugs mentions in 4112 and 4113
  packages/client/src/App.tsx
  packages/client/src/components/DateRangePickerForFormField.tsx
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/search/advancedSearch/utils.test.ts
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/search/src/features/search/utils.ts
Labels: 🏥 Failing Tests

#4461 Update Pill to use colors
  packages/components/src/Pill/Pill.tsx
Labels: ✅ Ready for merging

#4426 ocrvs-4410: Custom Field in form configuration becomes conditional field
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/config/src/handlers/formDraft/createFormDraft/handler.test.ts
  packages/config/src/handlers/formDraft/createFormDraft/handler.ts
  packages/config/src/handlers/question/updateQuestion/handler.ts
  packages/config/src/models/question.ts
Labels: ✅ Ready for merging

#4434 ocrvs-4307: UI issue in Form config: icon of error message not clearly visible
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/i18n/messages/views/customFieldForm.ts
Labels: 💅 Waiting For Review

#4452 Installed React-Signature-Canvas to configure Informant signature before registration
  package.json
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/tests/util.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  yarn.lock
Labels: 💅 Waiting For Review

#4444 chore(integration-configuration): System migrations for integration configuration
  packages/migration/migrate-mongo-config-user-mgnt.js
  packages/migration/migrations/application-config/20221212134153-update-systems.js
  packages/migration/migrations/user-mgnt/20221212134201-update-systems.js
  packages/migration/package.json
Labels: 💅 Waiting For Review, 👌LGTM

#4398 docs(1.2.0): ui-kit documentation and change log
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/FormConfigElementCard/FormConfigElementCard.stories.tsx
  packages/components/src/Toast/Toast.tsx
  packages/components/src/ToggleIcon/ToggleIcon.stories.tsx
  packages/components/src/ToggleIcon/ToggleIcon.tsx
  packages/components/stories/intro.stories.mdx
  packages/components/stories/releases.stories.mdx
Labels: 💅 Waiting For Review, 📄Documentation

#4322 OCRVS-4033 - Feature: Configurable admin levels
  packages/client/src/extract-translations.ts
  packages/client/src/forms/configuration/README.md
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/administrative/utils.ts
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/child-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/mutation/event-mappings.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/location.ts
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/setupTests.ts
  packages/client/src/tests/languages.json
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/locationUtils.test.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
  packages/client/src/views/SysAdmin/Performance/reports/utils.test.ts
  packages/client/typings/window.d.ts
  packages/components/src/AppHeader/Desktop/DesktopHeader.tsx
  packages/components/src/AppHeader/Mobile/MobileHeader.tsx
  packages/components/src/Workqueue/components/ListItemAction.tsx
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/configApi.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/influxdb/client.ts
  packages/metrics/test/setupJest.ts
Labels: 👌LGTM, ⏳ Waiting for CI, ✅ Ready for merging

#4480 NGA Death form changes - informant
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/i18n/messages/form.ts
  yarn.lock
Labels: 🇳🇬 Nigeria

#4474 OCRVS-4433: We need to make sure that default backups do not have run migrations in them
  infrastructure/clear-all-data.sh
  packages/migration/migrations/user-mgnt/20221212134201-update-systems.js
  packages/migration/package.json
  packages/migration/revertMigrations.sh
  packages/migration/runMigrations.sh
Labels: 👌LGTM

#4466 ocrvs-4214-fix Handled last name first on review header
  packages/client/src/utils/draftUtils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 🙋Question

#4479 NGA - Death form
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/ethnicOrigins.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/mutation/informant-mapping.ts
  packages/client/src/forms/register/fieldMappings/death/query/declaration-mappings.ts
  packages/client/src/forms/stateOfOrigins.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/components/src/components/forms/DateField.tsx
  packages/components/src/components/forms/Select.tsx
  packages/components/src/components/forms/TextInput.tsx
  packages/gateway/src/features/registration/fhir-builders.ts
  yarn.lock
Labels: ✅ Ready for merging

#4490 ocrvs-4485: On work queue users will only see corresponding location declarations
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/gateway/src/features/search/root-resolvers.ts
Labels: 🙋Question

#4132 Updated the influx library to the version 5.9.3 from 5.0.7
  packages/metrics/package.json
  packages/metrics/src/features/declarationsStarted/service.ts
  packages/metrics/src/features/getEventDuration/handler.ts
  packages/metrics/src/features/getTimeLogged/utils.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/searchMetrics/service.ts
  yarn.lock
Labels: ✋On Hold

#4505 ocrvs-4487: Fix overlap bookmark
  packages/client/src/components/Header/Header.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/components/src/SideNavigation/LeftNavigation.tsx
Labels: ✅ Ready for merging

#4506 Fixed eventLocation id not saving on search for death declarations
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/death/service.ts
  packages/workflow/src/features/registration/handler.ts
Labels: ✅ Ready for merging

#4509 Add delete_index privileges for elastic search
  infrastructure/elasticsearch/roles/search_user.json
Labels: 💅 Waiting For Review

#4507 Fix name not found on record audit page if french lang is selected
  packages/client/src/views/RecordAudit/utils.ts
Labels: 💅 Waiting For Review

#4508 OCRVS-4310: Resolve State & district of farajaland in summary page
  packages/client/src/views/CorrectionForm/utils.ts
Labels: 💅 Waiting For Review

#4476 ocrvs-3853: bugs
  packages/client/src/utils/gateway.ts
  packages/client/src/views/Performance/RegistrationsList.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
Labels: 💅 Waiting For Review

#4516 Add countryconfig service to SMS token audience
  packages/auth/src/features/authenticate/service.ts
  packages/auth/src/features/retrievalSteps/sendUserName/service.ts
  packages/auth/src/features/verifyCode/service.ts
Labels: 💅 Waiting For Review

#4315 Made user and userInput types more strict
  packages/client/graphql.schema.json
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/configuration/formConfig/utils/index.ts
  packages/client/src/profile/profileActions.ts
  packages/client/src/profile/profileReducer.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/Unlock/ForgotPIN.test.tsx
  packages/client/src/views/UserAudit/UserAudit.tsx
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/features/resendSMSInvite/handler.test.ts
  packages/user-mgnt/src/features/resetPassword/handler.test.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.test.ts
  packages/user-mgnt/src/model/user.ts
  packages/user-mgnt/tsconfig.json
Labels: 💅 Waiting For Review
