Repository opencrvs/opencrvs-core, pull requests merged in 2022-09, with the labels that each got.

#3867 OCRVS-3760 - `<Text>`
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/certificate/fieldDefinitions/payment-section.ts
  packages/client/src/forms/index.ts
  packages/client/src/styledComponents.ts
  packages/client/src/views/UserSetup/SecurityQuestionView.tsx
  packages/components/.storybook/preview.tsx
  packages/components/src/components/Text/Text.stories.tsx
  packages/components/src/components/Text/Text.tsx
  packages/components/src/components/Text/index.ts
  packages/components/src/components/charts/AxisTick.tsx
  packages/components/src/components/charts/TriLineChart.tsx
  packages/components/src/components/charts/VerticalBar.tsx
  packages/components/src/components/colors.ts
  packages/components/src/components/fonts.ts
  packages/components/src/components/forms/ErrorText.tsx
  packages/components/src/components/interface/Pill.tsx
  packages/components/src/components/styleguide/ThemeWrapper.tsx
  packages/components/src/components/theme.ts
  packages/components/src/components/typography/Paragraph.ts
  packages/components/src/components/typography/index.ts
Labels: 💅 Waiting For Review

#3826 ocrvs-3731 Added application version validation and clear declarations draft
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/storage.ts
  packages/client/src/utils.ts
  packages/client/src/utils/constants.ts
  packages/components/src/components/interface/Navigation/LeftNavigation.tsx
Labels: 💅 Waiting For Review

#3795 ocrvs-3788 Fixed default form not published issue
  packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.tsx
  packages/config/src/handlers/formDraft/updateFormDraft/handler.test.ts
  packages/config/src/handlers/formDraft/updateFormDraft/handler.ts
Labels: 💥 Hot Fixes

#3805 ocrvs 3581 User can't correct record if they are unassigned from that record
  packages/gateway/src/features/correction/root-resolvers.test.ts
  packages/gateway/src/features/correction/root-resolvers.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
Labels: 💥 Hot Fixes

#3889 ocrvs-3873 Disabled password change button in offline mode
  packages/client/src/views/Settings/items/Password.tsx
Labels: 💅 Waiting For Review

#3835 ocrvs-3332 Removed some unnecessary review modal descriptions
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/tests/languages.json
Labels: 💅 Waiting For Review

#3857 Update Node versions OpenCRVS supports
  .nvmrc
  README.md
  infrastructure/license-config.json
Labels: 💅 Waiting For Review

#3888 ocrvs-3870 Fixed performance page crashes when goes to online from offline state
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: 💅 Waiting For Review

#3876 ocrvs-3839 Added new clear and restore backup workflow action
  .github/workflows/reset-env-action.yml
Labels: 💅 Waiting For Review

#3883 ocrvs-3864 Fixed multiple time certificate prints system crash issue
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/RegisterForm/ReviewForm.tsx
Labels: 💅 Waiting For Review

#3827 Ocrvs 3209 Completeness rates fixes
  packages/client/src/components/LocationPicker.tsx
  packages/client/src/components/SegmentedControl.tsx
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx
Labels: 💅 Waiting For Review

#3787 ocrvs-3552: Use operation history to show last activity time in workqueue
  packages/client/src/declarations/index.ts
  packages/client/src/search/queries.ts
  packages/client/src/search/transformer.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/OfficeHome/utils.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
Labels: 🙋Question, 🔧Waiting for fixes

#3923 ocrvs-3864-fix Fixed markEventAsCertified handler issue in workflow
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
Labels: 💅 Waiting For Review

#3858 ocrvs-3781 Bootstrap minio
  .github/workflows/deploy.yml
  Dockerfile
  deploy.sh
  docker-compose.demo-deps.yml
  docker-compose.deploy.yml
  docker-compose.deps.yml
  docker-compose.dev-deps.yml
  docker-compose.prod-deploy.yml
  docker-compose.qa-deploy.yml
  docker-compose.yml
  infrastructure/nginx-deploy-config.sh
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  packages/auth/src/constants.ts
  packages/client/Dockerfile
  packages/components/src/components/interface/components/DocumentImage.tsx
  packages/documents/.dockerignore
  packages/documents/.eslintrc.js
  packages/documents/.gitignore
  packages/documents/Dockerfile
  packages/documents/logs/.gitignore
  packages/documents/package.json
  packages/documents/src/config/plugins.ts
  packages/documents/src/config/routes.ts
  packages/documents/src/constants.ts
  packages/documents/src/features/uploadDocument/handler.test.ts
  packages/documents/src/features/uploadDocument/handler.ts
  packages/documents/src/index.test.ts
  packages/documents/src/index.ts
  packages/documents/src/logger.ts
  packages/documents/src/minio/client.ts
  packages/documents/src/minio/constants.ts
  packages/documents/src/server.ts
  packages/documents/test/cert.key.pub
  packages/documents/test/setupJest.ts
  packages/documents/tsconfig.json
  packages/documents/typings/hapi-sentry.d.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/death-fhir-builders.test.ts
  packages/gateway/src/features/registration/fhir-builders.test.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/utils/validators.ts
  yarn.lock
Labels: 💅 Waiting For Review

#3874 ocrvs-3755 Generate birth and death declarations report from hearth-db
  docker-compose.deploy.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.yml
  packages/metrics/package.json
  packages/metrics/scripts/reportGenerator.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/constants.ts
  packages/metrics/src/features/vsExport/handler.ts
  packages/metrics/tsconfig.json
  yarn.lock
Labels: 💅 Waiting For Review

#3915 ocrvs-3837 Cron job scheduler for VSExport
  docker-compose.deploy.yml
  docker-compose.prod-deploy.yml
  docker-compose.yml
  infrastructure/license-config.json
  packages/metrics/src/constants.ts
  packages/scheduler/Dockerfile
  packages/scheduler/README.md
  packages/scheduler/cronTabFiles/VSExportCrontab
  packages/scheduler/jobs/runVSExport.sh
  packages/scheduler/start.sh
Labels: 💅 Waiting For Review

#3957 ocrvs-3838 Upload vsExport files to mino and store file urls to mongo reports collection
  deploy.sh
  docker-compose.deploy.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.yml
  infrastructure/mongodb/docker-entrypoint-initdb.d/create-mongo-users.sh
  infrastructure/mongodb/on-deploy.sh
  packages/documents/src/config/routes.ts
  packages/documents/src/features/uploadVSExportFile/handler.test.ts
  packages/documents/src/features/uploadVSExportFile/handler.ts
  packages/metrics/src/api.ts
  packages/metrics/src/config/database.test.ts
  packages/metrics/src/config/database.ts
  packages/metrics/src/constants.ts
  packages/metrics/src/features/vsExport/handler.ts
  packages/metrics/src/models/vsExports.ts
  packages/metrics/src/server.ts
Labels: 💅 Waiting For Review

#3961 OCRVS-3561: Date of informant etc
  .github/workflows/cd-manual-e2e.yml
  .github/workflows/e2e.yml
  infrastructure/server-setup/example-1.ini
  packages/client/src/forms/configuration/default.ts
Labels: 💅 Waiting For Review

#3799 OCRVS-3763 / `<Table>`
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserAuditList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserAuditList.tsx
  packages/components/src/ListTable/ListTable.stories.tsx
  packages/components/src/ListTable/ListTable.tsx
  packages/components/src/Table/Table.stories.tsx
  packages/components/src/Table/Table.tsx
  packages/components/src/Table/index.ts
  packages/components/src/Workqueue/types.ts
  packages/components/src/icons/index.ts
Labels: 🎁Components, 💅 Waiting For Review

#3956 Storybook intro
  packages/client/src/components/formConfig/formTools/components.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigSettings.tsx
  packages/components/.storybook/main.js
  packages/components/.storybook/preview.jsx
  packages/components/.storybook/theme.js
  packages/components/src/AppBar/AppBar.stories.tsx
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/Button/Button.tsx
  packages/components/src/Checkbox/Checkbox.stories.tsx
  packages/components/src/Content/Content.stories.tsx
  packages/components/src/DateField/DateField.stories.tsx
  packages/components/src/Divider/Divider.stories.mdx
  packages/components/src/ErrorMessage/ErrorMessage.stories.tsx
  packages/components/src/ErrorMessage/ErrorMessage.tsx
  packages/components/src/FormTabs/FormTabs.stories.tsx
  packages/components/src/Frame/Frame.stories.tsx
  packages/components/src/ImageUploader/ImageUploader.stories.tsx
  packages/components/src/LineChart/LineChart.stories.tsx
  packages/components/src/Link/Link.ts
  packages/components/src/ListViewSimplified/ListViewSimplified.stories.tsx
  packages/components/src/ListViewSimplified/ListViewSimplified.tsx
  packages/components/src/Pagination/Pagination.stories.tsx
  packages/components/src/Pill/Pill.stories.tsx
  packages/components/src/ProgressBar/ProgressBar.stories.tsx
  packages/components/src/ResponsiveModal/ResponsiveModal.stories.tsx
  packages/components/src/SearchTool/SearchTool.stories.tsx
  packages/components/src/Select/Select.stories.tsx
  packages/components/src/SubSectionDivider/SubSectionDivider.stories.tsx
  packages/components/src/Summary/Summary.stories.tsx
  packages/components/src/Summary/Summary.tsx
  packages/components/src/Summary/components/Row.tsx
  packages/components/src/Toggle/Toggle.stories.tsx
  packages/components/src/Toggle/Toggle.tsx
  packages/components/src/Toggle/index.ts
  packages/components/src/ToggleMenu/ToggleMenu.stories.tsx
  packages/components/src/WarningMessage/WarningMessage.stories.tsx
  packages/components/src/WarningMessage/WarningMessage.tsx
  packages/components/src/Workqueue/Workqueue.stories.tsx
  packages/components/src/icons/BackArrowDeepBlue.tsx
  packages/components/src/index.ts
  packages/components/stories/component-status.stories.mdx
  packages/components/stories/intro.stories.mdx
Labels: 🚧 work in progress

#3979 ocrvs-3977 Fixed multipleBirth of mother field value on declaration
  packages/client/src/tests/default.json
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
Labels: 💅 Waiting For Review

#3984 Button fixes
  packages/components/src/Alert/Alert.tsx
  packages/components/src/AppBar/AppBar.stories.tsx
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/Button/Button.tsx
  packages/components/src/Workqueue/Workqueue.stories.tsx
  packages/components/src/colors.ts
  packages/components/src/icons/Activity.tsx
  packages/components/src/icons/BackArrow.tsx
  packages/components/src/icons/ForwardArrowDeepBlue.tsx
  packages/components/src/icons/HelpBlue.tsx
  packages/components/stories/colors.stories.mdx
Labels: 🎁Components

#3981 Storybook intro updates
  packages/components/stories/intro.stories.mdx
Labels: 🎁Components

#3982 Ocrvs 2796 Fix empty location filter bug
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: ✅ Ready for merging

#3950 ocrvs-3640 userAudit frontend
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
Labels: 🚧 work in progress

#3834 OCRVS-3753: RECORD_SEARCH system client for advanced search
  packages/client/src/views/RecordAudit/History.tsx
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/features/user/utils/index.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/server.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/searchMetrics/handler.ts
  packages/metrics/src/features/searchMetrics/service.ts
  packages/metrics/src/influxdb/client.ts
  packages/search/src/config/routes.ts
  packages/search/src/features/registration/assignment/handler.test.ts
  packages/search/src/features/registration/assignment/handler.ts
  packages/search/src/features/search/handler.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/getUser/handler.ts
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/model/system.ts
  packages/user-mgnt/src/utils/userUtils.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/test/utils.ts
  packages/workflow/src/utils/authUtils.ts
  packages/workflow/src/utils/formDraftUtils.test.ts
Labels: 👌LGTM

#3862 Get styleguide hosted
  package.json
  packages/components/.storybook/main.js
  packages/components/Dockerfile
Labels: 💅 Waiting For Review

#4007 Revert "Revert "Get styleguide hosted""
  docker-compose.deploy.yml
  infrastructure/traefik.toml
  package.json
  packages/components/.storybook/main.js
  packages/components/Dockerfile
  packages/components/package.json
Labels: 📄Documentation

#3886 ocrvs-3025 Certificate config: Doc upload - use same component as gov logo upload
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
Labels: 👌LGTM

#3960 Upload buffer csv to minio and delete files after upload
  packages/documents/src/features/uploadVSExportFile/handler.ts
  packages/metrics/src/api.ts
  packages/metrics/src/features/vsExport/handler.ts
Labels: 💅 Waiting For Review

#3996 Fix navigation Performance Icon color
  packages/components/src/SideNavigation/NavigationItem.tsx
  packages/components/src/icons/Activity.tsx
  packages/components/src/icons/Users.tsx
Labels: ✅ Ready for merging

#4008 Storybook intro copy fixes
  packages/components/stories/intro.stories.mdx
  packages/components/stories/releases.stories.mdx
Labels: ✅ Ready for merging
