Repository opencrvs/opencrvs-core, pull requests merged in 2022-06, with the labels that each got.

#3277 ocrvs-3130 Team and Performance page offline state fix
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Team/TeamSearch.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: 💅 Waiting For Review

#3298 ocrvs-3252 Checked correct section for finding edited row
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: 💅 Waiting For Review

#3329 Removed clearing data on QA and some bugfixes
  deploy.sh
  infrastructure/clear-all-data.sh
  infrastructure/restore-metadata.sh
  package.json
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/user.ts
  packages/client/src/tests/default.json
  packages/client/src/tests/languages.json
  packages/login/src/i18n/messages/views/resetCredentialsForm.ts
  packages/login/src/views/resetCredentialsForm/phoneNumberVerificationForm.tsx
Labels: 💅 Waiting For Review

#3303 Ocrvs 3212: sorting in wq is being done by last column
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/OfficeHome/utils.ts
Labels: 👌LGTM

#3304 OCRVS-3284: Additional comment box not appear in death declaration page
  packages/client/src/forms/register/fieldMappings/death/mutation/event-mappings.ts
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#3306 ocrvs-3278 Custom phone number fixes
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/configuration/formConfig/utils.ts
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/SaveActionModal.test.tsx
  packages/config/src/handlers/formDraft/createFormDraft/handler.ts
Labels: 💅 Waiting For Review

#3310 OCRVS-3292 Fix place of death on certificate
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/mutation/event-mappings.ts
Labels: 💅 Waiting For Review

#3322 ocrvs-3114 Show full-screen modal on change password and deactivate user page
  packages/client/src/views/Settings/PasswordChangeModal.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
Labels: 💅 Waiting For Review

#3327 ocrvs-3263 dhis2Notification declaration history
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/user.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/components/src/components/icons/Box.tsx
  packages/components/src/components/icons/index.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#3337 Intl messages hotfix
  packages/client/src/i18n/messages/location.ts
  packages/client/src/i18n/messages/user.ts
  packages/client/src/tests/languages.json
Labels: 👌LGTM, 💥 Hot Fixes

#3342 performance-status-block-fix: Fixed performance page error
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/metricsQuery.ts
Labels: ⏳ Waiting for CI

#3338 ocrvs-3081: event column copy bug fixed on ready for review
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
Labels: 💅 Waiting For Review

#3345 ocrvs-2971 Fixed 'no' appearing instead of '-'
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#3346 Performance fixes continued
  packages/metrics/src/features/certifications/service.ts
Labels: 💅 Waiting For Review

#3343 ocrvs-3000: loading in search made same as workqueue
  packages/client/src/views/OfficeHome/LoadingIndicator.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#3331 FIX: Correct Record is not showing Informant details
  packages/client/src/declarations/index.ts
Labels: ✅ Ready for merging

#3344 National Registrars statistics
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/views/SysAdmin/Performance/ApplicationSourcesReport.tsx
Labels: 👌LGTM, ⏳ Waiting for CI

#3347 Fixed column alignment in performance view
  packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.tsx
Labels: 💅 Waiting For Review

#3348 Ocrvs 3024 Preview certificate print
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
Labels: 💅 Waiting For Review

#3358 ocrvs-3190: Added different message for showing yes and no in fees required in co…
  packages/client/src/forms/correction/payment.ts
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/i18n/messages/views/correction.ts
Labels: 💅 Waiting For Review

#3364 ocrvs-3098: document uploader alignment fixed in user review form
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.tsx
Labels: 💅 Waiting For Review

#3365 ocrvs-3071: no records tab in wq refactored
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/index.ts
  packages/client/src/i18n/messages/workQueue.ts
  packages/client/src/views/OfficeHome/inExternalValidation/InExternalValidationTab.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
Labels: 👌LGTM

#3369 ocrvs-3057: circle button modified in pagination
  packages/components/src/components/interface/PaginationModified.tsx
Labels: 👌LGTM

#3370 hotfix-ocrvs-3130 Fixed performance page offline to online state change issue
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: 💅 Waiting For Review

#3372 ocrvs-3179: Added currency of application config in performance
  packages/client/src/views/SysAdmin/Performance/PaymentsAmountComponent.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: 💅 Waiting For Review

#3388 ocrvs-3251: Fixed certification payment issue when payment is zero
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
Labels: 👌LGTM

#3376 ocrvs-3375 Changed verbiage for Corrected record history
  packages/client/src/views/RecordAudit/utils.ts
Labels: 💅 Waiting For Review, 👌LGTM

#3381 ocrvs-3363: default message added for registerConfirmationTitle
  packages/client/src/i18n/messages/views/review.ts
Labels: 💅 Waiting For Review

#3386 ocrvs-3308 Used proper ENCOUNTER_CODE depending on the event
  packages/gateway/src/features/registration/fhir-builders.ts
Labels: 💅 Waiting For Review, 👌LGTM

#3394 Also add questionnaire to death type-resolvers
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 👌LGTM, ⏳ Waiting for CI

#3393 FIX: Error message now gets displayed on validation fail
  packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx
Labels: 👌LGTM

#3395 Copy changes to names and login
  packages/client/src/forms/configuration/default.ts
  packages/client/src/i18n/messages/form.ts
  packages/login/src/i18n/messages/views/stepOneForm.ts
  packages/login/src/i18n/messages/views/stepTwoForm.ts
  packages/login/src/views/StepTwo/StepTwoForm.tsx
Labels: ⏳ Waiting for CI

#3396 Ocrvs 3340 Show signature selection form group for National Registrar
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/tests/default.json
Labels: 💅 Waiting For Review

#3404 ocrvs-3156: tooltip message added for form config
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/components/formConfig/formTools/components.tsx
  packages/client/src/i18n/messages/views/formConfig.ts
Labels: 👌LGTM

#3407 ocrvs-3269 Fixed application config fee input alignment issue
  packages/client/src/views/SysAdmin/Config/Application/DynamicModal.tsx
Labels: 💅 Waiting For Review

#3409 ocrvs-2812-fix: Fixed empty health institution issue
  packages/client/src/views/RecordAudit/utils.ts
Labels: 💅 Waiting For Review

#3412 Content fixes
  packages/client/src/components/Page.tsx
  packages/client/src/components/ProtectedPage.tsx
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/eventInfo.ts
  packages/client/src/i18n/messages/views/userForm.ts
  packages/client/src/tests/default.json
  packages/client/src/utils/constants.ts
  packages/client/src/views/PrintCertificate/utils.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
Labels: ⏳ Waiting for CI

#3414 ocrvs-2556 Show govt logo onboarding welcome screen
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/views/UserSetup/UserSetupPage.tsx
Labels: 👌LGTM

#3427 ocrvs:3267 Fixed correction update issue in performance page
  packages/client/src/views/CorrectionForm/utils.ts
Labels: 💅 Waiting For Review

#3428 ocrvs-2912 Replaced OpenCRVS logo with country logo
  packages/client/src/utils/userUtils.ts
  packages/client/src/views/RegisterForm/review/ReviewHeader.tsx
  packages/client/src/views/SysAdmin/Config/Application/Application.tsx
  packages/client/src/views/Unlock/ForgotPIN.tsx
  packages/client/src/views/Unlock/Unlock.tsx
  packages/client/src/views/UserSetup/UserSetupPage.tsx
  packages/components/public/logo.png
  packages/components/src/components/icons/CountryLogo.stories.tsx
  packages/components/src/components/icons/CountryLogo.tsx
  packages/components/src/components/icons/Logo.tsx
  packages/components/src/components/icons/index.ts
  packages/login/src/login/reducer.ts
  packages/login/src/login/selectors.ts
  packages/login/src/views/StepOne/StepOneForm.tsx
Labels: 💅 Waiting For Review

#3429 Ocrvs 3130 Handle offline state to layout right portion of Performance Home
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: 💅 Waiting For Review

#3434 Increased upload timeout and changed validation message on collector
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/mappings/deserializer.ts
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/i18n/messages/views/eventInfo.ts
  packages/client/src/utils/timeoutLink.ts
  packages/client/src/utils/validate.ts
Labels: ⏳ Waiting for CI

#3436 Ocrvs 3275 Fixed system crash after user creation and FA name sorting issue
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review

#3367 Ocrvs 2977 Fixed languages
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/secureAccount.ts
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/search/transformer.ts
  packages/client/src/utils/draftUtils.ts
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/SecureAccount/SecureAccountView.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: 💅 Waiting For Review

#3446 ocrvs-2156: tooltip added on custom field tools
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
Labels: 👌LGTM

#3448 ocrvs-3274 Fixed deactivated FA list filter issue on performance
  packages/client/src/views/Performance/FieldAgentList.tsx
Labels: 👌LGTM, 🏎 auto-merging

#3447 ocrvs:3421: Fixed multiple time currency appearing issue
  packages/client/src/forms/correction/payment.ts
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
Labels: 👌LGTM, ✅ Ready for merging

#3466 ocrvs-2544-fix: column alignmnt set to left on workflow status
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: 💅 Waiting For Review

#3463 ocrvs-3452 Fixed system crash when clicked back button after closing an incomplete declaration
  packages/client/src/views/RegisterForm/DeclarationForm.tsx
Labels: 👌LGTM, 🏎 auto-merging

#3467 Ocrvs 3423
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/components/src/components/interface/TableView.tsx
Labels: 👌LGTM

#3472 ocrvs-3456 Fixed mobile form config message typo
  packages/client/src/i18n/messages/views/formConfig.ts
Labels: 💅 Waiting For Review

#3465 Fixed console log error while filling up health institution from regi…
  packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
Labels: 👌LGTM, 🏎 auto-merging

#3438 ocrvs-3341: Removed a field from user review page if it is hidden in form
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#3458 ocrvs-3418-fix Fixed back button issue on team page
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review

#3475 ocrvs-3462: pagination added on workflowStatus on performance
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: 💅 Waiting For Review

#3479 ocrvs-2977-fix Some languages related change
  packages/client/src/components/LocationPicker.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/SysAdmin/Team/TeamSearch.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/components/src/components/interface/LocationSearch/LocationSearch.stories.tsx
  packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
Labels: 💅 Waiting For Review

#3455 ocrvs-3416: Disabled national registrar creation and update without signature
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 👌LGTM, ⏳ Waiting for CI

#3451 Auto hide Notification
  packages/components/src/components/interface/FloatingNotification.tsx
Labels: 💅 Waiting For Review

#3444 Ocrvs 2707: content page added on team page
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/navigation/index.ts
  packages/client/src/user/userReducer.ts
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/client/src/views/SysAdmin/Team/TeamSearch.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
  packages/components/src/components/interface/Header/AppHeader.stories.tsx
  packages/components/src/components/interface/Header/Mobile/MobileHeader.tsx
Labels: 👌LGTM

#3309 Deleted declarations from Field Agent that downloaded before 24 hours
  packages/client/src/declarations/index.ts
Labels: 👌LGTM, ⏳ Waiting for CI

#3493 ocrvs-3239 Fixed form config messages
  packages/client/src/i18n/messages/views/formConfig.ts
Labels: 💅 Waiting For Review

#3485 ocrvs 3471: Photo Spinning Issue
  packages/components/src/components/interface/components/PanViewer.tsx
Labels: 👌LGTM, ⏳ Waiting for CI, ☕️ Discussion

#3497 OCRVS-3368: FIX: Address Fields will be reset based on dependent fields
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/index.ts
Labels: ✅ Ready for merging

#3495 ocrvs-2841: padding issue fixed with ActionPageLight and SysAdminContentWrapper
  packages/client/src/views/SysAdmin/Config/Application/Application.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
  packages/components/src/components/interface/ActionPageLight.tsx
Labels: 💅 Waiting For Review

#3506 Conflicts fixes
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/search/queries.ts
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 🏥 Failing Tests

#3512 ocrvs-3496 Fixed cross button not working on user review form
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review

#3351 ocrvs-3114: Responsive modal set on middle of height of screen on desktop view.
  packages/client/src/views/Settings/PasswordChangeModal.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
  packages/components/src/components/interface/ResponsiveModal.tsx
Labels: 👌LGTM

#3526 Merging redux declarations with indexed declarations
  packages/client/src/declarations/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.init.test.tsx
Labels: 💅 Waiting For Review

#3380 ocrvs-3202 Modified layout of Change Avatar modal
  packages/client/src/views/Settings/AvatarChangeModal.tsx
  packages/components/src/components/icons/Square.tsx
  packages/components/src/components/icons/index.ts
  packages/components/src/components/interface/ResponsiveModal.tsx
Labels: 👌LGTM

#3519 ocrvs-3518 Fixed declarations assigned and registered issue for registrar
  packages/gateway/src/features/registration/root-resolvers.ts
Labels: 💅 Waiting For Review

#3529 Ocrvs 3516 Fixed record stays assigned to Registrar after printing issue
  packages/client/src/SubmissionController.ts
Labels: 💅 Waiting For Review

#3527 ocrvs-3488: no result message in search added
  packages/client/src/i18n/messages/views/search.ts
  packages/client/src/tests/languages.json
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#3523 ocrvs-3521 Fixed form config published/deleted issue for the first time
  packages/workflow/src/utils/formDraftUtils.ts
Labels: 💅 Waiting For Review

#3535 ocrvs-2895: deleted all code related to print receipt
  packages/client/src/views/PrintCertificate/PDFUtils.test.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/PrintCertificate/Payment.tsx
Labels: 💅 Waiting For Review

#3532 Ocrvs 3518 Fixed declarations remains downloaded after printing issue
  packages/client/src/SubmissionController.ts
Labels: 💅 Waiting For Review

#3534 Custom field refactor
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/formConfig/actions.ts
  packages/client/src/forms/configuration/formConfig/reducer.ts
  packages/client/src/forms/configuration/formConfig/utils/customConfig.ts
  packages/client/src/forms/configuration/formConfig/utils/previewGroup.ts
  packages/client/src/setupTests.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
Labels: 👌LGTM

#3538 ocrvs-3464: Fixed event select issue of registration by status page
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: 💅 Waiting For Review

#3539 ocrvs-3530 Hide form config not published config for mobile device
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx
Labels: 👌LGTM

#3541 ocrvs-3158 Changed FormConfig settings icon color and shape
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
  packages/components/src/components/icons/SettingsBlue.tsx
Labels: 👌LGTM

#3546 FIX: Form Config is now more responsive
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/forms/index.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
Labels: 💅 Waiting For Review

#3554 'createdAt' is being used in sentForReview column
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
Labels: 💅 Waiting For Review

#3579 ocrvs-3578 Fixed from config update bug
  packages/workflow/src/utils/formDraftUtils.ts
Labels: 💅 Waiting For Review

#3577 ocrvs-3568 Provided a way to recover from error
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/queries.ts
Labels: 💅 Waiting For Review

#3569 Add cert link and rename SMS env vars
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/notification/src/constants.ts
Labels: 💅 Waiting For Review, ⏳ Waiting for CI

#3609 removes ?? from templete
  .github/ISSUE_TEMPLATE/user-story.md
Labels: 💅 Waiting For Review
