Repository opencrvs/opencrvs-core, pull requests merged in 2022-10, with the labels that each got.

#3952 Cache deleting
  packages/client/src/src-sw.js
Labels: 💅 Waiting For Review

#4009 ocrvs-3868: Show a message 'updated' in the edited column of updatedhistories if the type is document
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: 💅 Waiting For Review

#4013 ocrvs-3859-fix Download certificate pdf in mobile device while printing
  packages/client/src/pdfRenderer/index.ts
Labels: 💅 Waiting For Review

#3943 ocrvs-3735 Changed labels for documents in review section
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/tests/languages.json
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#4030 ocrvs-3985 Fixed default configurable field required issue
  packages/client/src/forms/questionConfig/transformers.ts
Labels: ✅ Ready for merging

#4016 Pass applicationDebugVersion to LeftNavigation
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/index.tsx
  packages/client/src/utils/constants.ts
  packages/components/src/SideNavigation/LeftNavigation.stories.tsx
  packages/components/src/SideNavigation/LeftNavigation.tsx
Labels: ⏳ Waiting for CI

#3998 ocrvs-3917 Upgrade typescript
  packages/auth/package.json
  packages/auth/src/features/authenticate/__snapshots__/service.test.ts.snap
  packages/auth/src/features/authenticate/service.test.ts
  packages/auth/src/features/authenticate/service.ts
  packages/auth/src/features/refresh/handler.ts
  packages/commons/package.json
  packages/config/package.json
  packages/config/src/config/database.ts
  packages/config/src/handlers/certificate/certificateHandler.ts
  packages/config/src/utils/verifyToken.ts
  packages/gateway/package.json
  packages/gateway/src/features/registration/fhir-builders.test.ts
  packages/gateway/src/routes/verifyCode/handler.ts
  packages/gateway/tsconfig.json
  packages/integration/package.json
  packages/metrics/package.json
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/user-mgnt/src/database.ts
  packages/user-mgnt/src/features/activateUser/handler.test.ts
  packages/user-mgnt/src/features/changeAvatar/handler.test.ts
  packages/user-mgnt/src/features/changePassword/handler.test.ts
  packages/user-mgnt/src/features/changePhone/handler.test.ts
  packages/user-mgnt/src/features/createUser/handler.test.ts
  packages/user-mgnt/src/features/createUser/service.test.ts
  packages/user-mgnt/src/features/getAvatar/handler.test.ts
  packages/user-mgnt/src/features/getRoles/handler.ts
  packages/user-mgnt/src/features/getUser/handler.test.ts
  packages/user-mgnt/src/features/getUserMobile/handler.test.ts
  packages/user-mgnt/src/features/resendSMSInvite/handler.test.ts
  packages/user-mgnt/src/features/searchUsers/handler.ts
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/updateUser/handler.test.ts
  packages/user-mgnt/src/features/userAudit/handler.test.ts
  packages/user-mgnt/src/features/verifyPassword/handler.test.ts
  packages/user-mgnt/src/features/verifyPasswordById/handler.test.ts
  packages/user-mgnt/src/features/verifySecurityAnswer/handler.test.ts
  packages/user-mgnt/src/features/verifyUser/handler.test.ts
  packages/user-mgnt/typings/mockingoose.d.ts
  packages/webhooks/package.json
  packages/webhooks/src/database.ts
  packages/webhooks/src/features/manage/handler.test.ts
  packages/webhooks/typings/mockingoose.d.ts
  packages/workflow/package.json
  patches/mockingoose+2.15.2.patch
  yarn.lock
Labels: 💅 Waiting For Review

#4010 ocrvs-3852 Added conditional parameters for custom form field
  packages/client/graphql.schema.json
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/components/formConfig/formTools/components.tsx
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/configuration/formConfig/reducer.ts
  packages/client/src/forms/configuration/formConfig/utils/defaultConfig.ts
  packages/client/src/forms/configuration/formConfig/utils/index.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/i18n/messages/views/customFieldForm.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.test.tsx
  packages/client/src/views/Unlock/ForgotPIN.tsx
  packages/components/src/icons/Condition.stories.tsx
  packages/components/src/icons/Condition.tsx
  packages/components/src/icons/index.ts
  packages/config/src/handlers/question/createQuestion/handler.test.ts
  packages/config/src/handlers/question/createQuestion/handler.ts
  packages/config/src/handlers/question/getQuestions/handler.test.ts
  packages/config/src/handlers/question/updateQuestion/handler.test.ts
  packages/config/src/handlers/question/updateQuestion/handler.ts
  packages/config/src/models/question.ts
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#3938 Outbox v2
  packages/client/src/SubmissionController.ts
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/views/OfficeHome/LoadingIndicator.tsx
  packages/client/src/views/OfficeHome/NotificationToast.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/Outbox.test.tsx
  packages/client/src/views/OfficeHome/Outbox.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.test.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/components/src/icons/PaperPlane.stories.tsx
  packages/components/src/icons/PaperPlane.tsx
  packages/components/src/icons/StatusSubmissionWaiting.stories.tsx
  packages/components/src/icons/StatusSubmissionWaiting.tsx
  packages/components/src/icons/index.ts
Labels: ❌ Conflicts

#4057 Ocrvs 3650 Fix declaration icon color bug
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review, ⏳ Waiting for CI

#4058 ocrvs-3651 Changed uploaded icon to downloaded icon in draft tab
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
Labels: 💅 Waiting For Review

#4071 Fix the generate:test:forms command
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/index.tsx
  packages/client/src/utils/constants.ts
Labels: ⏳ Waiting for CI

#4012 Ocrvs 3636 - As a National Registrar / National Sys Admin I want to view available VS exports
  packages/client/graphql.schema.json
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/utils/constants.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Performance/Vsexports/VSExport.tsx
  packages/client/src/views/SysAdmin/Performance/Vsexports/queries.ts
  packages/components/src/components/icons/Export.tsx
  packages/components/src/components/icons/index.ts
  packages/components/src/components/interface/Navigation/NavigationGroup.stories.tsx
  packages/components/src/components/interface/Navigation/NavigationItem.stories.tsx
  packages/components/src/components/interface/Navigation/NavigationSubItem.stories.tsx
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/vsExport/handler.ts
Labels: 🔧Waiting for fixes

#4045 hide delete button on preview screen for small web screens
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging

#4068 ocrvs-3927: add field ID section on the right side nav in form config
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/i18n/messages/views/formConfig.ts
Labels: ✅ Ready for merging

#4069 ocrvs-4019 Fixed publishedWarning message on declaration form config page
  packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx
Labels: ✅ Ready for merging

#4072 In offline on application config, government logo modal showing incorrect message #3843
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/GovtLogo.tsx
Labels: ✅ Ready for merging

#4074 ocrvs-4032 Fixed ForgotPIN page UI issue
  packages/client/src/views/Unlock/ForgotPIN.tsx
Labels: ✅ Ready for merging

#4081 Removed ID check table from correction summary page
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
Labels: ✅ Ready for merging

#4093 Invert conditional logic for customize field
  packages/client/src/forms/configuration/customUtils.ts
Labels: 💅 Waiting For Review

#4085 OCRVS-4056 Fix application config regex overflow
  packages/client/src/views/SysAdmin/Config/Application/Components.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/NIDNumPattern.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/PhoneNumPattern.tsx
  packages/components/src/Text/Text.stories.tsx
  packages/components/src/Text/Text.tsx
Labels: ✅ Ready for merging

#3724 Submits death webhook and handles new MOSIP UIN requirement
  .github/workflows/deploy.yml
  deploy.sh
  infrastructure/openhim-base-config.json
  infrastructure/restore-metadata-updates.sh
  infrastructure/server-setup/playbook-3.yml
  package.json
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/tests/default.json
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/typings/window.d.ts
  packages/config/src/config/routes.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/constants.ts
  packages/metrics/test/setupJest.ts
  packages/migration/migrations/openhim/20221011150329-channels-v1.1.0-to-v1.2.0.cjs
  packages/webhooks/src/config/routes.ts
  packages/webhooks/src/features/event/handler.ts
  packages/webhooks/src/features/event/service.test.ts
  packages/webhooks/src/features/event/service.ts
  packages/workflow/src/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/test/utils.ts
  yarn.lock
Labels: 📄Documentation

#4078 ocrvs-3933 Fixed corrector requester bug
  packages/client/src/declarations/index.ts
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: ✅ Ready for merging

#4096 fix spacing below top nav bar
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/components/src/Content/Container.tsx
Labels: ✅ Ready for merging

#4050 Disable arrow back button if correction is made or after printing a certificate
  packages/client/src/components/Header/Header.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/tests/default.json
  packages/client/src/tests/mock-drafts.ts
  packages/client/src/views/CorrectionForm/CorrectionForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.test.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
Labels: ✅ Ready for merging

#4104 Added custom Required error message on correction page
  packages/client/src/forms/correction/reason.ts
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/i18n/messages/views/correction.ts
Labels: ✅ Ready for merging

#4079 ocrvs-3926 - Default "Has a cause of death been established?" to "No" with checkbox
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/components/src/Select/Select.tsx
Labels: ✅ Ready for merging

#4002 OCRVS-3997 / Ready for review -page accessibility
  packages/client/src/components/charts/RegRatesLineChart.tsx
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/components.tsx
  packages/client/src/views/OfficeHome/inExternalValidation/InExternalValidationTab.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/components/.eslintrc.js
  packages/components/.storybook/main.js
  packages/components/.storybook/preview.jsx
  packages/components/package.json
  packages/components/src/Button/Button.styles.ts
  packages/components/src/Content/Content.stories.tsx
  packages/components/src/DateField/DateField.stories.tsx
  packages/components/src/DocumentViewer/components/PanDraggable.tsx
  packages/components/src/DocumentViewer/components/PanViewer.tsx
  packages/components/src/Frame/Frame.stories.tsx
  packages/components/src/Frame/Frame.tsx
  packages/components/src/Frame/components/SkipToContent.tsx
  packages/components/src/ImageUploader/ImageUploader.stories.tsx
  packages/components/src/InputField/InputField.tsx
  packages/components/src/LineChart/LineChart.stories.tsx
  packages/components/src/LineChart/LineChart.tsx
  packages/components/src/Link/Link.stories.tsx
  packages/components/src/Link/Link.tsx
  packages/components/src/ListTable/ListTable.stories.tsx
  packages/components/src/ListViewSimplified/ListViewSimplified.stories.tsx
  packages/components/src/LocationSearch/LocationSearch.stories.tsx
  packages/components/src/LocationSearch/LocationSearch.tsx
  packages/components/src/PINKeypad/PINKeypad.stories.tsx
  packages/components/src/PINKeypad/PINKeypad.tsx
  packages/components/src/Pagination/Pagination.tsx
  packages/components/src/Radio/Radio.tsx
  packages/components/src/SideNavigation/NavigationItem.tsx
  packages/components/src/ToggleMenu/ToggleMenu.tsx
  packages/components/src/ViewData/DataRow.tsx
  packages/components/src/ViewData/DataSection.tsx
  packages/components/src/ViewData/ListRow.tsx
  packages/components/src/Workqueue/Workqueue.stories.tsx
  packages/components/src/Workqueue/components/ListItemAction.tsx
  packages/components/src/Workqueue/components/WorkqueueRowDesktop.tsx
  packages/components/src/buttons/LinkButton.stories.tsx
  packages/components/src/buttons/LinkButton.tsx
  packages/components/stories/releases.stories.mdx
  yarn.lock
Labels: ✅ Ready for merging

#4097 Ocrvs 3126 - Form radio buttons should be Checkbox's
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/tests/default.json
  packages/client/src/views/PrintCertificate/Payment.test.tsx
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/components/src/Link/Link.tsx
Labels: 💅 Waiting For Review

#4115 Replaced Uploaded Icon with Downloaded Icon for Draft Record Audit Page
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: ✅ Ready for merging

#4133 Add signature input for informant when B1 form is not present
  packages/client/package.json
  packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  yarn.lock
Labels: 🇳🇬 Nigeria

#4131 Nigeria form changes
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/documents-mappings.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/i18n/messages/views/eventInfo.ts
  packages/client/src/utils/validate.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🇳🇬 Nigeria

#4140 Amended CHECKBOX field
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging

#4130 Fixed adding custom input field error on CustomFieldTool
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
Labels: 💅 Waiting For Review

#4149 ocrvs-4105 Backend+Frontend
  packages/client/graphql.schema.json
  packages/client/src/App.tsx
  packages/client/src/components/Header/Header.tsx
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/i18n/messages/views/header.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/search/queries.ts
  packages/client/src/utils/constants.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.test.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/SearchResult/queries.ts
  packages/components/src/Icon/types.ts
  packages/components/src/SearchTool/SearchTool.tsx
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.test.ts
  packages/search/src/features/search/utils.ts
Labels: 💅 Waiting For Review

#4076 ocrvs-3544 Amend history actions
  packages/client/graphql.schema.json
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/utils/draftUtils.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/utils.ts
  packages/gateway/src/config/plugins.ts
  packages/gateway/src/features/correction/root-resolvers.test.ts
  packages/gateway/src/features/fhir/constants.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/fhir-builders.test.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/utils/testUtils.ts
  packages/search/src/config/routes.ts
  packages/search/src/features/search/handler.ts
  packages/workflow/src/config/plugins.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/task/fhir/constants.ts
  packages/workflow/src/features/task/fhir/utils.test.ts
  packages/workflow/src/features/task/fhir/utils.ts
  packages/workflow/src/features/task/handler.ts
  packages/workflow/src/features/user/utils.ts
  packages/workflow/src/test/utils.ts
  packages/workflow/src/utils/formDraftUtils.test.ts
Labels: 👌LGTM

#4151 Feedback changes
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/gateway/src/features/location/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🇳🇬 Nigeria

#4067 OCRVS-1098: Upgrade to Traefik 2.8
  docker-compose.deploy.yml
  infrastructure/traefik.toml
Labels: 💅 Waiting For Review

#4154 QR codes & other updates in birth certificate
  packages/client/package.json
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/pdfRenderer/index.ts
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
  yarn.lock
Labels: 🇳🇬 Nigeria

#3721 [1.0.3] OCRVS-3673: Move the sending logic out of notification service into a country config package handler
  .vscode/settings.json
  packages/components/src/Icon/types.ts
  packages/components/src/Select/Select.tsx
  packages/notification/Dockerfile
  packages/notification/package.json
  packages/notification/src/constants.ts
  packages/notification/src/features/sms/service.test.ts
  packages/notification/src/features/sms/service.ts
  packages/notification/src/features/sms/utils.ts
  packages/notification/typings/iconv.d.ts
  yarn.lock
Labels: 🔧Waiting for fixes, 📄Documentation

#4162 Upgrade Sentry
  infrastructure/nginx-default.conf
  packages/client/package.json
  packages/client/src/components/ErrorBoundary.tsx
  packages/client/src/components/Query.tsx
  packages/client/src/components/StyledErrorBoundary.tsx
  packages/client/src/components/form/FetchButton.tsx
  packages/client/src/index.tsx
  packages/client/src/profile/serviceApi.ts
  packages/client/src/store.ts
  packages/client/src/utils/apolloClient.ts
  packages/client/src/utils/authApi.ts
  packages/client/src/utils/authUtils.ts
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/login/package.json
  packages/login/src/ErrorBoundary.tsx
  packages/login/src/index.tsx
  packages/login/src/store.ts
  packages/login/src/utils/authApi.ts
  packages/login/src/utils/authUtils.ts
  yarn.lock
Labels: 🔧Waiting for fixes

#4124 ocrvs-4039 Reset password feature
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/user/mutations.ts
  packages/client/src/user/queries.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/notification/src/config/routes.ts
  packages/notification/src/features/sms/user-handler.test.ts
  packages/notification/src/features/sms/user-handler.ts
  packages/notification/src/features/sms/utils.ts
  packages/notification/src/i18n/messages.ts
  packages/notification/src/tests/util.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/resstPassword/handler.test.ts
  packages/user-mgnt/src/features/resstPassword/handler.ts
Labels: 💅 Waiting For Review

#4116 ocrvs n 4038 Send a username reminder
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/user/mutations.ts
  packages/client/src/user/queries.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/components/src/Select/Select.tsx
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.test.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/service.ts
Labels: 💅 Waiting For Review

#4107 Handle supervisory area extension in gateway
  packages/auth/src/features/retrievalSteps/verifyUser/handler.ts
  packages/client/graphql.schema.json
  packages/client/src/components/LocationPicker.tsx
  packages/client/src/components/ProfileMenu.tsx
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/userForm.ts
  packages/client/src/profile/queries.ts
  packages/client/src/user/queries.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/utils/userUtils.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/client/src/views/Settings/items/Title.tsx
  packages/client/src/views/Settings/items/index.ts
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx
  packages/client/src/views/SysAdmin/Performance/LocationPicker.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Team/TeamSearch.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/utils.ts
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/features/verifyUser/handler.ts
  packages/user-mgnt/src/model/user.ts
Labels: ⛔ Blocked, 🇳🇬 Nigeria

#4166 #4141 new handler and route to retreive all systems
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/system/handler.ts
Labels: 🔧Waiting for fixes

#4106 ocrvs-3975 Removed e2e file and modified check-before-build file
  .github/workflows/cd-to-staging.yml
  .github/workflows/e2e.yml
  check-before-build.sh
  packages/client/src/views/PrintCertificate/Payment.test.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.test.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.test.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/PrintCertificate/utils.ts
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
Labels: 💅 Waiting For Review

#4077 Ocrvs 3955 - Minio url caching and invalidation of caching
  .github/workflows/deploy.yml
  deploy.sh
  docker-compose.deploy.yml
  docker-compose.dev-deps.yml
  docker-compose.yml
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  packages/client/src/declarations/index.ts
  packages/client/src/src-sw.js
  packages/client/src/utils/commonUtils.ts
  packages/client/src/utils/constants.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/components/src/DocumentViewer/components/DocumentImage.tsx
  packages/documents/package.json
  packages/documents/src/minio/client.ts
  packages/metrics/src/config/database.ts
Labels: 👌LGTM

#4148 Created page template to view list of Client in Integrations page
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/SysAdmin/Config/Integrations/Integrations.tsx
Labels: 💅 Waiting For Review

#4080 <Toast/> component updated
  packages/client/src/components/Notification.tsx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/Toast/Toast.stories.mdx
  packages/components/src/Toast/Toast.tsx
Labels: 💅 Waiting For Review

#4052 Ocrvs 3942 audit v2
  .gitignore
  infrastructure/license-config.json
  packages/auth/src/constants.ts
  packages/auth/src/features/authenticate/service.ts
  packages/auth/src/features/invalidateToken/handler.ts
  packages/auth/src/features/retrievalSteps/sendUserName/handler.test.ts
  packages/auth/src/features/retrievalSteps/sendUserName/handler.ts
  packages/auth/src/features/retrievalSteps/sendUserName/service.ts
  packages/auth/src/features/retrievalSteps/verifyUser/service.ts
  packages/auth/src/features/verifyCode/handler.ts
  packages/client/graphql.schema.json
  packages/client/src/components/Header/Header.tsx
  packages/client/src/components/Page.tsx
  packages/client/src/components/ProtectedPage.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/i18n/messages/views/userSetup.ts
  packages/client/src/user/queries.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/client/src/views/UserAudit/UserAudit.tsx
  packages/client/src/views/UserAudit/UserAuditHistory.test.tsx
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
  packages/components/src/Icon/types.ts
  packages/components/src/Select/Select.tsx
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/audit/handler.ts
  packages/metrics/src/features/audit/service.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/utils/authUtils.ts
  packages/user-mgnt/src/constants.ts
  packages/user-mgnt/src/features/changePassword/handler.ts
  packages/user-mgnt/src/features/changePhone/handler.ts
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/features/userAudit/handler.ts
  packages/user-mgnt/src/features/verifyPassword/handler.ts
  packages/user-mgnt/src/features/verifyUser/handler.ts
  packages/user-mgnt/src/utils/userUtils.ts
Labels: 🔧Waiting for fixes

#4144 Fuzzy matching in location search in performance page
  packages/client/src/components/LocationPicker.tsx
  packages/components/package.json
  packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
  yarn.lock
Labels: 🚧 work in progress, 🇳🇬 Nigeria

#4163 Ocrvs 4134 - Accordion component
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/components/src/Accordion/Accordion.stories.tsx
  packages/components/src/Accordion/Accordion.tsx
  packages/components/src/Accordion/index.ts
Labels: 🚧 work in progress

#4098 ocrvs-4004: Add a constant 'ENABLE_REVIEW_SCROLL' and prevent scrolling of documents in document review section
  packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/utils/constants.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 🔧Waiting for fixes

#4066 Changes bug template
  .github/ISSUE_TEMPLATE/---bug.md
  .github/ISSUE_TEMPLATE/bug.md
Labels: 💅 Waiting For Review
