Repository opencrvs/opencrvs-core, pull requests merged in 2022-04, with the labels that each got.

#2795 Improved the form draft handler
  packages/config/src/handlers/updateFormDraft/handler.test.ts
  packages/config/src/handlers/updateFormDraft/handler.ts
Labels: 💅 Waiting For Review

#2766 Created a simplified ListView component
  packages/components/src/components/buttons/Button.tsx
  packages/components/src/components/buttons/index.ts
  packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.stories.tsx
  packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.tsx
  packages/components/src/components/interface/Pill.stories.tsx
  packages/components/src/components/interface/Pill.tsx
  packages/components/src/components/interface/ToggleMenu.tsx
  packages/components/src/components/interface/index.ts
Labels: ✅ Ready for merging

#2763 Added new user information
  README.md
Labels: 👌LGTM, ⏳ Waiting for CI

#2784 OCRVS-2559-dynamicModal: NIDPhoneNumContent on DynamicModal fixed
  packages/client/src/views/SysAdmin/Config/DynamicModal.tsx
  packages/client/src/views/SysAdmin/Config/NIDPhoneNumContent.tsx
  packages/components/src/components/interface/ResponsiveModal.tsx
Labels: 👌LGTM

#2808 OCRVS-2381: List view simplified on settings page
  packages/client/src/i18n/messages/user.ts
  packages/client/src/views/Settings/Settings.test.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/components/src/components/buttons/LinkButton.tsx
  packages/components/src/components/interface/Content.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2789 ocrvs-2562 Fixed some UI issue in application config
  packages/client/src/forms/configuration/index.ts
  packages/client/src/views/SysAdmin/Config/Application.tsx
  packages/client/src/views/SysAdmin/Config/DynamicModal.tsx
  packages/client/src/views/SysAdmin/Config/utils.ts
  packages/components/src/components/interface/Tabs.tsx
Labels: 👌LGTM, 🏎 auto-merging

#2769 Ocrvs 2740: form-config-wizard basic markup completed.
  packages/client/src/App.tsx
  packages/client/src/components/formConfig/FormConfigCanvas.tsx
  packages/client/src/components/formConfig/PageNavigation.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/FormConfig.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/authUtils.ts
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/client/src/views/SysAdmin/Config/FormConfigWizard.test.tsx
  packages/client/src/views/SysAdmin/Config/FormConfigWizard.tsx
  packages/components/src/components/buttons/Toggle.tsx
  packages/components/src/components/interface/EventTopBar.tsx
  packages/components/src/components/interface/Navigation/NavigationSubItem.tsx
Labels: 👌LGTM

#2858 ocrvs-2402-fix: supporting document bug fixed
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.test.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/components/src/components/icons/Delete.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2868 ocrvs-2402: FormFieldGenerator bug fix
  packages/client/src/components/form/FormFieldGenerator.tsx
Labels: 💥 Hot Fixes

#2817 ocrvs-2739 Improved form draft fetching reducer
  packages/client/src/forms/configuration/actions.ts
  packages/client/src/forms/configuration/reducer.ts
  packages/client/src/views/SysAdmin/Config/Form/FormConfiguration.test.tsx
  packages/client/src/views/SysAdmin/Config/Form/FormConfiguration.tsx
Labels: 🔧Waiting for fixes

#2848 ocrvs-navigation: intl used on navigation messages
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/navigation/index.ts
  packages/client/src/tests/util.tsx
  packages/client/src/views/FieldAgentHome/FieldAgentHome.test.tsx
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/OfficeHome/OfficeHome.test.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/tabs/reject/rejectTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/review/reviewTab.test.tsx
  packages/components/src/components/interface/Navigation/NavigationItem.tsx
  packages/components/src/components/interface/Navigation/NavigationSubItem.tsx
Labels: ✅ Ready for merging

#2854 Ocrvs 2404 Bug fixes
  packages/client/src/forms/correction/payment.ts
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/components/src/components/interface/TableView.tsx
Labels: 💅 Waiting For Review

#2876 ocrvs-2853: Language bug fix
  packages/client/src/views/Settings/SettingsPage.tsx
Labels: ⏳ Waiting for CI, ✅ Ready for merging

#2875 ocrvs-2791 Fixed user form signature error issue
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 👌LGTM, ⏳ Waiting for CI

#2745 Updates Box component and uses it in Content component
  packages/client/src/components/Page.tsx
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/components/src/components/buttons/ListItemAction.tsx
  packages/components/src/components/interface/ActionPageLight.tsx
  packages/components/src/components/interface/Box.tsx
  packages/components/src/components/interface/Content.tsx
  packages/components/src/components/interface/EventTopBar.tsx
  packages/components/src/components/interface/Header/Mobile/MobileHeader.tsx
  packages/components/src/components/interface/Header/PageHeader.stories.tsx
  packages/components/src/components/interface/Header/PageHeader.tsx
  packages/components/src/components/interface/Navigation/LeftNavigation.tsx
  packages/components/src/components/interface/Tabs.tsx
  packages/components/src/components/interface/ViewData/ListRow.tsx
  packages/components/src/components/interface/index.ts
Labels: 💅 Waiting For Review

#2874 Showed brn/drn with grey box when record is not downloaded
  packages/client/src/views/Home/RecordAudit.tsx
Labels: 👌LGTM, ✅ Ready for merging

#2860 ocrvs-2793 Removed Performance Oversight role from core
  packages/client/src/i18n/messages/user.ts
  packages/client/src/tests/languages.json
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/user-mgnt/src/utils/userUtils.ts
Labels: 👌LGTM, ⏳ Waiting for CI

#2857 Fixed issues of creating new password for a new user
  packages/client/src/views/UserSetup/CreatePassword.test.tsx
  packages/client/src/views/UserSetup/CreatePassword.tsx
Labels: ✅ Ready for merging

#2813 ocrvs-2774 Amend Question label, placeholder, description & tool tip for localisation.
  packages/client/src/components/Page.tsx
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/index.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/tests/util.tsx
  packages/config/src/handlers/createQuestion/handler.test.ts
  packages/config/src/handlers/createQuestion/handler.ts
  packages/config/src/handlers/getQuestions/handler.test.ts
  packages/config/src/handlers/updateFormDraft/handler.ts
  packages/config/src/handlers/updateQuestion/handler.test.ts
  packages/config/src/handlers/updateQuestion/handler.ts
  packages/config/src/models/question.ts
  packages/gateway/src/features/formDraft/schema.graphql
  packages/gateway/src/features/questions/root-resolvers.test.ts
  packages/gateway/src/features/questions/root-resolvers.ts
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#2851 Ocrvs 2400 Fixed Corrector VerifyID bugs
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/components/src/components/interface/ResponsiveModal.tsx
  packages/components/src/components/interface/ViewData/LabelValuePair.tsx
Labels: 💅 Waiting For Review

#2867 ocrvs-2457 Removed archived button from SentForApproval queue
  packages/client/src/views/Home/RecordAudit.tsx
Labels: 👌LGTM

#2873 ocrvs-2424-fix: bug fixed for record-audit summary
  packages/client/src/views/Home/RecordAudit.tsx
Labels: 💅 Waiting For Review

#2890 Modified the ListViewItem actions prop
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.stories.tsx
  packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.tsx
Labels: 👌LGTM

#2893 Store environment variables in Github Environments, create a multi-purpose deployment pipeline
  .github/workflows/cd-manual-e2e.yml
  .github/workflows/cd-release.yml
  .github/workflows/cd-version.yml
  .github/workflows/deploy.yml
Labels: 💅 Waiting For Review

#2832 UI updates to TableView
  packages/client/src/views/Home/RecordAudit.tsx
  packages/components/src/components/interface/TableView.tsx
Labels: 👌LGTM

#2889 ocrvs-2776-fix: Fixed alignment issues of loader in responsive screen
  packages/client/src/components/Page.tsx
  packages/client/src/components/ProtectedPage.tsx
Labels: 👌LGTM

#2788 [OCRVS-2781] Enabling access control on a MongoDB deployment
  deploy.sh
  docker-compose.deploy.yml
  docker-compose.prod-deploy-3.yml
  docker-compose.prod-deploy-5.yml
  infrastructure/clear-all-data.sh
  infrastructure/emergency-backup-metadata.sh
  infrastructure/emergency-restore-metadata.sh
  infrastructure/mongodb/README.md
  infrastructure/mongodb/docker-entrypoint-initdb.d/create-mongo-users.sh
  infrastructure/mongodb/on-deploy.sh
  infrastructure/restore-metadata-updates.sh
  infrastructure/restore-metadata.sh
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
Labels: 👌LGTM

#2891 [OCRVS-2807] Setup basic credentials and authentication for ElasticSearch and applications using it
  deploy.sh
  docker-compose.deploy.yml
  infrastructure/clear-all-data.sh
  infrastructure/elasticsearch/elasticsearch.yml
  infrastructure/elasticsearch/roles/kibana_user.json
  infrastructure/elasticsearch/roles/search_user.json
  infrastructure/elasticsearch/setup-helpers.sh
  infrastructure/elasticsearch/setup-users.sh
  infrastructure/emergency-backup-metadata.sh
  infrastructure/emergency-restore-metadata.sh
  infrastructure/monitoring/apm/apm-server.yml
  infrastructure/monitoring/beats/metricbeat.yml
  infrastructure/monitoring/kibana/alert-rules.json
  infrastructure/monitoring/kibana/setup-alerts.js
  infrastructure/server-setup/README.md
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  infrastructure/setup-deploy-config.sh
Labels: 👌LGTM

#2922 Merge master to develop
  README.md
  dev.sh
  packages/auth/package.json
  packages/client/package.json
  packages/commons/package.json
  packages/components/package.json
  packages/gateway/package.json
  packages/integration/package.json
  packages/login/package.json
  packages/metrics/package.json
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/webhooks/package.json
  packages/workflow/package.json
  setup.sh
Labels: 💅 Waiting For Review

#2894 Changed Content component Tab bar to accept buttons
  packages/client/src/views/SysAdmin/Config/Application.tsx
  packages/components/src/components/interface/Box.tsx
  packages/components/src/components/interface/Content.tsx
Labels: 💅 Waiting For Review

#2907 ocrvs-2870 Form Config Settings
  packages/client/src/App.tsx
  packages/client/src/components/formConfig/SectionNavigation.tsx
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/navigation/index.ts
  packages/client/src/setupTests.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SysAdmin/Config/Application/DynamicModal.tsx
  packages/client/src/views/SysAdmin/Config/Application/utils.ts
  packages/client/src/views/SysAdmin/Config/Forms/FormConfigSettings.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/FormConfigSettings.tsx
  packages/client/src/views/SysAdmin/Config/Forms/FormConfigWizard.tsx
  packages/client/typings/window.d.ts
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/login/src/utils/authApi.ts
  packages/metrics/src/configApi.ts
  packages/metrics/src/constants.ts
  packages/metrics/test/setupJest.ts
Labels: 👌LGTM, ✅ Ready for merging

#2885 various ui bug fixes
  packages/client/src/components/StyledErrorBoundary.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/components/src/components/buttons/SecondaryButton.tsx
  packages/components/src/components/colors.ts
  packages/components/src/components/forms/DateField.tsx
  packages/components/src/components/forms/ImageUploader.tsx
  packages/components/src/components/forms/PasswordInput.tsx
  packages/components/src/components/forms/Select.tsx
  packages/components/src/components/forms/TextArea.tsx
  packages/components/src/components/forms/TextInput.tsx
  packages/components/src/components/icons/BRN.tsx
  packages/components/src/components/icons/Phone.tsx
  packages/components/src/components/icons/TrackingID.tsx
  packages/components/src/components/icons/User.tsx
  packages/components/src/components/interface/Divider.tsx
  packages/components/src/components/interface/SearchTool/SearchTool.tsx
  packages/components/src/components/interface/Tabs.tsx
  packages/components/src/components/interface/ToggleMenu.tsx
  packages/components/src/components/interface/index.ts
Labels: 👌LGTM

#2931 New performance home
  packages/client/src/App.tsx
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/ApplicationSourcesComp.tsx
  packages/client/src/views/SysAdmin/Performance/CertificationRateComponent.tsx
  packages/client/src/views/SysAdmin/Performance/CompletenessReport.tsx
  packages/client/src/views/SysAdmin/Performance/CorrectionsReport.tsx
  packages/client/src/views/SysAdmin/Performance/NoResultMessage.tsx
  packages/client/src/views/SysAdmin/Performance/OperationalReport.test.tsx
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
  packages/client/src/views/SysAdmin/Performance/PaymentsAmountComponent.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceStats.tsx
  packages/client/src/views/SysAdmin/Performance/RegistrationRates.tsx
  packages/client/src/views/SysAdmin/Performance/RegistrationsReport.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/metricsQuery.ts
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/client/src/views/SysAdmin/Performance/utils.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/components/src/components/icons/Activity.tsx
  packages/components/src/components/interface/Content.tsx
  packages/components/src/components/interface/ResponsiveModal.tsx
  packages/gateway/src/features/metrics/root-resolvers.ts
Labels: 💅 Waiting For Review

#2954 Location stats frontend
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/views/SysAdmin/Performance/CorrectionsReport.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceStats.tsx
  packages/client/src/views/SysAdmin/Performance/metricsQuery.ts
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/config/routes.ts
  packages/search/src/features/search/handler.ts
  packages/search/src/features/search/utils.ts
Labels: 🔧Waiting for fixes

#2948 Fetched practitioner role from task business status
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/pointGenerator.ts
Labels: 💅 Waiting For Review

#2959 Ocrvs-2838-update-field-agent-list: Updated field agent list with content component
  packages/client/src/tests/schema.graphql
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#2969 OCRVS-2958 Added modal for form config mobile view
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/views/SysAdmin/Config/Forms/Home/DraftsTab.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigMobileViewModal.tsx
Labels: ✅ Ready for merging

#2945 Form config 2728
  packages/client/src/App.tsx
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/CustomFieldForm.tsx
  packages/client/src/components/formConfig/SectionNavigation.tsx
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/configFields/actions.ts
  packages/client/src/forms/configuration/configFields/reducer.ts
  packages/client/src/forms/configuration/configFields/utils.ts
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/views/customFieldForm.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/views/SysAdmin/Config/Forms/Home/ActionsModal.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
  packages/components/src/components/buttons/Toggle.tsx
  packages/components/src/components/icons/Tooltip.tsx
  packages/components/src/components/interface/FormConfigElementCard.tsx
Labels: ✅ Ready for merging

#2963 Ocrvs 2775
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/utils/authUtils.ts
  packages/client/src/views/OfficeHome/LoadingIndicator.test.tsx
  packages/client/src/views/OfficeHome/OfficeHome.test.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/Outbox.tsx
  packages/client/src/views/OfficeHome/tabs/WQContentWrapper.tsx
  packages/client/src/views/OfficeHome/tabs/inExternalValidation/InExternalValidationTab.tsx
  packages/client/src/views/OfficeHome/tabs/inExternalValidation/inExternalValidationTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/tabs/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/tabs/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/tabs/readyForReview/readyForReview.test.tsx
  packages/client/src/views/OfficeHome/tabs/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/tabs/readyToPrint/readyToPrint.test.tsx
  packages/client/src/views/OfficeHome/tabs/requiresUpdate/RequiresUpdateFieldAgent.tsx
  packages/client/src/views/OfficeHome/tabs/requiresUpdate/RequiresUpdateRegistrar.tsx
  packages/client/src/views/OfficeHome/tabs/requiresUpdate/requiresUpdateRegistrar.test.tsx
  packages/client/src/views/OfficeHome/tabs/sentForApproval/SentForApproval.test.tsx
  packages/client/src/views/OfficeHome/tabs/sentForApproval/SentForApproval.tsx
  packages/client/src/views/OfficeHome/tabs/sentForReview/SentForReview.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/components/interface/GridTable/GridTable.tsx
  packages/components/src/components/interface/GridTable/GridTableRowDeskop.tsx
Labels: 🏥 Failing Tests

#2957 ocrvs-2727 Changing the order of questions
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/CustomFieldForm.tsx
  packages/client/src/forms/configuration/configFields/actions.ts
  packages/client/src/forms/configuration/configFields/motionUtils.test.ts
  packages/client/src/forms/configuration/configFields/motionUtils.ts
  packages/client/src/forms/configuration/configFields/reducer.ts
  packages/client/src/forms/configuration/configFields/selectors.ts
  packages/client/src/forms/configuration/configFields/utils.ts
  packages/gateway/src/features/questions/root-resolvers.ts
Labels: 💅 Waiting For Review

#2961 Ocrvs 2898 Show Radio and Select options content keys
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/forms/configuration/configFields/utils.test.ts
  packages/client/src/forms/configuration/configFields/utils.ts
Labels: 👌LGTM

#2974 Remove extract translations from git actions
  .github/workflows/lint-and-test.yml
Labels: 💅 Waiting For Review

#2964 ocrvs-2725 Show hide default fields
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/CustomFieldForm.tsx
  packages/client/src/components/formConfig/SectionNavigation.tsx
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/configFields/actions.ts
  packages/client/src/forms/configuration/configFields/reducer.ts
  packages/client/src/forms/configuration/configFields/selectors.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
  packages/components/src/components/buttons/Toggle.tsx
  packages/components/src/components/interface/FormConfigElementCard.stories.tsx
  packages/components/src/components/interface/FormConfigElementCard.tsx
  packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.tsx
  packages/components/src/components/interface/Pill.tsx
Labels: 💅 Waiting For Review
