Repository opencrvs/opencrvs-core, pull requests merged in 2022-07, with the labels that each got.

#3615 Ocrvs 3580 Fix assigned user not showing in record audit
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: ✅ Ready for merging

#3614 Used refetchQueries instead of manual refetch
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: 👌LGTM, ✅ Ready for merging

#3632 Ocrvs 3328 Style & icon fixes
  packages/client/src/views/OfficeHome/LoadingIndicator.tsx
  packages/components/src/components/icons/ConnectionError.tsx
  packages/components/src/components/icons/index.ts
Labels: 💅 Waiting For Review

#3634 ocrvs-3564: Change imageLoadingError state when file is being uploaded
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
Labels: 💅 Waiting For Review

#3648 ocrvs-2331-fix Added TRADITIONAL_BIRTH_ATTENDANT as attendantType for birth declaration
  packages/client/src/tests/schema.graphql
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#3665 ocrvs=3542: Set spinners size to 24 on performance page
  packages/client/src/views/SysAdmin/Performance/CertificationRatesReport.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: ✅ Ready for merging

#3612 ocrvs-3572 Prevented loading workqueue data from record audit
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: ✅ Ready for merging

#3661 Ocrvs 2921 Refactor change phone number components
  packages/client/src/App.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/Settings/ChangePhoneModal/ChangeNumberView.tsx
  packages/client/src/views/Settings/ChangePhoneModal/ChangePhoneModal.test.tsx
  packages/client/src/views/Settings/ChangePhoneModal/ChangePhoneModal.tsx
  packages/client/src/views/Settings/ChangePhoneModal/VerifyCodeView.tsx
  packages/client/src/views/Settings/ChangePhonePage.tsx
  packages/client/src/views/Settings/items/PhoneNumber.tsx
Labels: ✅ Ready for merging

#3646 ocrvs-3454 Persisted the country logo in localStorage
  packages/login/src/views/StepOne/StepOneForm.tsx
  packages/login/src/views/StepOne/stepOneContainer.test.tsx
Labels: ✅ Ready for merging

#3670 Update new user flow
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/i18n/messages/views/userForm.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: ✅ Ready for merging

#3566 Convert app config from class to functional component
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SysAdmin/Config/Application/Application.test.tsx
  packages/client/src/views/SysAdmin/Config/Application/Application.tsx
  packages/client/src/views/SysAdmin/Config/Application/Components.tsx
  packages/client/src/views/SysAdmin/Config/Application/DynamicModal.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthLateFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthLateRegistrationPeriod.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/index.ts
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathDelayedRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/index.ts
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/ApplicationName.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/Currency.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/GovtLogo.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/NIDNumPattern.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/NIDPhoneNumContent.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/PhoneNumPattern.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/index.ts
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/client/src/views/SysAdmin/Config/Application/utils.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigSettings.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigSettings.tsx
  packages/components/src/components/forms/FormTabs.tsx
  packages/gateway/src/features/formDraft/root-resolvers.test.ts
Labels: 💅 Waiting For Review

#3667 Ocrvs 2811 Improve test coverage (performance, certificates)
  packages/client/src/tests/templates.json
  packages/client/src/views/PrintCertificate/PDFUtils.test.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.test.tsx
  packages/client/src/views/SysAdmin/Performance/utils.tsx
Labels: 💅 Waiting For Review

#3669 ocrvs-2918 Update Onboarding flow to use Content component
  packages/client/src/views/UserSetup/CreatePassword.tsx
  packages/client/src/views/UserSetup/SecurityQuestionView.tsx
  packages/client/src/views/UserSetup/SetupConfirmationPage.tsx
  packages/client/src/views/UserSetup/SetupReviewPage.tsx
  packages/client/src/views/UserSetup/UserSetupPage.test.tsx
  packages/client/src/views/UserSetup/UserSetupPage.tsx
  packages/components/src/components/interface/Content.tsx
Labels: 💅 Waiting For Review

#3655 ocrvs-3391 Fixed performance page fee currency
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthLateFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/utils.ts
  packages/client/src/views/SysAdmin/Performance/PaymentsAmountComponent.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/components/src/components/symbol/FormattedNumberCurrency.tsx
Labels: 💅 Waiting For Review

#3681 ocrvs-2871 Archive in progress declarations
  packages/client/src/tests/default.json
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: 💅 Waiting For Review

#3611 ocrvs-3575 Added default conditionals for custom fields
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/configuration/formConfig/utils/index.ts
Labels: 💅 Waiting For Review
