Repository opencrvs/opencrvs-core, pull requests merged in 2022-11, with the labels that each got.

#4186 OCRVS-4142 Expose integrations from user-mgnt to frontend
  docker-compose.yml
  packages/client/src/offline/reducer.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/typings/window.d.ts
  packages/config/src/config/constants.ts
  packages/config/src/config/routes.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/handlers/system/systemHandler.ts
  packages/config/src/models/config.ts
  packages/config/src/services/userManagementService.ts
  packages/config/src/utils/auth.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/test/setupJest.ts
  packages/user-mgnt/src/config/routes.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/test/utils.ts
Labels: ✅ Ready for merging

#4168 Feature/user reset password user reminder
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/user/mutations.ts
  packages/client/src/user/queries.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/notification/src/config/routes.ts
  packages/notification/src/features/sms/user-handler.test.ts
  packages/notification/src/features/sms/user-handler.ts
  packages/notification/src/features/sms/utils.ts
  packages/notification/src/i18n/messages.ts
  packages/notification/src/tests/util.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/resstPassword/handler.test.ts
  packages/user-mgnt/src/features/resstPassword/handler.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.test.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/service.ts
Labels: ⭐️ Epic, ✅ Ready for merging

#4188 OCRVS-3592 Fetch integrations from config to list them on IntegrationsList
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SysAdmin/Config/Integrations/Integrations.tsx
Labels: 💅 Waiting For Review

#4173 ocrvs-4127 Back end: AdvancedSearch - Create/Delete operations
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/userUtils.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/gateway/src/features/advanceSearch/root-resolvers.test.ts
  packages/gateway/src/features/advanceSearch/root-resolvers.ts
  packages/gateway/src/features/advanceSearch/schema.graphql
  packages/gateway/src/features/advanceSearch/type-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/getUser/handler.test.ts
  packages/user-mgnt/src/features/userSearchRecord/handler.test.ts
  packages/user-mgnt/src/features/userSearchRecord/handler.ts
  packages/user-mgnt/src/model/user.ts
Labels: 💅 Waiting For Review

#4197 ocrvs-4121: View record loading page
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/ViewRecord/ViewRecord.test.tsx
  packages/client/src/views/ViewRecord/ViewRecord.tsx
  packages/client/src/views/ViewRecord/query.ts
Labels: ✅ Ready for merging

#4200 ocrvs-4135: Add a wrapper for daterangepicker which can be used from formfieldgenerator
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/components/DateRangePickerForFormField.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/formConfig.ts
Labels: ❌ Conflicts

#4227 Make 2-factor authentication configurable
  docker-compose.yml
  packages/auth/src/constants.ts
  packages/auth/src/features/authenticate/handler.ts
  packages/auth/src/features/authenticate/service.ts
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SysAdmin/Config/Application/Application.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/TwoFactorAuth.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/index.ts
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🇳🇬 Nigeria

#4204 Ocrvs 3595 -As a System Admin I want to enable and disable a client integration
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/views/SysAdmin/Config/Integrations/Integrations.tsx
  packages/gateway/src/features/integrations/root-resolvers.test.ts
  packages/gateway/src/features/integrations/root-resolvers.ts
  packages/gateway/src/features/integrations/schema.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/features/system/handler.ts
Labels: ✅ Ready for merging

#4229 ocrvs 4113 - Advanced search form for death tab
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/views/advancedSearchForm.ts
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
Labels: 💅 Waiting For Review

#4196 ocrvs-4112 - Advanced search form for birth tab
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/advancedSearch/fieldDefinitions/Birth.ts
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/advancedSearchForm.ts
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/components/src/Accordion/Accordion.stories.tsx
  packages/components/src/Accordion/Accordion.tsx
Labels: 💅 Waiting For Review

#4181 Integration client creation modal UI implementation and design
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Integrations/Integrations.tsx
  packages/components/src/Alert/Alert.tsx
  packages/notification/src/features/sms/user-handler.test.ts
Labels: ⏳ Waiting for CI, ✅ Ready for merging

#4178 Ocrvs 4141 systems
  infrastructure/license-config.json
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/model/system.ts
  packages/user-mgnt/src/utils/userUtils.ts
Labels: 💅 Waiting For Review

#4224 Ocrvs 4189 - Clicking "Create" in the "Create client" -modal will call a mutation in the GraphQL gateway, and populate "Client ID", "Client Secret" and "Sha secret"
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Integrations/Integrations.tsx
  packages/gateway/src/features/clientRegistration/root-resolvers.ts
  packages/gateway/src/features/clientRegistration/schema.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/features/system/handler.ts
Labels: ✅ Ready for merging

#4243 Added METRICS_URL for user-mgnt service in docker yml
  docker-compose.yml
Labels: ✅ Ready for merging

#4242 Hide ID check row on record audit history page if requester is Another Agent Or Me
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: ✅ Ready for merging

#4240 ocrvs-4032 Fixed form config edit system crash bug
  packages/client/src/components/formConfig/Canvas.tsx
Labels: ✅ Ready for merging

#4233 ocrvs-4032: retain language on the can not login page
  packages/client/src/views/Unlock/ForgotPIN.test.tsx
  packages/client/src/views/Unlock/ForgotPIN.tsx
  packages/login/src/Page.tsx
  packages/login/src/i18n/components/LanguageSelect.tsx
Labels: ✅ Ready for merging

#4245 Saving ID verification info
  packages/client/src/views/CorrectionForm/utils.ts
Labels: ✅ Ready for merging

#4237 ocrvs-3717: fixed document title name
  packages/login/src/Page.tsx
  packages/login/src/views/resetCredentialsForm/forgottenItemForm.tsx
Labels: ✅ Ready for merging

#4246 Vs-export - Fix HEARTH_MONGO_URL & clear data
  infrastructure/clear-all-data.sh
  packages/metrics/scripts/VSExportGenerator.ts
Labels: 💅 Waiting For Review

#4238 ocrvs-4167: fixed undefined lastname on review page
  packages/client/src/utils/draftUtils.ts
Labels: ✅ Ready for merging

#4251 ocrvs-4208 - Fix bug in change phone number via setting page
  packages/client/src/views/Settings/ChangePhoneModal/VerifyCodeView.tsx
  packages/user-mgnt/src/features/getUser/handler.ts
Labels: 💅 Waiting For Review

#4269 ocrvs-4234 - Fix hardcoded correction in correctionsReport.tsx file
  packages/client/src/views/SysAdmin/Performance/CorrectionsReport.tsx
Labels: ✅ Ready for merging

#4268 ocrvs-4259 Update username notification not sending updated username
  packages/user-mgnt/src/features/updateUser/handler.ts
Labels: ✅ Ready for merging

#4179 Feature: View Record
  infrastructure/license-config.json
  packages/client/graphql.schema.json
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/ViewRecord/ViewRecord.test.tsx
  packages/client/src/views/ViewRecord/ViewRecord.tsx
  packages/client/src/views/ViewRecord/query.ts
  packages/components/src/TextArea/TextArea.tsx
  packages/gateway/src/features/fhir/constants.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/task/fhir/constants.ts
Labels: ⭐️ Epic, ✅ Ready for merging

#4252 ocrvs-4211: Notify user when they reconnect
  packages/client/src/components/Notification.test.tsx
  packages/client/src/components/Notification.tsx
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/index.tsx
  packages/client/src/notification/actions.ts
  packages/client/src/notification/reducer.ts
Labels: ✅ Ready for merging

#4277 ocrvs-4175: fixed missing name in french unassigned declaration
  packages/client/src/utils/data-formatting.ts
Labels: ✅ Ready for merging

#4231 ocrvs-4147
  packages/client/graphql.schema.json
  packages/client/src/ListSyncController.ts
  packages/client/src/search/queries.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/Settings/Settings.test.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/gateway/src/features/advanceSearch/schema.graphql
  packages/gateway/src/features/advanceSearch/type-resolvers.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/notification/src/features/sms/user-handler.test.ts
  packages/search/src/config/routes.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/search/handler.test.ts
  packages/search/src/features/search/handler.ts
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.test.ts
  packages/search/src/features/search/utils.ts
Labels: 💅 Waiting For Review

#4293 ocrvs-4248: In Application config- Currency modal, the verbiage is showing wrong
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/Currency.tsx
Labels: ✅ Ready for merging

#4292 ocrvs-4249: The modal title of delay registration in birth tab is showing wrong
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedRegistrationTarget.tsx
Labels: ✅ Ready for merging

#4275 ocrvs-4172: Enable all previously disabled User Audit links
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
Labels: ✅ Ready for merging

#4289 regStatus for in progress migration added
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/migration/migrations/hearth/20221115062056-update-status-in-complete-fields.js
Labels: ✅ Ready for merging

#4296 In application config, Within legally specified time gets changed when delayed registration fee is changed
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedFee.tsx
Labels: ✅ Ready for merging

#4285 Added customField handlebar name on config and redux template
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/mappings/mutation/index.ts
  packages/client/src/forms/mappings/query/index.ts
  packages/client/src/forms/register/customFieldMappings/mutation/customField-mappings.ts
  packages/client/src/forms/register/customFieldMappings/query/customField-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
Labels: 💅 Waiting For Review

#4301 ocrvs-4203: Back and forward button gets disabled
  packages/client/src/components/Header/Header.tsx
Labels: ✅ Ready for merging

#4267 ocrvs-4118 elasticSearch migration to add missing identifiers, DOB, gender, eventJurisdictionIds and eventCountry
  packages/migration/migrations/hearth/20221017133354-restore-supporting-document.js
  packages/migration/migrations/hearth/20221110092434-add_identifiers_DOB_gender_location.js
  packages/migration/package.json
  packages/migration/utils/elasticsearch-helper.js
  packages/migration/utils/hearth-helper.js
Labels: 💅 Waiting For Review

#4274 VSExport fixes: remove create-mongo-users - Fix Traefik and Minio hosting errors
  .github/workflows/deploy.yml
  Dockerfile
  deploy.sh
  docker-compose.demo-deps.yml
  docker-compose.deploy.yml
  docker-compose.deps.yml
  docker-compose.dev-deps.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.yml
  infrastructure/mongodb/README.md
  infrastructure/mongodb/docker-entrypoint-initdb.d/create-mongo-users.sh
  infrastructure/mongodb/on-deploy.sh
  infrastructure/nginx-deploy-config.sh
  packages/client/Dockerfile
  packages/client/src/declarations/index.ts
  packages/client/src/setupTests.ts
  packages/client/src/src-sw.js
  packages/client/src/utils/constants.ts
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Performance/Vsexports/VSExport.tsx
  packages/client/typings/window.d.ts
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/metrics/.gitignore
  packages/metrics/package.json
  packages/metrics/src/constants.ts
  packages/metrics/src/features/vsExport/handler.ts
  packages/metrics/src/scripts/VSExportGenerator.ts
  packages/metrics/test/setupJest.ts
  yarn.lock
Labels: 👌LGTM

#4281 Verify qr code
  packages/client/src/App.tsx
  packages/client/src/components/ProtectedPage.tsx
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/profile/profileReducer.ts
  packages/client/src/utils/authUtils.ts
  packages/client/src/views/PrintCertificate/DeclarationInfo.tsx
  packages/client/src/views/PrintCertificate/VerifyDetails.tsx
  packages/login/src/login/reducer.ts
Labels: 🇳🇬 Nigeria

#4298 Integration configuration harmonization
  packages/auth/src/features/system/handler.ts
  packages/client/graphql.schema.json
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/client/src/views/SysAdmin/Config/Systems/mutations.ts
  packages/client/src/views/SysAdmin/Config/Systems/useSystems.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/gateway/src/features/clientRegistration/root-resolvers.ts
  packages/gateway/src/features/clientRegistration/schema.graphql
  packages/gateway/src/features/systems/root-resolvers.test.ts
  packages/gateway/src/features/systems/root-resolvers.ts
  packages/gateway/src/features/systems/schema.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/system/handler.ts
Labels: 🚧 work in progress

#4270 locations api exposed
  docker-compose.yml
  infrastructure/export-registrations.sh
  packages/gateway/package.json
  packages/gateway/src/config/plugins.ts
  packages/gateway/src/config/routes.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/restLocation/locationHandler.ts
  packages/gateway/src/features/restLocation/utils.test.ts
  packages/gateway/src/features/restLocation/utils.ts
  packages/gateway/src/routes/getUserAvatar/export-all-route.ts
  packages/gateway/src/routes/metrics/export-all-route.ts
  packages/gateway/src/routes/metrics/montly-export-route.ts
  packages/gateway/src/routes/registrations/export-route.ts
  packages/gateway/src/routes/verifyCode/export-route.ts
  packages/gateway/src/utils/testUtils.ts
  yarn.lock
Labels: 👌LGTM, 📄Documentation

#4313 ocrvs-4201: When searched an assigned application, in record audit page it is showing not assigned
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: ✅ Ready for merging

#4230 Refresh system client secret
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/client/src/views/SysAdmin/Config/Systems/mutations.ts
  packages/client/src/views/SysAdmin/Config/Systems/useSystems.ts
  packages/gateway/src/features/systems/root-resolvers.test.ts
  packages/gateway/src/features/systems/root-resolvers.ts
  packages/gateway/src/features/systems/schema.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/utils/userUtils.ts
Labels: ⏳ Waiting for CI

#4308 reset password & username reminder added in user audit
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/UserAudit/UserAudit.tsx
Labels: ✅ Ready for merging

#4314 OCRVS-4070: Disable OpenHIM API endpoint unless whitelisted
  docker-compose.deploy.yml
  packages/client/vite.config.js
  packages/login/vite.config.js
  packages/migration/migrations/openhim/20221121124457-remove-old-transactions.cjs
Labels: 📄Documentation

#4331 For all application actions ID Check option is showing. ID check should be available for Certified and Corrected record action
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: ✅ Ready for merging

#4198 OCRVS-3853
  packages/client/graphql.schema.json
  packages/client/src/App.tsx
  packages/client/src/components/SegmentedControl.tsx
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/Performance/RegistrationsList.test.tsx
  packages/client/src/views/Performance/RegistrationsList.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/RegistrationsReport.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/client/vite.config.js
  packages/components/src/AppHeader/Mobile/MobileHeader.tsx
  packages/components/src/Pagination/Pagination.tsx
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/features/metrics/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/login/vite.config.js
  packages/metrics/package.json
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/metrics/constants.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/totalMetrics/handler.ts
  packages/metrics/src/influxdb/client.ts
  packages/migration/migrations/hearth/20221017133354-restore-supporting-document.js
  packages/migration/migrations/hearth/20221031131452-add_practioner_id_event_registrations.js
  packages/migration/utils/influx-helper.js
Labels: ✅ Ready for merging

#4223 Hotfix v1.1.2
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  package.json
  packages/auth/package.json
  packages/client/package.json
  packages/client/src/utils/constants.ts
  packages/commons/package.json
  packages/components/package.json
  packages/gateway/package.json
  packages/integration/package.json
  packages/login/package.json
  packages/metrics/package.json
  packages/migration/package.json
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/webhooks/package.json
  packages/workflow/package.json
Labels: ❌ Conflicts, 🔧Waiting for fixes

#4330 ocrvs-4214 Enable reordering of default fields
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/formTools/components.tsx
  packages/client/src/forms/configuration/defaultUtils.ts
  packages/client/src/forms/configuration/formConfig/reducer.ts
  packages/client/src/forms/configuration/formConfig/selectors.ts
  packages/client/src/forms/configuration/formConfig/utils/customConfig.ts
  packages/client/src/forms/configuration/formConfig/utils/defaultConfig.ts
  packages/client/src/forms/configuration/formConfig/utils/index.ts
  packages/client/src/forms/configuration/formConfig/utils/motion.test.ts
  packages/client/src/forms/configuration/formConfig/utils/motion.ts
  packages/client/src/forms/configuration/formConfig/utils/previewGroup.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/SaveActionModal.test.tsx
  packages/components/src/FormConfigElementCard/FormConfigElementCard.tsx
Labels: 💅 Waiting For Review

#4342 search filter styling and background
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/components/src/SearchTool/SearchTool.tsx
Labels: 🙋Question, 💅 Waiting For Review

#4332 Ocrvs 4114 AdvancedSearch config page and AdvancedSearchResult page
  packages/client/src/App.tsx
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/components/DateRangePickerForFormField.tsx
  packages/client/src/components/Header/Header.tsx
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/advancedSearch/fieldDefinitions/Birth.ts
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/views/advancedSearchForm.ts
  packages/client/src/i18n/messages/views/advancedSearchResult.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/notification/reducer.ts
  packages/client/src/search/advancedSearch/actions.ts
  packages/client/src/search/advancedSearch/advancedSearchSelectors.ts
  packages/client/src/search/advancedSearch/reducer.ts
  packages/client/src/search/advancedSearch/utils.test.ts
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/search/queries.ts
  packages/client/src/store.ts
  packages/client/src/tests/default.json
  packages/client/src/tests/util.tsx
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/OfficeHome/WQContentWrapper.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.test.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/components/src/Accordion/Accordion.stories.tsx
  packages/components/src/Accordion/Accordion.tsx
  packages/components/src/Pill/Pill.tsx
  packages/search/src/features/search/utils.ts
Labels: 🚧 work in progress

#4374 Send MOSIP authdata as an object rather than an array
  packages/workflow/src/features/registration/utils.ts
Labels: ⏳ Waiting for CI, ✅ Ready for merging
