Repository opencrvs/opencrvs-core, pull requests merged in 2022-03, with the labels that each got.

#2625 ocrvs-312 Change default notification to floating
  packages/client/src/components/Notification.test.tsx
  packages/client/src/components/Notification.tsx
  packages/client/src/views/Settings/ChangePhonePage.test.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/components/src/components/interface/FloatingNotification.stories.tsx
  packages/components/src/components/interface/FloatingNotification.tsx
  packages/components/src/components/interface/Notification.stories.tsx
  packages/components/src/components/interface/Notification.tsx
  packages/components/src/components/interface/index.ts
Labels: 👌LGTM

#2648 Removed unnecessary state from DocumentUploader
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/components/src/components/forms/ImageUploader.tsx
Labels: 💅 Waiting For Review

#2622 Ocrvs 2571: Default value for state and district set according to agents location
  packages/client/src/components/form/FormFieldGenerator.tsx
Labels: 💅 Waiting For Review, 👌LGTM, ✅ Ready for merging

#2610 ocrvs-2425-new: Added some formats for the columns of record audit page history table
  packages/client/src/views/Home/RecordAudit.tsx
  packages/components/src/components/interface/TableView.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2598 Ocrvs-2459
  packages/client/src/components/DuplicateDetails.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/transformer/index.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/FieldAgentHome/InProgress.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/components/src/components/interface/Content.tsx
  packages/components/src/components/interface/TableView.tsx
  packages/gateway/src/features/fhir/templates.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/features/legacy/handler.ts
  packages/search/src/features/search/handler.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.ts
Labels: 💅 Waiting For Review

#2600 Ocrvs 2457 Archive a declaration
  infrastructure/openhim-base-config.json
  packages/client/src/SubmissionController.test.ts
  packages/client/src/SubmissionController.ts
  packages/client/src/applications/index.test.ts
  packages/client/src/applications/index.ts
  packages/client/src/components/DuplicateDetails.tsx
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/utils/constants.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/Home/RecordAudit.test.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/Home/queries.ts
  packages/client/src/views/OfficeHome/NotificationToast.tsx
  packages/client/src/views/OfficeHome/Outbox.test.tsx
  packages/client/src/views/OfficeHome/Outbox.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/components/buttons/TertiaryButton.tsx
  packages/components/src/components/icons/ApplicationIcon.tsx
  packages/components/src/components/icons/Archive.stories.tsx
  packages/components/src/components/icons/Archive.tsx
  packages/components/src/components/icons/index.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/handler.test.ts
Labels: 👌LGTM

#2631 Ocrvs 2532: Document Uploader issue fixed.
  packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
Labels: 👌LGTM, ✅ Ready for merging

#2342 Ocrvs 2319 - Form config part one
  packages/client/src/App.test.tsx
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/deserializer.test.tsx
  packages/client/src/forms/register/fieldDefinitions/register.ts
  packages/client/src/forms/register/reducer.ts
  packages/client/src/forms/register/reviewReducer.ts
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/forms/user/mutation/mutations.ts
  packages/client/src/forms/user/query/queries.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/views/userForm.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/offline/selectors.ts
  packages/client/src/setupTests.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/util.tsx
  packages/client/src/user/userReducer.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/client/typings/window.d.ts
  packages/config/package.json
  packages/config/src/config/routes.ts
  packages/config/src/handlers/createQuestion/handler.test.ts
  packages/config/src/handlers/createQuestion/handler.ts
  packages/config/src/handlers/getQuestions/handler.test.ts
  packages/config/src/handlers/getQuestions/handler.ts
  packages/config/src/handlers/updateQuestion/handler.test.ts
  packages/config/src/handlers/updateQuestion/handler.ts
  packages/config/src/models/question.ts
  packages/gateway/src/features/certificate/schema.graphql
  packages/gateway/src/features/questions/root-resolvers.test.ts
  packages/gateway/src/features/questions/root-resolvers.ts
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/transformation/index.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/features/legacy/handler.ts
  packages/search/src/features/search/handler.ts
  yarn.lock
Labels: 💅 Waiting For Review

#2624 ocrvs:2547 removed switch case from validate.ts and remove validation for brn, drn, passport, driving license
  packages/client/src/setupTests.ts
  packages/client/src/utils/validate.test.ts
  packages/client/src/utils/validate.ts
Labels: 👌LGTM

#2603 ocrvs-2458 Reinstate archived application
  infrastructure/openhim-base-config.json
  packages/client/src/SubmissionController.test.ts
  packages/client/src/SubmissionController.ts
  packages/client/src/applications/index.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/utils/constants.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/Home/RecordAudit.test.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/OfficeHome/NotificationToast.tsx
  packages/client/src/views/OfficeHome/Outbox.tsx
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/composition.test.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/handler.test.ts
Labels: 💅 Waiting For Review

#2669 ocrvs-2458 Fixed some reviewed issue
  packages/client/src/SubmissionController.test.ts
  packages/client/src/SubmissionController.ts
  packages/client/src/applications/index.ts
  packages/client/src/forms/index.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/Home/RecordAudit.test.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/OfficeHome/NotificationToast.tsx
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
Labels: 💅 Waiting For Review

#2646 ocrvs-1631 Refactor the event names
  infrastructure/openhim-base-config.json
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/metrics/constants.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.ts
Labels: ✅ Ready for merging

#2686 ocrvs-1968-userProfile: menu button added on userProfile page in mobile view
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
Labels: ✅ Ready for merging

#2696 ocrvs-2555 Fixed some application config reviewed issue
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/views/SysAdmin/Config/Application.tsx
  packages/client/src/views/SysAdmin/Config/DynamicModal.tsx
  packages/metrics/src/features/applicationsStarted/handler.test.ts
  packages/metrics/src/features/locationWiseEventEstimations/handler.test.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/index.test.ts
  packages/metrics/test/setupJest.ts
Labels: 💅 Waiting For Review

#2692 (ocrvs-2382-fix) Disable back arrow button on landing page
  packages/client/src/components/interface/Header/Header.tsx
  packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx
Labels: 💅 Waiting For Review

#2681 Fixed alignment and mobile view issues of record audit page
  packages/client/src/views/Home/RecordAudit.tsx
Labels: 💅 Waiting For Review

#2687 ocrvs-2642 Added fonts in storybook
  packages/components/.storybook/preview.js
  packages/components/package.json
  packages/components/public/fonts/notosans-regular-webfont-en.ttf
  packages/components/public/fonts/notosans-semibold-webfont-en.ttf
Labels: 👌LGTM

#2684 [1984][2664] Fix metrics not working in deployed environments because of wrong config url
  .github/workflows/build-images-from-branch.yml
  docker-compose.yml
  packages/metrics/src/constants.ts
Labels: 👹Bug

#2658 Buttons UI updates
  packages/components/src/components/buttons/Button.tsx
  packages/components/src/components/buttons/CircleButton.tsx
  packages/components/src/components/buttons/LinkButton.tsx
  packages/components/src/components/buttons/PrimaryButton.tsx
  packages/components/src/components/buttons/SecondaryButton.tsx
  packages/components/src/components/buttons/TertiaryButton.tsx
Labels: 💅 Waiting For Review

#2682 tableview-ocrvs-2543: Part 2- Listview Component
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserAuditList.tsx
  packages/components/src/components/interface/ViewData/ListRow.tsx
  packages/components/src/components/interface/ViewData/ListView.stories.tsx
  packages/components/src/components/interface/ViewData/ListView.tsx
Labels: 💅 Waiting For Review

#2677 CI: Check before building images in manual E2E action
  .github/workflows/cd-manual-e2e.yml
Labels: 💅 Waiting For Review

#2704 ocrvs-2689 Added reinstated row in task history
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/Home/RecordAudit.tsx
  packages/gateway/src/features/fhir/constants.ts
  packages/gateway/src/features/fhir/templates.ts
  packages/gateway/src/features/fhir/utils.test.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/fhir-builders.test.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/utils/testUtils.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/legacy/handler.ts
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/fhir/constants.ts
  packages/workflow/src/features/task/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/task/fhir/utils.test.ts
  packages/workflow/src/features/task/fhir/utils.ts
  packages/workflow/src/features/task/handler.test.ts
  packages/workflow/src/features/task/handler.ts
  packages/workflow/src/test/utils.ts
Labels: 💅 Waiting For Review

#2729 ocrvs 2556: Change country logo from application config
  packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/offline/selectors.ts
  packages/client/src/pdfRenderer/transformer/offlineTransformer.ts
  packages/client/src/setupTests.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/tests/util.tsx
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Config/Application.test.tsx
  packages/client/src/views/SysAdmin/Config/Application.tsx
  packages/client/src/views/SysAdmin/Config/DynamicModal.tsx
  packages/client/src/views/SysAdmin/Config/mutations.ts
  packages/client/src/views/SysAdmin/Config/utils.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.test.tsx
  packages/client/typings/window.d.ts
  packages/config/src/handlers/applicarationConfigHandler.ts
  packages/config/src/handlers/applicationConfigHandler.test.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/login/src/utils/authApi.ts
  packages/metrics/src/configApi.ts
Labels: ✅ Ready for merging

#2716 Declaration icon fixes
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/components/src/components/buttons/LinkButton.tsx
  packages/components/src/components/buttons/TertiaryButton.tsx
  packages/components/src/components/colors.ts
  packages/components/src/components/icons/DeclarationIcon.stories.tsx
  packages/components/src/components/icons/DeclarationIcon.tsx
  packages/components/src/components/icons/DeclarationIconSmall.stories.tsx
  packages/components/src/components/icons/DeclarationIconSmall.tsx
  packages/components/src/components/interface/ActionPageLight.tsx
  packages/components/src/components/interface/Content.tsx
  packages/components/src/components/interface/EventTopBar.tsx
  packages/components/src/components/interface/Navigation/NavigationItem.stories.tsx
  packages/components/src/components/interface/Navigation/NavigationItem.tsx
  packages/components/src/components/interface/ResponsiveModal.tsx
  packages/components/src/components/interface/ViewData/ListRow.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2744 ocrvs-2393: default message changed for documentForWhom
  packages/client/src/i18n/messages/views/review.ts
Labels: 💅 Waiting For Review

#2713 updates session expiry modal from old component
  packages/client/src/components/SessionExpireConfirmation.tsx
Labels: 🚧 work in progress

#2752 Ocrvs-2698: Showed application search bar in header in performance and team page
  packages/client/src/components/interface/Header/Header.tsx
Labels: 💅 Waiting For Review

#2749 Ocrvs-2651: Fixed mother and father details bug when sending incomplete application
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 🙋Question, 👌LGTM

#2767 Removed SearchInput
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/components/interface/SearchInput.stories.tsx
  packages/components/src/components/interface/SearchInput.tsx
  packages/components/src/components/interface/SearchInputWithIcon.stories.tsx
  packages/components/src/components/interface/SearchInputWithIcon.tsx
  packages/components/src/components/interface/SearchTool/SearchTool.tsx
  packages/components/src/components/interface/index.ts
Labels: 💅 Waiting For Review, 👌LGTM

#2770 Fixed the issue in death record correction section while selecting 'someone else'
  packages/client/src/forms/correction/corrector.ts
Labels: 💅 Waiting For Review

#2765 Button size variants
  packages/components/src/components/buttons/Button.tsx
  packages/components/src/components/buttons/PrimaryButton.stories.tsx
  packages/components/src/components/buttons/SecondaryButton.tsx
  packages/components/src/components/buttons/SuccessButton.stories.tsx
  packages/components/src/components/buttons/TertiaryButton.stories.tsx
  packages/components/src/components/buttons/index.ts
  packages/components/src/components/icons/Activity.tsx
  packages/components/src/components/icons/Configuration.tsx
  packages/components/src/components/icons/DeclarationIcon.tsx
  packages/components/src/components/icons/Users.tsx
Labels: 💅 Waiting For Review

#2757 Field agents can now download rejected declarations
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/utils/commonUtils.ts
  packages/client/src/utils/draftUtils.ts
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/workflow/src/features/events/auth.ts
Labels: ⏳ Waiting for CI

#2760 ocrvs-2724 FormConfigElementCard component
  packages/client/src/App.tsx
  packages/client/src/components/formConfig/Canvas.tsx
  packages/components/src/components/buttons/CircleButton.stories.tsx
  packages/components/src/components/buttons/CircleButton.tsx
  packages/components/src/components/icons/ArrowDown.tsx
  packages/components/src/components/icons/ArrowUp.tsx
  packages/components/src/components/icons/Trash.tsx
  packages/components/src/components/icons/index.ts
  packages/components/src/components/interface/FormConfigElementCard.stories.tsx
  packages/components/src/components/interface/FormConfigElementCard.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#2768 Fixed the missing status showing bug
  packages/client/src/i18n/messages/views/registrarHome.ts
  packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
Labels: 💅 Waiting For Review

#2753 Toggle added on storybook
  packages/components/src/components/buttons/Toggle.stories.tsx
  packages/components/src/components/buttons/Toggle.tsx
  packages/components/src/components/interface/EventTopBar.tsx
Labels: 👌LGTM, 🔧Waiting for fixes

#2748 ocrvs-1618 Improved change avatar
  packages/client/src/profile/profileReducer.test.ts
  packages/client/src/profile/profileReducer.ts
  packages/client/src/views/Settings/AvatarChangeModal.tsx
  packages/client/src/views/Settings/ChangePhonePage.test.tsx
  packages/client/src/views/Settings/ChangePhonePage.tsx
  packages/client/src/views/Settings/ImageLoader.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: ✅ Ready for merging

#2751 OCRVS-2566: Clean up unnecessary task history
  packages/client/src/SubmissionController.ts
  packages/client/src/declarations/index.ts
  packages/client/src/search/queries.ts
  packages/client/src/search/transformer.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/draftUtils.test.ts
  packages/client/src/utils/draftUtils.ts
  packages/client/src/views/FieldAgentHome/FieldAgentHome.test.tsx
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/tabs/review/reviewTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/review/reviewTab.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 👌LGTM, 💂 Coverage Required

#2778 OCRVS-2703: Reason for rejection
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/Home/RecordAudit.tsx
  packages/components/src/components/icons/DeclarationIconSmall.tsx
  packages/gateway/src/features/fhir/templates.ts
  packages/gateway/src/features/registration/fhir-builders.test.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/utils/testUtils.ts
Labels: 💂 Coverage Required

#2626 Ocrvs 2589 Print PDF certifcate from svg content from config
  packages/client/package.json
  packages/client/public/assets/sample-signature.png
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/forms/certificate/fieldDefinitions/preview-section.ts
  packages/client/src/forms/certificate/printReducer.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/deserializer.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/query/event-mappings.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/pdfRenderer/transformer/types.ts
  packages/client/src/pdfRenderer/transformer/userTransformer.ts
  packages/client/src/templates/register.ts
  packages/client/src/tests/register.json
  packages/client/src/transformer/index.ts
  packages/client/src/utils/data-formatting.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.test.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/SysAdmin/Config/Certificates.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates.tsx
  packages/client/src/views/SysAdmin/Config/previewDummyData.ts
  yarn.lock
Labels: 💅 Waiting For Review
