Repository opencrvs/opencrvs-core, pull requests merged in 2022-08, with the labels that each got.

#3679 ocrvs-3489: Add/fix the media queries for createPin page, certificate preview page and reviewAction page
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/views/PIN/CreatePin.tsx
  packages/client/src/views/Unlock/Unlock.tsx
  packages/components/src/components/forms/PDFViewer/PDFViewer.tsx
  packages/components/src/components/interface/PINKeypad.tsx
Labels: 👌LGTM

#3686 ocrvs-3607 Refactored SubmissionController
  packages/client/package.json
  packages/client/src/InboxController.test.ts
  packages/client/src/InboxController.ts
  packages/client/src/SubmissionController.test.ts
  packages/client/src/SubmissionController.ts
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/components/review/RejectRegistrationForm.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/declarations/submissionMiddleware.test.ts
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/forms/index.ts
  packages/client/src/store.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/apolloClient.ts
  packages/client/src/views/CorrectionForm/CorrectionForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/DataProvider/MutationProvider.tsx
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/mutations.test.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/DataProvider/death/queries.test.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/OfficeHome/Outbox.test.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/PrintCertificate/Payment.test.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.test.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.init.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  yarn.lock
Labels: 👌LGTM

#3693 Ocrvs 3662
  dev.sh
  setup-scripts/setup-countryconfig.sh
Labels: 💅 Waiting For Review

#3697 ocrvs-3315 Provided fhirIdMapping for QuestionnaireResponse
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 💅 Waiting For Review

#3689 ocrvs-3296 Removed internal calls to verifyToken from metrics, notifications, workflow, user-mgnt, search microservice
  docker-compose.yml
  packages/metrics/src/constants.ts
  packages/metrics/src/server.ts
  packages/notification/src/constants.ts
  packages/notification/src/server.ts
  packages/search/src/constants.ts
  packages/search/src/server.ts
  packages/user-mgnt/src/constants.ts
  packages/user-mgnt/src/server.ts
  packages/workflow/src/constants.ts
  packages/workflow/src/server.ts
Labels: 🙋Question, 🔧Waiting for fixes

#3702 ocrvs-1585 Removed /generate & /generateEventDurationMetrics routes from metrics…
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/legacy/handler.test.ts
  packages/metrics/src/features/legacy/handler.ts
Labels: 💅 Waiting For Review

#3723 ocrvs-2871-hotfix Fixed record audit crash when there is no name
  packages/client/src/views/RecordAudit/utils.ts
Labels: 💅 Waiting For Review

#3695 ocrvs-3658 Fix infinite loading issue
  packages/client/src/InboxController.test.ts
  packages/client/src/InboxController.ts
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/components/review/RejectRegistrationForm.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/declarations/selectors.ts
  packages/client/src/utils/draftUtils.test.ts
  packages/client/src/utils/draftUtils.ts
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 👌LGTM

#3698 ocrvs-1875 Fixed locationsearch suggestions based on input text
  packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
Labels: 💅 Waiting For Review

#3740 Fixed govt logo size error and some app config state issue
  packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthLateFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/ApplicationName.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/Currency.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/GovtLogo.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/NIDNumPattern.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/PhoneNumPattern.tsx
Labels: 💅 Waiting For Review

#3734 ocrvs-3683 Fixed proof of legal guardianship document type
  packages/client/src/forms/configuration/default.ts
  packages/client/src/tests/default.json
Labels: 💅 Waiting For Review

#3761 ocrvs-3658 Filtered out processing declarations from search
  packages/client/src/declarations/index.ts
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#3772 OCRVS-3652: FA will not unassign others from rejected records
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/user/utils.ts
  packages/workflow/src/test/utils.ts
Labels: 👌LGTM

#3793 Fixed ErrorMessage width
  packages/components/src/components/forms/ErrorMessage.tsx
Labels: 💅 Waiting For Review

#3801 OCRVS 3800 / Fix `<PageHeader>` being 1px too tall
  packages/components/src/components/interface/Header/PageHeader.tsx
Labels: 🚧 work in progress

#3794 Fix work queue showing records other than given office
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/type-resolvers.ts
Labels: 👌LGTM

#3822 OCRVS-3820 / Fix incompatible TS types by pinning @types/react version
  package.json
  yarn.lock
Labels: ✅ Ready for merging

#3825 Move deprecated components to their own section
  packages/components/src/components/buttons/Action.stories.tsx
  packages/components/src/components/buttons/ArrowExpansionButton.stories.tsx
  packages/components/src/components/buttons/ExpansionButton.stories.tsx
  packages/components/src/components/buttons/IconButton.stories.tsx
  packages/components/src/components/charts/Bar.stories.tsx
  packages/components/src/components/charts/Legend.stories.tsx
  packages/components/src/components/interface/ActionPage.stories.tsx
  packages/components/src/components/interface/Banner.stories.tsx
  packages/components/src/components/interface/Chip.stories.tsx
  packages/components/src/components/interface/DataTable/DataTable.stories.tsx
  packages/components/src/components/interface/DataTable/Pagination.stories.tsx
  packages/components/src/components/interface/DataTable/SortAndFilter.stories.tsx
  packages/components/src/components/interface/ExpandableNotification/ExpandableNotification.stories.tsx
  packages/components/src/components/interface/HamburgerMenu.stories.tsx
  packages/components/src/components/interface/InvertSpinner.stories.tsx
  packages/components/src/components/interface/ListItem.stories.tsx
  packages/components/src/components/interface/ListItemExpansion.stories.tsx
  packages/components/src/components/interface/Modal.stories.tsx
  packages/components/src/components/interface/ResultList.stories.tsx
  packages/components/src/components/interface/SectionDrawer.stories.tsx
  packages/components/src/components/interface/SelectGroup.stories.tsx
  packages/components/src/components/interface/SubPage.stories.tsx
  packages/components/src/components/interface/TopBar.stories.tsx
  packages/components/src/components/interface/ViewData/DataRow.stories.tsx
  packages/components/src/components/interface/ViewData/DataSection.stories.tsx
  packages/components/src/components/interface/ViewData/LabelValuePair.stories.tsx
Labels: 💅 Waiting For Review

#3786 OCRVS-3777 / Re-think Layout components and create `<Frame>`
  packages/client/src/components/HamburgerMenu.test.tsx
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/views/EventInfo/EventInfo.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/components/src/components/Frame/Frame.stories.tsx
  packages/components/src/components/Frame/Frame.tsx
  packages/components/src/components/Frame/components/Layout.tsx
  packages/components/src/components/Frame/components/Section.tsx
  packages/components/src/components/Frame/components/index.ts
  packages/components/src/components/Frame/index.ts
  packages/components/src/components/buttons/index.ts
  packages/components/src/components/interface/ActionPage.stories.tsx
  packages/components/src/components/interface/ActionPage.tsx
  packages/components/src/components/interface/ActionPageLight.stories.tsx
  packages/components/src/components/interface/Banner.stories.tsx
  packages/components/src/components/interface/Banner.tsx
  packages/components/src/components/interface/Chip.tsx
  packages/components/src/components/interface/Content.tsx
  packages/components/src/components/interface/DataTable/DataTable.stories.tsx
  packages/components/src/components/interface/DataTable/DataTable.tsx
  packages/components/src/components/interface/DataTable/index.ts
  packages/components/src/components/interface/EventTopBar.tsx
  packages/components/src/components/interface/GridTable/GridTable.tsx
  packages/components/src/components/interface/GridTable/GridTableRowDeskop.tsx
  packages/components/src/components/interface/GridTable/GridTableRowMobile.tsx
  packages/components/src/components/interface/GridTable/ListItemAction.tsx
  packages/components/src/components/interface/GridTable/index.ts
  packages/components/src/components/interface/GridTable/types.ts
  packages/components/src/components/interface/HamburgerMenu.stories.tsx
  packages/components/src/components/interface/HamburgerMenu.tsx
  packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx
  packages/components/src/components/interface/Header/PageHeader.tsx
  packages/components/src/components/interface/ListItem.stories.tsx
  packages/components/src/components/interface/ListItem.tsx
  packages/components/src/components/interface/ListItemExpansion.stories.tsx
  packages/components/src/components/interface/ListItemExpansion.tsx
  packages/components/src/components/interface/Navigation/LeftNavigation.stories.tsx
  packages/components/src/components/interface/Navigation/LeftNavigation.tsx
  packages/components/src/components/interface/ResultList.stories.tsx
  packages/components/src/components/interface/ResultList.tsx
  packages/components/src/components/interface/SubPage.stories.tsx
  packages/components/src/components/interface/SubPage.tsx
  packages/components/src/components/interface/TopBar.tsx
  packages/components/src/components/interface/index.ts
  packages/components/src/components/layout/Page.tsx
  packages/components/src/components/layout/index.ts
Labels: 🎁Components, 💅 Waiting For Review

#3831 ocrvs-3216-fix FIXED Uploaded certificate is not being change in preview immediately
  packages/client/src/offline/reducer.ts
Labels: 💅 Waiting For Review

#3819 OCRVS-3811 / `<Pagination>`
  packages/client/src/views/OfficeHome/WQContentWrapper.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/components/src/components/Pagination/Pagination.stories.tsx
  packages/components/src/components/Pagination/Pagination.tsx
  packages/components/src/components/Pagination/index.ts
  packages/components/src/components/buttons/CircleButton.tsx
  packages/components/src/components/forms/PDFViewer/PDFViewer.tsx
  packages/components/src/components/interface/DataTable/Pagination.stories.tsx
  packages/components/src/components/interface/DataTable/Pagination.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
  packages/components/src/components/interface/PaginationModified.stories.tsx
  packages/components/src/components/interface/TableView.tsx
  packages/components/src/components/interface/index.ts
  packages/components/src/components/styleForPagination/PaginationWrapper.tsx
  packages/components/src/components/styleForPagination/index.ts
Labels: 💅 Waiting For Review

#3749 ocrvs-2688 - Resolve restart issues with encrypted folders and move secrets
  .github/workflows/deploy.yml
  README.md
  deploy.sh
  docker-compose.deploy.yml
  infrastructure/emergency-backup-metadata.sh
  infrastructure/emergency-restore-metadata.sh
  infrastructure/logrotate.conf
  infrastructure/monitoring/elastalert/rules/alert.yaml
  infrastructure/restore-metadata-updates.sh
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  infrastructure/setup-deploy-config.sh
  package.json
  setup.sh
Labels: 💅 Waiting For Review

#3842 OCRVS-3811 - Pagination
  packages/client/src/views/OfficeHome/WQContentWrapper.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/components/src/components/Pagination/Pagination.stories.tsx
  packages/components/src/components/Pagination/Pagination.tsx
  packages/components/src/components/Pagination/index.ts
  packages/components/src/components/buttons/CircleButton.tsx
  packages/components/src/components/forms/PDFViewer/PDFViewer.tsx
  packages/components/src/components/interface/DataTable/Pagination.stories.tsx
  packages/components/src/components/interface/DataTable/Pagination.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
  packages/components/src/components/interface/PaginationModified.stories.tsx
  packages/components/src/components/interface/TableView.tsx
  packages/components/src/components/interface/index.ts
  packages/components/src/components/styleForPagination/PaginationWrapper.tsx
  packages/components/src/components/styleForPagination/index.ts
Labels: 💅 Waiting For Review

#3804 ocrvs-3726 Bootstrap migration package
  .github/workflows/deploy.yml
  deploy.sh
  docker-compose.deploy.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.yml
  package.json
  packages/migration/Dockerfile
  packages/migration/README.md
  packages/migration/migrate-mongo-config.js
  packages/migration/migrations/20220817082035-informant-legal-guardin-doc.js
  packages/migration/package.json
  packages/migration/runMigrations.sh
  yarn.lock
Labels: 💅 Waiting For Review

#3828 ocrvs-3729 StartedBy metrics migration
  docker-compose.yml
  packages/migration/migrations/20220817082035-informant-legal-guardin-doc.js
  packages/migration/migrations/20220822085901-rejected-declarations-started-by.js
  packages/migration/package.json
Labels: 💅 Waiting For Review

#3847 Ocrvs 3738 Migration approach OpenHIM
  docker-compose.deploy.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.yml
  packages/migration/migrate-mongo-config-hearth.js
  packages/migration/migrate-mongo-config-openhim.js
  packages/migration/migrations/hearth/20220817082035-informant-legal-guardin-doc.js
  packages/migration/migrations/hearth/20220822085901-rejected-declarations-started-by.js
  packages/migration/migrations/openhim/20220825071508-channels-v1.0.1.cjs
  packages/migration/migrations/openhim/20220826062206-channels-v1.0.1-to-v1.1.0.cjs
  packages/migration/migrations/openhim/openhim-base-config-v1.0.1.json
  packages/migration/runMigrations.sh
  packages/migration/utils/openhim-helpers.cjs
  setup-scripts/setup-countryconfig.sh
Labels: 💅 Waiting For Review
