Repository opencrvs/opencrvs-core, pull requests merged in 2022-05, with the labels that each got.

#2966 Performance status and few refactoring
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/views/SysAdmin/Performance/LocationStatsView.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/StatusWiseDeclarationCountView.tsx
  packages/client/src/views/SysAdmin/Performance/utils.tsx
  packages/components/src/components/interface/Content.tsx
Labels: 💅 Waiting For Review

#2965 ocrvs-2836: Updated record of status page and removed all events option from performance events dropdown
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: 💅 Waiting For Review

#2984 Form config remove configFields from IndexedDB
  packages/client/src/components/Page.tsx
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/CustomFieldForm.tsx
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/configFields/actions.ts
  packages/client/src/forms/configuration/configFields/selectors.ts
  packages/client/src/forms/configuration/formConfig/actions.ts
  packages/client/src/forms/configuration/formConfig/motionUtils.test.ts
  packages/client/src/forms/configuration/formConfig/motionUtils.ts
  packages/client/src/forms/configuration/formConfig/reducer.ts
  packages/client/src/forms/configuration/formConfig/selectors.ts
  packages/client/src/forms/configuration/formConfig/utils.test.ts
  packages/client/src/forms/configuration/formConfig/utils.ts
  packages/client/src/forms/configuration/formDrafts/actions.ts
  packages/client/src/forms/configuration/formDrafts/reducer.ts
  packages/client/src/forms/configuration/formDrafts/selectors.ts
  packages/client/src/forms/configuration/formDrafts/utils.ts
  packages/client/src/forms/configuration/index.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/store.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/views/SysAdmin/Config/Forms/Home/ActionsModal.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/ActionsNotification.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/DraftsTab.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/PublishedTab.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/SaveActionModal.tsx
  packages/client/src/views/SysAdmin/Config/Forms/hooks.tsx
Labels: 💅 Waiting For Review

#2993 Fix to hiding fathers addresses and add missing other family member phone
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
Labels: 💥 Hot Fixes

#2980 OCRVS-2897: Render ConfigPlaceholder
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/ConfigPlaceholder.tsx
  packages/client/src/forms/configuration/formConfig/motionUtils.ts
  packages/client/src/forms/configuration/formConfig/reducer.ts
  packages/client/src/forms/configuration/formConfig/utils.ts
Labels: 🚧 work in progress, ⛔ Blocked

#2982 Ocrvs 2915: ListViewSimplified is used in all places where ListView was.
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/tests/util.tsx
  packages/client/src/views/RegisterForm/DeclarationForm.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Config/Application.test.tsx
  packages/client/src/views/SysAdmin/Config/Application.tsx
  packages/client/src/views/SysAdmin/Config/Certificates.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/components/src/components/buttons/LinkButton.tsx
  packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.tsx
  packages/components/src/components/interface/ViewData/ListView.stories.tsx
  packages/components/src/components/interface/ViewData/ListView.tsx
  packages/components/src/components/interface/ViewData/index.ts
  yarn.lock
Labels: 💅 Waiting For Review, 👌LGTM

#3007 ocrvs-2850: profile image uploader bug fixed
  packages/components/src/components/interface/ResponsiveModal.tsx
Labels: 🙋Question, 🔧Waiting for fixes

#2999 ocrvs-2910: search icon dont appear for sysadmin, natlsysadmin and performance manager
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/utils/constants.ts
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/search/src/config/routes.ts
Labels: 🙋Question, 👌LGTM, 💂 Coverage Required

#3011 Fixed bug of certificate print when the language is French
  packages/client/src/pdfRenderer/index.ts
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
Labels: 🔧Waiting for fixes

#3027 Form config bug fixes
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/CustomFieldForm.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/configuration/formConfig/selectors.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
  packages/components/src/components/forms/InputField/InputField.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#3034 FormConfig: Toggle button fix
  packages/client/src/components/formConfig/CustomFieldForm.tsx
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigSettings.tsx
  packages/components/src/components/buttons/Toggle.stories.tsx
  packages/components/src/components/buttons/Toggle.tsx
Labels: 💅 Waiting For Review

#3036 Fixed bug while updating registrar
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review

#3014 ocrvs-2734: width changed in review section
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging

#3040 [OCRVS-2997] Fix validation errors showing too early.
  packages/client/graphql.schema.json
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx
Labels: 💅 Waiting For Review, 👌LGTM

#3035 OCRVS-2947: prevented system crash when downloading application on offline
  packages/client/src/declarations/index.ts
Labels: 💅 Waiting For Review

#3046 Some fixes to form config settings
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/index.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigSettings.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
Labels: 💅 Waiting For Review

#3041 Client language will be change following the login screen
  packages/client/src/components/Page.tsx
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/declarations/index.test.ts
  packages/client/src/i18n/reducer.ts
  packages/client/src/i18n/utils.ts
  packages/client/src/profile/profileActions.ts
  packages/client/src/profile/profileReducer.test.ts
  packages/client/src/profile/profileReducer.ts
  packages/client/src/utils/userUtils.ts
  packages/client/src/views/Home/RecordAudit.test.tsx
  packages/client/src/views/OfficeHome/OfficeHome.test.tsx
  packages/client/src/views/OfficeHome/inExternalValidation/inExternalValidationTab.test.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx
  packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdateRegistrar.test.tsx
  packages/client/src/views/OfficeHome/sentForApproval/SentForApproval.test.tsx
  packages/client/src/views/PrintCertificate/Payment.test.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.init.test.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/client/src/views/UserSetup/SetupConfirmationPage.test.tsx
  packages/client/src/views/UserSetup/UserSetupPage.test.tsx
  packages/login/src/login/reducer.ts
Labels: 👌LGTM

#3050 Ocrvs 2947 fix: prevent download on offline
  packages/client/package.json
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/i18n/messages/constants.ts
  packages/components/package.json
  yarn.lock
Labels: 👌LGTM, ⏳ Waiting for CI

#3055 ocrvs-3008: System crash bug fixed that was happening for tabId
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/views/CorrectionForm/CorrectionReasonForm.test.tsx
  packages/client/src/views/CorrectionForm/CorrectionReasonForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.test.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.test.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.test.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.test.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 👌LGTM

#2983 OCRVS-2952 Removed locationId limitation for Registrar's declarations searching
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 👌LGTM, ⏳ Waiting for CI

#3047 ocrvs-3012-bug-fix: Updated otherInformant field
  packages/client/src/forms/configuration/default.ts
Labels: ⏳ Waiting for CI

#3068 fix styling on bullet list
  packages/components/src/components/typography/BulletList.tsx
Labels: 💅 Waiting For Review

#3067 removes max-width on fields
  packages/components/src/components/forms/InputField/InputField.tsx
  packages/components/src/components/forms/TextInput.tsx
Labels: 👌LGTM

#3080 Added roles on ProtectedRoute for handle unauthorised access
  packages/client/src/App.tsx
  packages/client/src/components/ProtectedRoute.tsx
  packages/client/src/tests/util.tsx
  packages/client/src/utils/authUtils.ts
  packages/client/src/views/CorrectionForm/ReviewForm.test.tsx
Labels: 💅 Waiting For Review

#3075 informant dob in default.ts validation changed to allow informant younger than the child.
  packages/client/src/forms/configuration/default.ts
Labels: 💅 Waiting For Review

#3072 Refactored Content component
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/views/CorrectionForm/CorrectionReasonForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/utils.tsx
  packages/components/src/components/interface/Content.stories.tsx
  packages/components/src/components/interface/Content.tsx
  packages/components/src/components/interface/Header/AppHeader.tsx
  packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx
  packages/components/src/components/interface/Header/Mobile/MobileHeader.tsx
  packages/components/src/components/interface/Header/PageHeader.tsx
Labels: 💅 Waiting For Review, ✅ Ready for merging

#3107 ocrvs-2553-fix Fixed config mobile view header
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/i18n/messages/constants.ts
Labels: 💅 Waiting For Review

#3101 ocrvs-3016: location format changed in record audit page
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/Home/utils.ts
Labels: 👌LGTM

#3102 ocrvs-3078 Fixed reset password back button issue
  packages/login/src/views/resetCredentialsForm/updatePasswordForm.tsx
Labels: 💅 Waiting For Review

#3109 FormConfig: Unit Tests
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/formConfig/reducer.ts
  packages/client/src/forms/configuration/formConfig/utils.test.ts
  packages/client/src/forms/configuration/formDrafts/queries.ts
  packages/client/src/forms/configuration/formDrafts/utils.ts
  packages/client/src/setupTests.ts
  packages/client/src/tests/default.json
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/views/SysAdmin/Config/Forms/Home/ActionsModal.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/DraftsTab.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/DraftsTab.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/SaveActionModal.test.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/SaveActionModal.tsx
  packages/components/src/components/interface/FormConfigElementCard.tsx
Labels: 👌LGTM

#3116 Ocrvs 3061
  packages/client/generate-form.sh
  packages/client/src/forms/configuration/default.ts
  packages/client/src/generate-form.ts
  packages/client/src/tests/default.json
Labels: 👌LGTM

#3106 record audit refactored and bug fixed on downlowding state on recordaudit
  packages/client/src/App.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/navigation/index.ts
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/Home/utils.ts
  packages/client/src/views/OfficeHome/components.tsx
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/queries.ts
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#3127 ocrvs-2416-fix: Removed registration agent scope from showing correct record button
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: 👌LGTM

#3129 Ocrvs 3062 Fixed incomplete declaration attachment update issue
  packages/client/src/forms/configuration/default.ts
  packages/client/src/tests/default.json
Labels: 💅 Waiting For Review

#3118 SubmissionController bug fix
  packages/client/src/SubmissionController.ts
Labels: 🙋Question

#3115 udpate width of Content to be consistent
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#3033 workqueue ui polish
  packages/client/src/views/OfficeHome/LoadingIndicator.tsx
  packages/client/src/views/OfficeHome/WQContentWrapper.tsx
  packages/client/src/views/OfficeHome/components.tsx
  packages/components/src/components/buttons/ListItemAction.tsx
  packages/components/src/components/buttons/PrimaryButton.tsx
  packages/components/src/components/interface/DataTable/Pagination.tsx
  packages/components/src/components/interface/GridTable/GridTable.tsx
  packages/components/src/components/interface/GridTable/GridTableRowDeskop.tsx
  packages/components/src/components/interface/GridTable/GridTableRowMobile.tsx
  packages/components/src/components/interface/PaginationModified.tsx
  packages/components/src/components/interface/Tabs.tsx
  packages/components/src/components/styleForPagination/DesktopWrapper.tsx
  packages/components/src/components/styleForPagination/MobileWrapper.tsx
Labels: 👌LGTM

#3137 ToggleMenu now uses CircleButton
  packages/client/src/components/ProfileMenu.tsx
  packages/components/src/components/interface/ToggleMenu.stories.tsx
  packages/components/src/components/interface/ToggleMenu.tsx
Labels: ⏳ Waiting for CI, ✅ Ready for merging

#3138 Fixed first login issues of system admin when there is no registrars at that location
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/pdfRenderer/transformer/userTransformer.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/userUtils.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/model/user.ts
Labels: 🙋Question, ✅ Ready for merging

#3182 Hotfix 2426
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: 💥 Hot Fixes

#3103 ocrvs 3089 - Fixing duplicate mobile number issue during create or update
  packages/client/src/components/Notification.tsx
  packages/client/src/i18n/messages/user.ts
  packages/client/src/notification/actions.ts
  packages/client/src/notification/reducer.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/user/userReducer.ts
  packages/client/src/views/Settings/ChangePhonePage.test.tsx
  packages/client/src/views/Settings/ChangePhonePage.tsx
  packages/client/src/views/Settings/mutations.ts
  packages/client/src/views/Settings/queries.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/routes/verifyCode/handler.ts
  packages/user-mgnt/src/features/changePhone/handler.ts
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/features/getUser/handler.ts
  packages/user-mgnt/src/features/updateUser/handler.test.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/model/user.ts
Labels: 👌LGTM

#3069 Improve the server setup docs
  .github/workflows/cd-manual-e2e.yml
  .github/workflows/cd-version.yml
  .github/workflows/deploy.yml
  README.md
  deploy.sh
  docker-compose.deploy.yml
  docker-compose.prod-deploy-1.yml
  infrastructure/monitoring/elastalert/rules/alert.yaml
  infrastructure/monitoring/elastalert/rules/auth.yaml
  infrastructure/server-setup/README.md
  infrastructure/server-setup/example-1.ini
  infrastructure/server-setup/example-3.ini
  infrastructure/server-setup/example-5.ini
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  infrastructure/setup-deploy-config.sh
Labels: 💅 Waiting For Review

#3195 bug fixes styling for selects
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/components/src/components/buttons/SecondaryButton.tsx
  packages/components/src/components/forms/Select.tsx
  packages/components/src/components/select/Select.tsx
Labels: 💅 Waiting For Review

#3194 ocrvs-3175 Merged enabled configuration with default field
  packages/client/src/forms/configuration/index.ts
Labels: 🏎 auto-merging

#3201 Setup CORS and refactored farajaland to remove the farajaland directory
  docker-compose.deploy.yml
  packages/auth/src/constants.ts
  packages/auth/src/server.ts
  packages/client/extract-translations.sh
  packages/client/src/extract-translations.ts
  packages/config/src/config/constants.ts
  packages/config/src/logger.ts
  packages/config/src/server.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/server.ts
  packages/login/extract-translations.sh
  packages/login/src/extract-translations.ts
  packages/notification/extract-translations.sh
  packages/notification/src/extract-translations.ts
Labels: 💅 Waiting For Review

#3193 [OCRVS-3149] Validate incoming attachment types
  packages/gateway/package.json
  packages/gateway/src/features/correction/root-resolvers.test.ts
  packages/gateway/src/features/correction/root-resolvers.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/utils/validators.ts
  yarn.lock
Labels: 👌LGTM

#3206 [3154][3152] Make all publicly accessible domains require an SSL connection, add cache control headers
  docker-compose.deploy.yml
Labels: 💅 Waiting For Review

#3200 [OCRVS-3148] Hide registrar signature from field agents
  packages/client/graphql.schema.json
  packages/client/src/user/queries.ts
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/user/type-resolvers.test.ts
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🙋Question, 💅 Waiting For Review

#3217 Show fathers address option if mothers details not available
  packages/auth/src/server.ts
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/gateway/src/server.ts
Labels: 💅 Waiting For Review

#3207 ocrvs-3174 Showed default configuration in preview tab
  packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.tsx
Labels: 👌LGTM

#3215 ocrvs-3155,59,61,62 FormConfig content keys & canvas scroll
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/configuration/formConfig/utils.ts
  packages/client/src/tests/default.json
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
Labels: 💅 Waiting For Review

#3189 OCRVS-3019: Fixed duplicate items in supporting document dropdown
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging

#3208 Ocrvs 3147 Resolve config issues
  packages/client/public/config.js
  packages/client/src/offline/reducer.ts
  packages/client/src/utils/referenceApi.ts
  packages/config/src/config/routes.ts
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/handlers/certificate/certificateHandler.ts
  packages/config/src/utils/verifyToken.ts
  packages/login/public/config.js
  packages/login/src/utils/authApi.ts
  packages/metrics/src/configApi.ts
  packages/metrics/src/features/export/handler.ts
  packages/metrics/src/features/metrics/handler.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/metrics/utils.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/registration/utils.ts
Labels: 💅 Waiting For Review

#3205 National registrar user
  README.md
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/forms/user/query/queries.ts
  packages/client/src/i18n/messages/user.ts
  packages/client/src/navigation/index.ts
  packages/client/src/tests/default.json
  packages/client/src/user/userReducer.ts
  packages/client/src/utils/authUtils.ts
  packages/client/src/utils/constants.ts
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
  packages/gateway/src/features/role/root-resolvers.ts
  packages/gateway/src/features/role/schema.graphql
  packages/gateway/src/features/role/type-resolvers.ts
  packages/gateway/src/features/role/utils.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/features/getRoles/handler.test.ts
  packages/user-mgnt/src/features/getRoles/handler.ts
Labels: 👌LGTM

#3236 [HOTFIX] App not loading when logging in as a field agent templates
  docker-compose.deploy.yml
  packages/client/public/robots.txt
  packages/client/src/offline/reducer.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/login/public/robots.txt
Labels: 💥 Hot Fixes

#3223 ocrvs-3165 Fixed alignment in CustomFieldTools
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/components/formConfig/formTools/components.tsx
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
Labels: 💅 Waiting For Review

#3220 Removed signature from User schema
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🏎 auto-merging

#3222 ocrvs-3164 Removed the required state from CustomFieldForm
  packages/client/src/components/formConfig/Canvas.tsx
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx
  packages/client/src/components/formConfig/formTools/components.tsx
  packages/client/src/forms/configuration/formConfig/utils.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
Labels: 🏎 auto-merging

#3218 FIX: Deleting draft will take back to default config
  packages/client/src/views/SysAdmin/Config/Forms/Home/ActionsModal.tsx
  packages/config/src/handlers/formDraft/updateFormDraft/handler.ts
Labels: ✅ Ready for merging, 🏎 auto-merging

#3255 OCRVS-2924 Removed login background image and changed background color
  packages/client/src/views/PIN/CreatePin.tsx
  packages/client/src/views/SecureAccount/SecureAccountView.tsx
  packages/client/src/views/Unlock/Unlock.tsx
  packages/components/src/components/colors.ts
  packages/login/src/common/DarkPage/DarkPage.tsx
Labels: 🏎 auto-merging

#3249 Downloaded application was not showing due to wrong trackingId check
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: 🏎 auto-merging

#3238 Now mother option will be hidden
  packages/client/src/views/CorrectionForm/CorrectorForm.test.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
Labels: 💅 Waiting For Review

#3246 Hotfix: User Profile user's type check was missing
  packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
Labels: 💅 Waiting For Review, Priority: high, 💥 Hot Fixes

#3247 ccrvs-3120: Field agent workqueue refactored.
  packages/client/src/ListSyncController.ts
  packages/client/src/SubmissionController.test.ts
  packages/client/src/SubmissionController.ts
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/search/transformer.ts
  packages/client/src/views/OfficeHome/OfficeHome.test.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/components.tsx
  packages/client/src/views/OfficeHome/inExternalValidation/InExternalValidationTab.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdateFieldAgent.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdateRegistrar.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/components/interface/Content.tsx
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 👌LGTM

#3270 Ocrvs 3173 Fix for reason not showing
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review, ⏳ Waiting for CI

#3273 ocrvs-3169 Showed correct record button for registrar only
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
Labels: 👌LGTM

#3262 ocrvs-3112 Duplicate flow
  packages/client/src/App.tsx
  packages/client/src/InboxController.test.ts
  packages/client/src/InboxController.ts
  packages/client/src/components/DuplicateDetails.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/i18n/messages/views/duplicates.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/tests/languages.json
  packages/client/src/transformer/index.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/Duplicates/DuplicateWarning.test.tsx
  packages/client/src/views/Duplicates/DuplicateWarning.tsx
  packages/client/src/views/Duplicates/NotDuplicateConfirmation.test.tsx
  packages/client/src/views/Duplicates/NotDuplicateConfirmation.tsx
  packages/client/src/views/Duplicates/ReviewDuplicates.test.tsx
  packages/client/src/views/Duplicates/ReviewDuplicates.tsx
  packages/client/src/views/Duplicates/utils.ts
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/queries.ts
  packages/client/src/views/RegisterForm/ReviewForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/components/interface/Warning.tsx
Labels: ✅ Ready for merging
