Repository opencrvs/opencrvs-core, pull requests merged in 2022-02, with the labels that each got.

#2512 ocrvs 2399 Correction Form
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
Labels: 💅 Waiting For Review, 🏥 Failing Tests

#2490 Correction reason frontend
  packages/client/src/forms/correction/reason.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/views/CorrectionForm/CorrectionForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionReasonForm.tsx
Labels: 💅 Waiting For Review

#2480 ocrvs-2341: Fathers Residential address fields hidden when user do not have fathers details
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 👌LGTM

#2516 Upgraded node-fetch to satisfy new security warning
  packages/auth/package.json
  packages/commons/package.json
  packages/gateway/package.json
  packages/metrics/package.json
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/webhooks/package.json
  packages/workflow/package.json
  yarn.lock
Labels: 👌LGTM

#2356 Ocrvs 1968: menu button added on user submenu on mobile screen
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 👌LGTM, ⏳ Waiting for CI

#2507 Ocrvs 2400 Added VerifyID component for certificate corrector
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/offline/selectors.ts
  packages/client/src/tests/register.json
  packages/client/src/tests/util.tsx
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.test.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
Labels: 💅 Waiting For Review

#2527 Adjust Actions to deploy e2e tests on staging only and releases to farajaland env
  .github/workflows/build-and-publish.yml
  .github/workflows/cd-release.yml
  .github/workflows/cd-version.yml
  .github/workflows/e2e.yml
  .github/workflows/lint-and-test.yml
  deploy.sh
  package.json
Labels: 🙋Question

#2325 ocrvs-1809 (Change phone number as a USER)
  docker-compose.yml
  packages/auth/src/features/authenticate/service.ts
  packages/auth/src/features/system/handler.ts
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/user.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/profile/profileActions.ts
  packages/client/src/profile/profileReducer.ts
  packages/client/src/profile/profileSelectors.ts
  packages/client/src/profile/serviceApi.ts
  packages/client/src/views/Settings/ChangePhonePage.tsx
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/gateway/package.json
  packages/gateway/src/constants.ts
  packages/gateway/src/features/user/database.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/utils/index.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/index.ts
  packages/gateway/src/routes/verifyCode/export-route.ts
  packages/gateway/src/routes/verifyCode/handler.test.ts
  packages/gateway/src/routes/verifyCode/handler.ts
  packages/gateway/test/setupJest.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/changePhone/handler.test.ts
  packages/user-mgnt/src/features/changePhone/handler.ts
Labels: 👌LGTM

#2546 Allow setting declarations 'created at' value from outside (#2537)
  packages/gateway/src/features/registration/death-fhir-builders.test.ts
  packages/gateway/src/features/registration/fhir-builders.test.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/transformation/index.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/workflow/package.json
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/index.ts
Labels: ✅ Ready for merging

#2554 Ocrvs 2404
  packages/client/src/applications/index.ts
  packages/client/src/forms/correction/corrector.ts
  packages/client/src/forms/correction/payment.ts
  packages/client/src/forms/correction/reason.ts
  packages/client/src/forms/correction/verifyCorrector.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/offline/selectors.ts
  packages/client/src/tests/register.json
  packages/client/src/tests/util.tsx
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/CorrectionForm/CorrectionForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionReasonForm.test.tsx
  packages/client/src/views/CorrectionForm/CorrectionReasonForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.test.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.test.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/CorrectionForm/ReviewForm.test.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.test.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/OfficeHome/RowHistoryView.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/components/src/components/interface/ListTable/ListTable.stories.tsx
  packages/components/src/components/interface/ListTable/ListTable.tsx
Labels: 💅 Waiting For Review

#2581 Ocrvs 2496: changed applicant and contact point page in birth and death application
  packages/client/src/App.tsx
  packages/client/src/forms/index.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/selectInformant.ts
  packages/client/src/navigation/index.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/SelectInformant/SelectInformant.tsx
  packages/client/src/views/SelectInformant/SelectInformantBirth.test.tsx
  packages/client/src/views/SelectInformant/SelectInformantDeath.test.tsx
  packages/client/src/views/SelectInformant/SelectInformantSection.ts
  packages/client/src/views/SelectPrimaryApplicant/SelectPrimaryApplicant.test.tsx
  packages/client/src/views/SelectPrimaryApplicant/SelectPrimaryApplicant.tsx
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 👌LGTM

#2421 Ocrvs 2405 Correct record gateway, workflow, FHIR
  infrastructure/openhim-base-config.json
  packages/gateway/src/features/correction/root-resolvers.test.ts
  packages/gateway/src/features/correction/root-resolvers.ts
  packages/gateway/src/features/fhir/templates.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/fhir-builders.test.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.ts
Labels: 👌LGTM, ✅ Ready for merging

#2586 Added new Tableview component updating the styling of ListTable component
  packages/components/src/components/colors.ts
  packages/components/src/components/fonts.ts
  packages/components/src/components/interface/TableView.tsx
  packages/components/src/components/interface/index.ts
Labels: 👌LGTM

#2525 Ocrvs 2406 Back end 2 Correct record search and metrics
  packages/components/src/components/interface/DocumentViewer.tsx
  packages/gateway/src/graphql/schema.d.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/registration/test-data/request-correction-birth-request.json
  packages/metrics/src/features/registration/test-data/request-correction-death-request.json
  packages/metrics/src/influxdb/client.ts
  packages/search/src/elasticsearch/utils.test.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/test/utils.ts
Labels: 👌LGTM, ✅ Ready for merging

#2538 Ocrvs 2424: recordAudit short summary completed
  packages/client/src/App.tsx
  packages/client/src/applications/index.ts
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/views/FieldAgentHome/FieldAgentHome.test.tsx
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/FieldAgentHome/InProgress.tsx
  packages/client/src/views/FieldAgentHome/SentForReview.tsx
  packages/client/src/views/Home/RecordAudit.test.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/OfficeHome/OfficeHome.test.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/RowHistoryView.tsx
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/tabs/approvals/approvalTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/approvals/approvalTab.tsx
  packages/client/src/views/OfficeHome/tabs/externalValidation/externalValidationTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/externalValidation/externalValidationTab.tsx
  packages/client/src/views/OfficeHome/tabs/inProgress/inProgressTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/inProgress/inProgressTab.tsx
  packages/client/src/views/OfficeHome/tabs/print/printTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/print/printTab.tsx
  packages/client/src/views/OfficeHome/tabs/reject/rejectTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/reject/rejectTab.tsx
  packages/client/src/views/OfficeHome/tabs/review/reviewTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/review/reviewTab.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/components/colors.ts
  packages/components/src/components/fonts.ts
  packages/components/src/components/icons/ApplicationIcon.tsx
  packages/components/src/components/interface/Content.stories.tsx
  packages/components/src/components/interface/Content.tsx
  packages/components/src/components/interface/GridTable/GridTable.tsx
  packages/components/src/components/interface/ListItem.tsx
Labels: 💅 Waiting For Review, ✅ Ready for merging

#2616 Improve error messaging on invalid declaration payloads
  docker-compose.dev-deps.yml
  infrastructure/hearth-plugins/checkDuplicateTask.js
  packages/gateway/src/features/transformation/index.test.ts
  packages/gateway/src/features/transformation/index.ts
  packages/metrics/src/features/registration/pointGenerator.ts
Labels: 💅 Waiting For Review

#2591 ocrvs-2577: three dots menu made available only for national sysadmin, and sysadmin just for his office
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: 🙋Question, 💅 Waiting For Review, 👌LGTM

#2572 ocrvs-2382 Modified top nav header UI
  packages/client/src/components/Avatar/AvatarSmall.tsx
  packages/client/src/components/interface/Header/Header.tsx
  packages/client/src/i18n/messages/views/header.ts
  packages/client/src/navigation/index.ts
  packages/components/src/components/colors.ts
  packages/components/src/components/icons/BRN.tsx
  packages/components/src/components/icons/ForwardArrowDeepBlue.stories.tsx
  packages/components/src/components/icons/ForwardArrowDeepBlue.tsx
  packages/components/src/components/icons/Phone.tsx
  packages/components/src/components/icons/TrackingID.tsx
  packages/components/src/components/icons/User.tsx
  packages/components/src/components/icons/index.ts
  packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx
  packages/components/src/components/interface/Header/Mobile/MobileHeader.tsx
  packages/components/src/components/interface/SearchTool/SearchTool.tsx
  packages/components/src/components/interface/ToggleMenu.tsx
Labels: 👌LGTM

#2609 Ocrvs 2570: District and State dafault to agent's location when creating a birth application
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/tests/languages.json
  packages/client/src/tests/register.json
  packages/components/src/components/forms/RadioGroup/RadioGroup.tsx
  packages/components/src/components/interface/RadioButton.tsx
Labels: 💅 Waiting For Review

#2615 Make it possible to change logging level with an environment variable
  docker-compose.deploy.yml
  docker-compose.deps.yml
  docker-compose.dev-deps.yml
  packages/auth/src/logger.ts
  packages/config/src/config/logger.ts
  packages/gateway/src/logger.ts
  packages/metrics/src/config/plugins.ts
  packages/metrics/src/logger.ts
  packages/notification/src/logger.ts
  packages/search/src/logger.ts
  packages/user-mgnt/src/logger.ts
  packages/webhooks/src/logger.ts
  packages/workflow/src/logger.ts
Labels: 💅 Waiting For Review

#2613 Add X-Correlation-ID support for services
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/transformation/index.ts
  packages/gateway/src/graphql/config.test.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/index.ts
  packages/metrics/src/features/eventEstimations/handler.ts
  packages/metrics/src/features/locationWiseEventEstimations/handler.ts
  packages/metrics/src/features/metrics/handler.ts
  packages/metrics/src/features/monthWiseEventEstimations/handler.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/index.ts
  packages/webhooks/src/features/event/handler.ts
  packages/webhooks/src/features/event/service.test.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/handler.ts
Labels: 💅 Waiting For Review

#2614 Upgrade to Elasticsearch 7.17.0
  docker-compose.deps.yml
  docker-compose.dev-deps.yml
  packages/gateway/package.json
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/tsconfig.json
  packages/metrics/src/features/applicationsStarted/handler.test.ts
  packages/metrics/src/features/legacy/handler.test.ts
  packages/metrics/src/features/legacy/handler.ts
  packages/metrics/src/features/locationWiseEventEstimations/handler.test.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/test/setupJest.ts
  packages/search/package.json
  packages/search/src/elasticsearch/client.ts
  packages/search/src/elasticsearch/dbhelper.ts
  packages/search/src/features/search/handler.ts
  packages/search/tsconfig.json
  yarn.lock
Labels: ⏳ Waiting for CI

#2580 Ocrvs 2427 Added DECLARATION_UPDATED task
  packages/client/src/components/DuplicateDetails.tsx
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-template.test.ts
  packages/workflow/src/features/registration/fhir/fhir-template.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/fhir/fhir-bundle-modifier.ts
Labels: ✅ Ready for merging

#2621 ocrvs-2456 Amend search to use RecordAudit
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/FieldAgentHome/FieldAgentHome.test.tsx
  packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
  packages/client/src/views/FieldAgentHome/InProgress.tsx
  packages/client/src/views/FieldAgentHome/SentForReview.tsx
  packages/client/src/views/Home/Details.test.tsx
  packages/client/src/views/Home/Details.tsx
  packages/client/src/views/Home/RecordAudit.test.tsx
  packages/client/src/views/Home/RecordAudit.tsx
  packages/client/src/views/Home/queries.ts
  packages/client/src/views/OfficeHome/tabs/approvals/approvalTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/approvals/approvalTab.tsx
  packages/client/src/views/OfficeHome/tabs/externalValidation/externalValidationTab.tsx
  packages/client/src/views/OfficeHome/tabs/inProgress/inProgressTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/inProgress/inProgressTab.tsx
  packages/client/src/views/OfficeHome/tabs/print/printTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/print/printTab.tsx
  packages/client/src/views/OfficeHome/tabs/reject/rejectTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/reject/rejectTab.tsx
  packages/client/src/views/OfficeHome/tabs/review/reviewTab.test.tsx
  packages/client/src/views/OfficeHome/tabs/review/reviewTab.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: ✅ Ready for merging
