Repository opencrvs/opencrvs-core, pull requests merged in 2023-04, with the labels that each got.

#4945 ocrvs-4472: View potential duplicate in user audit page
  packages/client/src/i18n/messages/views/userSetup.ts
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/audit/service.ts
  packages/metrics/src/features/registration/handler.ts
  packages/migration/migrations/openhim/20230328101901-potential-duplicate.cjs
  packages/workflow/src/features/events/utils.ts
Labels: ✅ Ready for merging

#5000 [OCRVS-4862] Enable custom fields to omit "required" field
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
Labels: 🇨🇲 Cameroon

#4968 fix(components): update disabled text inputs to have grey border
  packages/client/src/components/charts/RegRatesLineChart.tsx
  packages/client/src/views/UserSetup/UserSetupPage.tsx
  packages/components/src/AppHeader/Mobile/MobileHeader.tsx
  packages/components/src/Box/Box.tsx
  packages/components/src/SideNavigation/LeftNavigation.tsx
  packages/components/src/TextInput/TextInput.tsx
  packages/components/src/ToggleMenu/ToggleMenu.tsx
  packages/components/src/ViewData/DataRow.tsx
  packages/components/src/ViewData/ListRow.tsx
  packages/components/src/theme.ts
  packages/login/src/views/resetCredentialsForm/updatePasswordForm.tsx
Labels: 💅 Waiting For Review

#4983 fix: tabs alignment left
  packages/components/src/FormTabs/FormTabs.stories.tsx
  packages/components/src/FormTabs/components/Tabs.tsx
Labels: ✅ Ready for merging

#4981 fix: font size used in input and select field
  packages/components/src/Select/Select.tsx
  packages/components/src/TextInput/TextInput.tsx
Labels: ✅ Ready for merging

#5005 fix underline with links
  packages/components/src/Link/Link.tsx
Labels: ✅ Ready for merging

#4988 fix: Accordian ui
  packages/components/src/Accordion/Accordion.tsx
Labels: ✅ Ready for merging

#4974 Fix marriage declaration proofOfMarriageNotice attachment not showing in review Section
  packages/client/src/forms/configuration/default/marriage.ts
Labels: 💅 Waiting For Review

#4989 fix: Advance search and results ui
  packages/client/src/i18n/messages/views/advancedSearchResult.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/AdvancedSearch/BookmarkAdvancedSearchResult.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
Labels: ✅ Ready for merging

#4943 Show specific error when no internet
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/views/UserSetup/SetupReviewPage.tsx
Labels: 🇳🇬 Nigeria

#5019 [OCRVS-4994] Enable default configuration format for config coming from country config
  packages/client/src/forms/configuration/customUtils.ts
  packages/config/src/handlers/question/getQuestions/handler.test.ts
  packages/config/src/handlers/question/getQuestions/handler.ts
Labels: 🇨🇲 Cameroon

#4998 fix: Select to use Icon
  packages/components/src/Select/Select.stories.tsx
  packages/components/src/Select/Select.tsx
  packages/components/stories/iconography.stories.mdx
  packages/components/stories/intro.stories.mdx
Labels: ✅ Ready for merging, 🏎 Auto Merging

#4986 Implement mandatory 'Status' (title) for all users
  packages/client/graphql.schema.json
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/userForm.ts
  packages/client/src/profile/queries.ts
  packages/client/src/tests/util.tsx
  packages/client/src/user/queries.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/Settings/SettingsPage.tsx
  packages/client/src/views/Settings/items/Title.tsx
  packages/client/src/views/Settings/items/index.ts
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/Unlock/ForgotPIN.test.tsx
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/features/resendSMSInvite/handler.test.ts
  packages/user-mgnt/src/features/resetPassword/handler.test.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.test.ts
  packages/user-mgnt/src/model/user.ts
Labels: 🇨🇲 Cameroon

#5038 fix(metabase): update-database script 'envsubst' -check for Ubuntu
  packages/dashboards/update-database.sh
Labels: ✅ Ready for merging

#5020 Certificate template amends
  packages/client/src/templates/register.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5057 Add lga to population estimeted per day table
  packages/migration/migrations/hearth/20230406120018-add-lga-to-population-estimates-per-day.js
Labels: 🇳🇬 Nigeria

#4987 fix: record audit buttons order and alignment
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/components/src/AppBar/AppBar.tsx
  packages/components/src/Content/Content.tsx
  packages/components/src/Icon/all-icons.ts
Labels: ✅ Ready for merging

#4997 fix: small UI updates to Avatar
  packages/client/src/components/Avatar/AvatarSmall.tsx
  packages/client/src/components/Avatar/AvatarVerySmall.tsx
  packages/client/src/components/Avatar/index.ts
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/utils/constants.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/user-mgnt/src/constants.ts
Labels: ✅ Ready for merging

#4999 fix: changes nav buttons to medium
  packages/client/src/components/Header/HistoryNavigator.tsx
Labels: ✅ Ready for merging

#5015 Fixed EventRegistration __resolveType gor health notification
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/query/declaration-mappings.ts
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: ✅ Ready for merging

#5017 set default page dashboard
  packages/client/src/navigation/index.ts
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/Performance/Dashboard.tsx
Labels: ✅ Ready for merging

#5018 Fixed optional marriageDate outbox error
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
Labels: ✅ Ready for merging

#5047 Ocrvs 4957
  packages/metrics/src/features/metrics/utils.test.ts
  packages/metrics/src/features/metrics/utils.ts
Labels: ✅ Ready for merging

#5027 refactor: TextArea background to white
  packages/components/src/TextArea/TextArea.tsx
Labels: 💅 Waiting For Review

#5082 fix migration issue
  packages/metrics/src/features/analytics/viewRefresher.ts
Labels: 🇳🇬 Nigeria

#5056 Upgrade storybook to 7.0
  package.json
  packages/client/src/components/charts/RegRatesLineChart.tsx
  packages/components/.storybook/main.ts
  packages/components/.storybook/manager-head.html
  packages/components/.storybook/manager.ts
  packages/components/.storybook/preview.jsx
  packages/components/.storybook/preview.tsx
  packages/components/.storybook/theme.ts
  packages/components/package.json
  packages/components/src/AppBar/AppBar.tsx
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/DateField/DateField.tsx
  packages/components/src/Divider/Divider.stories.mdx
  packages/components/src/FileSelectLink/FileSelectLink.tsx
  packages/components/src/Icon/Icon.stories.tsx
  packages/components/src/Icon/Icon.tsx
  packages/components/src/ImageUploader/ImageUploader.tsx
  packages/components/src/LineChart/LineChart.tsx
  packages/components/stories/colors.stories.mdx
  packages/components/stories/iconography.stories.mdx
  packages/components/stories/intro.stories.mdx
  packages/components/stories/releases.stories.mdx
  packages/components/stories/typography.stories.mdx
  packages/components/tsconfig.json
  packages/documents/package.json
  yarn.lock
Labels: ✅ Ready for merging

#5090 Force disk encryption and enable configurable diskspace
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
Labels: 📄 Documentation

#5093 [OCRVS-4967] Enable running migrations against a completely empty database
  packages/migration/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.js
Labels: 🇨🇲 Cameroon

#5054 CAMEROON: Declarant/informant page in Birth form
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/tests/util.tsx
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/RegisterForm/DeclarationForm.test.tsx
  packages/client/src/views/ViewRecord/ViewRecord.test.tsx
Labels: 🏎 Auto Merging, 🇨🇲 Cameroon

#5092 Fixed spelling of 'two' for 2nd witness while declaring marriage records
  packages/client/src/forms/configuration/default/marriage.ts
Labels: ✅ Ready for merging

#5063 Ocrvs 5023 Certificate amends
  packages/client/package.json
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/i18n/components/I18nContainer.tsx
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/PrintCertificate/PDFUtils.test.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/SysAdmin/Config/Application/utils.ts
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🇨🇲 Cameroon

#5104 Add Registrar filtering
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/views/performance.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Performance/Registrations.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/client/src/views/SysAdmin/Performance/reports/registrations/RegistrationsDataTable.tsx
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/metrics/schema.graphql
  packages/gateway/src/features/metrics/type-resolver.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/officewiseRegistrations/handler.ts
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/influxdb/client.ts
  packages/migration/migrations/hearth/20230414085340-add_practitioner_id_event_registrations.js
  packages/migration/utils/influx-helper.js
Labels: 🇳🇬 Nigeria

#5103 Fixed incomplete marriage declaration not store in elastic
  packages/search/src/features/registration/marriage/service.ts
Labels: 💅 Waiting For Review

#5100 fix dashboard redirect for national registrar
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/views/OfficeHome/Home.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
Labels: ✅ Ready for merging

#5106 Update messages based on logic
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/utils/validate.ts
Labels: 🇳🇬 Nigeria

#5107 HOTFIX: Address fields exception
  packages/client/src/utils/referenceApi.ts
Labels: ✅ Ready for merging

#5117 Ocrvs 5035 Born on date in words
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 🇨🇲 Cameroon

#4933 Mosip callback handling and formdata population
  .github/workflows/deploy.yml
  deploy.sh
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/nidVerificationCallback.ts
  packages/client/src/setupTests.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/transformer/index.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.test.tsx
  packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.tsx
  packages/client/src/views/OIDPVerificationCallback/queries.ts
  packages/client/src/views/OIDPVerificationCallback/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/Select/Select.tsx
  packages/components/src/VerificationButton/VerificationButton.tsx
  packages/gateway/src/constants.ts
  packages/gateway/src/features/OIDPUserInfo/oidp-types.ts
  packages/gateway/src/features/OIDPUserInfo/schema.graphql
  packages/gateway/src/features/OIDPUserInfo/utils.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/test/setupJest.ts
  packages/user-mgnt/src/constants.ts
Labels: 💅 Waiting For Review

#5122 Security ques feature & Add missing avatar
  packages/auth/src/features/retrievalSteps/verifyNumber/handler.ts
  packages/auth/src/features/retrievalSteps/verifyUser/handler.ts
  packages/auth/src/features/retrievalSteps/verifyUser/service.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/client/src/views/SysAdmin/Performance/reports/registrations/RegistrationsDataTable.tsx
  packages/login/src/login/actions.ts
  packages/login/src/utils/authApi.ts
  packages/login/src/views/resetCredentialsForm/phoneNumberVerificationForm.tsx
  packages/login/src/views/resetCredentialsForm/recoveryCodeEntryForm.tsx
  packages/login/src/views/resetCredentialsForm/securityQuestionForm.tsx
  packages/user-mgnt/src/features/verifySecurityAnswer/handler.ts
  packages/user-mgnt/src/features/verifyUser/handler.ts
  packages/user-mgnt/src/model/user.ts
Labels: 🇳🇬 Nigeria

#5124 [OCRVS-4975] Make signature required for registration agents and registrars
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
Labels: 🇨🇲 Cameroon

#5109 Disallow registration without secretary signature
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
Labels: 🇨🇲 Cameroon

#5052 feat(si-hackathon): handle integrating system type OSIA
  .github/workflows/deploy.yml
  deploy.sh
  packages/client/graphql.schema.json
  packages/client/src/components/form/FetchButton.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/deserializer.ts
  packages/client/src/forms/mappings/mutation/field-mapping.test.ts
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/register/queries/useVerifyNationalIdQuery.ts
  packages/client/src/forms/utils.ts
  packages/client/src/hooks/useCurrentDraftDeclaration.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/components/src/VerificationButton/VerificationButton.stories.tsx
  packages/components/src/VerificationButton/VerificationButton.tsx
  packages/gateway/src/constants.ts
  packages/gateway/src/features/verifyNationalId/root-resolvers.ts
  packages/gateway/src/features/verifyNationalId/schema.graphql
  packages/gateway/src/features/verifyNationalId/utils.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/constants.ts
  packages/user-mgnt/src/model/system.ts
  packages/user-mgnt/src/utils/system.ts
Labels: 👌 LGTM

#5144 Force disk encryption and add encrypted_disk_size param for Ansible
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
Labels: 📄 Documentation

#5123 Ocrvs 5081 - recordSearch api update for marriages
  packages/gateway/src/features/bookmarkAdvancedSearch/schema.graphql
  packages/gateway/src/features/correction/root-resolvers.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.ts
Labels: 📄 Documentation

#5156 feat(search): allow searching with record/composition/declaration id
  packages/gateway/src/features/bookmarkAdvancedSearch/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.ts
Labels: 👌 LGTM

#5050 [si-hackathon] Certified webhook
  docker-compose.yml
  packages/migration/migrations/openhim/20230405091629-add-webhook-on-certified.cjs
  packages/webhooks/src/config/routes.ts
  packages/webhooks/src/constants.ts
  packages/webhooks/src/features/event/handler.ts
  packages/webhooks/src/features/event/service.ts
  packages/workflow/src/features/registration/handler.ts
  yarn.lock
Labels: 🔧Waiting for fixes

#5166 CAMEROON: Declarant/Informant page in Death form
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 🇨🇲 Cameroon

#5177 Modify visibilty based on existance information & change navbar title inconsistency
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging

#5172 Add office select input in review section component
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/mutation/event-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/mutation/registration-mappings.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/utils/constants.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/RegisterForm/review/RegistrationOfficeSelect.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.ts
Labels: 🚧 work in progress, 🇨🇲 Cameroon

#5165 Add OSIA_UIN_VID_NID to identifier of child if generation is successful
  infrastructure/license-config.json
  packages/client/graphql.schema.json
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/registration/handler.ts
Labels: ✅ Ready for merging
