Repository opencrvs/opencrvs-core, pull requests merged in 2023-03, with the labels that each got.

#4696 Bug fix on titleCase
  packages/migration/migrations/hearth/20230127063226-update-practitioner-role.js
  packages/migration/package.json
  yarn.lock
Labels: ✅ Ready for merging

#4779 feat(national-id-verification): add National ID verification environment variables to deploy.sh
  .github/workflows/deploy.yml
  deploy.sh
Labels: 💅 Waiting For Review

#4780 role optional for systems
  packages/search/src/elasticsearch/utils.ts
Labels: ✅ Ready for merging

#4783 feat(national-id-verification): check nonce in verification callback
  packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.tsx
  packages/client/src/views/OIDPVerificationCallback/utils.ts
Labels: 💅 Waiting For Review

#4778 Persistent middleware hotfix
  packages/client/src/App.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/utils/ApolloProvider.tsx
  packages/client/src/utils/apolloClient.ts
  packages/client/src/utils/persistence/persistenceMiddleware.ts
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: 💅 Waiting For Review

#4792 Verification button integration
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/components/src/VerificationButton/VerificationButton.tsx
Labels: 💅 Waiting For Review

#4804 feat(national-id-verification): create GraphQL endpoint to fetch data from OIDP endpoint
  .github/workflows/deploy.yml
  deploy.sh
  packages/gateway/package.json
  packages/gateway/src/config/routes.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/features/OIDPUserInfo/root-resolvers.test.ts
  packages/gateway/src/features/OIDPUserInfo/root-resolvers.ts
  packages/gateway/src/features/OIDPUserInfo/schema.graphql
  packages/gateway/src/features/OIDPUserInfo/utils.ts
  packages/gateway/src/features/oidp/handler.ts
  packages/gateway/src/features/oidp/oidp-types.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/test/setupJest.ts
  packages/gateway/tsconfig.json
  yarn.lock
Labels: ✅ Ready for merging

#4809 Fix e2e tests
  packages/client/src/declarations/index.ts
  packages/config/src/models/config.ts
Labels: ✅ Ready for merging

#4829 feat(national-id-verification): handle when user is offline
  packages/client/src/App.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/utils.ts
  packages/client/src/views/AdvancedSearch/RemoveBookmarkModal.tsx
  packages/client/src/views/AdvancedSearch/SaveBookmarkModal.tsx
  packages/client/src/views/OfficeHome/LoadingIndicator.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/Settings/items/Password.tsx
  packages/client/src/views/Settings/items/PhoneNumber.tsx
  packages/client/src/views/SysAdmin/InformantSMSNotification/InformantSMSNotification.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/VerificationButton/VerificationButton.stories.tsx
  packages/components/src/VerificationButton/VerificationButton.tsx
  packages/user-mgnt/src/features/system/handler.ts
Labels: 💅 Waiting For Review

#4813 ocrvs-4287 Fix informant SMS toggle
  packages/client/src/views/SysAdmin/InformantSMSNotification/InformantSMSNotification.tsx
Labels: 💅 Waiting For Review

#4530 feat(documentation): Workflow sequence diagrams (#4530
  sequence-diagrams/backend/create-birth-registration-registrar.md
  sequence-diagrams/backend/create-birth-registration.md
  sequence-diagrams/backend/mark-birth-as-archived.md
  sequence-diagrams/backend/mark-birth-as-assigned.md
  sequence-diagrams/backend/mark-birth-as-certified.md
  sequence-diagrams/backend/mark-birth-as-downloaded.md
  sequence-diagrams/backend/mark-birth-as-reinstated.md
  sequence-diagrams/backend/mark-birth-as-void.md
  sequence-diagrams/backend/request-birth-registration-correction.md
Labels: ✅ Ready for merging

#4801 ocrvs-4448: fix roles showing in English when language is French
  packages/client/src/views/RecordAudit/History.tsx
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: ✅ Ready for merging

#4655 fix: remove "0" from the front of version name
  README.md
  packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx
Labels: ✋ On Hold

#4839 Marriage declaration test
  packages/client/graphql.schema.json
  packages/client/src/forms/configuration/default/marriage.ts
  packages/client/src/tests/mock-drafts.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.test.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/PrintCertificate/utils.ts
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/scripts/VSExportGenerator.ts
Labels: 💅 Waiting For Review

#4825 Use facility names in health integrations
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: ✅ Ready for merging

#4843 [OCRVS-4808] Fix address field shifting issue in form config
  packages/client/src/forms/configuration/index.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#4826 Added custom validator for custom fields.
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/forms/advancedSearch/fieldDefinitions/Birth.ts
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/certificate/fieldDefinitions/payment-section.ts
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/administrative/utils.ts
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/configuration/formConfig/utils/defaultConfig.ts
  packages/client/src/forms/configuration/formConfig/utils/index.ts
  packages/client/src/forms/configuration/formConfig/utils/previewGroup.ts
  packages/client/src/forms/correction/corrector.ts
  packages/client/src/forms/correction/payment.ts
  packages/client/src/forms/correction/reason.ts
  packages/client/src/forms/correction/supportDocument.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/deserializer.test.tsx
  packages/client/src/forms/mappings/deserializer.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/forms/utils.ts
  packages/client/src/forms/validation.ts
  packages/client/src/review/reject-registration.ts
  packages/client/src/tests/util.tsx
  packages/client/src/user/user-audit.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueFormForOthers.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/SysAdmin/Config/UserRoles/utils.ts
  packages/config/src/models/question.ts
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🇨🇲 Cameroon

#4835 [OCRVS-4818] Enable making a default field optional, flag to run validations on empty fields
  packages/client/graphql.schema.json
  packages/client/src/forms/configuration/formConfig/utils/defaultConfig.ts
  packages/client/src/forms/configuration/formConfig/utils/index.ts
  packages/client/src/forms/configuration/formConfig/utils/previewGroup.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/deserializer.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/forms/validation.ts
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/validate.ts
  packages/config/src/models/question.ts
  packages/gateway/src/graphql/schema.d.ts
Labels: 🇨🇲 Cameroon

#4831 Allow apostrophe and hyphen in english name
  packages/client/src/utils/validate.test.ts
  packages/client/src/utils/validate.ts
Labels: 🇳🇬 Nigeria

#4836 Show correct role in details page while user setup
  packages/client/src/views/UserSetup/SetupReviewPage.tsx
Labels: 🇳🇬 Nigeria

#4844 Add eye icon for password setup
  packages/client/src/views/Settings/PasswordChangeModal.tsx
  packages/client/src/views/UserSetup/CreatePassword.tsx
Labels: 🇳🇬 Nigeria

#4857 Temporary webhook route for marriage declaration
  packages/webhooks/src/config/routes.ts
  packages/webhooks/src/features/event/handler.ts
Labels: 💅 Waiting For Review

#4824 Add unit in custom number field
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/deserializer.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/views/customFieldForm.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/components/src/InputField/InputField.tsx
  packages/config/src/handlers/question/createQuestion/handler.ts
  packages/config/src/handlers/question/updateQuestion/handler.ts
  packages/config/src/models/question.ts
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/login/src/utils/fieldUtils.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#4840 Fixed certificate test handle rejection
  packages/client/src/views/PrintCertificate/utils.ts
Labels: ✅ Ready for merging

#4864 Fixed client unit test
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
Labels: 💅 Waiting For Review

#4866 Added cross button on verify certificate page
  packages/client/src/views/IssueCertificate/IssueCertificate.tsx
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
Labels: ✅ Ready for merging

#4877 Marriage declaration
  packages/client/graphql.schema.json
  packages/client/src/App.tsx
  packages/client/src/components/SessionExpireConfirmation.tsx
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/configuration/default/marriage.ts
  packages/client/src/profile/profileActions.ts
  packages/client/src/profile/profileReducer.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/DataProvider/marriage/mutations.ts
  packages/client/src/views/IssueCertificate/IssueCertificate.tsx
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
  packages/gateway/src/features/location/schema.graphql
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/login/src/Page.tsx
  packages/login/src/login/actions.ts
  packages/login/src/login/reducer.ts
Labels: 💅 Waiting For Review

#4799 ocrvs-4720: Remove extra location id in catchmentAreasId
  packages/user-mgnt/src/features/createUser/handler.test.ts
  packages/user-mgnt/src/features/createUser/service.ts
Labels: ✅ Ready for merging

#4867 Check if registrationSMS is turn on before send notification for birth and death
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/utils.ts
Labels: ✅ Ready for merging

#4816 fix dateOfDeath of being any age
  packages/client/src/forms/configuration/default/death.ts
Labels: ❌ Conflicts

#4819 Ocrvs 4812- readyToIssue hidden based on printInAdvance
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
Labels: ✅ Ready for merging

#4873 correction record flow fix for issued declaration
  packages/client/src/views/CorrectionForm/utils.ts
Labels: ✅ Ready for merging

#4889 ocrvs-4556
  packages/client/src/i18n/messages/views/formConfig.ts
Labels: ✅ Ready for merging

#4871 Add warning circle validation for multiple inputs
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/components/src/components/forms/DateField.tsx
Labels: 🇳🇬 Nigeria

#4879 Remove state adress from urban field
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/register/fieldMappings/death/mutation/event-mappings.ts
Labels: 🇳🇬 Nigeria

#4885 Full name fix for team page
  packages/gateway/src/features/user/root-resolvers.ts
Labels: 🇳🇬 Nigeria

#4870 Fixed certification issued count
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
Labels: 💅 Waiting For Review

#4872 Fixed verify collector hasShowedVerifiedDocument bug
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
Labels: ✅ Ready for merging

#4878 Fixed Local Registrar role in certificate preview
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
Labels: ✅ Ready for merging

#4851 feat(national-id-verification): transform OIDP string locations to Hearth FHIR Id's
  .github/workflows/deploy.yml
  deploy.sh
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/features/OIDPUserInfo/oidp-types.ts
  packages/gateway/src/features/OIDPUserInfo/root-resolvers.test.ts
  packages/gateway/src/features/OIDPUserInfo/schema.graphql
  packages/gateway/src/features/OIDPUserInfo/utils.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/test/setupJest.ts
Labels: 💅 Waiting For Review

#4891 Fixed vsExport for issued
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/metrics/src/scripts/VSExportGenerator.ts
Labels: ✅ Ready for merging

#4887 view page and comment field fix
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging

#4827 feat(national-id-verification): rename MOSIP_UINTOKEN to MOSIP_PSUT_TOKEN_ID
  packages/client/graphql.schema.json
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/test/utils.ts
Labels: 💅 Waiting For Review, 📄 Documentation

#4905 Ocrvs 4820 - advanceSearch fix for registered declarations
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
Labels: ✅ Ready for merging

#4906 Fix resendSMS error notification
  packages/login/src/views/StepTwo/StepTwoContainer.tsx
Labels: ✅ Ready for merging

#4914 Fix child age +/-3 year for birth deduplication
  packages/search/src/features/registration/deduplicate/deduplicate.test.ts
  packages/search/src/features/registration/deduplicate/service.ts
Labels: 💅 Waiting For Review

#4770 fix: Remove 3 dot menu for LOCAL_USER_ADMIN in user audit
  packages/client/src/views/UserAudit/UserAudit.test.tsx
  packages/client/src/views/UserAudit/UserAudit.tsx
Labels: 💅 Waiting For Review

#4894 add warning circle in review page
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 🇳🇬 Nigeria

#4908 Fix security question related issues
  packages/login/src/i18n/messages/views/resetCredentialsForm.ts
  packages/login/src/utils/dataCleanse.ts
  packages/login/src/views/resetCredentialsForm/phoneNumberVerificationForm.tsx
  packages/login/src/views/resetCredentialsForm/recoveryCodeEntryForm.tsx
  packages/login/src/views/resetCredentialsForm/securityQuestionForm.tsx
  packages/login/src/views/resetCredentialsForm/updatePasswordForm.tsx
  packages/user-mgnt/src/features/verifySecurityAnswer/handler.ts
Labels: 🇳🇬 Nigeria

#4917 Shows death duplicate notification toast and added deceaseDob for duplicate logic
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/search/src/features/registration/deduplicate/deduplicate.test.ts
  packages/search/src/features/registration/deduplicate/service.ts
Labels: 💅 Waiting For Review

#4915 issue tab trackingId and regNo sort
  packages/client/src/views/OfficeHome/utils.ts
Labels: ✅ Ready for merging

#4920 Fixed RA duplicate flow issue
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
Labels: 💅 Waiting For Review

#4899 Add missing fields & reorganise mother & father sections
  packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/config/src/models/question.ts
Labels: 🇨🇲 Cameroon

#4909 ocrvs-4901
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/user.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RecordAudit/utils.ts
  packages/gateway/src/features/fhir/constants.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/constants.ts
  packages/search/src/elasticsearch/utils.test.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/composition.test.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
Labels: ✅ Ready for merging

#4921 duplicate comparison page DOB fix
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
Labels: ✅ Ready for merging

#4931 Unassign declaration on archive
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
Labels: 💅 Waiting For Review

#4932 Shows duplicates icon for declaration view
  packages/client/src/views/ViewRecord/ViewRecord.tsx
Labels: ✅ Ready for merging

#4880 feat(national-id-verification): Application configuration for National ID
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/client/src/views/SysAdmin/Config/Systems/useSystems.ts
  packages/components/src/Select/Select.stories.tsx
  packages/components/src/Select/Select.tsx
  packages/components/stories/releases.stories.mdx
  packages/gateway/src/features/systems/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/migrations/user-mgnt/20230315074827-create-integrating-system-type.js
  packages/user-mgnt/src/features/system/handler.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/test/utils.ts
Labels: ✅ Ready for merging

#4884 Ocrvs 4806 Certificate multiple signatures
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 👌 LGTM, 🇨🇲 Cameroon

#4951 Shows marriageDate on draft work-queue
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
Labels: 💅 Waiting For Review

#4962 Fixed marriage declaration attachment bug
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#4966 fix(national-id-verification): integratingSystemType issues
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/utils/nationalIdUtils.ts
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/client/src/views/SysAdmin/Config/Systems/mutations.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/model/system.ts
  packages/user-mgnt/src/utils/system.ts
Labels: 💅 Waiting For Review

#4959 Search with bride and groom name, nid
  infrastructure/license-config.json
  packages/dashboards/initialize-database.sh
  packages/dashboards/open-shell.sh
  packages/dashboards/run-dev.sh
  packages/dashboards/run.sh
  packages/dashboards/update-database.sh
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/utils.ts
Labels: 💅 Waiting For Review

#4875 #4750 Fix local - international - local phone number transformations for all countries
  packages/client/package.json
  packages/client/src/forms/mappings/query/field-mapping.test.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.test.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/forms/utils.ts
  packages/client/src/profile/profileReducer.test.ts
  packages/client/src/setupTests.ts
  packages/client/src/utils/locationUtils.test.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/Settings/ChangePhoneModal/ChangeNumberView.tsx
  packages/client/src/views/Settings/ChangePhoneModal/VerifyCodeView.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx
  packages/gateway/package.json
  packages/gateway/src/features/user/utils/index.test.ts
  packages/gateway/src/features/user/utils/index.ts
  packages/gateway/typings/country-data.d.ts
  packages/login/package.json
  packages/login/src/utils/dataCleanse.ts
  packages/login/src/views/resetCredentialsForm/phoneNumberVerificationForm.test.tsx
  packages/login/typings/country-data.d.ts
  packages/workflow/package.json
  packages/workflow/src/features/user/utils.ts
  yarn.lock
Labels: 🇨🇲 Cameroon

#4978 fix: width of team page
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: ✅ Ready for merging

#4973 fix: updates icon weight to bold
  packages/components/src/Icon/Icon.tsx
Labels: ✅ Ready for merging

#4990 fix: LocationSearch ui
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/LocationSearch/LocationSearch.tsx
Labels: 💅 Waiting For Review
