Repository opencrvs/opencrvs-core, pull requests merged in 2023-08, with the labels that each got.

#5725 Fixed email notification flow
  packages/notification/src/config/routes.ts
  packages/notification/src/features/sms/birth-handler.ts
  packages/notification/src/features/sms/death-handler.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.ts
Labels: 💅 Waiting For Review

#5721 Unit test fix
  packages/client/src/tests/util.tsx
  packages/client/src/views/CorrectionForm/ReviewForm.test.tsx
  packages/client/src/views/RegisterForm/DeclarationForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/gateway/src/features/correction/root-resolvers.test.ts
  packages/gateway/src/features/fhir/utils.test.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/death-fhir-builders.test.ts
  packages/gateway/src/features/registration/death-type-resolvers.test.ts
  packages/gateway/src/features/registration/fhir-builders.test.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/notification/src/features/sms/birth-handler.test.ts
  packages/notification/src/features/sms/death-handler.test.ts
  packages/notification/src/index.test.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/test/utils.ts
Labels: 💅 Waiting For Review

#5601 Feature data seeding
  package.json
  packages/auth/src/features/authenticateSuperUser/handler.ts
  packages/auth/src/server.ts
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/handlers/certificate/certificateHandler.test.ts
  packages/config/src/handlers/certificate/certificateHandler.ts
  packages/config/src/models/certificate.ts
  packages/data-seeder/.eslintrc.js
  packages/data-seeder/README.md
  packages/data-seeder/package.json
  packages/data-seeder/src/certificates.ts
  packages/data-seeder/src/constants.ts
  packages/data-seeder/src/index.ts
  packages/data-seeder/src/locations.ts
  packages/data-seeder/src/roles.ts
  packages/data-seeder/src/users.ts
  packages/data-seeder/src/utils.ts
  packages/data-seeder/tsconfig.json
  packages/gateway/src/constants.ts
  packages/gateway/src/features/certificate/root-resolvers.ts
  packages/gateway/src/features/restLocation/locationHandler.ts
  packages/gateway/src/features/restLocation/utils.ts
  packages/gateway/src/features/role/schema.graphql
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/index.test.ts
  packages/gateway/src/server.ts
  packages/migration/package.json
  packages/migration/src/migrations/application-config/20230301124048-add-marriage-certificate-configuration.ts
  packages/migration/src/migrations/hearth/20230127063226-update-practitioner-role.ts
  packages/migration/src/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.ts
  packages/migration/src/migrations/user-mgnt/20230615104846-create-opencrvs-super-user.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/features/updateRole/handler.ts
  packages/user-mgnt/src/model/systemRole.ts
  packages/user-mgnt/src/server.ts
  yarn.lock
Labels: 🚧 work in progress

#5732 exit button fix
  packages/client/src/declarations/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: ✅ Ready for merging

#5730 last updated time fix
  packages/client/src/declarations/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
Labels: ✅ Ready for merging

#5735 preview certificate fix
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
Labels: 👌 LGTM

#5741 Fixed informant email notification
  packages/notification/src/features/sms/birth-handler.ts
  packages/notification/src/features/sms/death-handler.ts
  packages/workflow/src/features/registration/utils.ts
Labels: 💅 Waiting For Review

#5724 Validator to check that a date is valid
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/utils/validate.ts
Labels: 🇨🇲 Cameroon

#5750 update maxLength from cameroon config
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/index.tsx
Labels: 🇨🇲 Cameroon

#5752 ocrvs-5562 Location data validation & seeding process improvements
  deploy.sh
  infrastructure/restore-metadata.sh
  package.json
  packages/data-seeder/package.json
  packages/data-seeder/src/certificates.ts
  packages/data-seeder/src/constants.ts
  packages/data-seeder/src/index.ts
  packages/data-seeder/src/locations.ts
  packages/data-seeder/src/roles.ts
  packages/data-seeder/src/users.ts
  packages/data-seeder/src/utils.ts
  packages/data-seeder/tsconfig.json
  packages/gateway/src/constants.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/features/createUser/handler.ts
Labels: 👌 LGTM

#5441 ocrvs-5257 configurable child identifiers
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.ts
Labels: 👌 LGTM

#5449 saving system object in task instead of systemId
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/client/src/views/RecordAudit/History.tsx
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/src/migrations/hearth/20230602090436-update-identifier-with-system.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
Labels: 👌 LGTM

#5757 brn drn messages update
  packages/client/src/components/Header/Header.tsx
  packages/client/src/i18n/messages/views/header.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
Labels: ✅ Ready for merging

#5762 refactor: small ui fixes
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/components/src/BulletList/BulletList.tsx
  packages/components/src/Content/Content.tsx
Labels: ✅ Ready for merging

#5775 user create page fix
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: ✅ Ready for merging

#5766 fix save and exit button for correct record
  packages/client/src/i18n/messages/views/register.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#5771 heading component update
  packages/components/src/Heading3/Heading3.tsx
Labels: 💅 Waiting For Review

#5777 Fix wrong name appearing in certified audit for multiple certified de…
  packages/client/src/views/RecordAudit/History.tsx
Labels: 💅 Waiting For Review, 👌 LGTM

#5798 Data generator fix: Update schema and fhir-builders
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#5787 date of birth fix in id verifier
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
Labels: 💅 Waiting For Review

#5817 Remove retry on seed fail
  development-environment/seed.sh
  package.json
Labels: 💅 Waiting For Review

#5823 fix user activation modal
  packages/client/src/user/userReducer.ts
Labels: ⏳ Waiting for CI, ✅ Ready for merging

#5646 hide search option based on availability of form data
  packages/client/src/components/Header/Header.tsx
Labels: ⏳ Waiting for CI, ✅ Ready for merging

#5836 Rename seed vars, deprecate old secrets
  packages/data-seeder/src/certificates.ts
  packages/data-seeder/src/constants.ts
  packages/data-seeder/src/index.ts
  packages/data-seeder/src/locations.ts
  packages/data-seeder/src/roles.ts
  packages/data-seeder/src/users.ts
Labels: 💅 Waiting For Review

#5819 Check for MARRIAGE event for bride/groom informant
  packages/gateway/src/features/registration/fhir-builders.ts
Labels: 💅 Waiting For Review

#5828 dashboard urls hide for prod
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/utils/constants.ts
Labels: ✅ Ready for merging

#5832 id verifier for correction modal title fix
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
Labels: ✅ Ready for merging

#5834 fix informant type change to parent
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: ✅ Ready for merging

#5835 ocrvs-5826 Return presigned url from vsexport resolver
  packages/client/src/views/SysAdmin/Vsexports/VSExport.tsx
  packages/gateway/src/features/metrics/type-resolvers.ts
Labels: 💅 Waiting For Review

#5742 Appearing spinner after logging in
  packages/client/src/components/Page.tsx
Labels: 💅 Waiting For Review

#5840 creating user in offline toast message fix
  packages/client/src/components/Notification.tsx
  packages/client/src/i18n/messages/views/notifications.ts
Labels: 💅 Waiting For Review
