Repository opencrvs/opencrvs-core, pull requests merged in 2023-07, with the labels that each got.

#5624 Cameroon update size and margin of helpertext
  packages/components/src/InputField/InputDescriptor.tsx
Labels: 🇨🇲 Cameroon

#5627 fix(pentest): remove unsafe inline CSP
  infrastructure/nginx-default.conf
Labels: ✅ Ready for merging

#5625 fix(pentest): remove nginx version from being exposed
  infrastructure/nginx-default.conf
Labels: ✅ Ready for merging

#5580 ocrvs-5540 Seed roles
  packages/gateway/src/features/dataSeeding/index.ts
  packages/migration/src/migrations/hearth/20230127063226-update-practitioner-role.ts
  packages/migration/src/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.ts
  packages/migration/src/migrations/user-mgnt/20230615104846-create-opencrvs-super-user.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/systemRole/create.ts
  packages/user-mgnt/src/features/updateRole/handler.ts
  packages/user-mgnt/src/model/systemRole.ts
  packages/user-mgnt/src/server.ts
Labels: 💅 Waiting For Review

#5630 seeding certificate
  packages/config/src/models/certificate.ts
  packages/gateway/src/features/dataSeeding/certificateSeeding.ts
  packages/gateway/src/features/dataSeeding/index.ts
Labels: 💅 Waiting For Review

#5636 Stack {{name}} {{Givennames}} for Registrar and Secretary
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/pdfRenderer/transformer/userTransformer.ts
Labels: 🇨🇲 Cameroon

#5634 Cameroon: Localize office names
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/Organisation/AdministrativeLevels.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RegisterForm/review/RegistrationOfficeSelect.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: 🇨🇲 Cameroon

#5548 refactor: document viewer/s
  packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentPreview.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx
  packages/components/src/Divider/Divider.tsx
  packages/components/src/DocumentViewer/DocumentViewer.tsx
  packages/components/src/DocumentViewer/components/DocumentImage.tsx
  packages/components/src/DocumentViewer/components/PanControls.tsx
  packages/components/src/DocumentViewer/components/PanViewer.tsx
Labels: 💅 Waiting For Review

#5518 Create elastic search index after service is up
  dev.sh
  setup-elastic-index.sh
Labels: 👌 LGTM

#5559 birthDate in patient update for individual age
  packages/gateway/src/features/registration/fhir-builders.ts
Labels: 👌 LGTM, ⏳ Waiting for CI

#5644 GN-034 French translation of the nationalities must be in the feminine form.
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 🇨🇲 Cameroon

#5650 Ocrvs 5546
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/validators.ts
  packages/client/src/transformer/index.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/ViewRecord/query.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/registration/utils.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
Labels: 💅 Waiting For Review

#5661 Ocrvs 5514 Death Declaration Form
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/tests/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 💅 Waiting For Review

#5666 Fix end date always being set to end of today
  packages/client/src/components/DateRangePicker.test.tsx
  packages/client/src/components/DateRangePicker.tsx
Labels: 💅 Waiting For Review

#5667 ocrvs-5656 Sync performance & dashboards data created from data-generator
  packages/metrics/src/features/performance/viewRefresher.ts
  packages/migration/src/migrations/hearth/20230221105416-create-performance-views.ts
Labels: ⏳ Waiting for CI

#5652 GN-035 : the 'Confirm' button should be inactive until any change
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 🇨🇲 Cameroon

#5664 MR-031 - Cameroon marriage supporting document updated
  packages/client/src/forms/register/fieldMappings/marriage/mutation/documents-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/query/documents-mappings.ts
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🇨🇲 Cameroon

#5672 Hide date fields if unknown checkbox is checked
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/configuration/default/marriage.ts
Labels: 🇨🇲 Cameroon

#5668 Fixed marriage declaration form
  packages/client/graphql.schema.json
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/index.ts
  packages/client/src/user/user-audit.ts
  packages/client/src/user/userReducer.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/ViewRecord/query.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#5669 Cameroon GN 037
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/utils/constants.ts
  packages/client/src/views/OfficeHome/OfficeHome.test.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/workqueue/reducer.ts
Labels: 🏥 Failing Tests, 🇨🇲 Cameroon

#5641 ocrvs-5538 seed the locations
  packages/gateway/src/features/dataSeeding/index.ts
  packages/gateway/src/features/restLocation/utils.ts
Labels: 👌 LGTM, 🏥 Failing Tests

#5690 GN-038 : Fuzzy matching in location search in performance page
  packages/client/src/components/LocationPicker.tsx
  packages/components/package.json
  packages/components/src/LocationSearch/LocationSearch.tsx
  yarn.lock
Labels: 🇨🇲 Cameroon

#5692 ocrvs-5572 Informant email
  packages/client/graphql.schema.json
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/setupTests.ts
  packages/client/src/tests/mock-graphql-responses.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/InformantSMSNotification/InformantSMSNotification.tsx
  packages/client/src/views/SysAdmin/InformantSMSNotification/mutations.ts
  packages/client/src/views/SysAdmin/InformantSMSNotification/queries.ts
  packages/client/typings/window.d.ts
  packages/gateway/src/features/informantSMSNotifications/root-resolvers.test.ts
  packages/gateway/src/features/informantSMSNotifications/root-resolvers.ts
  packages/gateway/src/features/informantSMSNotifications/schema.graphql
  packages/gateway/src/features/informantSMSNotifications/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/notification/src/features/sms/birth-handler.test.ts
  packages/notification/src/features/sms/birth-handler.ts
  packages/notification/src/features/sms/death-handler.test.ts
  packages/notification/src/features/sms/death-handler.ts
  packages/notification/src/features/sms/service.test.ts
  packages/notification/src/features/sms/service.ts
  packages/notification/src/features/sms/user-handler.ts
  packages/notification/src/features/sms/utils.ts
  packages/notification/src/index.test.ts
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-template.test.ts
  packages/workflow/src/features/registration/fhir/fhir-template.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.test.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/smsNotificationUtils.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/handler.ts
  packages/workflow/src/test/utils.ts
Labels: 💅 Waiting For Review

#5685 GN-041: publish getLocalizedLocationName function
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 🇨🇲 Cameroon

#5712 Update Saving and Exiting a declaration form,View Record,Review section.
  packages/client/src/i18n/messages/views/register.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/client/src/views/ViewRecord/ViewRecord.tsx
Labels: 💅 Waiting For Review

#5720 hide upload button for supporting documents in review section when in viewRecord
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#5574 Change avatar and fix profile image loading issue
  packages/client/graphql.schema.json
  packages/client/src/components/interface/DownloadButton.test.tsx
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/search/queries.ts
  packages/client/src/search/transformer.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/RecordAudit/queries.ts
  packages/documents/src/config/routes.ts
  packages/documents/src/features/getDocument/handler.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/features/fhir/minioAPI.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/context.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/routes/getUserAvatar/export-all-route.ts
  packages/gateway/src/routes/getUserAvatar/handler.test.ts
  packages/gateway/src/routes/getUserAvatar/handler.ts
  packages/migration/src/migrations/user-mgnt/20230623175740-migrate-profile-image-to-minio.ts
  packages/migration/src/utils/minio-helper.ts
  packages/user-mgnt/src/constants.ts
  packages/user-mgnt/src/features/getAvatar/handler.ts
Labels: 👌 LGTM

#5683 Handle non 2XX response from /refreshToken endpoint
  packages/client/src/components/ProtectedPage.tsx
  packages/client/src/utils/authUtils.ts
Labels: 👌 LGTM
