Repository opencrvs/opencrvs-core, pull requests merged in 2023-11, with the labels that each got.

#6135 Skip decorative types when checking for unknowns
  packages/config/src/handlers/forms/validation.ts
Labels: 💥 Hot Fixes

#6146 ocrvs-6126 Introduce a new handlebar "printInAdvance"
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/PrintCertificate/utils.ts
Labels: 👌 LGTM, 💥 Hot Fixes, 📄 Documentation

#6152 ocrvs-6080 Handle empty deceased/child resource in search
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
Labels: 💥 Hot Fixes

#6151 ocrvs-6147 Support single location level in verify certificate
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
Labels: 💥 Hot Fixes

#6141 Opencrvs form flashes
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/views/PrintRecord/Body.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  yarn.lock
Labels: 🇨🇲 Cameroon

#6166 OCRVS-6022: Allow null values for user mobile and emailForNotification when creating users but still check for uniqueness
  packages/migration/src/migrations/user-mgnt/20231106130956-email-mobile-unique-index.ts
  packages/user-mgnt/src/model/user.ts
Labels: 💅 Waiting For Review

#6165 Fetch certificate configuration from country config
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/pdfRenderer/index.ts
  packages/client/src/pdfRenderer/transformer/types.ts
  packages/client/src/setupTests.ts
  packages/client/src/src-sw.ts
  packages/client/src/templates/register.ts
  packages/client/src/tests/templates.json
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 🔧Waiting for fixes, 💥 Hot Fixes, 📄 Documentation

#6173 ocrvs-6080 Initialize object before setting value
  packages/client/src/forms/register/mappings/event-specific-fields/death/mutation/deceased-mappings.ts
Labels: 💥 Hot Fixes

#6145 feat: rate limiting for gateway
  packages/gateway/package.json
  packages/gateway/src/config/plugins.ts
  packages/gateway/src/config/routes.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/rate-limit.test.ts
  packages/gateway/src/rate-limit.ts
  packages/gateway/src/routes/verifyCode/handler.test.ts
  packages/gateway/src/routes/verifyCode/handler.ts
  packages/gateway/src/server.ts
  packages/gateway/src/utils/redis-test-utils.ts
  packages/gateway/src/utils/redis.ts
  packages/gateway/test/setupJest.ts
  packages/search/src/features/registration/deduplicate/deduplicate.test.ts
  packages/search/src/features/registration/deduplicate/test-util.ts
  yarn.lock
Labels: 💅 Waiting For Review

#6184 chore: disable rate limiting
  packages/gateway/src/constants.ts
  packages/gateway/src/rate-limit.test.ts
Labels: 💅 Waiting For Review

#6189 Opencrvs translation for field agent
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/i18n/messages/views/selectInformant.ts
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
Labels: 🇨🇲 Cameroon

#6194 Fix missing correction request inputs
  packages/client/src/forms/utils.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/records/correction-request.ts
Labels: 👌 LGTM

#6112 Ocrvs 6093
  docker-compose.yml
  packages/workflow/src/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.test.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
Labels: 👌 LGTM, 💔 Conflicts

#6229 track all changed values for correction
  packages/client/src/transformer/index.ts
Labels: 👌 LGTM

#6196 ocrvs-6191 Use deceased death date to calculate birth
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/migration/package.json
  packages/migration/src/migrations/hearth/20231123125224-deceased-birth-date.ts
  packages/migration/src/utils/progressTracker.ts
Labels: 💅 Waiting For Review, 💥 Hot Fixes
