Repository opencrvs/opencrvs-core, pull requests merged in 2023-06, with the labels that each got.

#5450 Cameroon certificate font changes
  packages/client/src/pdfRenderer/common_vfs.ts
  packages/client/src/templates/register.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 🇨🇲 Cameroon

#5447 #5444 fixed missing event type in ready to issue
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/components/src/Tooltip/Tooltip.stories.tsx
  packages/components/src/Tooltip/Tooltip.tsx
Labels: ✅ Ready for merging

#5452 Cameroon display place of birth
  packages/client/src/forms/configuration/default/marriage.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/RecordAudit/utils.ts
Labels: 🇨🇲 Cameroon

#5430 add email field for username reminder and password reset flow, and add handlers changes accordingly
  packages/auth/src/features/authenticate/service.ts
  packages/auth/src/features/retrievalSteps/verifyUser/handler.ts
  packages/auth/src/features/retrievalSteps/verifyUser/service.ts
  packages/client/src/i18n/messages/views/sysAdmin.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/UserAudit/UserAudit.tsx
  packages/components/src/InputField/InputField.tsx
  packages/gateway/src/features/user/root-resolvers.ts
  packages/login/package.json
  packages/login/src/i18n/messages/validations.ts
  packages/login/src/i18n/messages/views/resetCredentialsForm.ts
  packages/login/src/i18n/messages/views/stepTwoForm.ts
  packages/login/src/login/actions.ts
  packages/login/src/login/index.test.ts
  packages/login/src/login/reducer.ts
  packages/login/src/utils/authApi.ts
  packages/login/src/utils/authUtils.ts
  packages/login/src/utils/validate.ts
  packages/login/src/views/StepTwo/StepTwoContainer.tsx
  packages/login/src/views/resetCredentialsForm/phoneNumberVerificationForm.test.tsx
  packages/login/src/views/resetCredentialsForm/phoneNumberVerificationForm.tsx
  packages/login/src/views/resetCredentialsForm/recoveryCodeEntryForm.tsx
  packages/user-mgnt/src/features/verifyUser/handler.ts
Labels: 💅 Waiting For Review

#5451 passed 'event' to performance/field-agent
  packages/client/src/navigation/index.ts
  packages/client/src/views/Performance/FieldAgentList.test.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/ApplicationSourcesReport.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/components/src/Tooltip/Tooltip.stories.tsx
  packages/components/src/Tooltip/Tooltip.tsx
Labels: ✅ Ready for merging

#5448 Decouple the notification service from the NOTIFICATION_DELIVERY_METH…
  packages/notification/src/constants.ts
  packages/notification/src/features/sms/birth-handler.ts
  packages/notification/src/features/sms/death-handler.ts
  packages/notification/src/features/sms/service.test.ts
  packages/notification/src/features/sms/service.ts
  packages/notification/src/features/sms/user-handler.ts
  packages/notification/src/features/sms/utils.ts
Labels: 💅 Waiting For Review

#5406 move deployment infrastructure from Core to Farajaland
  .github/workflows/deploy.yml
  README.md
  deploy.sh
  deploy_key.enc
  docker-compose.deploy.yml
  docker-compose.prod-deploy.yml
  docker-compose.qa-deploy.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.staging-deploy.yml
  infrastructure/clear-all-data.sh
  infrastructure/cryptfs/bootstrap.sh
  infrastructure/cryptfs/mount.sh
  infrastructure/cryptfs/umount.sh
  infrastructure/elasticsearch/jvm.options
  infrastructure/elasticsearch/roles/kibana_user.json
  infrastructure/elasticsearch/roles/search_user.json
  infrastructure/elasticsearch/setup-helpers.sh
  infrastructure/elasticsearch/setup-settings.sh
  infrastructure/elasticsearch/setup-users.sh
  infrastructure/elasticsearch/setup.sh
  infrastructure/hearth-queryparam-extensions.json
  infrastructure/logrotate.conf
  infrastructure/mongodb/README.md
  infrastructure/mongodb/on-deploy.sh
  infrastructure/monitoring/apm/apm-server.yml
  infrastructure/monitoring/beats/metricbeat.yml
  infrastructure/monitoring/beats/rollover-policy.json
  infrastructure/monitoring/elastalert/elastalert.yaml
  infrastructure/monitoring/elastalert/rules/alert.yaml
  infrastructure/monitoring/elastalert/rules/auth.yaml
  infrastructure/monitoring/kibana/config.ndjson
  infrastructure/monitoring/kibana/kibana.yml
  infrastructure/monitoring/logstash/logstash.conf
  infrastructure/monitoring/logstash/logstash.yml
  infrastructure/openhim-base-config.json
  infrastructure/openhim-console-config.deploy.json
  infrastructure/openhim-console-config.json
  infrastructure/restore-metadata.sh
  infrastructure/rotate-secrets.sh
  infrastructure/server-setup/example-1.ini
  infrastructure/server-setup/example-3.ini
  infrastructure/server-setup/example-5.ini
  infrastructure/server-setup/group_vars/all.yml
  infrastructure/server-setup/playbook-1.yml
  infrastructure/server-setup/playbook-3.yml
  infrastructure/server-setup/playbook-5.yml
  infrastructure/setup-deploy-config.sh
  license-config.json
  license-header.txt
  package.json
Labels: 💅 Waiting For Review

#5429 ocrvs-5413 reset performance & dashboard on form config change
  docker-compose.deploy.yml
  docker-compose.replicas-3.yml
  docker-compose.replicas-5.yml
  docker-compose.yml
  infrastructure/mongodb/on-deploy.sh
  packages/config/src/services/formDraftService.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/constants.ts
  packages/metrics/src/features/metrics/handler.ts
  packages/metrics/src/influxdb/client.ts
Labels: ✅ Ready for merging

#5477 Fix bug in data rendering in record audit
  packages/client/src/views/RecordAudit/utils.ts
Labels: 🇨🇲 Cameroon

#5453 Show state, district, city properly on correction view after location change
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging

#5486 Fixed email notification issues
  license-config.json
  packages/client/src/views/Settings/ChangeEmailModal/ChangeEmailView.tsx
  packages/client/src/views/Settings/items/EmailAddress.tsx
  packages/notification/src/features/sms/user-handler.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/resetPassword/handler.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/service.ts
Labels: 💅 Waiting For Review

#5478 Cameroon tranlate for preview page
  packages/client/src/forms/configuration/default/marriage.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/eventInfo.ts
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/RecordAudit/History.tsx
Labels: 🇨🇲 Cameroon

#5511 Update icons
  packages/client/public/favicon.ico
  packages/client/public/images/icons/icon-128x128.png
  packages/client/public/images/icons/icon-144x144.png
  packages/client/public/images/icons/icon-152x152.png
  packages/client/public/images/icons/icon-196x196.png
  packages/client/public/images/icons/icon-256x256.png
  packages/client/public/images/icons/icon-512x512.png
  packages/client/public/images/icons/icon-72x72.png
  packages/login/public/favicon.ico
Labels: 🇨🇲 Cameroon

#5498 Make certificate printable without collector form
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
Labels: 🇨🇲 Cameroon

#4694 Removed GQLHumanName because the name is already typed
  graphql.config.json
  packages/client/src/forms/configuration/administrative/utils.ts
  packages/client/src/forms/mappings/query/field-mapping.test.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.test.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/query/documents-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/query/declaration-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/query/documents-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/query/documents-mappings.ts
  packages/client/src/forms/register/queries/person.ts
  packages/client/src/pdfRenderer/transformer/userTransformer.ts
  packages/client/src/search/transformer.ts
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx
  packages/client/src/views/SysAdmin/Performance/reports/completenessRates/CompletenessDataTable.tsx
  packages/client/src/views/SysAdmin/Performance/utils.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/workqueue/reducer.ts
  packages/gateway/src/features/user/root-resolvers.ts
Labels: ✅ Ready for merging

#5522 Fix download issues
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 🇨🇲 Cameroon

#5527 Few email message fix
  packages/login/src/i18n/messages/views/resetCredentialsForm.ts
  packages/login/src/i18n/messages/views/stepTwoForm.ts
  packages/login/src/views/StepTwo/StepTwoContainer.tsx
  packages/login/src/views/resetCredentialsForm/recoveryCodeEntryForm.tsx
  packages/user-mgnt/src/features/verifyPassword/handler.ts
Labels: ⏳ Waiting for CI

#5528 Hide add event button for registrar
  packages/client/src/components/Header/Header.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
Labels: 🇨🇲 Cameroon

#5529 Custom question disabled
  packages/client/graphql.schema.json
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🇨🇲 Cameroon

#5533 Cameroon some fix translate
  packages/client/src/forms/register/customFieldMappings/query/customField-mappings.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/RecordAudit/History.tsx
Labels: 🇨🇲 Cameroon

#5535 Added new handler for exact DOB unknown template
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/configuration/default/marriage.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 💅 Waiting For Review

#5536 Add arial fonts in pdfmake vfs
  packages/client/src/pdfRenderer/common_vfs.ts
  packages/client/src/templates/register.ts
Labels: 🇨🇲 Cameroon

#5557 User creation user-name fix
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/gateway/src/index.test.ts
  packages/search/src/index.test.ts
  packages/user-mgnt/src/index.test.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5560 Add support for conditional expression to get agentDefault initial value
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/utils.ts
Labels: 🇨🇲 Cameroon

#5568 Show Organisation view for national system admin
  packages/client/src/components/interface/Navigation.tsx
Labels: 💅 Waiting For Review

#5577 Fixed Birth and death intro
  packages/client/src/i18n/messages/views/eventInfo.ts
Labels: 💅 Waiting For Review

#5497 add marriage configuration on/off for vital event
  packages/client/graphql.schema.json
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/client/typings/window.d.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/src/migrations/application-config/20230208081755-add-marriage-configuration.ts
Labels: ✅ Ready for merging

#5578 GN-025 : Account creation
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
Labels: 🇨🇲 Cameroon

#5457 Add migration for populating the missing eventCountry and eventlocationId / eventJurisidictionIds. Implement ticket #5266
  packages/migration/src/migrations/hearth/20230602120944-populate-valid-locationid.ts
  packages/migration/src/utils/elasticsearch-helper.ts
Labels: ✅ Ready for merging

#5550 url update for login authComplete action
  packages/login/src/login/reducer.ts
Labels: ✅ Ready for merging

#5596 Add support for country custom question template
  packages/client/src/forms/register/customFieldMappings/query/customField-mappings.ts
Labels: 🇨🇲 Cameroon

#5597 Cameroon update to informant type value
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
Labels: 🇨🇲 Cameroon

#5621 Cameroon update record audit birth and death
  packages/client/src/views/RecordAudit/utils.ts
Labels: 🇨🇲 Cameroon

#5547 Add validation for eventNotification payload, and fix the tech debt of unusual indexing in address/location transformers
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/administrative/utils.ts
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/child-mappings.test.ts
  packages/client/src/forms/register/fieldMappings/birth/mutation/child-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/mutation/event-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/mutation/event-mappings.ts
  packages/client/src/tests/default.json
  packages/client/src/views/Settings/AvatarChangeModal.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
  packages/gateway/package.json
  packages/gateway/src/constants.ts
  packages/gateway/src/features/eventNotification/eventNotificationHandler.ts
  packages/gateway/src/features/restLocation/locationHandler.ts
  yarn.lock
Labels: ⏳ Waiting for CI, ✅ Ready for merging
