Repository opencrvs/opencrvs-core, pull requests merged in 2023-02, with the labels that each got.

#4634 Ocrvs 4471 Duplicate button modal with trackingIds in a drop-down and reason for duplication
  packages/client/src/i18n/messages/views/duplicates.ts
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.test.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.tsx
Labels: 🔧Waiting for fixes

#4618 Add organisation view to list locations & offices
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/Organisation/AdministrativeLevels.tsx
  packages/components/src/Breadcrumb/Breadcrumb.stories.tsx
  packages/components/src/Breadcrumb/Breadcrumb.tsx
  packages/components/src/Breadcrumb/index.ts
  packages/components/src/Link/Link.tsx
  packages/components/src/ListViewSimplified/ListViewSimplified.tsx
  packages/components/src/index.ts
  packages/components/stories/releases.stories.mdx
Labels: 🏎 auto-merging

#4541 As a registrar, I want to check for potential duplicates before registering a birth
  .vscode/settings.json
  packages/client/graphql.schema.json
  packages/client/src/components/Notification.tsx
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/notification/actions.ts
  packages/client/src/notification/reducer.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
  packages/components/src/Link/Link.tsx
  packages/components/stories/releases.stories.mdx
  packages/gateway/src/features/correction/root-resolvers.test.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/package.json
  packages/search/src/config/routes.ts
  packages/search/src/elasticsearch/dbhelper.test.ts
  packages/search/src/elasticsearch/dbhelper.ts
  packages/search/src/elasticsearch/utils.test.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/assignment/service.ts
  packages/search/src/features/registration/birth/composition.test.ts
  packages/search/src/features/registration/birth/handler.test.ts
  packages/search/src/features/registration/birth/noParents.test.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/deduplicate/deduplicate.test.ts
  packages/search/src/features/registration/deduplicate/handler.ts
  packages/search/src/features/registration/deduplicate/service.ts
  packages/search/src/features/registration/deduplicate/test-util.ts
  packages/search/src/features/search/handler.test.ts
  packages/search/src/features/search/handler.ts
  packages/search/src/features/search/service.test.ts
  packages/workflow/src/features/events/handler.ts
  yarn.lock
Labels: 💅 Waiting For Review

#4595 mark the record as not a duplicate
  packages/client/graphql.schema.json
  packages/client/src/declarations/index.ts
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/i18n/messages/views/duplicates.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/tests/languages.json
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/DataProvider/mutation.ts
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.test.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.tsx
  packages/gateway/src/features/fhir/constants.ts
  packages/gateway/src/features/fhir/utils.test.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/deduplicate/handler.ts
  packages/search/src/features/registration/deduplicate/service.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/task/fhir/constants.ts
Labels: 💅 Waiting For Review

#4674 ocrvs-4662
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/i18n/reducer.ts
  packages/client/src/tests/util.tsx
  packages/client/src/user/selectors.ts
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/client/src/views/UserAudit/UserAudit.tsx
Labels: 🏥 Failing Tests

#4635 Ocrvs - 4371
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/store.ts
  packages/client/src/utils/apolloClient.ts
  packages/client/src/utils/persistence/index.ts
  packages/client/src/utils/persistence/persistLink.ts
  packages/client/src/utils/persistence/persistenceMapper.ts
  packages/client/src/utils/persistence/persistenceMiddleware.ts
  packages/client/src/utils/persistence/transform.ts
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/metricsQuery.ts
  yarn.lock
Labels: 🙏 forgive coverage

#4563 ocrvs-4371 Optimize the getLocationStatistics query
  packages/metrics/src/api.ts
  packages/metrics/src/features/locationStatistics/service.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/countUsersByLocation/handler.ts
  packages/user-mgnt/src/features/countUsersByLocation/service.ts
Labels: 💅 Waiting For Review

#4698 Fixed ageOfIndividualInYears field validation and customisable false
  packages/client/src/forms/configuration/default.ts
  packages/client/src/utils/date-formatting.ts
  packages/client/src/utils/validate.ts
Labels: 💅 Waiting For Review

#4682 Run migration scripts so that file path references always start from the migration directory
  packages/migration/revertMigrations.sh
  packages/migration/runMigrations.sh
Labels: 💅 Waiting For Review

#4695 Added marriageEventHandler in search packages
  packages/search/src/config/routes.ts
  packages/search/src/constants.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/marriage/handler.test.ts
  packages/search/src/features/registration/marriage/handler.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/search/src/test/utils.ts
Labels: 💅 Waiting For Review

#4656 ocrvs-4355 Certificate Issue Backend+FrontEnd
  packages/client/src/SubmissionController.ts
  packages/client/src/declarations/index.ts
  packages/client/src/declarations/submissionMiddleware.test.ts
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/i18n/messages/views/userSetup.ts
  packages/client/src/tests/languages.json
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/components/src/PDFViewer/PDFViewer.tsx
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/audit/service.ts
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
  packages/migration/migrations/openhim/20230131130400-add-certificate-issue-channel.cjs
  packages/user-mgnt/src/features/userSearchRecord/handler.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/test/utils.ts
Labels: 💅 Waiting For Review

#4667 marriage event configuration
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SysAdmin/Config/Application/Application.test.tsx
  packages/client/src/views/SysAdmin/Config/Application/Application.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/MarriageProperties/MarriageDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/MarriageProperties/MarriageDelayedRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/MarriageProperties/MarriageFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/MarriageProperties/MarriageRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/MarriageProperties/index.ts
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/client/src/views/SysAdmin/Config/Application/utils.ts
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/migrations/application-config/20230208081755-add-marriage-configuration.js
Labels: 💅 Waiting For Review

#4718 Implement more advanced yarn dev experience
  dev.sh
Labels: 🧬 Improvement, 📄Documentation

#4702 Feature: print in advance & marriage certificate
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/tests/languages.json
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/templates.json
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/PrintCertificate/utils.ts
  packages/client/src/views/SysAdmin/Config/Application/Application.test.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthDelayedRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthLateFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/BirthProperties/BirthRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathDelayedFee.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathFeeOnTime.tsx
  packages/client/src/views/SysAdmin/Config/Application/Tabs/DeathProperties/DeathRegistrationTarget.tsx
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/client/typings/window.d.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/configApi.ts
Labels: 🚧 work in progress

#4729 ocrvs-4448: Show role label based on intl locale on record audit history
  packages/client/src/views/RecordAudit/History.tsx
Labels: 💅 Waiting For Review

#4717 ocrvs-4641 Marriage event declaration form
  packages/client/src/App.tsx
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/configuration/formConfig/reducer.ts
  packages/client/src/forms/configuration/formDrafts/utils.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/mappings/mutation/index.ts
  packages/client/src/forms/mappings/query/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/forms/register/fieldMappings/marriage/mutation/documents-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/mutation/event-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/mutation/registration-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/query/documents-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/query/registration-mappings.ts
  packages/client/src/forms/register/reducer.ts
  packages/client/src/forms/register/reviewReducer.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/i18n/messages/views/selectInformant.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/pdfRenderer/transformer/utils.ts
  packages/client/src/utils/constants.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/validate.test.ts
  packages/client/src/utils/validate.ts
  packages/client/src/views/DataProvider/QueryProvider.tsx
  packages/client/src/views/DataProvider/marriage/mutations.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/EventInfo/EventInfo.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/PrintCertificate/utils.ts
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RegisterForm/DeclarationForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
Labels: 💅 Waiting For Review, 🚧 work in progress

#4713 Ocrvs 4357 - Issuing a certificate
  packages/client/src/App.tsx
  packages/client/src/ListSyncController.ts
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/declarations/index.test.ts
  packages/client/src/declarations/index.ts
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/issueCertificate.ts
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/i18n/messages/workQueue.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/styledComponents.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/IssueCertificate/IssueCertificate.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueFormForOthers.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssuePayment.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/client/src/views/OfficeHome/utils.ts
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/workqueue/reducer.ts
  packages/components/src/Workqueue/Workqueue.tsx
Labels: 🔧Waiting for fixes

#4759 Add verificationButton component and use it in formfield
  packages/components/src/VerificationButton/VerificationButton.stories.tsx
  packages/components/src/VerificationButton/VerificationButton.tsx
  packages/components/src/VerificationButton/index.ts
  packages/components/stories/releases.stories.mdx
Labels: 💅 Waiting For Review

#4753 feat(national-id-verification): Pass OIDP claims to frontend
  docker-compose.deploy.yml
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/systems/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/constants.ts
  packages/user-mgnt/src/utils/system.ts
Labels: 💅 Waiting For Review

#4685 prepare workflow microservice for marriage event
  packages/migration/migrations/openhim/20230210112528-marriage-channels.cjs
  packages/migration/utils/openhim-helpers.cjs
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/events/auth.test.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/events/utils.ts
  packages/workflow/src/features/legacy/handler.test.ts
  packages/workflow/src/features/legacy/handler.ts
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-template.test.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.test.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/fhir/utils.ts
  packages/workflow/src/features/task/handler.ts
  packages/workflow/src/test/utils.ts
Labels: 💅 Waiting For Review

#4751 Reg Agent reviewing potential duplicate
  packages/client/src/declarations/index.ts
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RegisterForm/ReviewForm.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/ViewRecord/query.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/deduplicate/service.ts
Labels: 💅 Waiting For Review
