Repository opencrvs/opencrvs-core, pull requests merged in 2023-01, with the labels that each got.

#4514 ocrvs-4217: Fix workflowstatus table's column widths for mobile device
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: 🔧Waiting for fixes

#4513 ocrvs-3942 User audit history fixes
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
  packages/metrics/src/features/audit/service.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
  packages/workflow/src/features/events/handler.ts
Labels: 💅 Waiting For Review

#4511 Certificate changes nga
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/mappings/query/index.ts
  packages/client/src/forms/register/fieldMappings/death/query/deceased-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/query/event-mappings.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/PrintCertificate/utils.ts
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
Labels: ✅ Ready for merging

#4522 Import fetch for resetPassword handler
  packages/user-mgnt/src/features/resetPassword/handler.ts
Labels: 💅 Waiting For Review

#4468 ocrvs-4287 Informant SMS notifications
  packages/client/graphql.schema.json
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/tests/mock-graphql-responses.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigSettings.tsx
  packages/client/src/views/SysAdmin/InformantSMSNotification/InformantSMSNotification.test.tsx
  packages/client/src/views/SysAdmin/InformantSMSNotification/InformantSMSNotification.tsx
  packages/client/src/views/SysAdmin/InformantSMSNotification/mutations.ts
  packages/client/src/views/SysAdmin/InformantSMSNotification/queries.ts
  packages/config/src/config/routes.ts
  packages/config/src/handlers/informantSMSNotifications/createInformantSMSNotification/handler.test.ts
  packages/config/src/handlers/informantSMSNotifications/createInformantSMSNotification/handler.ts
  packages/config/src/handlers/informantSMSNotifications/getInformantSMSNotification/handler.test.ts
  packages/config/src/handlers/informantSMSNotifications/getInformantSMSNotification/handler.ts
  packages/config/src/handlers/informantSMSNotifications/updateInformantSMSNotification/handler.test.ts
  packages/config/src/handlers/informantSMSNotifications/updateInformantSMSNotification/handler.ts
  packages/config/src/models/informantSMSNotifications.ts
  packages/gateway/src/features/informantSMSNotifications/root-resolvers.test.ts
  packages/gateway/src/features/informantSMSNotifications/root-resolvers.ts
  packages/gateway/src/features/informantSMSNotifications/schema.graphql
  packages/gateway/src/features/informantSMSNotifications/type-resolvers.ts
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/migrations/application-config/20221221093004-store-informant-sms-notification.js
  packages/migration/utils/resource-helper.js
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/handler.ts
  packages/workflow/src/test/utils.ts
Labels: 💅 Waiting For Review

#4346 Informant signature with exact date of birth unknown
  packages/client/graphql.schema.json
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/configuration/default.ts
  packages/client/src/forms/mappings/mutation/field-mappings.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/tests/default.json
  packages/client/src/tests/mock-drafts.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/client/src/views/SysAdmin/Config/Application/utils.ts
  packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigSettings.tsx
  packages/client/src/views/ViewRecord/query.ts
  packages/client/typings/window.d.ts
  packages/components/src/DateField/DateField.tsx
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/models/config.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  yarn.lock
Labels: 💅 Waiting For Review

#4580 Duplicates view on review page
  packages/client/graphql.schema.json
  packages/client/src/declarations/index.ts
  packages/client/src/i18n/messages/views/duplicates.ts
  packages/client/src/transformer/index.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/queries.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/ViewRecord/query.ts
  packages/components/src/DocumentViewer/DocumentViewer.tsx
  packages/components/src/FormTabs/FormTabs.tsx
  packages/components/src/FormTabs/components/Tabs.tsx
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  yarn.lock
Labels: 💅 Waiting For Review

#4531 Checkbox visual improvements
  packages/components/src/Checkbox/Checkbox.stories.tsx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/CheckboxGroup.tsx
  packages/components/src/icons/Tick.tsx
  packages/components/stories/releases.stories.mdx
Labels: 👌LGTM

#4575 Adding mapping function for template
  packages/client/src/forms/configuration/README.md
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/forms/mappings/query/field-mappings.ts
Labels: 💅 Waiting For Review

#4585 Added values in getSystemRoles query
  packages/client/graphql.schema.json
  packages/client/src/forms/user/query/queries.ts
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/role/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#4604 Added new ComparisonList view component
  packages/components/src/ComparisonListView/ComparisonListView.stories.tsx
  packages/components/src/ComparisonListView/ComparisonListView.tsx
  packages/components/src/ComparisonListView/RowView.tsx
Labels: 💅 Waiting For Review

#4587 chore: upgrade React from 16 to 18
  package.json
  packages/client/package.json
  packages/client/src/components/ErrorBoundary.tsx
  packages/client/src/components/Notification.tsx
  packages/client/src/components/Page.tsx
  packages/client/src/components/ProtectedPage.tsx
  packages/client/src/components/ScrollToTop.tsx
  packages/client/src/components/TransitionWrapper.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx
  packages/client/src/index.tsx
  packages/client/src/tests/util.tsx
  packages/client/src/tests/wait-for-element.ts
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/DataProvider/QueryProvider.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/utils.ts
  packages/client/src/views/RegisterForm/StickyFormTabs.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Config/Systems/DeleteSystemModal.tsx
  packages/client/src/views/SysAdmin/Team/TeamSearch.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/components/package.json
  packages/components/recreate-src-index-ts.sh
  packages/components/src/ActionPageLight/ActionPageLight.tsx
  packages/components/src/DocumentViewer/DocumentViewer.tsx
  packages/components/src/DocumentViewer/components/PanDraggable.tsx
  packages/components/src/ExpandableNotification/ExpandableNotification.stories.tsx
  packages/components/src/ExpandableNotification/ExpandableNotification.tsx
  packages/components/src/ExpandableNotification/index.ts
  packages/components/src/InputField/InputDescriptor.tsx
  packages/components/src/InputField/InputError.tsx
  packages/components/src/InputField/InputField.tsx
  packages/components/src/ListTable/ListTable.tsx
  packages/components/src/Modal/Modal.stories.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/PageWrapper/PageWrapper.tsx
  packages/components/src/ResponsiveModal/ResponsiveModal.tsx
  packages/components/src/SideNavigation/LeftNavigation.tsx
  packages/components/src/Table/Table.tsx
  packages/components/src/Workqueue/Workqueue.tsx
  packages/components/src/Workqueue/components/ListItemAction.tsx
  packages/components/src/Workqueue/components/WorkqueueRowDesktop.tsx
  packages/components/src/index.ts
  packages/login/package.json
  packages/login/src/ErrorBoundary.tsx
  packages/login/src/index.tsx
  packages/login/src/tests/util.tsx
  yarn.lock
Labels: 💅 Waiting For Review

#4631 chore(components): remove Component status page from Storybook
  packages/components/stories/component-status.stories.mdx
Labels: 💅 Waiting For Review

#4630 ocrvs-4469 Potential duplicates comparison view
  packages/client/src/declarations/index.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/duplicates.ts
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.test.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
  packages/client/src/views/RegisterForm/duplicate/SupportingDocumentsView.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/ViewRecord/query.ts
  packages/components/src/ComparisonListView/ComparisonListView.stories.tsx
  packages/components/src/ComparisonListView/ComparisonListView.tsx
  packages/components/src/ComparisonListView/RowView.tsx
  packages/components/src/ComparisonListView/index.ts
  packages/components/src/Content/Content.tsx
  packages/components/src/DocumentViewer/DocumentViewer.tsx
  packages/components/src/index.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 💅 Waiting For Review

#4648 ocrvs: 4446-Backend
  packages/gateway/src/features/role/root-resolvers.test.ts
  packages/gateway/src/features/role/root-resolvers.ts
  packages/gateway/src/features/role/schema.graphql
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/updateRole/handler.test.ts
  packages/user-mgnt/src/features/updateRole/handler.ts
Labels: 🔧Waiting for fixes

#4526 OCRVS-4286: Update on Rejection modal
  packages/client/graphql.schema.json
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/review/RejectRegistrationForm.test.tsx
  packages/client/src/components/review/RejectRegistrationForm.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/recordAudit.ts
  packages/client/src/i18n/messages/views/reject.ts
  packages/client/src/review/reducer.ts
  packages/client/src/review/reject-registration.ts
  packages/client/src/review/selectors.ts
  packages/client/src/store.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/SysAdmin/Performance/utils.tsx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/Button/Button.tsx
  packages/components/src/ResponsiveModal/ResponsiveModal.tsx
  packages/gateway/src/features/fhir/constants.ts
  packages/gateway/src/features/fhir/templates.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/task/fhir/constants.ts
Labels: 💅 Waiting For Review

#4649 ocrvs-4616 Fix practitionerRole, recordAudit, userAudit and team
  packages/client/src/declarations/index.ts
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/profile/queries.ts
  packages/client/src/setupTests.ts
  packages/client/src/tests/util.tsx
  packages/client/src/user/queries.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/userUtils.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
  packages/client/src/views/SysAdmin/Config/UserRoles/utils.ts
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/client/src/views/Unlock/ForgotPIN.test.tsx
  packages/client/src/views/UserAudit/UserAudit.test.tsx
  packages/client/src/views/UserAudit/UserAudit.tsx
  packages/client/src/views/UserSetup/SetupReviewPage.test.tsx
  packages/client/src/views/UserSetup/SetupReviewPage.tsx
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/user/type-resolvers.test.ts
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/utils/testUtils.ts
  packages/login/src/utils/authApi.ts
  packages/migration/migrations/hearth/20230127063226-update-practitioner-role.js
  packages/migration/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.js
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/assignment/handler.test.ts
  packages/search/src/features/registration/birth/composition.test.ts
  packages/search/src/features/registration/birth/noParents.test.ts
  packages/search/src/features/registration/death/handler.test.ts
  packages/search/src/test/utils.ts
  packages/user-mgnt/src/features/activateUser/handler.test.ts
  packages/user-mgnt/src/features/createUser/handler.test.ts
  packages/user-mgnt/src/features/createUser/handler.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/getRoles/handler.test.ts
  packages/user-mgnt/src/features/getUser/handler.test.ts
  packages/user-mgnt/src/features/resendSMSInvite/handler.test.ts
  packages/user-mgnt/src/features/resetPassword/handler.test.ts
  packages/user-mgnt/src/features/searchUsers/handler.test.ts
  packages/user-mgnt/src/features/searchUsers/handler.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.test.ts
Labels: 💅 Waiting For Review
