Repository opencrvs/opencrvs-core, pull requests merged in 2023-12, with the labels that each got.

#6156 validate-and-update-endpoint-workflow
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/transformer/index.ts
  packages/commons/src/fhir/index.ts
  packages/commons/src/fhir/task.ts
  packages/commons/src/fhir/transformers/index.ts
  packages/commons/src/fhir/transformers/input.ts
  packages/commons/src/record.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/user/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/workflow/index.ts
  packages/migration/src/migrations/openhim/20231115134531-remove-validation-and-update-channels.ts
  packages/migration/src/utils/openhim-helpers.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/correction/routes.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/records/correction-request.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/update.test.ts
  packages/workflow/src/records/handler/update.ts
  packages/workflow/src/records/handler/validate.test.ts
  packages/workflow/src/records/handler/validate.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/states.ts
  packages/workflow/test/mocks/updateBirthRecord.ts
Labels: 🔧Waiting for fixes

#6342 Ocrvs 6210 Remove state level performance data fetch calls
  packages/client/src/utils/persistence/persistenceMiddleware.ts
Labels: 👌 LGTM

#6352 Fix error when you click in back button
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/components/src/Workqueue/Workqueue.tsx
  packages/workflow/src/features/registration/handler.test.ts
Labels: 🇨🇲 Cameroon

#6233 fix detect event for issuing an event
  packages/workflow/src/features/registration/utils.ts
Labels: 👌 LGTM

#6353 [OCRVS 6250] Feature flags
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/setupTests.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/client/typings/window.d.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review, ✅ Ready for merging

#6177 disable review button for validation errors on fields
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/forms/validation.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/tests/util.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 👌 LGTM

#6374 Created Discussion template
  .github/DISCUSSION_TEMPLATE/Installation.yml
  .github/ISSUE_TEMPLATE/---bug.md
  .github/ISSUE_TEMPLATE/---feature.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/user-story.md
  license-config.json
Labels: 💅 Waiting For Review

#6369 Remove unecessary retry when unassigned
  packages/client/src/utils/apolloClient.ts
Labels: 👌 LGTM

#6360 Ocrvs 5791 download
  packages/commons/package.json
  packages/commons/src/authentication.ts
  packages/gateway/src/features/registration/__snapshots__/type-resolvers.test.ts.snap
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/download.test.ts
  packages/workflow/src/records/handler/download.ts
  packages/workflow/src/records/search.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/records/user.ts
  packages/workflow/src/utils/authUtils.ts
Labels: 👌 LGTM
