Repository opencrvs/opencrvs-core, pull requests merged in 2023-10, with the labels that each got.

#5993 unable marriage form declaration when logged as field agent
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5862 content title ui fix for mobile
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueFormForOthers.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssuePayment.tsx
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/UserSetup/CreatePassword.tsx
  packages/client/src/views/UserSetup/SecurityQuestionView.tsx
  packages/components/src/Content/Content.tsx
  packages/login/src/views/resetCredentialsForm/forgottenItemForm.tsx
  packages/login/src/views/resetCredentialsForm/phoneNumberVerificationForm.tsx
  packages/login/src/views/resetCredentialsForm/securityQuestionForm.tsx
Labels: ✅ Ready for merging

#6028 Add place of death in record audit
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#6053 create validation function dateNotPastFieldDate
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/utils/validate.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#6041 Ocrvs 6031 Show correct button for certified declarations
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: 💅 Waiting For Review

#5872 Ocrvs 5795 - search by email
  packages/client/src/components/Header/Header.tsx
  packages/client/src/i18n/messages/views/header.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/search/queries.ts
  packages/client/src/search/transformer.ts
  packages/client/src/utils/constants.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/Icon/all-icons.ts
  packages/gateway/src/features/bookmarkAdvancedSearch/schema.graphql
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/src/migrations/hearth/20221110092434-add_identifiers_DOB_gender_location.ts
  packages/migration/src/migrations/hearth/20230905130632-elastic-search-property-rename.ts
  packages/migration/src/utils/elasticsearch-helper.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.ts
Labels: 💅 Waiting For Review, 💥 Hot Fixes

#6061 Remove FIELD_AGENT as informantType options when user is REGISTRATION
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/utils.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#6072 Opencrvs confirm button remains inactive
  packages/client/src/forms/utils.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#6064 Make field details, form values and declaration values available for option conditional
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/utils.ts
Labels: 🇨🇲 Cameroon

#6077 refactor id verifier for print and issue
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/correction/verifyCorrector.ts
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
Labels: 👌 LGTM, 💥 Hot Fixes

#6076 ocrvs-6063 query validation for location endpoint
  packages/data-seeder/src/locations.ts
  packages/gateway/src/config/routes.ts
  packages/gateway/src/features/eventNotification/eventNotificationHandler.ts
  packages/gateway/src/features/restLocation/locationHandler.ts
  packages/migration/src/migrations/hearth/20230905130632-elastic-search-property-rename.ts
Labels: 💥 Hot Fixes

#6054 Ocrvs 5793 Cameroon improvements
  packages/auth/src/config/plugins.ts
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/client/src/utils/validate.ts
  packages/client/vite.config.js
  packages/config/src/config/plugins.ts
  packages/documents/src/config/plugins.ts
  packages/gateway/src/config/plugins.ts
  packages/gateway/src/config/routes.ts
  packages/gateway/src/features/healthCheck/handler.ts
  packages/gateway/src/index.test.ts
  packages/login/src/utils/authUtils.ts
  packages/login/vite.config.js
  packages/metrics/src/config/plugins.ts
  packages/notification/src/config/plugins.ts
  packages/search/src/config/plugins.ts
  packages/search/src/config/routes.ts
  packages/search/src/index.test.ts
  packages/user-mgnt/src/config/plugins.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/index.test.ts
  packages/webhooks/src/config/plugins.ts
  packages/workflow/src/config/plugins.ts
Labels: 💥 Hot Fixes, ✅ Ready for merging

#6024 Ocrvs 5794 - configurable signature for different users
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/typings/window.d.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/server.ts
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 💥 Hot Fixes

#6003 signature row fix for create user
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💥 Hot Fixes, ✅ Ready for merging

#5999 Fix deps vulnerabilities
  packages/auth/package.json
  packages/auth/src/logger.ts
  packages/client/package.json
  packages/client/src/views/RecordAudit/utils.ts
  packages/config/package.json
  packages/config/src/config/logger.ts
  packages/config/src/logger.ts
  packages/documents/package.json
  packages/documents/src/logger.ts
  packages/documents/src/minio/sign.ts
  packages/documents/typings/minio.d.ts
  packages/gateway/package.json
  packages/gateway/src/features/OIDPUserInfo/root-resolvers.test.ts
  packages/gateway/src/features/application/root-resolvers.test.ts
  packages/gateway/src/features/bookmarkAdvancedSearch/root-resolvers.test.ts
  packages/gateway/src/features/certificate/root-resolvers.test.ts
  packages/gateway/src/features/correction/root-resolvers.test.ts
  packages/gateway/src/features/fhir/utils.test.ts
  packages/gateway/src/features/informantSMSNotifications/root-resolvers.test.ts
  packages/gateway/src/features/location/root-resolvers.test.ts
  packages/gateway/src/features/metrics/root-resolvers.test.ts
  packages/gateway/src/features/notification/root-resolvers.test.ts
  packages/gateway/src/features/registration/death-type-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/role/root-resolvers.test.ts
  packages/gateway/src/features/role/type-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/features/systems/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/type-resolvers.test.ts
  packages/gateway/src/logger.ts
  packages/metrics/package.json
  packages/metrics/src/logger.ts
  packages/migration/package.json
  packages/notification/package.json
  packages/notification/src/logger.ts
  packages/search/package.json
  packages/search/src/features/registration/deduplicate/service.ts
  packages/search/src/logger.ts
  packages/user-mgnt/package.json
  packages/user-mgnt/src/logger.ts
  packages/webhooks/package.json
  packages/webhooks/src/logger.ts
  packages/workflow/package.json
  packages/workflow/src/logger.ts
  patches/mockingoose+2.15.2.patch
  patches/pdfmake+0.2.7.patch
  yarn.lock
Labels: 💥 Hot Fixes, ✅ Ready for merging

#6016 Requirements for Niue
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/utils.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/config/src/handlers/forms/validation.ts
  packages/login/src/common/LoginBackgroundWrapper.tsx
  packages/login/src/login/selectors.ts
Labels: 💥 Hot Fixes

#6058 Ocrvs 5994 - list for certificator collector and correction requester
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/certificate/printReducer.ts
  packages/client/src/forms/correction/corrector.ts
  packages/client/src/forms/correction/verifyCorrector.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/issueCertificate.ts
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/store.ts
  packages/client/src/views/CorrectionForm/CorrectorForm.test.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.tsx
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/components/src/Radio/RadioGroup.tsx
Labels: 👌 LGTM, 💥 Hot Fixes

#5700 Print record view
  packages/client/src/App.tsx
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/printRecord.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/PrintRecord/Body.tsx
  packages/client/src/views/PrintRecord/Header.tsx
  packages/client/src/views/PrintRecord/PrintRecord.tsx
  packages/client/src/views/PrintRecord/Table.tsx
  packages/client/src/views/PrintRecord/utils.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/colors.ts
Labels: 💅 Waiting For Review

#6068 ocrvs-5800: version the rest apis in gateway
  packages/gateway/src/config/plugins.ts
  packages/gateway/src/config/routes.ts
  packages/gateway/src/features/eventNotification/eventNotificationHandler.ts
  packages/gateway/src/features/restLocation/locationHandler.ts
  packages/gateway/src/server.ts
Labels: 👌 LGTM

#6107 Add missing license headers and CI check
  .github/workflows/lint-and-test.yml
  license-config.json
  packages/client/src/hooks/useRecord.ts
  packages/client/src/i18n/messages/views/printRecord.ts
  packages/client/src/review/reject-correction.ts
  packages/client/src/views/PrintRecord/Body.tsx
  packages/client/src/views/PrintRecord/Header.tsx
  packages/client/src/views/PrintRecord/PrintRecord.tsx
  packages/client/src/views/PrintRecord/Table.tsx
  packages/client/src/views/PrintRecord/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSectionCorrection.tsx
  packages/client/src/views/ReviewCorrection/ReviewCorrection.tsx
  packages/commons/src/auth.ts
  packages/commons/src/fhir/composition.ts
  packages/commons/src/fhir/constants.ts
  packages/commons/src/fhir/encounter.ts
  packages/commons/src/fhir/extension.ts
  packages/commons/src/fhir/index.ts
  packages/commons/src/fhir/observation.ts
  packages/commons/src/fhir/patient.ts
  packages/commons/src/fhir/payments.ts
  packages/commons/src/fhir/practitioner.ts
  packages/commons/src/fhir/task.ts
  packages/commons/src/nominal.ts
  packages/commons/src/record.test.ts
  packages/commons/src/record.ts
  packages/commons/src/test-resources.ts
  packages/commons/src/types.ts
  packages/commons/src/uuid.ts
  packages/gateway/src/features/fhir/documentsAPI.ts
  packages/gateway/src/features/fhir/paymentsAPI.ts
  packages/gateway/src/features/fhir/service.ts
  packages/gateway/src/features/metrics/service.ts
  packages/gateway/src/features/registration/fixtures/birth-bundle.ts
  packages/gateway/src/features/registration/fixtures/death-bundle.ts
  packages/gateway/src/features/registration/fixtures/marriage-bundle.ts
  packages/gateway/src/features/user/usersAPI.ts
  packages/gateway/src/fetch.ts
  packages/gateway/src/graphql/query-generator.ts
  packages/gateway/src/search/index.ts
  packages/gateway/src/workflow/index.ts
  packages/migration/src/migrations/hearth/20230822143240-rename-request-correction-to-make-correction.ts
  packages/migration/src/migrations/openhim/20230822142113-rename-request-correction-to-make-correction.ts
  packages/notification/src/features/sms/correction.ts
  packages/search/src/features/records/handler.ts
  packages/search/src/features/records/service.ts
  packages/search/src/features/registration/record/handler.ts
  packages/workflow/src/documents.ts
  packages/workflow/src/features/correction/routes.ts
  packages/workflow/src/records/audit.ts
  packages/workflow/src/records/correction-request.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/index.ts
  packages/workflow/src/records/search.ts
  packages/workflow/src/records/state-transitions.test.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/states.ts
Labels: 👌 LGTM

#6104 Add registration location to email as a variable
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/documents/src/features/uploadSvg/handler.ts
  packages/notification/src/features/sms/birth-handler.test.ts
  packages/notification/src/features/sms/birth-handler.ts
  packages/notification/src/features/sms/death-handler.test.ts
  packages/notification/src/features/sms/death-handler.ts
  packages/notification/src/index.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-template.test.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/task/handler.test.ts
  packages/workflow/src/test/utils.ts
Labels: 👌 LGTM, 💥 Hot Fixes

#6116 Add core support for configurable death event
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/client/typings/window.d.ts
Labels: 👌 LGTM

#6115 Add support for passing intl and other context variables to custom handlebar helpers
  packages/client/src/forms/handlebarHelpers.ts
  packages/client/src/setupTests.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 💅 Waiting For Review

#6120 message fix for send for approval modal
  packages/client/src/i18n/messages/views/review.ts
Labels: 💅 Waiting For Review

#6105 feat: add partOf extension to addresses
  packages/client/src/forms/register/mappings/mutation/field-mappings.ts
  packages/commons/.eslintrc.js
  packages/commons/src/fhir/extension.ts
  packages/commons/src/fhir/index.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/fixtures/death-bundle.ts
  packages/gateway/src/features/registration/fixtures/marriage-bundle.ts
  packages/gateway/src/features/transformation/index.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/package.json
  packages/migration/revert-migrations.sh
  packages/migration/run-migrations.sh
  packages/migration/src/migrations/hearth/20231024153838-partof-to-address.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/records/service.ts
  packages/webhooks/src/features/manage/handler.test.ts
  packages/webhooks/src/features/manage/handler.ts
Labels: 💅 Waiting For Review, 📄 Documentation

#6123 Configurable domains & whitelist
  infrastructure/nginx-default.conf
  infrastructure/nginx-deploy-config.sh
  packages/auth/src/constants.ts
  packages/auth/src/server.ts
  packages/client/Dockerfile
  packages/config/src/config/constants.ts
  packages/config/src/handlers/forms/validation.ts
  packages/config/src/server.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/server.ts
  packages/login/Dockerfile
  packages/user-mgnt/src/features/updateRole/handler.ts
  packages/user-mgnt/src/model/systemRole.ts
Labels: 💥 Hot Fixes, 📄 Documentation

#6106 Id verifier and collector form fix
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/correction/corrector.ts
  packages/client/src/i18n/messages/views/certificate.ts
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: 💅 Waiting For Review
