Repository opencrvs/opencrvs-core, pull requests merged in 2023-05, with the labels that each got.

#5194 Added an option for custom options
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/config/src/handlers/question/getQuestions/handler.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5178 Disallow registration without secretary signature
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/i18n/messages/views/review.ts
Labels: 🇨🇲 Cameroon

#5183 [si-hackathon] Return more details in the birth search response
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review

#5207 Certificate: office location in the top header must be dynamically populated
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts
  packages/client/src/views/SysAdmin/Team/utils.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5210 [OCRVS-5033] Add a split helper for Handlebars
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 🇨🇲 Cameroon

#5224 Fix webook Joi validation and delete webhooks when an integration is deleted
  docker-compose.yml
  packages/gateway/src/constants.ts
  packages/gateway/src/features/systems/root-resolvers.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/webhooks/src/config/routes.ts
  packages/webhooks/src/features/manage/handler.ts
Labels: ⏳ Waiting for CI

#5246 fix: history label in record audit
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
Labels: 💅 Waiting For Review

#5061 Refactor: Appbar and components
  packages/client/src/components/Header/Header.tsx
  packages/client/src/components/ProfileMenu.tsx
  packages/components/src/AppBar/AppBar.stories.tsx
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/Button/Button.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/SearchTool/SearchTool.stories.tsx
  packages/components/src/SearchTool/SearchTool.tsx
  packages/components/src/ToggleMenu/ToggleMenu.tsx
Labels: ✅ Ready for merging

#5209 ocrvs-5155
  packages/migration/migrations/openhim/20230210112528-marriage-channels.cjs
Labels: ✅ Ready for merging

#5245 ocrvs-5181
  packages/client/src/views/Settings/ChangePhoneModal/ChangeNumberView.tsx
  packages/client/src/views/Settings/ChangePhoneModal/ChangePhoneModal.test.tsx
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/utils/index.ts
  packages/user-mgnt/src/features/getUser/handler.ts
Labels: ✅ Ready for merging

#5024 ocrvs-4979
  packages/auth/package.json
  packages/auth/src/features/verifyCode/service.ts
  packages/gateway/package.json
  packages/gateway/src/routes/verifyCode/handler.ts
  packages/user-mgnt/package.json
  packages/user-mgnt/src/features/changePassword/handler.test.ts
  packages/user-mgnt/src/features/changePassword/handler.ts
  packages/user-mgnt/src/features/system/handler.ts
  packages/user-mgnt/src/features/verifyPassword/handler.test.ts
  packages/user-mgnt/src/features/verifyPassword/handler.ts
  packages/user-mgnt/src/features/verifyPasswordById/handler.test.ts
  packages/user-mgnt/src/features/verifyPasswordById/handler.ts
  packages/user-mgnt/src/features/verifySecurityAnswer/handler.test.ts
  packages/user-mgnt/src/utils/hash.ts
  packages/webhooks/package.json
  yarn.lock
Labels: ✅ Ready for merging

#5250 [OCRVS-5227] Add support for new questions config fields: mapping, conditionals, extraValue
  packages/client/graphql.schema.json
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/schema.graphql
Labels: 🇨🇲 Cameroon

#5243 Ocrvs 4822
  packages/client/graphql.schema.json
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/formConfig/formTools/FormTools.tsx
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/i18n/messages/views/formConfig.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/utils/referenceApi.ts
  packages/gateway/src/features/location/schema.graphql
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5059 refactor: SideNav ui polish
  packages/client/src/components/Header/Header.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/components/src/Frame/Frame.stories.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/SideNavigation/LeftNavigation.stories.tsx
  packages/components/src/SideNavigation/LeftNavigation.tsx
  packages/components/src/SideNavigation/NavigationGroup.stories.tsx
  packages/components/src/SideNavigation/NavigationGroup.tsx
  packages/components/src/SideNavigation/NavigationItem.stories.tsx
  packages/components/src/SideNavigation/NavigationItem.tsx
  packages/components/src/SideNavigation/NavigationSubItem.stories.tsx
  packages/components/src/SideNavigation/NavigationSubItem.tsx
  packages/components/src/ToggleMenu/ToggleMenu.stories.tsx
  packages/components/src/colors.ts
  packages/components/src/icons/Expandable.tsx
Labels: ✋ On Hold, 👌 LGTM

#5267 fix hamburger menu not working
  packages/client/src/components/Header/Hamburger.tsx
  packages/client/src/components/Header/Header.tsx
Labels: 💅 Waiting For Review

#5230 Marriage form update
  packages/client/graphql.schema.json
  packages/client/src/forms/configuration/default/marriage.ts
  packages/client/src/forms/register/fieldMappings/marriage/mutation/documents-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/query/documents-mappings.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5279 fix: date width and Select ui
  packages/components/src/DateField/DateField.tsx
  packages/components/src/Select/Select.tsx
Labels: 💅 Waiting For Review

#5273 ocrvs-4677 Prevent username from getting updated needlessly
  packages/migration/migrations/user-mgnt/20230511082648-drop-usernamerecords-collection.js
  packages/user-mgnt/src/features/createUser/handler.test.ts
  packages/user-mgnt/src/features/createUser/service.test.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/updateUser/handler.test.ts
  packages/user-mgnt/src/model/usernameRecord.ts
Labels: ✅ Ready for merging

#5287 Removed label for witness 1 and witness 2 in marriage declaration
  packages/client/src/forms/configuration/default/marriage.ts
Labels: ✅ Ready for merging

#5307 Fix "circumstances of death" options
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 🇨🇲 Cameroon

#5291 ocrvs-5280 Preserve form state when going back a page
  packages/client/src/forms/register/fieldMappings/death/mutation/event-mappings.ts
  packages/client/src/forms/register/fieldMappings/marriage/mutation/registration-mappings.ts
  packages/client/src/views/CorrectionForm/CorrectionReasonForm.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueFormForOthers.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review, 👌 LGTM

#5306 Fixed supporting doc and signature fetch to work offline
  packages/client/src/declarations/index.ts
  packages/migration/migrations/user-mgnt/20230511082648-drop-usernamerecords-collection.js
Labels: 💅 Waiting For Review

#5321 Birth: Update options in Documents -> Other
  packages/client/graphql.schema.json
  packages/client/src/forms/register/fieldMappings/birth/mutation/documents-mappings.ts
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5308 Ocrvs 5254
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 🇨🇲 Cameroon

#5331 [OCRSV-5286] Make marriage signatures optional
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 🇨🇲 Cameroon

#5189 Ocrvs 5086 - fix address for same residence
  packages/client/src/forms/configuration/administrative/addresses.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging

#5366 Ocrvs 5343 Handle custom question `hideHeader`
  packages/client/graphql.schema.json
  packages/client/src/forms/configuration/customUtils.ts
  packages/client/src/forms/questionConfig/index.ts
  packages/client/src/forms/questionConfig/transformers.ts
  packages/client/src/utils/gateway.ts
  packages/gateway/src/features/questions/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5390 Fix startDate and endDate range in dateRangePicker. Fix #5357
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/components/DateRangePickerForFormField.tsx
Labels: 💅 Waiting For Review

#5386 correction summary warning fix
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
Labels: 🙋Question

#5398 Resolve textual values of custom select values before rendering in certificates
  packages/client/src/forms/register/customFieldMappings/query/customField-mappings.ts
Labels: 👌 LGTM

#5312 ocrvs-5021 make fields required in duplication check
  packages/search/src/features/registration/deduplicate/deduplicate.test.ts
  packages/search/src/features/registration/deduplicate/service.ts
Labels: 👌 LGTM

#5399 Verify all Document Type dropdowns have same options
  packages/client/src/forms/register/fieldMappings/birth/mutation/documents-mappings.ts
  packages/client/src/forms/register/fieldMappings/death/mutation/documents-mappings.ts
Labels: 🇨🇲 Cameroon

#5396 Ocrvs 5374
  packages/client/src/forms/configuration/default/marriage.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5317 Ocrvs warnig fix
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/components/src/InputField/InputField.tsx
  packages/migration/migrations/user-mgnt/20230511082648-drop-usernamerecords-collection.js
Labels: 👌 LGTM, ✅ Ready for merging

#5358 Add quickfix for workqueue count flickering. Fix #5268
  packages/client/src/declarations/submissionMiddleware.test.ts
  packages/client/src/declarations/submissionMiddleware.ts
Labels: ✅ Ready for merging

#5414 Ocrvs 5348 Update field agent home query to make independent of `declarationLocationId`
  packages/client/src/ListSyncController.ts
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/RecordAudit/utils.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5304 updates copy to use Full name
  packages/client/src/forms/configuration/default/birth.ts
  packages/client/src/forms/configuration/default/death.ts
  packages/client/src/forms/configuration/default/marriage.ts
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/user.ts
  packages/client/src/i18n/messages/views/userSetup.ts
  packages/client/src/tests/default.json
  packages/client/src/tests/languages.json
Labels: 👌 LGTM

#5235 invalidate cache after set time
  packages/client/src/components/Page.tsx
  packages/client/src/components/ProtectedPage.tsx
  packages/client/src/components/interface/DownloadButton.test.tsx
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/utils/apolloClient.ts
  packages/client/src/utils/constants.ts
  packages/client/src/utils/persistence/clearCache.test.ts
  packages/client/src/utils/persistence/clearCache.ts
  packages/client/src/utils/persistence/index.ts
  packages/client/src/utils/persistence/persistenceMiddleware.ts
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 👌 LGTM, ✅ Ready for merging

#5425 Ocrvs 5217 Add type of organisation field
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/i18n/messages/views/userForm.ts
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5393 updated performance page to not show spinner when data is cached
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: ✅ Ready for merging

#5408 Fixed correction count on dashboard
  packages/metrics/src/features/performance/viewRefresher.ts
Labels: ✅ Ready for merging

#5423 fix: search width on mobile
  packages/client/src/components/Header/Header.tsx
Labels: ✅ Ready for merging

#5421 Fixed query placeholders to fetch the missing values in #5415
  packages/metrics/src/features/declarationsStarted/service.ts
Labels: ✅ Ready for merging

#5422 uploaded large certificate name ui fix
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
Labels: ✅ Ready for merging

#5431 Add declarant label for a better reading
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 🇨🇲 Cameroon

#5416 fixes #5361: missing headers in mobile view
  packages/client/src/components/Header/Header.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/views/SysAdmin/Config/UserRoles/UserRoles.tsx
  packages/client/src/views/SysAdmin/InformantSMSNotification/InformantSMSNotification.tsx
  packages/client/src/views/SysAdmin/Vsexports/VSExport.tsx
Labels: ✅ Ready for merging

#5432 ocrvs-5280 Use both section & group id for form key
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: ✅ Ready for merging

#5427 links disable for performanceManager
  packages/client/src/hooks/useAuthorization.ts
  packages/client/src/views/Performance/RegistrationsList.tsx
Labels: ✅ Ready for merging

#5439 Fix user form issues
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/forms/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#4429 chore(components): update Pagination to use ui-kit components
  packages/components/src/Pagination/Pagination.tsx
Labels: 👌 LGTM

#5440 Cameroon: Marriage certificate fixes
  packages/client/src/forms/configuration/default/marriage.ts
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
Labels: 🇨🇲 Cameroon

#5438 Add declarant label for a better reading for record audit page
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 🇨🇲 Cameroon

#5220 Component: ListConfig
  packages/components/src/ListConfig/ListConfig.stories.tsx
  packages/components/src/ListConfig/ListConfig.tsx
  packages/components/src/ListConfig/index.ts
  packages/components/src/index.ts
  packages/components/stories/releases.stories.mdx
Labels: ✅ Ready for merging

#5402 ocrvs-5256 serve certificate templates from minio
  docker-compose.yml
  packages/client/graphql.schema.json
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/pdfRenderer/transformer/types.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Vsexports/VSExport.tsx
  packages/config/package.json
  packages/config/src/config/constants.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/handlers/certificate/certificateHandler.test.ts
  packages/config/src/handlers/certificate/certificateHandler.ts
  packages/config/src/services/documents.ts
  packages/documents/package.json
  packages/documents/src/config/routes.ts
  packages/documents/src/features/getDocument/handler.ts
  packages/documents/src/features/uploadSvg/handler.test.ts
  packages/documents/src/features/uploadSvg/handler.ts
  packages/documents/src/minio/sign.ts
  packages/gateway/src/features/certificate/root-resolvers.test.ts
  packages/gateway/src/features/certificate/root-resolvers.ts
  packages/gateway/src/features/certificate/schema.graphql
  packages/gateway/src/features/certificate/type-resolvers.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/registration/utils.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/routes/getPresignedMinioURL/export-all-route.ts
  packages/gateway/src/routes/getPresignedMinioURL/handler.ts
  packages/gateway/src/utils/documents.ts
  packages/migration/.eslintrc.js
  packages/migration/migrations/application-config/20230518055204-upload-certificate-templates-to-minio.js
  packages/migration/package.json
  packages/migration/utils/minio-helper.js
Labels: 👌 LGTM, ✅ Ready for merging

#5249 refactor: Contents padding
  packages/components/src/Content/Content.tsx
Labels: ✅ Ready for merging

#4996 refactor: reset username or password screens to use Frame/Content etc
  packages/components/src/Frame/Frame.tsx
  packages/login/src/i18n/messages/views/resetCredentialsForm.ts
  packages/login/src/views/resetCredentialsForm/forgottenItemForm.tsx
  packages/login/src/views/resetCredentialsForm/phoneNumberVerificationForm.tsx
  packages/login/src/views/resetCredentialsForm/recoveryCodeEntryForm.tsx
  packages/login/src/views/resetCredentialsForm/resetCredentialsSuccessPage.tsx
  packages/login/src/views/resetCredentialsForm/securityQuestionForm.tsx
  packages/login/src/views/resetCredentialsForm/updatePasswordForm.tsx
Labels: ✅ Ready for merging
