Repository opencrvs/opencrvs-core, pull requests merged in 2023-09, with the labels that each got.

#5849 fix dob field for id verifier
  packages/client/src/forms/correction/verifyCorrector.ts
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
Labels: ✅ Ready for merging

#5868 Remove request queue
  packages/client/src/src-sw.ts
Labels: 💅 Waiting For Review, 👌 LGTM

#5863 Fix multiple issues with record audit
  packages/client/src/views/RecordAudit/History.tsx
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
Labels: ✅ Ready for merging

#5871 Fixes query mapping bug for postcode/number/city and point setup script to opencrvs/countryconfig
  .gitignore
  README.md
  development-environment/dev.sh
  development-environment/setup-countryconfig.sh
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/config/src/handlers/forms/validation.ts
  setup.sh
Labels: 💅 Waiting For Review

#5784 disable renaming of user roles
  packages/client/src/forms/user/query/queries.ts
  packages/client/src/views/SysAdmin/Config/UserRoles/UserRoles.test.tsx
  packages/client/src/views/UserRoles/UserRoleManagementModal.tsx
Labels: ✅ Ready for merging

#5880 Amend seed user data to support optional mobile/email
  packages/data-seeder/src/users.ts
Labels: 💅 Waiting For Review

#5861 ocrvs-5842 Skip cache for RecordAudit fetchInfo
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: 💅 Waiting For Review

#5853 Fix supporting document not showing in duplicate declaration
  packages/client/src/declarations/index.ts
  packages/client/src/views/ViewRecord/query.ts
Labels: 💅 Waiting For Review, 👌 LGTM

#5852 OCRVS-5851: Add old hashing functions
  packages/user-mgnt/package.json
  packages/user-mgnt/src/features/verifyPassword/handler.ts
  packages/user-mgnt/src/utils/hash.ts
Labels: ✅ Ready for merging

#5875 informant payload fix for informant change
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#5878 signature payload fix for marriage
  packages/client/src/forms/register/mappings/event-specific-fields/marriage/mutation/registration-mappings.ts
Labels: 💅 Waiting For Review

#5894 Fix typo and move clear command
  development-environment/clear-all-data.sh
  package.json
  packages/client/src/forms/index.ts
  packages/client/src/forms/register/mappings/mutation/field-mappings.ts
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  yarn.lock
Labels: 💅 Waiting For Review

#5896 Fix React key warnings
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#5884 feat(g2p): allow searching with childs identifier
  packages/gateway/src/features/bookmarkAdvancedSearch/schema.graphql
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/features/registration/utils.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.ts
  packages/workflow/src/features/registration/handler.ts
Labels: 💅 Waiting For Review

#5917 Update for birth certification
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  yarn.lock
Labels: 💅 Waiting For Review, 🇨🇲 Cameroon

#5912 refactor system/integration auth flow to use OAuth 2.0
  packages/auth/src/features/system/handler.test.ts
  packages/auth/src/features/system/handler.ts
  packages/auth/src/server.ts
  packages/gateway/src/features/fhir/utils.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/features/search/utils.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/types.ts
Labels: 💅 Waiting For Review, 📄 Documentation

#5901 doc view for duplicate form fix
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
Labels: 💅 Waiting For Review

#5890 signature payload fix for marriage
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#5926 collector form fix for print in advance off
  packages/client/src/views/PrintCertificate/utils.ts
Labels: 👌 LGTM, ⏳ Waiting for CI

#5947 Allow HTML elements to be used in PARAGRAPH type form fields
  packages/client/src/components/form/FormFieldGenerator.tsx
Labels: 💅 Waiting For Review

#5969 Renovate/configure
  renovate.json
Labels: 💅 Waiting For Review

#5910 refactor: form headings
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/components/src/Content/Content.tsx
  packages/components/src/Heading3/Heading.stories.tsx
  packages/components/src/Heading3/Heading3.tsx
  packages/components/src/Headings/Headings.tsx
  packages/components/src/fonts.ts
Labels: 💅 Waiting For Review

#5963 back button hide for first section
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: ✅ Ready for merging

#5908 duplicate icon fix for in progress declarations
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
Labels: 💅 Waiting For Review

#5965 user details reducer update
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
Labels: 💅 Waiting For Review

#5979 duplicate form ui fix
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.tsx
Labels: 💅 Waiting For Review

#5929 user create payload name fix
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/type-resolvers.ts
Labels: 💅 Waiting For Review

#5920 rejection declarations default sorting update
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
Labels: 💅 Waiting For Review

#5985 typo fix for correction
  packages/client/src/i18n/messages/views/correction.ts
Labels: 💅 Waiting For Review

#5978 address fields fix for review section
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#5955 informant type change handle for correction
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#5983 localData property add in declaration state
  packages/client/src/declarations/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#5989 Fix clear command and reduce storage time of OpenHIM transactions
  development-environment/clear-all-data.sh
  packages/scheduler/jobs/clearOpenHIMTransactions.sh
Labels: 💅 Waiting For Review

#5990 Death reg: Allow parents and spouses details to be submitted
  packages/client/src/forms/register/mappings/query/father-mappings.ts
  packages/client/src/forms/register/mappings/query/index.ts
  packages/client/src/forms/register/mappings/query/mother-mappings.ts
  packages/client/src/forms/register/mappings/query/spouse-mappings.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/OIDPVerificationCallback/utils.ts
  packages/client/src/views/ViewRecord/query.ts
  packages/config/src/handlers/forms/validation.ts
  packages/gateway/src/features/registration/fhir-builders.ts
Labels: 💅 Waiting For Review
