Repository opencrvs/opencrvs-core, pull requests merged in 2024-09, with the labels that each got.

#7545 feat: align name field with fhir
  CHANGELOG.md
  packages/commons/src/fhir/patient.ts
  packages/commons/src/fhir/transformers/index.ts
  packages/commons/src/fixtures/birth-bundle.ts
  packages/commons/src/fixtures/death-bundle.ts
  packages/commons/src/fixtures/marriage-bundle.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/features/search/type-resolvers.ts
  packages/migration/src/migrations/hearth/20240828160959-align-family-prop-in-name.ts
  packages/notification/src/features/utils.ts
  packages/notification/src/features/utilsForPartiallyCompletedRecord.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/search/src/test/utils.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/test/utils.ts
  packages/workflow/test/mocks/records/certify.ts
  packages/workflow/test/mocks/records/readyForReview.ts
  packages/workflow/test/mocks/records/register.ts
Labels: ✅ Ready for merging

#7551 fix: add the missing location details to a newly created declaration which was causing advanced search to break
  CHANGELOG.md
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/create.ts
Labels: ✅ Ready for merging

#7306 Create a Script for Debugging Node.js Applications with Chrome DevTools
  debug-service-in-chrome.sh
  package.json
Labels: Tech, ✅ Ready for merging, 🧪 Experiment, 📝 CHANGELOG missing

#7479 Get client manifest and icons from country-config
  CHANGELOG.md
  packages/client/Dockerfile
  packages/client/nginx.conf
  packages/client/vite.config.ts
Labels: ✅ Ready for merging

#7555 fix: update address builder for event location
  CHANGELOG.md
  packages/commons/src/fhir/transformers/index.ts
Labels: ✅ Ready for merging

#7562 fix: correct user role not showing if role is updated
  CHANGELOG.md
  packages/commons/src/fhir/practitioner.ts
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: ✅ Ready for merging

#7383 Redact sensitive user information from log
  CHANGELOG.md
  packages/commons/src/logger.ts
Labels: ✅ Ready for merging

#7580 fix: fetch custom validators before deserializing
  CHANGELOG.md
  packages/client/src/declarations/submissionMiddleware.test.ts
  packages/client/src/forms/register/reducer.ts
  packages/client/src/forms/register/reviewReducer.ts
  packages/client/src/offline/actions.ts
  packages/client/src/tests/util.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.test.tsx
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.test.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/SysAdmin/Config/Systems/Systems.test.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/StatusWiseDeclarationCountView.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.test.tsx
Labels: 👌 LGTM

#7593 chore: display component library version via package.json
  packages/components/stories/intro.stories.mdx
Labels: ✅ Ready for merging

#7591 fix: create separate `unassigned` task when correcting record
  CHANGELOG.md
  packages/workflow/src/records/handler/correction/make-correction.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#7579 fix: amend updating signatures in client and workflow
  CHANGELOG.md
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/workflow/src/documents.ts
Labels: 💅 Waiting For Review

#7600 fix: send review form from client for correction actions instead of register form
  CHANGELOG.md
  packages/client/src/declarations/submissionMiddleware.ts
Labels: 💅 Waiting For Review

#7601 fix: update allowing file type condition for signature
  packages/client/src/components/form/SignatureField/SignatureUploader.tsx
  packages/client/src/forms/index.ts
Labels: 👌 LGTM, ✅ Ready for merging

#7569 feat: enable conditional filtering in document select options
  CHANGELOG.md
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
Labels: 💅 Waiting For Review

#7352 Remove update-application-config from backend
  CHANGELOG.md
  packages/client/graphql.schema.json
  packages/client/src/App.tsx
  packages/client/src/certificate/mutations.ts
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/InformantSMSNotification.test.tsx
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/InformantSMSNotification.tsx
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/mutations.ts
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/queries.ts
  packages/client/src/views/SysAdmin/Config/Application/Components.tsx
  packages/client/src/views/SysAdmin/Config/Application/mutation.test.ts
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/client/src/views/SysAdmin/Config/Application/utils.ts
  packages/config/src/config/routes.ts
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/handlers/certificate/certificateHandler.test.ts
  packages/config/src/handlers/certificate/certificateHandler.ts
  packages/config/src/handlers/informantSMSNotifications/createInformantSMSNotification/handler.test.ts
  packages/config/src/handlers/informantSMSNotifications/createInformantSMSNotification/handler.ts
  packages/config/src/handlers/informantSMSNotifications/getInformantSMSNotification/handler.test.ts
  packages/config/src/handlers/informantSMSNotifications/getInformantSMSNotification/handler.ts
  packages/config/src/handlers/informantSMSNotifications/updateInformantSMSNotification/handler.test.ts
  packages/config/src/handlers/informantSMSNotifications/updateInformantSMSNotification/handler.ts
  packages/config/src/models/informantSMSNotifications.ts
  packages/gateway/src/features/application/root-resolvers.test.ts
  packages/gateway/src/features/application/root-resolvers.ts
  packages/gateway/src/features/application/schema.graphql
  packages/gateway/src/features/application/type-resolvers.ts
  packages/gateway/src/features/certificate/root-resolvers.test.ts
  packages/gateway/src/features/certificate/root-resolvers.ts
  packages/gateway/src/features/certificate/schema.graphql
  packages/gateway/src/features/certificate/type-resolvers.ts
  packages/gateway/src/features/informantSMSNotifications/root-resolvers.test.ts
  packages/gateway/src/features/informantSMSNotifications/root-resolvers.ts
  packages/gateway/src/features/informantSMSNotifications/schema.graphql
  packages/gateway/src/features/informantSMSNotifications/type-resolvers.ts
  packages/gateway/src/features/notification/root-resolvers.test.ts
  packages/gateway/src/features/notification/root-resolvers.ts
  packages/gateway/src/features/notification/schema.graphql
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/src/migrations/application-config/20240708170106-remove-config-collections.ts
Labels: ✅ Ready for merging

#7476 fix: Wrong status shown in the Comparison View Page of duplicate record
  CHANGELOG.md
  packages/client/src/declarations/index.ts
  packages/client/src/views/CorrectionForm/CorrectionSummary.test.tsx
  packages/client/src/views/CorrectionForm/ReviewForm.test.tsx
  packages/client/src/views/CorrectionForm/utils.test.ts
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/PrintRecord/Body.tsx
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/ViewRecord/ViewRecord.tsx
Labels: ✅ Ready for merging

#7639 fix: exclude `UNASSIGNED_EXTENSION_URL` from the extension list of correctedTask
  packages/workflow/src/records/fhir.ts
Labels: 💅 Waiting For Review

#7644 Fix/migrate address and informant details
  packages/migration/src/migrations/hearth/20240923104723-change-task-input-output-id-with-postfix.ts
  packages/migration/src/migrations/hearth/20240923141025-change-task-input-output-informant-phone-value-id-value-code.ts
Labels: 💅 Waiting For Review

#7609 fix: docker compose check in setup
  CHANGELOG.md
  setup.sh
Labels: ✅ Ready for merging

#7618 fix(v1.6.0): Date validation not working in firefox
  CHANGELOG.md
  packages/client/src/utils/validate.ts
Labels: ✅ Ready for merging, 📝 CHANGELOG missing

#7672 fix: layout issue with AdvancedSearch's edit button not properly showing on mobile view
  CHANGELOG.md
  packages/client/src/components/DateRangePickerForFormField.tsx
Labels: 💅 Waiting For Review
