Repository opencrvs/opencrvs-core, pull requests merged in 2024-10, with the labels that each got.

#7665 Accessibility improvement in Choose New Password page
  CHANGELOG.md
  packages/client/src/views/UserSetup/CreatePassword.test.tsx
  packages/client/src/views/UserSetup/CreatePassword.tsx
Labels: 💅 Waiting For Review

#7651 refactor(env-vars): use envalid in user-mgnt
  packages/user-mgnt/package.json
  packages/user-mgnt/src/constants.ts
  packages/user-mgnt/src/environment.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/utils/system.ts
Labels: 💅 Waiting For Review

#7650 refactor(env-vars): use envalid in notification
  packages/notification/package.json
  packages/notification/src/constants.ts
  packages/notification/src/environment.ts
Labels: 💅 Waiting For Review

#7649 refactor(env-vars): check env vars in production for migration
  packages/migration/package.json
  packages/migration/run-migrations.sh
  packages/migration/src/migrate-mongo-config-application-config.js
  packages/migration/src/migrate-mongo-config-hearth.js
  packages/migration/src/migrate-mongo-config-openhim.js
  packages/migration/src/migrate-mongo-config-performance.js
  packages/migration/src/migrate-mongo-config-user-mgnt.js
Labels: 💅 Waiting For Review

#7625 refactor(env-vars): config, webhooks and gateway env validation
  packages/commons/src/token-verifier.test.ts
  packages/commons/src/token-verifier.ts
  packages/config/package.json
  packages/config/src/config/constants.ts
  packages/config/src/config/database.ts
  packages/config/src/config/plugins.ts
  packages/config/src/environment.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/handlers/dashboardQueries/dashboardQueries.ts
  packages/config/src/handlers/dashboardQueries/defaultQueries.ts
  packages/config/src/handlers/forms/formsHandler.ts
  packages/config/src/server.ts
  packages/config/src/services/documents.ts
  packages/config/src/services/hearth.ts
  packages/config/src/services/userManagement.ts
  packages/gateway/package.json
  packages/gateway/src/constants.ts
  packages/gateway/src/environment.ts
  packages/webhooks/package.json
  packages/webhooks/src/constants.ts
  packages/webhooks/src/environment.ts
Labels: 💅 Waiting For Review

#7722 fix: update defining development mode explicitly for gateway
  packages/gateway/package.json
Labels: 💅 Waiting For Review

#7653 fix: dropdown option height
  .github/CODEOWNERS
  CHANGELOG.md
  license-config.json
  packages/components/src/Select/Select.tsx
Labels: 💅 Waiting For Review, 📝 CHANGELOG missing

#7640 refactor: header component from class to functional
  packages/client/src/components/Header/Header.tsx
  packages/client/src/views/RegisterForm/DeclarationForm.tsx
  packages/components/src/InputField/InputField.stories.tsx
  packages/components/src/InputField/ValidIndicator.tsx
  packages/components/src/InputField/VerifyingIndicator.tsx
  packages/components/src/InputField/index.ts
Labels: ✅ Ready for merging

#7645 chore: configurable roles tasks
  packages/client/graphql.schema.json
  packages/client/src/declarations/index.test.ts
  packages/client/src/profile/queries.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RegisterForm/RegisterForm.init.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/Unlock/ForgotPIN.test.tsx
  packages/commons/src/fhir/practitioner.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/user/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/config/routes.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#7723 fix(header): advanced search button fixed and remove unused code
  packages/client/src/components/Header/Header.tsx
Labels: ✅ Ready for merging

#7734 fix: informant input flicker issue
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#7739 fix: notification content
  packages/notification/src/features/sentForUpdates/handler.ts
  packages/notification/src/features/utils.ts
Labels: 💅 Waiting For Review

#7742 fix(migration): introduce conditionality and continue indexing on failure
  packages/migration/src/migrations/hearth/20220822085901-rejected-declarations-started-by.ts
  packages/migration/src/migrations/hearth/20221017133354-restore-supporting-document.ts
  packages/migration/src/migrations/hearth/20221031131452-add_practioner_id_event_registrations.ts
  packages/migration/src/migrations/hearth/20221110092434-add_identifiers_DOB_gender_location.ts
  packages/migration/src/migrations/hearth/20221128065238-migrate-documents-to-minio.ts
  packages/migration/src/migrations/hearth/20230127063226-update-practitioner-role.ts
  packages/migration/src/migrations/hearth/20230221105416-create-performance-views.ts
  packages/migration/src/migrations/hearth/20230328065851-change-certified-status-to-issused.ts
  packages/migration/src/migrations/hearth/20230602120944-populate-valid-locationid.ts
  packages/migration/src/migrations/hearth/20231123125224-deceased-birth-date.ts
  packages/search/src/features/reindex/reindex.ts
Labels: 💅 Waiting For Review

#7747 fix: form value handle
  packages/client/src/transformer/index.ts
Labels: 💅 Waiting For Review

#7690 fix(v1.7.0): Only render units/postfix when field has a value
  CHANGELOG.md
  packages/client/src/views/PrintRecord/Body.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging, 📝 CHANGELOG missing

#7630 fix(v1.7.0): Improvement to only show items with values in review
  CHANGELOG.md
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: ✅ Ready for merging, 📝 CHANGELOG missing

#7729 (User roles) fix: update previour version of user details in indexdb
  packages/client/src/SubmissionController.test.ts
  packages/client/src/forms/conditionals.ts
  packages/client/src/forms/register/mappings/query/registration-mappings.ts
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/profile/profileReducer.ts
  packages/client/src/tests/mock-graphql-responses.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/user/userReducer.ts
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/Performance/RegistrationsList.tsx
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/Settings/items/Role.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/ViewRecord/ViewRecord.test.tsx
  packages/commons/src/fixtures/birth-bundle.ts
  packages/commons/src/fixtures/death-bundle.ts
  packages/commons/src/fixtures/marriage-bundle.ts
  packages/commons/src/test-resources.ts
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/search/src/test/utils.ts
  packages/webhooks/src/features/event/service.test.ts
  packages/workflow/test/mocks/practitionerRole.ts
Labels: 💅 Waiting For Review

#7763 /sendVerifyCode moved to gateway/config/routes.ts; dead code removed
  packages/gateway/src/config/routes.ts
  packages/gateway/src/routes/getPresignedMinioURL/export-all-route.ts
  packages/gateway/src/routes/getPresignedMinioURL/handler.ts
  packages/gateway/src/routes/verifyCode/export-route.ts
Labels: 💅 Waiting For Review

#7765 fix: find office location from current task
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 👌 LGTM

#7773 fix: hide signature for duplicate record
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#7697 feat: Update the order of system user add/edit form fields and labels and remove NID field
  CHANGELOG.md
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
  packages/client/src/i18n/messages/views/userForm.ts
  packages/client/src/tests/forms.json
  packages/client/src/tests/util.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/type-resolvers.test.ts
  packages/gateway/src/features/user/type-resolvers.ts
  packages/migration/src/migrations/user-mgnt/20241007100507-remove-nid-field.ts
  packages/user-mgnt/src/features/activateUser/handler.test.ts
  packages/user-mgnt/src/features/changeAvatar/handler.test.ts
  packages/user-mgnt/src/features/changeEmail/handler.test.ts
  packages/user-mgnt/src/features/changePassword/handler.test.ts
  packages/user-mgnt/src/features/changePhone/handler.test.ts
  packages/user-mgnt/src/features/createUser/handler.test.ts
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/resendInvite/handler.test.ts
  packages/user-mgnt/src/features/resetPassword/handler.test.ts
  packages/user-mgnt/src/features/updateUser/handler.test.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/features/userAudit/handler.test.ts
  packages/user-mgnt/src/features/userSearchRecord/handler.test.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.test.ts
  packages/user-mgnt/src/features/verifyPassword/handler.test.ts
  packages/user-mgnt/src/features/verifySecurityAnswer/handler.test.ts
  packages/user-mgnt/src/model/user.ts
Labels: 💅 Waiting For Review

#7674 feat(message-queue): allow confirming and rejecting record externally
  docker-compose.dev.yml
  packages/client/graphql.schema.json
  packages/client/src/declarations/createRecord.ts
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/tests/languages.json
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/commons/src/fhir/patient.ts
  packages/commons/src/message-queue/record.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/environment.ts
  packages/gateway/src/features/registration/__snapshots__/type-resolvers.test.ts.snap
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/graphql/query-generator.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/workflow/index.ts
  packages/metrics/src/features/registration/test-data/sent-for-updates-request.json
  packages/metrics/src/features/registration/test-data/task-history.json
  packages/search/src/test/utils.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/constants.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/records/handler/confirm.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/src/records/handler/register.ts
  packages/workflow/src/server.ts
  packages/workflow/src/workers.ts
  yarn.lock
Labels: 💅 Waiting For Review

#7822 fix: make all triggers of a specific http request touched on request change
  packages/client/src/components/form/Button.tsx
Labels: 💅 Waiting For Review

#7830 feat: show displayName of styled components in devtools
  packages/client/package.json
  packages/client/vite.config.ts
  yarn.lock
Labels: ✅ Ready for merging

#7842 fix: disable `google translate` extension
  packages/client/index.html
  packages/login/index.html
Labels: ✅ Ready for merging

#7633 feat: Action Menu
  CHANGELOG.md
  packages/client/src/components/ProfileMenu.test.tsx
  packages/client/src/components/interface/DownloadButton.test.tsx
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/declarations/utils.ts
  packages/client/src/i18n/messages/buttons.ts
  packages/client/src/i18n/messages/views/action.ts
  packages/client/src/search/transformer.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.test.tsx
  packages/client/src/views/OfficeHome/inExternalValidation/inExternalValidationTab.test.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx
  packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.test.tsx
  packages/client/src/views/RecordAudit/ActionMenu.test.tsx
  packages/client/src/views/RecordAudit/ActionMenu.tsx
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/RegisterForm/DeclarationForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SysAdmin/Config/Systems/Systems.test.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/UserAudit/UserAudit.test.tsx
  packages/commons/src/search.ts
  packages/components/src/Dropdown/Dropdown.stories.tsx
  packages/components/src/Dropdown/Dropdown.tsx
  packages/components/src/Dropdown/DropdownContext.tsx
  packages/components/src/Dropdown/index.ts
  packages/components/src/Icon/all-icons.ts
  packages/components/src/ToggleMenu/ToggleMenu.stories.tsx
  packages/components/src/ToggleMenu/ToggleMenu.tsx
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/features/search/type-resolvers.ts
Labels: 💅 Waiting For Review

#7791 (User roles) Add scopes to routes
  packages/auth/src/features/refresh/handler.test.ts
  packages/auth/src/features/verifyCode/handler.test.ts
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/components/Header/Header.tsx
  packages/client/src/components/ProtectedRoute.tsx
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/hooks/useAuthorization.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/persistence/persistenceMiddleware.ts
  packages/client/src/views/CorrectionForm/ReviewForm.test.tsx
  packages/client/src/views/RegisterForm/DeclarationForm.test.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.test.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Team/TeamSearch.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/commons/src/authentication.ts
  packages/commons/src/scopes.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/login/package.json
Labels: 💅 Waiting For Review

#7854 fix(ocrvs-5952): `informantType` in handlebars template object
  .github/workflows/build-images-from-branch.yml
  CHANGELOG.md
  packages/client/src/forms/register/mappings/query/field-mappings.ts
Labels: 👌 LGTM

#7810 fix: custom time period in user audit
  packages/client/src/components/DateRangePicker.tsx
Labels: 💅 Waiting For Review

#7789 fix: return first child "location" from query
  CHANGELOG.md
  packages/client/graphql.schema.json
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/Performance/RegistrationsList.tsx
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.test.tsx
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/gateway/src/features/location/root-resolvers.test.ts
  packages/gateway/src/features/location/root-resolvers.ts
  packages/gateway/src/features/location/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/location.ts
  packages/gateway/src/rate-limit.test.ts
Labels: 👌 LGTM

#7877 fix(rate-limit): use the value of an object key, instead of the key itself
  CHANGELOG.md
  packages/gateway/src/rate-limit.test.ts
  packages/gateway/src/rate-limit.ts
Labels: 💅 Waiting For Review
