Repository opencrvs/opencrvs-core, pull requests merged in 2024-03, with the labels that each got.

#6431 [State transitions] not duplicate
  packages/commons/src/fhir/transformers/templates.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/utils.ts
  packages/gateway/src/workflow/index.ts
  packages/metrics/src/config/routes.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/task/fhir/utils.ts
  packages/workflow/src/features/user/utils.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/download.ts
  packages/workflow/src/records/handler/not-duplicate.test.ts
  packages/workflow/src/records/handler/not-duplicate.ts
  packages/workflow/src/records/handler/unassign.ts
  packages/workflow/src/records/handler/update.test.ts
  packages/workflow/src/records/handler/update.ts
  packages/workflow/src/records/recordEvents.ts
  packages/workflow/src/records/search.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#6566 More class converts
  packages/components/src/Loader/Loader.tsx
  packages/components/src/PageWrapper/PageWrapper.tsx
  packages/components/src/Radio/Radio.tsx
  packages/components/src/Radio/RadioButton.tsx
  packages/components/src/Radio/RadioGroup.tsx
  packages/components/src/Select/Select.tsx
  packages/components/src/SubSectionDivider/SubSectionDivider.tsx
  packages/components/src/TextArea/TextArea.tsx
  packages/components/src/ViewData/DataRow.tsx
  packages/components/src/ViewData/DataSection.tsx
  packages/components/src/Workqueue/components/LoadMore.tsx
  packages/login/src/App.tsx
Labels: 👌 LGTM

#6577 Bugfixes from Uganda PoC
  CHANGELOG.md
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/ViewRecord/query.ts
  packages/config/src/handlers/forms/validation.ts
Labels: 💅 Waiting For Review, 💥 Hot Fixes

#6579 Component converts
  packages/components/src/Checkbox/CheckboxGroup.tsx
  packages/components/src/Content/Content.tsx
  packages/components/src/ExpandingMenu/ExpandingMenu.tsx
  packages/components/src/FileSelectLink/FileSelectLink.tsx
  packages/components/src/ImageUploader/ImageUploader.tsx
  packages/components/src/InputField/InputField.tsx
  packages/components/src/InputField/InputLabel.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/ProgressBar/ProgressBar.tsx
Labels: 💅 Waiting For Review

#6554 [State Transitions] Fix task creation taking previous status and encounter into account
  packages/workflow/src/records/fhir.ts
Labels: 👌 LGTM

#6581 ocrvs-6559 Update minimum password length validation
  CHANGELOG.md
  packages/client/src/views/UserSetup/CreatePassword.tsx
Labels: 💅 Waiting For Review, 💥 Hot Fixes

#6562 Converted Checkbox and ErrorBoundary components to the fucntion compo…
  packages/client/src/components/ErrorBoundary.tsx
  packages/components/src/ActionPageLight/ActionPageLight.tsx
  packages/components/src/AppHeader/AppHeader.tsx
  packages/components/src/AppHeader/Desktop/DesktopHeader.tsx
  packages/components/src/AppHeader/Mobile/MobileHeader.tsx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/CheckboxGroup.tsx
  packages/components/src/Content/Content.tsx
  packages/components/src/ExpandingMenu/ExpandingMenu.tsx
  packages/components/src/FileSelectLink/FileSelectLink.tsx
  packages/components/src/ImageUploader/ImageUploader.tsx
  packages/components/src/InputField/InputDescriptor.tsx
  packages/components/src/InputField/InputError.tsx
  packages/components/src/InputField/InputField.tsx
  packages/components/src/InputField/InputLabel.tsx
  packages/components/src/Loader/Loader.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/PageWrapper/PageWrapper.tsx
  packages/components/src/ProgressBar/ProgressBar.tsx
  packages/components/src/Radio/Radio.tsx
  packages/components/src/Radio/RadioButton.tsx
  packages/components/src/Radio/RadioGroup.tsx
  packages/components/src/Select/Select.tsx
  packages/components/src/Spinner/Spinner.tsx
  packages/components/src/SubSectionDivider/SubSectionDivider.tsx
  packages/components/src/TextArea/TextArea.tsx
  packages/components/src/ViewData/DataRow.tsx
  packages/components/src/ViewData/DataSection.tsx
  packages/components/src/ViewData/ListRow.tsx
  packages/components/src/Workqueue/components/LoadMore.tsx
  packages/login/src/App.tsx
  packages/login/src/ErrorBoundary.tsx
Labels: 🚧 work in progress

#6576 ocrvs-6469 include middlename when generating fullnames
  CHANGELOG.md
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/utils/data-formatting.ts
  packages/client/src/utils/draftUtils.test.ts
  packages/client/src/utils/draftUtils.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/RecordAudit/queries.ts
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/ViewRecord/query.ts
  packages/config/src/handlers/forms/validation.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
Labels: 👌 LGTM

#6585 Class converts to function
  packages/client/src/components/ProtectedAccount.tsx
  packages/components/src/ResponsiveModal/ResponsiveModal.tsx
Labels: 💅 Waiting For Review

#6587 Fix fetching declarations of current user for in progress declaration
  CHANGELOG.md
  packages/client/src/declarations/index.ts
Labels: 💅 Waiting For Review

#6563 [State transitions] Remove detect event
  development-environment/dev.sh
  docker-compose.demo-deps.yml
  docker-compose.dev-deps.yml
  docker-compose.dev.yml
  docker-compose.yml
  packages/commons/src/fhir/encounter.ts
  packages/commons/src/fhir/transformers/index.ts
  packages/config/src/config/constants.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/features/fhir/service.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/metrics/src/constants.ts
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/migration/src/migrations/openhim/20240305193551-remove-openhim-collections.ts
  packages/search/src/constants.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/user-mgnt/src/constants.ts
  packages/user-mgnt/src/features/createUser/handler.test.ts
  packages/webhooks/src/constants.ts
  packages/workflow/package.json
  packages/workflow/src/__mocks__/constants.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/constants.ts
  packages/workflow/src/features/events/auth.test.ts
  packages/workflow/src/features/events/auth.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/events/utils.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-template.test.ts
  packages/workflow/src/features/registration/fhir/fhir-template.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.test.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/task/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/task/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/task/handler.test.ts
  packages/workflow/src/features/task/handler.ts
  packages/workflow/src/features/user/utils.test.ts
  packages/workflow/src/features/user/utils.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/download.ts
  packages/workflow/src/records/handler/register.test.ts
  packages/workflow/src/records/handler/update.test.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/test/utils.ts
  packages/workflow/src/utils/formDraftUtils.test.ts
  packages/workflow/src/utils/formDraftUtils.ts
  setup.sh
  yarn.lock
Labels: 💅 Waiting For Review

#6514 fix: saving declarations when redirecting to nid integration
  license-config.json
  packages/client/graphql.schema.json
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/declarations/selectors.ts
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/IssueCertificate/IssueCertificate.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.test.tsx
  packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.tsx
  packages/client/src/views/OIDPVerificationCallback/utils.ts
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/gateway/src/features/systems/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
Labels: ✅ Ready for merging

#6606 Exclude location ref from RelatedPerson address
  packages/search/src/features/records/service.ts
Labels: 💅 Waiting For Review

#6608 fix(security): ignore metabase vulnerability errors until v0.49
  .trivyignore.yaml
Labels: 💅 Waiting For Review

#6630 Fix copy text extractor
  packages/client/extract-translations.sh
  packages/client/package.json
  packages/client/src/extract-translations.ts
  packages/client/src/i18n/messages/views/selectInformant.ts
  packages/login/extract-translations.sh
  packages/login/package.json
  packages/login/src/extract-translations.ts
  packages/notification/package.json
  packages/notification/src/extract-translations.ts
  patches/typescript-react-intl+0.3.0.patch
  yarn.lock
Labels: 🏥 Failing Tests

#6611 Refactor task create
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/archive.test.ts
  packages/workflow/src/records/handler/archive.ts
  packages/workflow/src/records/handler/download.ts
  packages/workflow/src/records/handler/duplicate.test.ts
  packages/workflow/src/records/handler/duplicate.ts
  packages/workflow/src/records/handler/reinstate.test.ts
  packages/workflow/src/records/handler/reinstate.ts
  packages/workflow/src/records/handler/unassign.ts
  packages/workflow/src/records/handler/update.test.ts
  packages/workflow/src/records/handler/view.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/test/handlers.ts
Labels: ✅ Ready for merging

#6620 Fix qr for death declaration
  CHANGELOG.md
  packages/commons/src/fhir/transformers/index.ts
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: ✅ Ready for merging

#6624 Fix 6216
  CHANGELOG.md
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/forms/correction/corrector.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/workflow/src/records/fhir.ts
Labels: 🔧Waiting for fixes

#5219 Component: ListReview
  packages/client/src/views/RegisterForm/DeclarationForm.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/components/src/Dialog/index.ts
  packages/components/src/Headings/index.ts
  packages/components/src/ListReview/ListReview.stories.tsx
  packages/components/src/ListReview/ListReview.tsx
  packages/components/src/ListReview/components/Header.tsx
  packages/components/src/ListReview/components/Row.tsx
  packages/components/src/ListReview/index.ts
  packages/components/src/index.ts
Labels: ✅ Ready for merging

#6616 fix(qr-code): page crash on verify certificate and add missing registrar information
  CHANGELOG.md
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/views/verifyCertificate.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
  packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/workflow/src/records/handler/verify.ts
  packages/workflow/src/records/state-transitions.ts
Labels: ✅ Ready for merging

#6640 refactor: renovate config
  renovate.json
Labels: 💅 Waiting For Review

#6591 Class converts
  packages/client/src/views/SysAdmin/Performance/reports/completenessRates/CompletenessDataTable.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
  packages/components/src/DocumentViewer/DocumentViewer.tsx
  packages/components/src/ListTable/ListTable.tsx
  packages/components/src/LoadingGrey/LoadingGrey.tsx
  packages/components/src/LoadingGrey/index.ts
  packages/components/src/PasswordInput/PasswordInput.tsx
  packages/components/src/Table/Table.tsx
  packages/components/src/ToggleMenu/ToggleMenu.tsx
  packages/components/src/Workqueue/Workqueue.tsx
  packages/components/src/index.ts
  packages/login/src/views/resetCredentialsForm/resetCredentialsSuccessPage.tsx
Labels: ✅ Ready for merging

#6637 feat: add a spinner to login & client after 2 seconds
  CHANGELOG.md
  packages/client/index.html
  packages/client/src/components/ProtectedPage.tsx
  packages/login/index.html
Labels: 💅 Waiting For Review

#6655 update renovate.json
  renovate.json
Labels: 💅 Waiting For Review

#6677 Fix bug introduced in #6591
  packages/components/src/ToggleMenu/ToggleMenu.tsx
Labels: ✅ Ready for merging

#6676 Update only the timeLogged value when unmounting
  CHANGELOG.md
  packages/client/src/components/TimeMounted.tsx
  packages/client/src/views/CorrectionForm/CorrectionForm.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
Labels: 💅 Waiting For Review

#6690 chore: remove common vfs to reduce bundle size
  packages/client/src/pdfRenderer/common_vfs.ts
  packages/client/src/pdfRenderer/index.ts
Labels: 💅 Waiting For Review

#6707 fix: review padding on mobile
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#6696 Fix unable to validate/ register incomplete death declaration and small fixes for incomplete declarations
  packages/client/src/declarations/index.ts
  packages/client/src/transformer/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/commons/package.json
  packages/gateway/package.json
Labels: ✅ Ready for merging
