Repository opencrvs/opencrvs-core, pull requests merged in 2024-02, with the labels that each got.

#6461 update password copy to suggest a 12 character long passphrase
  packages/client/src/i18n/messages/user.ts
  packages/client/src/i18n/messages/views/userSetup.ts
  packages/client/src/tests/languages.json
  packages/client/src/views/Settings/PasswordChangeModal.tsx
  packages/client/src/views/UserSetup/CreatePassword.tsx
  packages/login/src/i18n/messages/views/resetCredentialsForm.ts
  packages/login/src/views/resetCredentialsForm/updatePasswordForm.tsx
Labels: 💅 Waiting For Review

#6442 [state-transition] Cross office registration
  packages/commons/src/fhir/index.ts
  packages/commons/src/fhir/practitioner.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/records/audit.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/certify.ts
  packages/workflow/src/records/handler/create.test.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/src/records/handler/issue.ts
  packages/workflow/src/records/handler/register.test.ts
  packages/workflow/src/records/handler/register.ts
  packages/workflow/src/records/handler/reject.test.ts
  packages/workflow/src/records/handler/reject.ts
  packages/workflow/src/records/handler/update.ts
  packages/workflow/src/records/handler/validate.test.ts
  packages/workflow/src/records/handler/validate.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/records/user.ts
  packages/workflow/test/handlers.ts
  packages/workflow/test/mocks/locations.ts
Labels: 💅 Waiting For Review

#6445 [state-transitions] Refactor event names
  packages/commons/src/record.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
  packages/metrics/package.json
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/metrics/constants.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/registration/test-data/new-in-progress-request.json
  packages/metrics/src/features/registration/test-data/sent-for-approval-request.json
  packages/metrics/src/features/registration/test-data/sent-for-updates-request.json
  packages/metrics/src/features/registration/test-data/sent-notification-request.json
  packages/metrics/src/features/registration/test-data/waiting-validation-request.json
  packages/metrics/tsconfig.json
  packages/notification/src/config/routes.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/records/audit.ts
  packages/workflow/src/records/handler/certify.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/src/records/handler/issue.ts
  packages/workflow/src/records/handler/register.ts
  packages/workflow/src/records/handler/reinstate.test.ts
  packages/workflow/src/records/handler/reinstate.ts
  packages/workflow/src/records/handler/reject.ts
  packages/workflow/src/records/handler/validate.ts
  packages/workflow/src/records/notification.ts
  packages/workflow/src/records/recordEvents.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/utils/authUtils.ts
  packages/workflow/test/handlers.ts
Labels: 💅 Waiting For Review

#6446 [state-transitions] Align getRecordById's response with hearth
  packages/commons/src/fhir/composition.ts
  packages/commons/src/fhir/encounter.ts
  packages/commons/src/fhir/extension.ts
  packages/commons/src/fhir/index.ts
  packages/commons/src/fhir/transformers/utils.ts
  packages/commons/src/fixtures/birth-bundle.ts
  packages/commons/src/fixtures/death-bundle.ts
  packages/commons/src/fixtures/marriage-bundle.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/utils/testUtils.ts
  packages/notification/src/features/inProgress/handler.ts
  packages/notification/src/features/utils.ts
  packages/search/src/features/records/service.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/create.test.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/test/mocks/locations.ts
  packages/workflow/test/mocks/records/certify.ts
  packages/workflow/test/mocks/records/readyForReview.ts
  packages/workflow/test/mocks/records/register.ts
Labels: 💅 Waiting For Review

#6487 Add and configure Trivy for security scans
  .github/workflows/build-images-from-branch.yml
  .github/workflows/lint-and-test.yml
  .github/workflows/publish-release.yml
  .trivyignore.yaml
  packages/auth/Dockerfile
  packages/client/Dockerfile
  packages/components/Dockerfile
  packages/config/Dockerfile
  packages/config/src/handlers/forms/validation.ts
  packages/dashboards/Dockerfile
  packages/documents/Dockerfile
  packages/gateway/Dockerfile
  packages/login/Dockerfile
  packages/metrics/Dockerfile
  packages/migration/Dockerfile
  packages/notification/Dockerfile
  packages/scheduler/Dockerfile
  packages/search/Dockerfile
  packages/user-mgnt/Dockerfile
  packages/webhooks/Dockerfile
  packages/workflow/Dockerfile
  trivy.yaml
Labels: 👌 LGTM

#6467 [state-transitions] amend search
  packages/client/src/declarations/submissionMiddleware.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/composition.test.ts
  packages/search/src/features/registration/birth/handler.test.ts
  packages/search/src/features/registration/birth/noParents.test.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/handler.test.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/handler.test.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/search/src/test/utils.ts
  packages/search/tsconfig.json
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/records/handler/reject.ts
  packages/workflow/src/records/search.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#6495 Update message in dev.sh
  development-environment/dev.sh
Labels: ✅ Ready for merging

#6493 update migration of indexing email and phone field
  packages/migration/src/migrations/user-mgnt/20231106130956-email-mobile-unique-index.ts
Labels: 👌 LGTM

#6491 Allow occupation to be an optional field for deceased
  CHANGELOG.md
  packages/config/src/handlers/forms/validation.ts
Labels: 👌 LGTM, 💥 Hot Fixes

#6459 [state-transitions] view record
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
  packages/metrics/src/config/routes.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/download.ts
  packages/workflow/src/records/handler/view.test.ts
  packages/workflow/src/records/handler/view.ts
  packages/workflow/src/records/index.ts
  packages/workflow/src/records/recordEvents.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#6399 [OCRVS-6124] Fix locations seeding when there are many locations
  CHANGELOG.md
  packages/gateway/src/features/restLocation/locationHandler.ts
Labels: 💥 Hot Fixes, ✅ Ready for merging

#6463 [state-transitions] verify record
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/reject.ts
  packages/workflow/src/records/handler/update.ts
  packages/workflow/src/records/handler/verify.test.ts
  packages/workflow/src/records/handler/verify.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#6528 [OCRVS-6202] Fix for national id type search not showing in search dropdown
  packages/client/src/components/Header/Header.tsx
Labels: 💅 Waiting For Review

#6518 ocrvs-6517 Handle absence of informant section
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💥 Hot Fixes

#6477 ocrvs-6469 Allow optional middleName to be included in forms
  packages/client/codegen.yml
  packages/client/graphql.schema.json
  packages/client/src/search/queries.ts
  packages/client/src/utils/data-formatting.ts
  packages/client/src/utils/draftUtils.test.ts
  packages/client/src/utils/draftUtils.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/ViewRecord/query.ts
  packages/config/src/handlers/forms/validation.ts
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/search/type-resolvers.test.ts
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/migration/src/migrations/hearth/20240201123539-join-given-name.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
Labels: 🙋Question, 💅 Waiting For Review

#6533 Allow configurable location levels in config validator
  development-environment/dev.sh
  packages/config/src/handlers/forms/validation.ts
Labels: 💅 Waiting For Review

#6522 filter unassigned data with an additional action
  CHANGELOG.md
  packages/client/src/components/Notification.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/notification/actions.ts
  packages/client/src/notification/reducer.ts
  packages/client/src/tests/mock-graphql-responses.ts
  packages/client/src/workqueue/reducer.ts
Labels: ✅ Ready for merging

#6479 [State Transitions] add log time and note
  packages/config/src/handlers/forms/validation.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/register.ts
  packages/workflow/src/records/handler/validate.test.ts
  packages/workflow/src/records/handler/validate.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 👌 LGTM

#6456 [state-transitions] handle completing an incomplete declaration
  packages/client/src/transformer/index.ts
  packages/commons/src/fhir/encounter.ts
  packages/commons/src/fhir/observation.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/workflow/src/features/registration/handler.ts
Labels: 👌 LGTM

#6560 Update ---feature.md
  .github/ISSUE_TEMPLATE/---feature.md
Labels: 💅 Waiting For Review

#6549 Unassign fix
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/workqueue/reducer.ts
Labels: 👌 LGTM, 💥 Hot Fixes
