Repository opencrvs/opencrvs-core, pull requests merged in 2024-06, with the labels that each got.

#7006 fix: remove upload button when no supporting docs are configured
  CHANGELOG.md
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#7085 fix: only run prettier for staged graphql files
  packages/gateway/package.json
Labels: 💅 Waiting For Review

#7094 fix(ocrvs-7068): show requester, reason, comment, id verfied sections in action modal for action CORRECTED
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: 💅 Waiting For Review

#7096 fix: show correction rejection reason in history
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: 💅 Waiting For Review

#7081 Removed duplicateTrackingId check in createDuplicateTask method
  CHANGELOG.md
  packages/commons/src/fhir/extension.ts
  packages/workflow/src/records/fhir.ts
Labels: 👌 LGTM, ✅ Ready for merging

#7062 fix: update returned bundle of unassigned handler
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
Labels: ✅ Ready for merging

#7036 fix: Fix URL path by removing leading slash
  CHANGELOG.md
  packages/login/src/utils/authApi.ts
Labels: ✅ Ready for merging

#7066 Fix "Print and issue to groom|bride" is added to a different variable
  CHANGELOG.md
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/i18n/messages/form.ts
Labels: 👌 LGTM, ✅ Ready for merging

#7054 Revert "chore(deps): update dependency lint-staged to v15 (#6942)"
  package.json
  packages/components/package.json
  packages/data-seeder/package.json
  packages/documents/package.json
  packages/gateway/package.json
  packages/metrics/package.json
  packages/notification/package.json
  packages/search/package.json
  packages/workflow/package.json
  yarn.lock
Labels: ✅ Ready for merging

#6959 fix: update correction request task
  packages/client/src/views/ReviewCorrection/ReviewCorrection.tsx
  packages/workflow/src/records/__snapshots__/state-transitions.test.ts.snap
  packages/workflow/src/records/fhir.ts
Labels: 💅 Waiting For Review

#7084 Fix ocrvs-7060: In the certificate, the 'Place of Certification' shows wrong location
  CHANGELOG.md
  packages/client/src/views/PrintCertificate/usePrintableCertificate.ts
Labels: 💅 Waiting For Review

#7104 Cherry pick 7016, 7068
  CHANGELOG.md
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/config/src/config/routes.ts
  packages/config/src/handlers/dashboardQueries/dashboardQueries.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/configApi.ts
  packages/metrics/src/features/performance/viewRefresher.ts
Labels: 💅 Waiting For Review

#7019 [OCRVS 6971] Image compression reduction configuration
  CHANGELOG.md
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/i18n/messages/views/imageUpload.ts
  packages/client/src/utils/imageUtils.ts
  packages/client/src/views/Settings/ImageLoader.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
Labels: Docs

#7126 fix: memoization causing cache invalidation issues with locations
  packages/config/src/services/hearth.ts
Labels: 💅 Waiting For Review

#7125 fix: mongo aggregate query hitting the memory limit
  packages/search/src/features/records/service.ts
Labels: 💅 Waiting For Review

#7058 [OCRVS-6578] Enforce metabase default admin credentials to be changed
  CHANGELOG.md
  packages/dashboards/Dockerfile
  packages/dashboards/environment-configuration.sql
  packages/dashboards/package.json
  packages/dashboards/run-dev.sh
  packages/dashboards/run.sh
Labels: 👌 LGTM

#7127 chore: ignore braces vulnerability issue
  .trivyignore.yaml
Labels: 💅 Waiting For Review

#7025 fix: handle unauthorized error in gateway for no users found
  CHANGELOG.md
  packages/client/src/views/Settings/ChangeEmailModal/ChangeEmailModal.test.tsx
  packages/client/src/views/Settings/ChangeEmailModal/ChangeEmailView.tsx
  packages/client/src/views/Settings/ChangePhoneModal/ChangeNumberView.tsx
  packages/client/src/views/Settings/ChangePhoneModal/ChangePhoneModal.test.tsx
  packages/client/src/views/Settings/queries.ts
  packages/gateway/src/features/user/usersAPI.ts
Labels: 👌 LGTM

#7128 chore: update changelog to underline the reindexing change
  CHANGELOG.md
Labels: 💅 Waiting For Review

#7134 fix: resolve partOf refs to start with Location/
  packages/search/src/features/records/service.ts
Labels: 💅 Waiting For Review

#7067 Remove nonce check from MOSIP E-Signet
  packages/client/src/setupTests.ts
  packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.test.tsx
  packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.tsx
  packages/client/src/views/OIDPVerificationCallback/utils.ts
  packages/gateway/src/constants.ts
  packages/gateway/src/features/OIDPUserInfo/root-resolvers.test.ts
  packages/gateway/src/features/OIDPUserInfo/utils.ts
  packages/gateway/test/setupJest.ts
  packages/user-mgnt/src/constants.ts
Labels: ✅ Ready for merging

#7072 fix: update assignment check for unassign declaration
  CHANGELOG.md
  packages/client/src/components/interface/DownloadButton.test.tsx
  packages/client/src/components/interface/DownloadButton.tsx
  packages/commons/src/authentication.ts
  packages/workflow/src/features/task/fhir/utils.ts
  packages/workflow/src/features/user/utils.ts
  packages/workflow/src/records/handler/download.ts
  packages/workflow/src/records/handler/unassign.test.ts
  packages/workflow/src/records/handler/unassign.ts
  packages/workflow/src/records/user.ts
  packages/workflow/test/mocks/unassignedTask.ts
  packages/workflow/test/mocks/user.ts
Labels: ✅ Ready for merging

#7021 OCRVS-7005: Default to retrying the submission of records if something goes wrong in the backend
  packages/client/src/SubmissionController.ts
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/declarations/submissionMiddleware.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
Labels: 💅 Waiting For Review

#7150 refactor(metrics): only save leaf level locations
  packages/metrics/src/api.ts
  packages/metrics/src/configApi.ts
  packages/metrics/src/features/certifications/handler.ts
  packages/metrics/src/features/certifications/service.ts
  packages/metrics/src/features/corrections/handler.ts
  packages/metrics/src/features/corrections/service.ts
  packages/metrics/src/features/declarationsStarted/handler.test.ts
  packages/metrics/src/features/declarationsStarted/handler.ts
  packages/metrics/src/features/declarationsStarted/service.ts
  packages/metrics/src/features/getTimeLogged/handler.test.ts
  packages/metrics/src/features/getTimeLogged/utils.ts
  packages/metrics/src/features/metrics/handler.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/monthWiseEventEstimations/handler.test.ts
  packages/metrics/src/features/monthWiseEventEstimations/handler.ts
  packages/metrics/src/features/payments/handler.ts
  packages/metrics/src/features/payments/service.ts
  packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/totalMetrics/handler.ts
  packages/metrics/src/influxdb/client.ts
  packages/metrics/src/utils/queryHelper.ts
Labels: 👌 LGTM

#7185 chore(deps): upgrade jest & ts-jest to v27
  packages/auth/package.json
  packages/commons/package.json
  packages/components/package.json
  packages/config/package.json
  packages/documents/package.json
  packages/gateway/package.json
  packages/metrics/package.json
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/webhooks/package.json
  packages/workflow/package.json
  yarn.lock
Labels: ✅ Ready for merging

#7190 chore: handle `ws` security error
  .trivyignore.yaml
Labels: 💅 Waiting For Review

#7155 chore: deprecate admin UI menu items
  CHANGELOG.md
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/components/interface/Navigation.tsx
Labels: 💅 Waiting For Review, :cherries: To cherry pick

#7157 fix: certificate overflowing on the preview screen
  CHANGELOG.md
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
Labels: 💅 Waiting For Review, :cherries: To cherry pick

#7192 chore(v1.5.0): handle `ws` security error
  .trivyignore.yaml
Labels: ✅ Ready for merging

#7187 Update NavigationItem.tsx
  packages/components/src/SideNavigation/NavigationItem.tsx
Labels: 💅 Waiting For Review

#7146 fix: added missing 'requesterOther' params in client queries
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/death/queries.ts
Labels: ✅ Ready for merging

#7189 fix: allow searching with spouse, deceased and informant NID's
  CHANGELOG.md
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
  packages/commons/src/fhir/patient.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/search/src/features/search/handler.ts
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.ts
  packages/workflow/src/features/events/utils.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/validations.ts
Labels: 💅 Waiting For Review

#7202 fix: handle empty partOf
  packages/migration/src/migrations/hearth/20240508142533-location-view-with-plain-ids.ts
  packages/search/src/features/records/service.ts
Labels: ✅ Ready for merging

#7152 feat: "preview" handlebar for differentiating preview & print
  CHANGELOG.md
  packages/client/src/forms/register/mappings/query/registration-mappings.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/pdfRenderer/index.ts
  packages/client/src/pdfRenderer/transformer/fieldTransformer.test.ts
  packages/client/src/pdfRenderer/transformer/fieldTransformer.ts
  packages/client/src/pdfRenderer/transformer/index.ts
  packages/client/src/pdfRenderer/transformer/offlineTransformer.test.ts
  packages/client/src/pdfRenderer/transformer/offlineTransformer.ts
  packages/client/src/pdfRenderer/transformer/types.ts
  packages/client/src/pdfRenderer/transformer/userTransformer.test.ts
  packages/client/src/pdfRenderer/transformer/userTransformer.ts
  packages/client/src/pdfRenderer/transformer/utils.ts
  packages/client/src/tests/templates.json
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/PrintCertificate/usePrintableCertificate.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
Labels: ✅ Ready for merging

#7098 fix: amend date of certification for verifying certificate
  packages/client/src/i18n/messages/views/verifyCertificate.ts
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
  packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts
Labels: ✅ Ready for merging

#7122 fix: removed 'declarationJurisdictionId' while calculating AdvancedSearchForm validity
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/search/advancedSearch/utils.test.ts
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/components/src/SearchTool/SearchTool.tsx
Labels: 🏥 Failing Tests

#7117 fix: allow correction requested reg status for search request
  CHANGELOG.md
  packages/user-mgnt/src/features/userSearchRecord/handler.ts
Labels: ✅ Ready for merging

#7212 fix: sort not working in performance on completenessRate
  packages/client/src/views/SysAdmin/Performance/reports/completenessRates/CompletenessDataTable.tsx
Labels: 👌 LGTM

#7093 fix: delete certificate properties of payload for correction
  CHANGELOG.md
  packages/client/src/views/PrintCertificate/usePrintableCertificate.ts
Labels: ✅ Ready for merging

#7124 fix: amend download button on click functionality
  packages/client/src/components/interface/DownloadButton.tsx
Labels: ✅ Ready for merging

#7101 Fix: simplify and correct country data transformation logic
  CHANGELOG.md
  packages/client/src/forms/register/mappings/query/field-mappings.ts
Labels: ✅ Ready for merging

#7204 feat: log and mask the notification details
  packages/commons/src/logger.ts
  packages/notification/src/features/sms/service.ts
Labels: 💅 Waiting For Review

#7232 fix: remove --quiet from nodemon to see restarts
  packages/auth/package.json
  packages/components/package.json
  packages/config/package.json
  packages/documents/package.json
  packages/gateway/package.json
  packages/metrics/package.json
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/webhooks/package.json
  packages/workflow/package.json
Labels: ✅ Ready for merging

#7241 Enforce token for seeding roles and users
  packages/data-seeder/src/roles.ts
  packages/data-seeder/src/users.ts
Labels: 💅 Waiting For Review

#7248 fix: sort not working in performance on `totalRegistered`, `registeredWithinTargetd`, `estimated`
  packages/client/src/views/SysAdmin/Performance/reports/completenessRates/CompletenessDataTable.tsx
Labels: 👌 LGTM, ✅ Ready for merging

#7253 feat: reindex elasticsearch after running migrations
  packages/migration/package.json
  packages/migration/run-migrations.sh
  packages/migration/src/migrations/hearth/20240527130750-reindex-elasticsearch.ts
  packages/migration/src/reindex-search.ts
  packages/migration/src/utils/elasticsearch-helper.ts
  packages/search/src/config/routes.ts
  packages/search/src/features/reindex/handler.ts
  packages/search/src/features/reindex/reindex.ts
  yarn.lock
Labels: 💅 Waiting For Review

#7250 fix: 7205: Heading missing in mobile view
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/Performance/RegistrationsList.tsx
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: 💅 Waiting For Review

#7262 refactor: when reindexing, remove all indices except the latest one
  packages/migration/src/migrations/hearth/20240527130750-reindex-elasticsearch.ts
  packages/search/src/features/reindex/prune.ts
  packages/search/src/features/reindex/reindex.ts
Labels: 💅 Waiting For Review

#7265 fix: amend download button on click functionality
  packages/client/src/components/interface/DownloadButton.tsx
Labels: 💅 Waiting For Review

#7277 fix: increase rate limit on team searches
  packages/gateway/src/features/user/root-resolvers.ts
Labels: 💅 Waiting For Review

#7282 fix: storybook
  packages/components/.storybook/main.ts
  packages/components/package.json
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/Divider/Divider.stories.tsx
  packages/components/src/SideNavigation/LeftNavigation.stories.tsx
  packages/components/stories/colors.stories.mdx
  packages/components/stories/iconography.stories.mdx
  packages/components/stories/intro.stories.mdx
  packages/components/stories/releases.stories.mdx
  packages/components/stories/typography.stories.mdx
  yarn.lock
Labels: 💅 Waiting For Review
