Repository opencrvs/opencrvs-core, pull requests merged in 2024-12, with the labels that each got.

#7972 #7915 - Allow 'QuestionnaireResponse' resource type in the event notification APIs
  packages/gateway/src/features/eventNotification/eventNotificationHandler.ts
Labels: ✅ Ready for merging

#8108 feat: disable back button on a conditional expression
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 🚀 Ready to deploy

#8122 feat(v1.6.2): Add 6th level support for addresses
  packages/client/src/forms/register/mappings/mutation/field-mappings.ts
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/profile/mutations.ts
  packages/client/src/search/advancedSearch/reducer.ts
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/locationUtils.ts
  packages/config/src/handlers/forms/validation.ts
  packages/gateway/src/features/bookmarkAdvancedSearch/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/search/deprecation-support.ts
  packages/search/src/features/search/types.ts
  packages/user-mgnt/src/features/userSearchRecord/handler.ts
  packages/user-mgnt/src/model/user.ts
Labels: 🚀 Ready to deploy

#7947 fix: 'UserelationSomeoneElse' translation for Other option 4 form
  CHANGELOG.md
  packages/client/src/i18n/messages/form.ts
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
Labels: ✅ Ready for merging

#8120 feat(events-v2): form validation
  packages/client/src/App.tsx
  packages/client/src/v2-events/features/events/EventFormWizard.tsx
  packages/client/src/v2-events/features/events/EventSelection.tsx
  packages/client/src/v2-events/features/events/registered-fields/DateField.tsx
  packages/client/src/v2-events/features/events/registered-fields/RadioGroup.tsx
  packages/client/src/v2-events/features/events/registered-fields/TextField.tsx
  packages/client/src/v2-events/features/events/useEventConfiguration.ts
  packages/client/src/v2-events/features/events/useEventForm.ts
  packages/client/src/v2-events/features/events/useEventFormNavigation.tsx
  packages/client/src/v2-events/hooks/useModal.ts
  packages/client/src/v2-events/hooks/usePagination.ts
  packages/client/src/v2-events/routes/index.ts
  packages/commons/src/events/FieldConfig.ts
  packages/components/src/FormWizard/FormFieldRenderer.tsx
  packages/components/src/FormWizard/FormWizard.tsx
  packages/components/src/FormWizard/index.ts
Labels: 🚀 Ready to deploy

#8112 fix: Stops local sys admin from creating national level staff
  CHANGELOG.md
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/client/src/views/UserAudit/UserAudit.tsx
  packages/gateway/src/features/role/root-resolvers.test.ts
  packages/gateway/src/features/role/root-resolvers.ts
  packages/gateway/src/features/role/utils.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/utils/index.ts
Labels: 💅 Waiting For Review

#8164 Events V2: Create events
  .github/workflows/lint-and-test.yml
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/utils/timeoutLink.test.ts
  packages/client/src/v2-events/.eslintrc.js
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/conditionals.ts
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/components/forms/validation.ts
  packages/client/src/v2-events/features/debug/debug.tsx
  packages/client/src/v2-events/features/events/EventFormWizard.tsx
  packages/client/src/v2-events/features/events/EventSelection.tsx
  packages/client/src/v2-events/features/events/useEventConfiguration.ts
  packages/client/src/v2-events/features/events/useEventFormNavigation.tsx
  packages/client/src/v2-events/features/events/useEvents.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.test.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/hooks/usePagination.ts
  packages/client/src/v2-events/routes/index.ts
  packages/client/src/v2-events/trpc.tsx
  packages/client/tsconfig.json
  packages/commons/src/events/ActionDocument.ts
  packages/commons/src/events/ActionInput.ts
  packages/commons/src/events/EventDocument.ts
  packages/commons/src/events/EventIndex.ts
  packages/commons/src/events/EventInput.ts
  packages/commons/src/events/index.ts
  packages/components/src/FormWizard/FormWizard.tsx
  packages/events/src/router.ts
  packages/events/src/schema/index.ts
  packages/events/src/service/events.ts
  packages/events/src/service/indexing/indexing.ts
  packages/gateway/src/features/eventNotification/eventNotificationHandler.ts
  packages/gateway/src/v2-events/event-config/routes.ts
  packages/gateway/src/v2-events/events/type-resolvers.ts
  yarn.lock
Labels: 🚀 Ready to deploy

#8012 feat(user-scopes): control who can see organisation views
  packages/client/graphql.schema.json
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/components/interface/WorkQueueTabs.tsx
  packages/client/src/hooks/useAuthorization.ts
  packages/client/src/hooks/useNavigation.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/locationUtils.test.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/Organisation/AdministrativeLevels.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/StatusWiseDeclarationCountView.test.tsx
  packages/client/src/views/SysAdmin/Performance/utils.test.ts
  packages/client/src/views/SysAdmin/Performance/utils.tsx
  packages/commons/src/scopes.ts
Labels: 💅 Waiting For Review

#8105 feat(user-scopes): control read/create/update user using scopes
  packages/client/src/App.tsx
  packages/client/src/components/Header/Header.tsx
  packages/client/src/components/LocationPicker.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/hooks/useAuthorization.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/util.tsx
  packages/client/src/user/queries.ts
  packages/client/src/user/userReducer.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/Organisation/AdministrativeLevels.test.tsx
  packages/client/src/views/Organisation/AdministrativeLevels.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/UserAudit/UserAudit.test.tsx
  packages/client/src/views/UserAudit/UserAudit.tsx
  packages/commons/src/scopes.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/notification/src/config/routes.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/searchUsers/handler.test.ts
Labels: ✅ Ready for merging

#8034 feat: `upsertRegistrationIdentifier` gateway endpoint
  CHANGELOG.md
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/records/handler/upsert-identifiers.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 🚀 Ready to deploy

#7938 chore: Cleaned up the national ID integration code
  packages/auth/src/constants.ts
  packages/auth/src/features/oauthToken/client-credentials.ts
  packages/client/graphql.schema.json
  packages/client/src/i18n/messages/views/integrations.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/client/src/views/SysAdmin/Config/Systems/useSystems.ts
  packages/gateway/src/features/systems/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/webhooks/src/features/event/handler.ts
  packages/webhooks/src/features/event/service.test.ts
  packages/webhooks/src/features/event/service.ts
  packages/webhooks/src/features/manage/handler.ts
Labels: 👌 LGTM, ✅ Ready for merging, 🚀 Ready to deploy

#8128 chore: deprecate validator-api & age-verification-api
  CHANGELOG.md
  packages/auth/src/constants.ts
  packages/auth/src/features/oauthToken/client-credentials.ts
  packages/commons/src/authentication.ts
Labels: 🚀 Ready to deploy

#8161 feat: check environment variables are set before services start
  packages/documents/package.json
  packages/documents/src/constants.ts
  packages/metrics/package.json
  packages/metrics/src/constants.ts
  packages/metrics/src/features/metrics/constants.ts
  packages/search/package.json
  packages/search/src/constants.ts
  packages/search/src/environment.ts
  packages/workflow/package.json
  packages/workflow/src/constants.ts
  packages/workflow/src/environment.ts
  yarn.lock
Labels: 🚀 Ready to deploy

#8150 feat(user-scopes): address to-do items
  packages/client/src/components/Header/Header.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/hooks/useAuthorization.ts
  packages/client/src/utils/persistence/persistenceMiddleware.ts
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
Labels: ✅ Ready for merging

#8089 fix: exclude `bookmarkName` from `advancedSearchParams`
  packages/client/src/views/AdvancedSearch/SaveBookmarkModal.tsx
Labels: ✅ Ready for merging

#8221 Events linter
  packages/client/src/utils.ts
  packages/client/src/v2-events/.eslintrc.js
  packages/client/src/v2-events/components/IconWithName.tsx
  packages/client/src/v2-events/components/LoadingIndicator.tsx
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/components/forms/validation.ts
  packages/client/src/v2-events/features/debug/debug.tsx
  packages/client/src/v2-events/features/events/EventSelection.tsx
  packages/client/src/v2-events/features/events/actions/declare/Declare.tsx
  packages/client/src/v2-events/features/events/actions/declare/Review.tsx
  packages/client/src/v2-events/features/events/actions/register/Register.tsx
  packages/client/src/v2-events/features/events/components/FormHeader.tsx
  packages/client/src/v2-events/features/events/components/Preview.tsx
  packages/client/src/v2-events/features/events/registered-fields/DateField.tsx
  packages/client/src/v2-events/features/events/registered-fields/Paragraph.tsx
  packages/client/src/v2-events/features/events/registered-fields/RadioGroup.tsx
  packages/client/src/v2-events/features/events/registered-fields/TextField.tsx
  packages/client/src/v2-events/features/events/useEventConfiguration.ts
  packages/client/src/v2-events/features/events/useEventFormData.ts
  packages/client/src/v2-events/features/events/useEventFormNavigation.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.test.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventSummary.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/features/workqueues/components/ContentWrapper.tsx
  packages/client/src/v2-events/features/workqueues/index.tsx
  packages/client/src/v2-events/features/workqueues/utils.tsx
  packages/client/src/v2-events/hooks/useModal.ts
  packages/client/src/v2-events/hooks/usePagination.ts
  packages/client/src/v2-events/index.ts
  packages/client/src/v2-events/messages/constants.ts
  packages/client/src/v2-events/routes/config.tsx
  packages/client/src/v2-events/trpc.tsx
Labels: 🚀 Ready to deploy

#8045 fix: Added types for anys
  packages/client/src/components/form/FetchButton.tsx
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/PrintRecord/Body.tsx
  packages/client/src/views/Settings/PasswordChangeModal.tsx
  packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
  packages/client/src/views/SysAdmin/Vsexports/VSExport.tsx
Labels: 🔧Waiting for fixes

#8212 Chore/upgrade login to react router dom 6
  packages/auth/src/features/authenticate/service.ts
  packages/client/src/App.test.tsx
  packages/login/package.json
  packages/login/src/App.tsx
  packages/login/src/common/WithRouterProps.tsx
  packages/login/src/i18n/components/LanguageSelect.tsx
  packages/login/src/index.tsx
  packages/login/src/login/actions.ts
  packages/login/src/login/index.test.ts
  packages/login/src/login/reducer.ts
  packages/login/src/store.ts
  packages/login/src/tests/util.tsx
  packages/login/src/views/ResetCredentialsForm/AuthDetailsVerificationForm.test.tsx
  packages/login/src/views/ResetCredentialsForm/AuthDetailsVerificationForm.tsx
  packages/login/src/views/ResetCredentialsForm/ForgottenItemForm.test.tsx
  packages/login/src/views/ResetCredentialsForm/ForgottenItemForm.tsx
  packages/login/src/views/ResetCredentialsForm/RecoveryCodeEntryForm.tsx
  packages/login/src/views/ResetCredentialsForm/ResetCredentialsSuccessPage.test.tsx
  packages/login/src/views/ResetCredentialsForm/ResetCredentialsSuccessPage.tsx
  packages/login/src/views/ResetCredentialsForm/SecurityQuestionForm.tsx
  packages/login/src/views/ResetCredentialsForm/UpdatePasswordForm.test.tsx
  packages/login/src/views/ResetCredentialsForm/UpdatePasswordForm.tsx
  packages/login/src/views/StepOne/StepOneContainer.tsx
  packages/login/src/views/StepOne/stepOneContainer.test.tsx
  yarn.lock
Labels: 🚀 Ready to deploy

#8193 fix: stop revalidating with stale values
  packages/client/src/components/form/FormFieldGenerator.tsx
Labels: 💅 Waiting For Review

#8084 Ocrvs 6909
  packages/client/src/hooks/useAuthorization.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.test.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/gateway/src/features/search/root-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/utils.ts
  packages/gateway/src/features/user/utils/index.ts
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/types.ts
  packages/search/src/features/search/utils.test.ts
  packages/search/src/features/search/utils.ts
Labels: 💅 Waiting For Review

#8263 feat: store `createdAtLocation` for each action based on users primary office
  packages/commons/src/events/ActionDocument.ts
  packages/events/src/router/router.ts
  packages/events/src/service/events.ts
Labels: 💅 Waiting For Review
