Repository opencrvs/opencrvs-core, pull requests merged in 2024-11, with the labels that each got.

#7799 refactor: Converted the PerformanceHome to function component.
  packages/client/src/views/OfficeHome/LoadingIndicator.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
Labels: 💅 Waiting For Review

#7888 feat: handle foreignObject in svg to support html
  CHANGELOG.md
  packages/client/package.json
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 👌 LGTM

#7865 (User roles) Remove legacy scopes from client
  packages/auth/src/features/refresh/handler.test.ts
  packages/auth/src/features/verifyCode/handler.test.ts
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/components/interface/Navigation.test.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/hooks/useNavigation.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RecordAudit/ActionMenu.test.tsx
  packages/client/src/views/RecordAudit/ActionMenu.tsx
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.test.tsx
  packages/client/src/views/RegisterForm/ReviewForm.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/workqueue/reducer.ts
  packages/commons/src/authentication.ts
  packages/commons/src/scopes.ts
Labels: 💅 Waiting For Review

#7895 chore: amend commons scopes
  packages/commons/src/authentication.ts
  packages/commons/src/scopes.ts
Labels: ✅ Ready for merging

#7894 fix: amend auth scopes
  packages/auth/src/features/authenticateSuperUser/handler.ts
Labels: ✅ Ready for merging

#7891 Refactor/forgotten item component to functional
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/login/src/views/ResetCredentialsForm/ForgottenItemForm.tsx
  packages/login/src/views/ResetCredentialsForm/SecurityQuestionForm.tsx
Labels: 👌 LGTM, ✅ Ready for merging

#7897 chore: amend legacy scopes of config
  packages/config/src/config/routes.ts
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/config/src/handlers/certificate/certificateHandler.test.ts
  packages/config/src/handlers/certificate/certificateHandler.ts
Labels: ✅ Ready for merging

#7900 chore: amend metrics changes with scopes
  packages/metrics/src/config/routes.ts
  packages/metrics/src/features/audit/handler.ts
  packages/metrics/src/features/metrics/handler.test.ts
  packages/metrics/src/features/registration/handler.ts
  packages/metrics/src/features/registration/index.ts
  packages/metrics/src/features/registration/pointGenerator.test.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/utils/authUtils.ts
Labels: ✅ Ready for merging

#7932 Require PRs to have "🚀 Ready to deploy" label to be deployed
  .github/workflows/deploy-to-feature-environment.yml
  .github/workflows/on-label-added-for-pr.yml
  .github/workflows/trigger-e2e.yml
Labels: 🚀 Ready to deploy

#7893 fix: remove redundant client queries
  CHANGELOG.md
  packages/client/graphql.schema.json
  packages/client/src/declarations/index.test.ts
  packages/client/src/profile/queries.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/tests/util.tsx
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/OfficeHome/inExternalValidation/inExternalValidationTab.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.init.test.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/Unlock/ForgotPIN.test.tsx
Labels: ✅ Ready for merging

#7905 chore: amend workflow changes with scopes
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/records/handler/archive.test.ts
  packages/workflow/src/records/handler/archive.ts
  packages/workflow/src/records/handler/certify.test.ts
  packages/workflow/src/records/handler/certify.ts
  packages/workflow/src/records/handler/correction/approve.ts
  packages/workflow/src/records/handler/correction/make-correction.ts
  packages/workflow/src/records/handler/correction/reject.ts
  packages/workflow/src/records/handler/correction/request.ts
  packages/workflow/src/records/handler/create.test.ts
  packages/workflow/src/records/handler/download.test.ts
  packages/workflow/src/records/handler/download.ts
  packages/workflow/src/records/handler/issue.test.ts
  packages/workflow/src/records/handler/issue.ts
  packages/workflow/src/records/handler/register.test.ts
  packages/workflow/src/records/handler/register.ts
  packages/workflow/src/records/handler/reinstate.test.ts
  packages/workflow/src/records/handler/reinstate.ts
  packages/workflow/src/records/handler/reject.test.ts
  packages/workflow/src/records/handler/reject.ts
  packages/workflow/src/records/handler/update.test.ts
  packages/workflow/src/records/handler/update.ts
  packages/workflow/src/records/handler/validate.test.ts
  packages/workflow/src/records/handler/validate.ts
  packages/workflow/src/states.ts
  packages/workflow/src/utils/auth-utils.ts
  packages/workflow/test/mocks/user.ts
Labels: 💅 Waiting For Review

#7917 fix: include all child location in `getStatusWiseRegistrationCountHandler`
  packages/search/src/features/search/handler.test.ts
  packages/search/src/features/search/handler.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#7949 chore: update services with user scopes
  packages/gateway/src/features/bookmarkAdvancedSearch/root-resolvers.test.ts
  packages/gateway/src/features/bookmarkAdvancedSearch/root-resolvers.ts
  packages/notification/src/config/routes.ts
  packages/notification/src/features/sms/user-handler.test.ts
  packages/search/src/config/routes.ts
  packages/search/src/features/search/handler.test.ts
  packages/search/src/test/utils.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/features/activateUser/handler.test.ts
  packages/user-mgnt/src/features/changeAvatar/handler.test.ts
  packages/user-mgnt/src/features/changeEmail/handler.test.ts
  packages/user-mgnt/src/features/changePassword/handler.test.ts
  packages/user-mgnt/src/features/changePhone/handler.test.ts
  packages/user-mgnt/src/features/createUser/handler.test.ts
  packages/user-mgnt/src/features/getUser/handler.test.ts
  packages/user-mgnt/src/features/getUserMobile/handler.test.ts
  packages/user-mgnt/src/features/resendInvite/handler.test.ts
  packages/user-mgnt/src/features/resetPassword/handler.test.ts
  packages/user-mgnt/src/features/searchUsers/handler.test.ts
  packages/user-mgnt/src/features/system/handler.test.ts
  packages/user-mgnt/src/features/updateUser/handler.test.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/features/userAudit/handler.test.ts
  packages/user-mgnt/src/features/userSearchRecord/handler.test.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.test.ts
  packages/webhooks/src/features/manage/handler.test.ts
Labels: 👨‍👩‍👧 User roles, 🚀 Ready to deploy

#7925 feat: Created confirmRegistration, rejectRegistration GraphQL-endpoints
  docker-compose.dev.yml
  packages/commons/src/authentication.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/records/handler/register.test.ts
  packages/workflow/src/records/state-transitions.ts
  sequence-diagrams/backend/create-birth-registration-registrar.md
Labels: 💅 Waiting For Review, 🚀 Ready to deploy, MOSIP

#7879 chore: clean up MOSIP code
  .github/workflows/lint-and-test.yml
  packages/client/graphql.schema.json
  packages/client/src/forms/register/mappings/event-specific-fields/birth/mutation/registration-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/birth/query/registration-mappings.ts
  packages/client/src/forms/register/mappings/mutation/field-mappings.ts
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/tests/forms.json
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.test.tsx
  packages/client/src/views/ViewRecord/ViewRecord.test.tsx
  packages/client/src/views/ViewRecord/query.ts
  packages/commons/src/fhir/patient.ts
  packages/commons/src/fhir/task.ts
  packages/commons/src/fhir/transformers/index.ts
  packages/commons/src/fhir/transformers/input.ts
  packages/gateway/src/features/registration/__snapshots__/type-resolvers.test.ts.snap
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/features/search/utils.ts
  packages/workflow/src/__mocks__/constants.ts
  packages/workflow/src/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/test/utils.ts
Labels: 🚀 Ready to deploy

#7968 fix: include all child location in `getStatusWiseRegistrationCountHandler` (#7917)
  packages/search/src/features/search/handler.test.ts
  packages/search/src/features/search/handler.ts
Labels: 💅 Waiting For Review

#7995 fix(practitioner-role-code): create migrations for unifying role format
  packages/migration/src/migrations/hearth/20241114142053-update-practitioner-role-type-to-string-json.ts
  packages/migration/src/migrations/hearth/20241114153937-update-practitioner-role-history-type-to-string-json.ts
  packages/migration/src/utils/role-helper.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#8002 Events v2: Add some first structure for new events
  packages/client/src/App.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/v2-events/.eslintrc.js
  packages/client/src/v2-events/index.ts
  packages/client/src/v2-events/routes.ts
  packages/client/src/v2-events/useEvents.ts
  packages/client/src/v2-events/workqueues/index.tsx
  packages/events/.eslintrc.js
  packages/events/.gitignore
  packages/events/Dockerfile
  packages/events/Dockerfile.dockerignore
  packages/events/package.json
  packages/events/src/environment.ts
  packages/events/src/index.test.ts
  packages/events/src/index.ts
  packages/events/src/router.ts
  packages/events/src/service/events.ts
  packages/events/src/storage/__mocks__/mongodb.ts
  packages/events/src/storage/index.ts
  packages/events/src/storage/mongodb.ts
  packages/events/tsconfig.json
  packages/events/vitest.config.ts
  packages/gateway/src/v2-events/.eslintrc.js
  yarn.lock
Labels: 🚀 Ready to deploy

#7964 Feat/opencrvs toolkit
  .github/workflows/publish-toolkit-to-npm.yml
  license-config.json
  packages/toolkit/.gitignore
  packages/toolkit/.npmignore
  packages/toolkit/README.md
  packages/toolkit/package.json
  packages/toolkit/src/index.ts
  packages/toolkit/tsconfig.json
Labels: 💅 Waiting For Review

#7629 Refactoring of class components to functional components
  packages/client/src/components/charts/RegRatesLineChart.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/client/src/views/UserAudit/UserAuditHistory.tsx
Labels: ✅ Ready for merging

#7934 refactor: AuthDetailsVerificationComponent to functional component
  packages/login/src/views/ResetCredentialsForm/AuthDetailsVerificationForm.tsx
Labels: 💅 Waiting For Review

#8046 build: add entry for events service
  docker-compose.yml
Labels: 🚀 Ready to deploy

#8050 chore: add vs export scope in query
  packages/gateway/src/features/metrics/root-resolvers.ts
Labels: 💅 Waiting For Review

#8035 fix(v1.6.1): Add missing "Issued" status to external search results
  packages/search/src/features/search/utils.ts
Labels: 🚀 Ready to deploy

#7993 (User roles) fix: update mock url object of auth
  docker-compose.yml
  packages/auth/src/tests/util.ts
  packages/client/src/App.tsx
  packages/client/src/views/PrintCertificate/usePrintableCertificate.ts
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 🏥 Failing Tests

#8044 feat(fetch-button): disable continue button conditionally on a loading value
  CHANGELOG.md
  packages/client/src/forms/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#7933 Incorrect Fee Display on Performance Page for Certification and Correction Sequence.
  CHANGELOG.md
  packages/metrics/src/api.ts
  packages/metrics/src/features/registration/fhirUtils.ts
  packages/metrics/src/features/registration/pointGenerator.ts
  packages/metrics/src/features/registration/testUtils.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 🚀 Ready to deploy

#8041 Fix: advanced search pills
  packages/client/src/search/advancedSearch/utils.ts
Labels: 🚀 Ready to deploy

#7733 refactor: CreateNewUserComponent from class to functional.
  packages/client/src/App.tsx
  packages/client/src/components/TransitionWrapper.tsx
  packages/client/src/utils/constants.ts
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
Labels: ✅ Ready for merging

#7970 (User roles) Remove retrieval functionality
  CHANGELOG.md
  packages/client/src/components/interface/DownloadButton.test.tsx
  packages/client/src/components/interface/DownloadButton.tsx
  packages/client/src/declarations/utils.ts
  packages/client/src/hooks/useAuthorization.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/RecordAudit/ActionMenu.test.tsx
  packages/client/src/views/RecordAudit/ActionMenu.tsx
  packages/client/src/views/RecordAudit/utils.ts
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/commons/src/fhir/extension.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/download.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#7863 Simplifying gateways' return values
  packages/gateway/src/features/bookmarkAdvancedSearch/root-resolvers.ts
  packages/gateway/src/features/metrics/root-resolvers.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/features/search/utils.ts
  packages/gateway/src/features/systems/root-resolvers.ts
  packages/gateway/src/features/user/root-resolvers.ts
Labels: ✅ Ready for merging

#8086 fix: build `@opencrvs/toolkit` with `--format=cjs` option
  packages/toolkit/package.json
Labels: 💅 Waiting For Review

#8090 fix: add comment for new release scope
  packages/commons/src/scopes.ts
Labels: 🚀 Ready to deploy
