Repository opencrvs/opencrvs-core, pull requests merged in 2024-04, with the labels that each got.

#6706 Fix duplicate comparison page
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
  packages/workflow/src/records/handler/view.ts
Labels: 💅 Waiting For Review

#6718 Fix issuing a record and record audit history modal data
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/workqueue/reducer.ts
  packages/gateway/src/features/fhir/FHIRAPI.ts
  packages/metrics/src/features/registration/handler.ts
Labels: 💅 Waiting For Review

#6741 fix(search): update status mapping constant
  packages/search/src/elasticsearch/utils.ts
Labels: 👌 LGTM

#6739 fix: format event dates as localDates
  CHANGELOG.md
  packages/client/codegen.ts
  packages/client/codegen.yml
  packages/client/graphql.schema.json
  packages/client/package.json
  packages/client/src/forms/register/mappings/event-specific-fields/death/query/deceased-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/marriage/query/event-mappings.ts
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/utils/date-formatting.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/OfficeHome/inExternalValidation/InExternalValidationTab.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
  packages/client/tsconfig.json
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 👌 LGTM

#6708 Fix event location property in search
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/birth/composition.test.ts
  packages/search/src/features/registration/birth/handler.test.ts
  packages/search/src/features/registration/birth/noParents.test.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/handler.test.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
Labels: 💅 Waiting For Review

#6600 [OCRVS-6410] Mass email users
  packages/client/src/App.tsx
  packages/client/src/components/Notification.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/i18n/messages/constants.ts
  packages/client/src/i18n/messages/views/config.ts
  packages/client/src/i18n/messages/views/navigation.ts
  packages/client/src/i18n/messages/views/notifications.ts
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/notification/actions.ts
  packages/client/src/notification/reducer.ts
  packages/client/src/views/SysAdmin/Communications/AllUserEmail/AllUserEmail.tsx
  packages/client/src/views/SysAdmin/Communications/AllUserEmail/queries.ts
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/InformantSMSNotification.test.tsx
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/InformantSMSNotification.tsx
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/mutations.ts
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/queries.ts
  packages/gateway/package.json
  packages/gateway/src/config/plugins.ts
  packages/gateway/src/features/notification/root-resolvers.ts
  packages/gateway/src/features/notification/schema.graphql
  packages/gateway/src/features/notification/service.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/typings/hapi-sentry.d.ts
  packages/notification/package.json
  packages/notification/src/config/routes.ts
  packages/notification/src/constants.ts
  packages/notification/src/database.test.ts
  packages/notification/src/database.ts
  packages/notification/src/features/email/all-user-handler.ts
  packages/notification/src/features/email/service..ts
  packages/notification/src/features/inProgress/handler.ts
  packages/notification/src/features/readyForReview/handler.ts
  packages/notification/src/features/register/handler.ts
  packages/notification/src/features/sms/birth-handler.ts
  packages/notification/src/features/sms/correction.ts
  packages/notification/src/features/sms/death-handler.ts
  packages/notification/src/features/sms/service.test.ts
  packages/notification/src/features/sms/service.ts
  packages/notification/src/features/sms/user-handler.ts
  packages/notification/src/features/sms/utils.ts
  packages/notification/src/model/notificationQueue.ts
  packages/notification/src/server.ts
  yarn.lock
Labels: 👌 LGTM

#6726 Converted the scrollToTop component to the function
  packages/client/src/components/ScrollToTop.tsx
  packages/client/src/components/SessionExpireConfirmation.tsx
  packages/client/src/components/StyledErrorBoundary.tsx
Labels: 💅 Waiting For Review, 👌 LGTM

#6756 deps: remove openhim
  CHANGELOG.md
  development-environment/clear-all-data.sh
  development-environment/dev.sh
  docker-compose.deps.yml
  infrastructure/openhim-console-config.json
  packages/scheduler/crontab
  packages/scheduler/jobs/clearOpenHIMTransactions.sh
  setup.sh
Labels: 💅 Waiting For Review

#6755 fix: format event dates as localDates (v1.3.4)
  CHANGELOG.md
  packages/client/codegen.ts
  packages/client/codegen.yml
  packages/client/graphql.schema.json
  packages/client/package.json
  packages/client/src/forms/register/mappings/event-specific-fields/death/query/deceased-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/marriage/query/event-mappings.ts
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/utils/date-formatting.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/OfficeHome/inExternalValidation/InExternalValidationTab.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
  packages/client/tsconfig.json
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💥 Hot Fixes

#6754 fix: format event dates as localDates (v1.4.2)
  CHANGELOG.md
  packages/client/codegen.ts
  packages/client/codegen.yml
  packages/client/graphql.schema.json
  packages/client/package.json
  packages/client/src/forms/register/mappings/event-specific-fields/death/query/deceased-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/marriage/query/event-mappings.ts
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/utils/date-formatting.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/OfficeHome/inExternalValidation/InExternalValidationTab.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/RecordAudit/DeclarationInfo.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
  packages/client/tsconfig.json
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/graphql/common.graphql
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
Labels: 💥 Hot Fixes

#6710 fix ui so cta content block is seperate from record
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#6733 ocrvs-6678 fix advanced search result any status tag
  CHANGELOG.md
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
Labels: 👌 LGTM

#6759 fix(gateway): update user information payload
  CHANGELOG.md
  packages/gateway/src/features/user/root-resolvers.ts
Labels: 💅 Waiting For Review

#6834 Fix: ocrvs-6224 Show correct record option in certificate preview page when trying to print by RA
  CHANGELOG.md
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
Labels: 💅 Waiting For Review

#6856 [HOTFIX] Implementation changes due schema changes
  packages/notification/src/features/email/service..ts
Labels: 💥 Hot Fixes

#6867 refactor: move ESLint --fix run on staged files instead of every time in pre-commit
  packages/auth/package.json
  packages/client/package.json
  packages/commons/package.json
  packages/components/package.json
  packages/config/package.json
  packages/data-seeder/package.json
  packages/documents/package.json
  packages/gateway/package.json
  packages/login/package.json
  packages/metrics/package.json
  packages/migration/package.json
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/webhooks/package.json
  packages/workflow/package.json
  yarn.lock
Labels: 💅 Waiting For Review

#6872 [OCRVS-6179] Fix correction bug
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/workflow/src/records/fhir.ts
Labels: 👌 LGTM

#6868 feat: render certificate using svg's dimensions
  CHANGELOG.md
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/PrintCertificate/usePrintableCertificate.ts
Labels: 👌 LGTM

#6866 [ocrvs-6221] Fix bug causing a task without a 'reason' field ending up to search & metrics
  packages/commons/src/fhir/task.ts
  packages/commons/src/record.ts
  packages/workflow/src/features/correction/routes.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 👌 LGTM

#6880 fix: validate date string before converting to LocalDate
  CHANGELOG.md
  packages/client/src/forms/register/mappings/event-specific-fields/death/query/deceased-mappings.ts
Labels: 💅 Waiting For Review

#6878 refactor: class converts to function
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/components/src/InputField/ValidIndicator.tsx
Labels: ✅ Ready for merging

#6800 [OCRVS-5781] Fix search result declaration record audit unassign issue
  CHANGELOG.md
  packages/client/src/views/RecordAudit/RecordAudit.tsx
Labels: 👌 LGTM

#6875 fix: no supporting documents label showing even when documents are uploaded
  CHANGELOG.md
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💔 Conflicts

#6865 feat: allow defining maxLength attribute for number type fields
  CHANGELOG.md
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
Labels: 💅 Waiting For Review
