Repository opencrvs/opencrvs-core, pull requests merged in 2024-07, with the labels that each got.

#7288 fix: bad requests in elastic search when there is no mapping
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/service.ts
Labels: 💅 Waiting For Review

#7266 fix: filter out history resources
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#7290 fix: date of certification not being visible on death
  packages/client/src/utils/gateway.ts
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
  packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts
Labels: 💅 Waiting For Review

#7129 fix ocrvs-7099: System crashes occur for all birth statuses in the 'Registration by Status' section under Performance.
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/StatusWiseDeclarationCountView.tsx
  packages/client/src/views/SysAdmin/Performance/utils.tsx
Labels: 💅 Waiting For Review

#7142 fix workflow status' informant information
  packages/client/src/i18n/messages/form.ts
  packages/client/src/i18n/messages/views/selectInformant.ts
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Performance/queries.ts
  packages/commons/src/fhir/index.ts
  packages/components/src/Table/Table.tsx
  packages/gateway/src/features/search/type-resolvers.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/workflow/src/records/handler/update.ts
Labels: 💅 Waiting For Review

#7226 fix: render condition for review button in search result page
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#7227 In Correction Summary page, 'Make Correction' button incorrectly enabled and 'Correct record?' modal missing. #7225
  packages/client/src/forms/correction/payment.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/utils/currencyUtils.ts
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
Labels: 💅 Waiting For Review

#7307 fix: allow fonts from country config
  infrastructure/nginx-default.conf
Labels: 💅 Waiting For Review

#7296 fix: advanced search refetch queries not matching the searched ones
  packages/client/src/declarations/index.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
Labels: 💅 Waiting For Review

#7263 fix: Comment section not showing up
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/ReviewCorrection/ReviewCorrection.tsx
  packages/workflow/src/records/__snapshots__/state-transitions.test.ts.snap
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/correction/make-correction.ts
Labels: 💅 Waiting For Review

#7298 fix: remove extra param from adv search form state
  packages/client/src/search/advancedSearch/utils.ts
Labels: 💅 Waiting For Review

#7322 fix: redis hostname
  docker-compose.yml
  packages/webhooks/src/constants.ts
Labels: ✅ Ready for merging

#7328 Refactor client/transformer to improve document change tracking
  packages/client/src/transformer/index.ts
Labels: 💅 Waiting For Review

#7023 Track custom field changes for correction
  CHANGELOG.md
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#7315 fix: email of practitioner
  CHANGELOG.md
  packages/migration/src/migrations/hearth/20240703161352-fix-practitioner-email.ts
  packages/user-mgnt/src/features/createUser/handler.test.ts
  packages/user-mgnt/src/features/createUser/service.ts
Labels: 💅 Waiting For Review

#7314 fix: fetch Documents after resolving Encounters
  packages/search/src/features/records/service.ts
Labels: 💅 Waiting For Review

#7114 refactor: move signatures to review/preview section
  CHANGELOG.md
  packages/client/src/components/Header/Hamburger.tsx
  packages/client/src/components/ProfileMenu.tsx
  packages/client/src/components/form/DocumentUploadField/DocumentListPreview.tsx
  packages/client/src/components/form/DocumentUploadField/DocumentPreview.test.tsx
  packages/client/src/components/form/DocumentUploadField/DocumentPreview.tsx
  packages/client/src/components/form/DocumentUploadField/DocumentUploaderWithOption.tsx
  packages/client/src/components/form/DocumentUploadField/SimpleDocumentUploader.tsx
  packages/client/src/components/form/DocumentUploadField/__snapshots__/DocumentPreview.test.tsx.snap
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/form/SignatureField/SignatureUploader.tsx
  packages/client/src/declarations/index.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/register/mappings/event-specific-fields/birth/mutation/registration-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/birth/query/registration-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/death/mutation/registration-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/death/query/registration-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/marriage/mutation/registration-mappings.ts
  packages/client/src/forms/register/mappings/event-specific-fields/marriage/query/registration-mappings.ts
  packages/client/src/forms/register/reducer.ts
  packages/client/src/forms/register/reviewReducer.ts
  packages/client/src/tests/forms.json
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/userUtils.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/RegisterForm/DeclarationForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/ReviewForm.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.test.tsx
  packages/client/src/views/RegisterForm/duplicate/SupportingDocumentsView.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/RegisterForm/review/SignatureGenerator.tsx
  packages/client/src/views/SysAdmin/Performance/reports/operational/StatusWiseDeclarationCountView.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/UserSetup/SetupReviewPage.tsx
  packages/client/src/views/ViewRecord/ViewRecord.tsx
  packages/components/src/ImageUploader/ImageUploader.stories.tsx
  packages/components/src/ImageUploader/ImageUploader.tsx
  packages/components/src/InputField/InputField.tsx
  packages/components/src/InputField/InputLabel.tsx
  packages/config/src/handlers/forms/validation.ts
  packages/gateway/src/features/registration/__snapshots__/type-resolvers.test.ts.snap
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  yarn.lock
Labels: 💅 Waiting For Review

#7365 fix: use yarn run to execute ts-node
  packages/client/extract-translations.sh
  packages/login/extract-translations.sh
  packages/login/package.json
  packages/notification/extract-translations.sh
Labels: ✅ Ready for merging

#7368 fix: skip PR creation when milestone not set
  .github/workflows/auto-pr-to-release.yml
Labels: ✅ Ready for merging

#7364 chore!: remove deprecated inputFieldWidth
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/tests/forms.json
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
  packages/components/src/TextInput/TextInput.tsx
Labels: ✅ Ready for merging

#7361 Returning default location.name from notification since there is no language parameter
  packages/notification/src/features/utils.ts
Labels: 💅 Waiting For Review

#7384 (For 1.6) Revert "chore: remove leftover sysadmin code
  packages/client/graphql.schema.json
  packages/client/src/App.tsx
  packages/client/src/components/Header/Hamburger.tsx
  packages/client/src/components/ProfileMenu.tsx
  packages/client/src/components/form/DocumentUploadField/SimpleDocumentUploader.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/setupTests.ts
  packages/client/src/utils.ts
  packages/client/src/utils/currencyUtils.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/utils/userUtils.ts
  packages/client/src/views/AdvancedSearch/BookmarkAdvancedSearchResult.tsx
  packages/client/src/views/AdvancedSearch/RemoveBookmarkModal.tsx
  packages/client/src/views/AdvancedSearch/SaveBookmarkModal.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/Performance/FieldAgentList.tsx
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/Settings/items/Role.tsx
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/InformantSMSNotification.test.tsx
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/InformantSMSNotification.tsx
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/mutations.ts
  packages/client/src/views/SysAdmin/Communications/InformantSMSNotification/queries.ts
  packages/client/src/views/SysAdmin/Config/Application/Components.tsx
  packages/client/src/views/SysAdmin/Config/Application/mutation.test.ts
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/client/src/views/SysAdmin/Config/Application/utils.ts
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/index.ts
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
  packages/client/src/views/SysAdmin/Performance/PaymentsAmountComponent.tsx
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/client/src/views/SysAdmin/Vsexports/VSExport.tsx
  packages/client/src/views/UserRoles/UserRoleManagementModal.tsx
  packages/client/src/views/UserSetup/SetupReviewPage.tsx
Labels: 💅 Waiting For Review

#7344 Chore/ocrvs 7133 eslint warnings
  .eslintrc.js
  packages/auth/package.json
  packages/client/package.json
  packages/client/src/components/review/RejectRegistrationForm.tsx
  packages/client/src/tests/util.tsx
  packages/client/src/transformer/transformer.test.tsx
  packages/client/src/user/userReducer.ts
  packages/client/src/utils/persistence/transform.ts
  packages/client/src/utils/userUtils.ts
  packages/client/src/utils/validate.test.ts
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.test.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssuePayment.test.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssuePayment.tsx
  packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.test.tsx
  packages/client/src/views/OIDPVerificationCallback/utils.ts
  packages/client/src/views/OfficeHome/Home.tsx
  packages/client/src/views/OfficeHome/LoadingIndicator.tsx
  packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx
  packages/client/src/views/Performance/FieldAgentList.test.tsx
  packages/client/src/views/Performance/RegistrationsList.test.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/RegisterForm/PreviewForm.test.tsx
  packages/client/src/views/RegisterForm/RegisterForm.test.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.test.tsx
  packages/client/src/views/Settings/items/EmailAddress.tsx
  packages/client/src/views/Settings/items/PhoneNumber.tsx
  packages/client/src/views/SysAdmin/Performance/ApplicationSourcesReport.tsx
  packages/client/src/views/SysAdmin/Performance/CertificationRatesReport.tsx
  packages/client/src/views/SysAdmin/Performance/utils.tsx
  packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx
  packages/client/src/views/SysAdmin/Team/utils.ts
  packages/client/src/views/UserAudit/UserAudit.tsx
  packages/config/package.json
  packages/documents/package.json
  packages/gateway/package.json
  packages/gateway/src/features/user/utils/index.ts
  packages/metrics/package.json
  packages/metrics/src/features/vsExport/handler.ts
  packages/metrics/src/scripts/VSExportGenerator.ts
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/webhooks/package.json
  packages/workflow/package.json
Labels: 💅 Waiting For Review

#7400 fix: handling dynamic message labelparams in review section
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#7389 Upgrade Elasticsearch from 7.17 to 8
  docker-compose.deps.yml
  docker-compose.dev-deps.yml
  docker-compose.yml
  packages/commons/src/fhir/task.ts
  packages/commons/src/index.ts
  packages/commons/src/search.ts
  packages/commons/src/types.ts
  packages/gateway/package.json
  packages/gateway/src/features/search/root-resolvers.ts
  packages/migration/package.json
  packages/migration/src/migrations/hearth/20230328065851-change-certified-status-to-issused.ts
  packages/migration/src/migrations/hearth/20230602120944-populate-valid-locationid.ts
  packages/migration/src/utils/elasticsearch-helper.ts
  packages/migration/tsconfig.json
  packages/search/package.json
  packages/search/src/config/routes.ts
  packages/search/src/elasticsearch/dbhelper.test.ts
  packages/search/src/elasticsearch/dbhelper.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/delete/handler.ts
  packages/search/src/features/fhir/fhir-utils.ts
  packages/search/src/features/registration/assignment/service.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/deduplicate/deduplicate.test.ts
  packages/search/src/features/registration/deduplicate/service.ts
  packages/search/src/features/registration/deduplicate/test-util.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/search/src/features/reindex/prune.ts
  packages/search/src/features/reindex/reindex.ts
  packages/search/src/features/search/handler.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/utils.ts
  yarn.lock
Labels: 🙋Question, 💅 Waiting For Review, 🛣️ Infrastructure

#7408 chore(ocrvs-6821): do not render signature section when view record
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review
