Repository opencrvs/opencrvs-core, pull requests merged in 2024-01, with the labels that each got.

#6199 Ocrvs 5791 register
  packages/client/src/declarations/submissionMiddleware.ts
  packages/commons/package.json
  packages/commons/src/fixtures.ts
  packages/commons/src/fixtures/birth-bundle.ts
  packages/commons/src/fixtures/death-bundle.ts
  packages/commons/src/fixtures/marriage-bundle.ts
  packages/commons/src/record.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/user/utils/index.ts
  packages/gateway/src/workflow/index.ts
  packages/migration/src/migrations/openhim/20231117171009-remove-register-channels.ts
  packages/notification/src/config/routes.ts
  packages/notification/src/features/readyForReview/handler.ts
  packages/notification/src/features/register/handler.ts
  packages/notification/src/features/utils.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/events/handler.ts
  packages/workflow/src/features/registration/fhir/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/register.test.ts
  packages/workflow/src/records/handler/register.ts
  packages/workflow/src/records/notification.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/states.ts
  packages/workflow/src/test/utils.ts
Labels: 💅 Waiting For Review

#6357 [OCRVS-6355] Back button exception fix
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
Labels: Bug, 💅 Waiting For Review

#6389 If user has an invalid language in their query parameters when logging in
  packages/client/src/i18n/reducer.ts
  packages/login/src/i18n/reducer.ts
Labels: Bug

#6182 Hotfix v1.3.2
  .github/DISCUSSION_TEMPLATE/Installation.yml
  .github/ISSUE_TEMPLATE/---bug.md
  .github/ISSUE_TEMPLATE/---feature.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/user-story.md
  docker-compose.yml
  license-config.json
  package.json
  packages/auth/package.json
  packages/auth/src/features/authenticate/service.ts
  packages/client/package.json
  packages/client/src/components/form/ReviewActionComponent.tsx
  packages/client/src/forms/validation.ts
  packages/client/src/i18n/messages/views/review.ts
  packages/client/src/i18n/reducer.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/constants.ts
  packages/client/src/utils/persistence/persistenceMiddleware.ts
  packages/client/src/views/PrintCertificate/VerifyCollector.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/commons/package.json
  packages/components/package.json
  packages/config/package.json
  packages/dashboards/package.json
  packages/data-seeder/package.json
  packages/documents/package.json
  packages/gateway/package.json
  packages/gateway/src/features/registration/fhir-builders.ts
  packages/login/package.json
  packages/login/src/i18n/reducer.ts
  packages/metrics/package.json
  packages/migration/package.json
  packages/migration/src/migrations/hearth/20231123125224-deceased-birth-date.ts
  packages/migration/src/utils/progressTracker.ts
  packages/notification/package.json
  packages/search/package.json
  packages/user-mgnt/package.json
  packages/webhooks/package.json
  packages/workflow/package.json
  packages/workflow/src/constants.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.test.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/features/registration/utils.test.ts
  packages/workflow/src/features/registration/utils.ts
Labels: ✋ On Hold

#6384 [State transitions] Ocrvs 5791 unassign
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/unassign.test.ts
  packages/workflow/src/records/handler/unassign.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/test/mocks/unassignedTask.ts
Labels: 💅 Waiting For Review

#6407 [State transitions] ocrvs register query fix
  .vscode/settings.json
  packages/client/graphql.schema.json
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/mutations.ts
  packages/client/src/views/DataProvider/death/mutations.ts
  packages/client/src/views/DataProvider/marriage/mutations.ts
  packages/client/src/views/SysAdmin/Config/Application/mutations.ts
  packages/commons/src/fhir/transformers/index.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/src/records/handler/update.ts
Labels: 🔧Waiting for fixes

#6387 [State transitions] Ocrvs 5791 archive
  packages/client/src/declarations/submissionMiddleware.ts
  packages/commons/src/record.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/type-resolvers.test.ts
  packages/gateway/src/features/search/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/archive.test.ts
  packages/workflow/src/records/handler/archive.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/states.ts
Labels: ✅ Ready for merging

#6401 [State transitions] Certify record
  packages/client/src/forms/register/mappings/event-specific-fields/birth/mutation/registration-mappings.test.ts
  packages/client/src/forms/register/mappings/event-specific-fields/death/mutation/deceased-mappings.test.ts
  packages/client/src/forms/register/mappings/mutation/utils.ts
  packages/commons/src/fhir/composition.ts
  packages/commons/src/fhir/extension.ts
  packages/commons/src/fhir/index.ts
  packages/commons/src/fhir/patient.ts
  packages/commons/src/fhir/transformers/index.ts
  packages/commons/src/fhir/transformers/templates.ts
  packages/commons/src/fhir/transformers/utils.ts
  packages/commons/src/fixtures/birth-bundle.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/utils.ts
  packages/gateway/src/workflow/index.ts
  packages/search/src/features/records/handler.ts
  packages/workflow/src/__mocks__/constants.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/documents.ts
  packages/workflow/src/features/registration/handler.test.ts
  packages/workflow/src/records/audit.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/archive.test.ts
  packages/workflow/src/records/handler/certify.test.ts
  packages/workflow/src/records/handler/certify.ts
  packages/workflow/src/records/handler/create.test.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/src/records/handler/download.test.ts
  packages/workflow/src/records/handler/register.test.ts
  packages/workflow/src/records/handler/unassign.test.ts
  packages/workflow/src/records/handler/update.test.ts
  packages/workflow/src/records/handler/validate.test.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/records/validations/certify.ts
  packages/workflow/src/test/utils.ts
  packages/workflow/test/handlers.ts
  packages/workflow/test/mocks/createBirthRecord.ts
  packages/workflow/test/mocks/records/readyForReview.ts
  packages/workflow/test/mocks/records/register.ts
  packages/workflow/tsconfig.json
Labels: 💅 Waiting For Review, 👌 LGTM

#6443 [state-transition] Download history and attachment update fix
  packages/client/src/transformer/index.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#6420 [State transitions] Reject endpoint
  packages/client/src/tests/schema.graphql
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/records/audit.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/register.ts
  packages/workflow/src/records/handler/reject.test.ts
  packages/workflow/src/records/handler/reject.ts
  packages/workflow/src/records/handler/update.ts
  packages/workflow/src/records/handler/validate.ts
  packages/workflow/src/records/search.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/states.ts
Labels: 💅 Waiting For Review

#6449 Removed latest defaults from the core docker-compose
  docker-compose.yml
Labels: 💅 Waiting For Review

#6383 ocrvs-6363 create new handlebars for admin level location ids
  CHANGELOG.md
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/extract-translations.ts
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/forms/register/mappings/query/registration-mappings.ts
  packages/client/src/i18n/messages/location.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/search/advancedSearch/utils.test.ts
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/tests/languages.json
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/utils/locationUtils.test.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/Organisation/AdministrativeLevels.tsx
  packages/client/src/views/PrintCertificate/PDFUtils.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/client/src/views/SysAdmin/Performance/reports/utils.test.ts
Labels: 👌 LGTM, 💥 Hot Fixes

#6398 [State transitions] reinstate endpoint
  packages/commons/src/record.ts
  packages/gateway/src/features/registration/root-resolvers.test.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/records/audit.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/handler/archive.ts
  packages/workflow/src/records/handler/reinstate.test.ts
  packages/workflow/src/records/handler/reinstate.ts
  packages/workflow/src/records/index.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/states.ts
  packages/workflow/test/mocks/records/archive.ts
Labels: 💅 Waiting For Review

#6239 qr code query resolver fix
  packages/config/src/handlers/forms/validation.ts
  packages/gateway/src/features/registration/root-resolvers.ts
Labels: 💅 Waiting For Review

#6468 Filter PII out of logger messages
  CHANGELOG.md
  packages/gateway/src/features/OIDPUserInfo/utils.ts
  packages/notification/src/features/sms/birth-handler.ts
  packages/notification/src/features/sms/death-handler.ts
  packages/notification/src/features/sms/service.test.ts
  packages/notification/src/features/sms/service.ts
  packages/notification/src/features/sms/user-handler.ts
  packages/webhooks/src/features/event/handler.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/utils.ts
Labels: 👌 LGTM
