Repository opencrvs/opencrvs-core, pull requests merged in 2024-08, with the labels that each got.

#7398 Get cherry picked commits based on git log results against base sha
  .github/workflows/auto-pr-to-release.yml
Labels: 🙋Question

#7407 fix: save RN as identifier with lower priority
  packages/search/src/features/search/utils.ts
Labels: 👌 LGTM

#7362 feat!: update search bar depending on country config variables
  CHANGELOG.md
  packages/client/src/components/Header/Header.tsx
  packages/client/src/utils/constants.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SearchResult/SearchResult.test.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/components/src/AppBar/AppBar.stories.tsx
  packages/components/src/SearchTool/SearchTool.tsx
  packages/config/src/handlers/application/applicationConfigHandler.ts
Labels: ✅ Ready for merging

#7460 feat(ci): ensure all PRs have a changelog change
  .github/workflows/lint-and-test.yml
Labels: 💅 Waiting For Review

#7473 chore(sequence-diagrams): use leaf level locations
  sequence-diagrams/backend/create-birth-registration-field-agent.md
  sequence-diagrams/backend/create-birth-registration-registrar.md
  sequence-diagrams/backend/create-birth-registration-registration-agent.md
  sequence-diagrams/backend/mark-birth-as-certified.md
  sequence-diagrams/backend/mark-birth-as-reinstated.md
  sequence-diagrams/backend/mark-birth-as-void.md
Labels: ✅ Ready for merging

#7459 Fix/remove legacy index on reindex
  CHANGELOG.md
  packages/search/src/config/routes.ts
  packages/search/src/elasticsearch/client.ts
  packages/search/src/elasticsearch/dbhelper.test.ts
  packages/search/src/elasticsearch/dbhelper.ts
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/delete/handler.test.ts
  packages/search/src/features/delete/handler.ts
  packages/search/src/features/registration/assignment/service.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/deduplicate/deduplicate.test.ts
  packages/search/src/features/registration/deduplicate/handler.ts
  packages/search/src/features/registration/deduplicate/test-util.ts
  packages/search/src/features/registration/marriage/service.ts
  packages/search/src/features/reindex/handler.ts
  packages/search/src/features/reindex/prune.ts
  packages/search/src/features/reindex/reindex.test.ts
  packages/search/src/features/reindex/reindex.ts
  packages/search/src/features/search/handler.test.ts
  packages/search/src/features/search/handler.ts
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/service.ts
  packages/search/src/test/createHandlerSetup.ts
  packages/search/src/test/utils.ts
Labels: 👌 LGTM

#7488 fix: navigation version hover issue
  packages/client/src/index.tsx
  packages/client/src/utils/apolloClient.ts
  packages/client/src/utils/constants.ts
  packages/components/src/SideNavigation/LeftNavigation.tsx
Labels: ✅ Ready for merging

#7399 Updated CHANGELOG format
  CHANGELOG.md
Labels: 🔧Waiting for fixes

#7485 fix: date range edit not being clickable in advanced search
  CHANGELOG.md
  packages/client/src/components/DateRangePickerForFormField.tsx
  packages/components/src/Checkbox/Checkbox.tsx
Labels: Bug, ✅ Ready for merging

#7491 fix(registration-list): use time property instead of date for safer date format generation
  packages/client/src/utils/date-formatting.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/Performance/RegistrationsList.test.tsx
  packages/client/src/views/Performance/RegistrationsList.tsx
  packages/metrics/src/features/totalMetrics/handler.ts
Labels: ✅ Ready for merging

#7512 fix: use machine account gh token to allow for recursive triggers
  .github/workflows/auto-pr-to-release.yml
Labels: ✅ Ready for merging

#7517 Add multi-release support and resolution to cherry-pick automation
  .github/workflows/auto-pr-to-release.yml
Labels: 💅 Waiting For Review

#7519 Fix/missing security dependencies
  packages/auth/package.json
  packages/components/package.json
  packages/data-seeder/package.json
  packages/documents/package.json
  packages/gateway/package.json
  packages/login/package.json
  packages/metrics/package.json
  packages/notification/package.json
  packages/search/package.json
  packages/workflow/package.json
  yarn.lock
Labels: 💅 Waiting For Review

#7521 change serving country certificates
  packages/client/src/App.tsx
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/navigation/index.ts
  packages/client/src/navigation/routes.ts
  packages/client/src/offline/actions.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/pdfRenderer/index.ts
  packages/client/src/utils/referenceApi.test.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
  packages/client/src/views/SysAdmin/Config/Certificates/index.ts
  packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
  packages/data-seeder/src/certificates.ts
  packages/data-seeder/src/index.ts
Labels: ✅ Ready for merging

#7544 fix: prevent the same record with the same draft-id from being submitted twice [OCRVS-7477]
  CHANGELOG.md
  packages/commons/src/fhir/task.ts
  packages/commons/src/fhir/transformers/fhir-builders.test.ts
  packages/commons/src/fhir/transformers/index.ts
  packages/workflow/src/records/fhir.ts
Labels: 💅 Waiting For Review

#7513 Fix migration issues for countries migrating from 1.2
  packages/metrics/test/setupJest.ts
  packages/migration/src/migrations/hearth/20230221105416-create-performance-views.ts
  packages/migration/src/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.ts
  packages/search/src/test/utils.ts
Labels: 💅 Waiting For Review

#7535 (For 1.5.1) Fix migration issues for countries migrating from 1.2
  CHANGELOG.md
  packages/gateway/src/features/search/type-resolvers.ts
  packages/metrics/test/setupJest.ts
  packages/migration/src/migrations/hearth/20230221105416-create-performance-views.ts
  packages/migration/src/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.ts
  packages/migration/src/utils/elasticsearch-helper.ts
  packages/search/src/elasticsearch/dbhelper.test.ts
  packages/search/src/elasticsearch/dbhelper.ts
  packages/search/src/features/registration/deduplicate/service.ts
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/service.ts
  packages/search/src/test/utils.ts
Labels: 💅 Waiting For Review
