Repository opencrvs/opencrvs-core, pull requests merged in 2024-05, with the labels that each got.

#6809 fix: handle ADMIN_LEVEL > 2
  CHANGELOG.md
  docker-compose.yml
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/advancedSearch/fieldDefinitions/Birth.ts
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/PrintRecord/Body.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/config/src/config/constants.ts
  packages/config/src/config/routes.ts
  packages/config/src/handlers/locations/hierarchy.ts
  packages/config/src/utils/verifyToken.ts
  packages/config/tsconfig.json
Labels: 💅 Waiting For Review

#6923 Converted the SimpleDocumentUploader to function
  packages/client/src/components/Notification.tsx
  packages/client/src/components/ProfileMenu.tsx
  packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx
Labels: 👌 LGTM

#6828 fix: ocrvs-6621 Verify certificate only supports 2 location levels
  CHANGELOG.md
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx
  packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts
Labels: 💅 Waiting For Review

#6885 fix: update declaration misplacing values
  packages/client/src/transformer/index.ts
  packages/commons/src/fhir/transformers/index.ts
  packages/commons/src/fhir/transformers/utils.ts
Labels: 💅 Waiting For Review, 👌 LGTM

#6842 feat: add route in workflow to forward declaration of health systems
  packages/commons/src/fhir/index.ts
  packages/gateway/src/features/eventNotification/eventNotificationHandler.ts
  packages/gateway/src/workflow/index.ts
  packages/search/package.json
  packages/search/src/elasticsearch/utils.test.ts
  packages/search/src/elasticsearch/utils.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/registration/utils.ts
  packages/workflow/src/features/user/utils.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/src/records/handler/eventNotificationHandler.ts
Labels: 💅 Waiting For Review, 👌 LGTM

#6943 fix: add webhooks url env variable for workflow
  docker-compose.yml
Labels: 💅 Waiting For Review

#6960 Fix updated values
  packages/commons/src/fhir/transformers/index.ts
Labels: 💅 Waiting For Review

#6933 feat: save timeloggedMS for rejecting correction
  packages/client/graphql.schema.json
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway.ts
  packages/client/src/views/RegisterForm/review/ReviewSectionCorrection.tsx
  packages/commons/src/record.test.ts
  packages/commons/src/record.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/correction/routes.ts
  packages/workflow/src/records/handler/archive.ts
  packages/workflow/src/records/handler/correction/approve.ts
  packages/workflow/src/records/handler/correction/make-correction.ts
  packages/workflow/src/records/handler/correction/reject.ts
  packages/workflow/src/records/handler/correction/request.ts
  packages/workflow/src/records/handler/correction/utils.ts
  packages/workflow/src/records/handler/register.ts
  packages/workflow/src/records/handler/update.ts
  packages/workflow/src/records/handler/validate.ts
  packages/workflow/src/records/handler/verify.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/records/validations.ts
Labels: 💅 Waiting For Review

#6981 Fix: Ocrvs 6247 Registrar of any location should be able to review a correction request
  CHANGELOG.md
  packages/client/src/views/RecordAudit/ActionButtons.tsx
  packages/client/src/views/SearchResult/SearchResult.tsx
Labels: 💅 Waiting For Review

#6633 Converted the PINKeypad component
  packages/client/src/views/PIN/CreatePin.tsx
  packages/components/src/AppBar/AppBar.stories.tsx
  packages/components/src/DateField/DateField.tsx
  packages/components/src/PINKeypad/PINKeypad.tsx
  packages/components/src/Pagination/Pagination.tsx
  packages/components/src/SearchTool/SearchTool.tsx
Labels: 💅 Waiting For Review

#6914 feat: add new handlebars
  CHANGELOG.md
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.test.tsx
  packages/client/src/views/PrintCertificate/usePrintableCertificate.ts
Labels: 💅 Waiting For Review

#7001 docs: create a section for v1.6 changes
  CHANGELOG.md
Labels: 💅 Waiting For Review

#6962 feat: enable supporting documents to be made required
  CHANGELOG.md
  packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 👌 LGTM

#6982 UI Refactor: Radiobutton
  packages/client/src/index.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/Radio/RadioButton.tsx
  packages/components/src/Radio/RadioGroup.tsx
  packages/components/src/fonts.ts
Labels: 👌 LGTM

#7014 chore: handle configuration option restructure
  packages/client/src/tests/forms.json
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/typings/window.d.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
Labels: 💅 Waiting For Review

#7007 fix: set correction requested declaration to be retreived
  packages/client/src/components/interface/DownloadButton.tsx
  packages/workflow/src/records/handler/download.ts
Labels: 👌 LGTM, ✅ Ready for merging

#6839 Converted ReadyForReviewComponent to function
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/OfficeHome/inExternalValidation/InExternalValidationTab.tsx
  packages/client/src/views/OfficeHome/outbox/Outbox.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/components/src/AppBar/AppBar.tsx
  packages/components/src/AppHeader/AppHeader.tsx
  packages/components/src/Workqueue/Workqueue.tsx
  packages/components/src/hooks/index.ts
  packages/components/src/hooks/useWindowSize.ts
Labels: 👌 LGTM

#7010 [OCRVS-6163] Fix login config load issue
  CHANGELOG.md
  packages/login/src/App.tsx
  packages/login/src/Page.tsx
  packages/login/src/index.tsx
  packages/login/src/views/ResetCredentialsForm/AuthDetailsVerificationForm.test.tsx
  packages/login/src/views/ResetCredentialsForm/AuthDetailsVerificationForm.tsx
  packages/login/src/views/ResetCredentialsForm/Commons.tsx
  packages/login/src/views/ResetCredentialsForm/ForgottenItemForm.test.tsx
  packages/login/src/views/ResetCredentialsForm/ForgottenItemForm.tsx
  packages/login/src/views/ResetCredentialsForm/RecoveryCodeEntryForm.tsx
  packages/login/src/views/ResetCredentialsForm/ResetCredentialsSuccessPage.test.tsx
  packages/login/src/views/ResetCredentialsForm/ResetCredentialsSuccessPage.tsx
  packages/login/src/views/ResetCredentialsForm/SecurityQuestionForm.tsx
  packages/login/src/views/ResetCredentialsForm/UpdatePasswordForm.test.tsx
  packages/login/src/views/ResetCredentialsForm/UpdatePasswordForm.tsx
Labels: 👌 LGTM

#6991 UI Refactor: Heading and Divider
  packages/components/src/Divider/Divider.tsx
  packages/components/src/Headings/Headings.tsx
Labels: 👌 LGTM

#7008 UI Refactor: Document Upload components:
  packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentPreview.tsx
  packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx
  packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/ErrorText/ErrorText.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/LocationSearch/LocationSearch.tsx
  packages/components/src/Select/Select.tsx
  packages/components/stories/iconography.stories.mdx
Labels: 💅 Waiting For Review

#6980 UI Refactor: Content component
  packages/client/src/views/CorrectionForm/CorrectionReasonForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/CorrectorForm.tsx
  packages/client/src/views/CorrectionForm/IDVerifier.tsx
  packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueFormForOthers.tsx
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssuePayment.tsx
  packages/client/src/views/PrintCertificate/IDVerifier.tsx
  packages/client/src/views/PrintCertificate/Payment.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/client/src/views/RegisterForm/duplicate/DuplicateForm.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/client/src/views/UserSetup/CreatePassword.tsx
  packages/client/src/views/UserSetup/SecurityQuestionView.tsx
  packages/client/src/views/UserSetup/SetupReviewPage.tsx
  packages/client/src/views/UserSetup/UserSetupPage.tsx
  packages/components/src/Content/Content.tsx
  packages/components/src/Frame/components/Layout.tsx
  packages/login/src/views/ResetCredentialsForm/AuthDetailsVerificationForm.tsx
  packages/login/src/views/ResetCredentialsForm/ForgottenItemForm.tsx
  packages/login/src/views/ResetCredentialsForm/RecoveryCodeEntryForm.tsx
  packages/login/src/views/ResetCredentialsForm/SecurityQuestionForm.tsx
  packages/login/src/views/ResetCredentialsForm/UpdatePasswordForm.tsx
Labels: 💅 Waiting For Review

#6979 fix: informant's id becomes empty in a completely submitted declaration when informant is change from mother/father to others
  packages/workflow/src/records/handler/update.ts
  packages/workflow/src/records/state-transitions.ts
Labels: ✅ Ready for merging

#7026 Sets declaration form bottom buttons to column direction
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: 💅 Waiting For Review

#7027 [OCRVS-7016] Fix dashboard cron tasks not working
  CHANGELOG.md
  packages/config/src/config/routes.ts
  packages/config/src/handlers/dashboardQueries/dashboardQueries.ts
  packages/metrics/src/config/routes.ts
  packages/metrics/src/configApi.ts
  packages/metrics/src/features/performance/viewRefresher.ts
Labels: 👌 LGTM, Docs

#7029 Fix: Checkbox being selected when Select dropdown is active
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Radio/RadioButton.tsx
Labels: 💅 Waiting For Review

#7056 Fix: Ocrvs 7002 client modal glitches on Integrations page
  CHANGELOG.md
  packages/components/src/ResponsiveModal/ResponsiveModal.tsx
Labels: 💅 Waiting For Review

#7043 Fix: Reset pagination to page 1 when location changes
  CHANGELOG.md
  packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Labels: 🏥 Failing Tests

#7061 Fix: Ocrvs 6341-French translation missing for relationship to informant when trying to correct record, print and issue record
  CHANGELOG.md
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/forms/correction/corrector.ts
  packages/client/src/views/CorrectionForm/CorrectorForm.test.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Labels: 💅 Waiting For Review
