Repository opencrvs/opencrvs-core, pull requests merged in 2025-01, with the labels that each got.

#8265 feat: separate query for sent for review tab
  packages/client/src/ListSyncController.ts
  packages/client/src/components/interface/Navigation.tsx
  packages/client/src/declarations/index.test.ts
  packages/client/src/declarations/index.ts
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/workqueue/actions.ts
  packages/client/src/workqueue/reducer.ts
  packages/commons/src/fhir/index.ts
  packages/commons/src/fhir/practitioner.ts
  packages/workflow/src/features/user/utils.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/test/handlers.ts
Labels: 🚀 Ready to deploy

#8251 chore: remove all gql codes from v2 directory
  packages/gateway/src/graphql/config.ts
  packages/gateway/src/graphql/index.graphql
  packages/gateway/src/v2-events/events/root-resolvers.ts
  packages/gateway/src/v2-events/events/schema.graphql
  packages/gateway/src/v2-events/events/type-resolvers.ts
Labels: 🚀 Ready to deploy

#8197 feat: allow supplying a comment with confirmRegistration
  CHANGELOG.md
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/features/registration/handler.ts
  packages/workflow/src/records/fhir.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#8255 feat: implement `getInitialValue` and `fieldValueToString`
  packages/client/src/src-sw.ts
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/DocumentPreview.tsx
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/features/debug/debug.tsx
  packages/client/src/v2-events/features/events/actions/declare/Pages.tsx
  packages/client/src/v2-events/features/events/actions/declare/Review.tsx
  packages/client/src/v2-events/features/events/actions/register/Pages.tsx
  packages/client/src/v2-events/features/events/actions/register/Review.tsx
  packages/client/src/v2-events/features/events/components/Pages.tsx
  packages/client/src/v2-events/features/events/components/Review.tsx
  packages/client/src/v2-events/features/events/registered-fields/DateField.tsx
  packages/client/src/v2-events/features/events/registered-fields/Paragraph.tsx
  packages/client/src/v2-events/features/events/registered-fields/RadioGroup.tsx
  packages/client/src/v2-events/features/events/registered-fields/TextField.tsx
  packages/client/src/v2-events/features/events/useEventConfiguration.ts
  packages/client/src/v2-events/features/events/useEventFormData.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/action.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/create.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/delete.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/persist.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.test.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventSummary.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/hooks/useTransformer.ts
  packages/client/src/v2-events/layouts/form/index.tsx
  packages/client/src/v2-events/messages/constants.ts
  packages/client/src/v2-events/trpc.tsx
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/FieldValue.ts
  packages/commons/src/events/defineConfig.ts
  packages/commons/src/events/utils.ts
  packages/events/src/service/events.ts
  packages/events/src/service/files/index.ts
  yarn.lock
Labels: 💅 Waiting For Review

#8235 Fix: Signature not showing
  packages/client/src/src-sw.ts
  packages/client/src/views/PrintCertificate/usePrintableCertificate.ts
  packages/commons/src/client.ts
  packages/commons/src/documents.ts
  packages/gateway/src/features/fhir/minioAPI.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#8288 fix: track detailsExist form value
  packages/client/src/transformer/index.ts
Labels: 🚀 Ready to deploy

#8267 (User roles) fix search scope bugs
  packages/client/src/App.tsx
  packages/client/src/components/Header/Header.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/advancedSearch/fieldDefinitions/Birth.ts
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/forms/index.ts
  packages/client/src/hooks/useAuthorization.ts
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/utils/locationUtils.test.ts
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/SearchResult/AdvancedSearch.test.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
Labels: 💅 Waiting For Review

#8307 fix: add prop to protected component to show update action
  packages/client/src/components/ProtectedComponent.tsx
  packages/client/src/views/RecordAudit/ActionMenu.tsx
Labels: 💅 Waiting For Review

#8314 feat: add rule to only allow `@opencrvs/commons/client`
  packages/client/.eslintrc.js
Labels: 👌 LGTM

#8325 fix: log error instead of throwing for v2 events
  packages/data-seeder/src/locations.ts
Labels: 🚀 Ready to deploy

#8329 Events v2: implement deduplication configuration
  packages/auth/tsconfig.json
  packages/client/src/v2-events/features/events/fixtures.ts
  packages/client/src/v2-events/features/events/useEventConfiguration.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx
  packages/commons/src/events/ActionInput.ts
  packages/commons/src/events/DeduplicationConfig.ts
  packages/commons/src/events/EventConfig.ts
  packages/commons/src/events/index.ts
  packages/commons/src/events/utils.ts
  packages/commons/tsconfig.esm.json
  packages/commons/tsconfig.json
  packages/components/tsconfig.json
  packages/config/tsconfig.json
  packages/documents/tsconfig.json
  packages/events/package.json
  packages/events/src/router/router.ts
  packages/events/src/service/deduplication/deduplication.test.ts
  packages/events/src/service/deduplication/deduplication.ts
  packages/events/src/service/events.ts
  packages/events/src/service/indexing/indexing.test.ts
  packages/events/src/service/indexing/indexing.ts
  packages/events/src/storage/__mocks__/elasticsearch.ts
  packages/events/src/storage/elasticsearch.ts
  packages/events/src/tests/setup.ts
  packages/events/tsconfig.json
  packages/metrics/tsconfig.json
  packages/notification/tsconfig.json
  packages/search/tsconfig.json
  packages/toolkit/package.json
  packages/toolkit/src/conditionals/deduplication.ts
  packages/toolkit/src/conditionals/index.ts
  packages/webhooks/tsconfig.json
  packages/workflow/tsconfig.json
  yarn.lock
Labels: 🚀 Ready to deploy

#8332 fix: save additional practitioner role entry in bundle during view action
  packages/client/src/forms/advancedSearch/fieldDefinitions/Birth.ts
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
  packages/client/src/forms/index.ts
  packages/client/src/search/advancedSearch/utils.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/locationUtils.ts
  packages/client/src/views/OfficeHome/OfficeHome.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/commons/src/client.ts
  packages/workflow/src/features/user/utils.ts
  packages/workflow/src/records/handler/view.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 💅 Waiting For Review

#8318 Fix issue with formatting national phone numbers for countries with a '0' national prefix
  CHANGELOG.md
  packages/client/src/forms/register/mappings/query/registration-mappings.test.ts
  packages/client/src/forms/register/mappings/query/registration-mappings.ts
Labels: 🔧Waiting for fixes, 🚀 Ready to deploy

#8274 Feat: implement birth v2
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/components/forms/validation.ts
  packages/client/src/v2-events/features/events/EventSelection.tsx
  packages/client/src/v2-events/features/events/components/Review.tsx
  packages/client/src/v2-events/features/events/registered-fields/BulletList.tsx
  packages/client/src/v2-events/features/events/registered-fields/Checkbox.tsx
  packages/client/src/v2-events/features/events/registered-fields/Select.tsx
  packages/client/src/v2-events/features/events/registered-fields/SelectCountry.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx
  packages/commons/src/events/EventConfig.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/FormConfig.ts
  packages/events/src/service/indexing/indexing.ts
  packages/toolkit/package.json
  packages/toolkit/src/conditionals/index.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#8341 Fix issue with formatting national phone numbers for countries with a '0' national prefix
  packages/client/src/forms/register/mappings/query/registration-mappings.ts
Labels: 🚀 Ready to deploy

#8327 feat: create address input
  packages/client/src/offline/selectors.ts
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/features/events/components/Review.tsx
  packages/client/src/v2-events/features/events/registered-fields/Checkbox.tsx
  packages/client/src/v2-events/features/events/registered-fields/Location.tsx
  packages/client/src/v2-events/features/events/registered-fields/LocationSearch.tsx
  packages/client/src/v2-events/features/events/registered-fields/RadioGroup.tsx
  packages/client/src/v2-events/features/events/registered-fields/Select.tsx
  packages/client/src/v2-events/features/events/registered-fields/SelectCountry.tsx
  packages/client/src/v2-events/features/events/registered-fields/TextField.tsx
  packages/client/src/v2-events/hooks/useTransformer.ts
  packages/commons/src/events/DeduplicationConfig.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/FieldValue.ts
  packages/commons/src/events/defineConfig.ts
  packages/commons/src/events/utils.ts
  packages/events/src/service/indexing/indexing.ts
  packages/toolkit/package.json
Labels: 💅 Waiting For Review

#8287 INFORMANT_SIGNATURE & INFORMANT_SIGNATURE_REQUIRED are now deprecated…
  CHANGELOG.md
  packages/client/src/setupTests.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/schema.graphql
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/utils/referenceApi.ts
  packages/client/typings/window.d.ts
  packages/config/src/handlers/application/applicationConfigHandler.test.ts
  packages/config/src/handlers/application/applicationConfigHandler.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#8349 fix: update resolver parameter of certTemplateId
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 💅 Waiting For Review

#8196 feat: QR code scanner
  .github/workflows/storybook-deploy.yml
  CHANGELOG.md
  packages/client/package.json
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/components/form/IDVerificationBanner.tsx
  packages/client/src/components/form/LinkButton.tsx
  packages/client/src/components/form/ReaderGenerator.tsx
  packages/client/src/components/form/Redirect.tsx
  packages/client/src/components/form/http.ts
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/views/id-verification-banner.ts
  packages/client/src/i18n/messages/views/qr-reader.ts
  packages/client/src/transformer/index.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
  packages/components/package.json
  packages/components/src/Dialog/Dialog.tsx
  packages/components/src/Divider/Divider.stories.tsx
  packages/components/src/Divider/Divider.tsx
  packages/components/src/IDReader/IDReader.stories.tsx
  packages/components/src/IDReader/components.tsx
  packages/components/src/IDReader/index.tsx
  packages/components/src/IDReader/readers/QRReader/InfoBox.tsx
  packages/components/src/IDReader/readers/QRReader/QRReader.tsx
  packages/components/src/IDReader/readers/QRReader/Scanner.tsx
  packages/components/src/IDReader/types.ts
  packages/components/src/Icon/all-icons.ts
  packages/components/src/index.ts
  packages/config/src/handlers/forms/field.ts
  yarn.lock
Labels: 🚀 Ready to deploy

#8195 Break word in table rows in low resolution
  packages/components/src/Frame/components/Layout.tsx
  packages/components/src/ListReview/components/Row.tsx
Labels: 🚀 Ready to deploy

#8370 Events v2: create Elasticsearch indices and aliases when events service starts
  docker-compose.yml
  packages/auth/src/features/anonymousToken/handler.ts
  packages/events/src/environment.ts
  packages/events/src/index.ts
  packages/events/src/service/auth/index.ts
  packages/events/src/service/indexing/indexing.ts
Labels: 🚀 Ready to deploy

#8291 feat: `updateField` GraphQL mutation
  CHANGELOG.md
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/schema.graphql
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/gateway/src/workflow/index.ts
  packages/workflow/src/__mocks__/constants.ts
  packages/workflow/src/config/routes.ts
  packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
  packages/workflow/src/features/registration/fhir/fhir-utils.ts
  packages/workflow/src/records/handler/create.test.ts
  packages/workflow/src/records/handler/create.ts
  packages/workflow/src/records/handler/update-field.ts
  packages/workflow/src/records/handler/upsert-identifiers.ts
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/records/token-exchange.ts
  packages/workflow/src/utils/country-config-api.ts
Labels: 🚀 Ready to deploy

#8386 Events v2: add a dummy registration confirm handler
  packages/events/src/router/event/index.ts
  packages/events/src/service/config/config.ts
Labels: 🚀 Ready to deploy

#8510 Events v2 demo branch
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/components/forms/validation.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverviewContext.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistory.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistoryModal.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/messages.ts
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/hooks/useTransformer.ts
  packages/client/src/v2-events/messages/index.ts
  packages/client/src/v2-events/messages/registrarHome.ts
  packages/commons/src/events/ActionDocument.ts
  packages/events/src/router/user/user.list.test.ts
  packages/events/src/service/deduplication/deduplication.test.ts
  packages/events/src/service/deduplication/deduplication.ts
  packages/events/src/service/indexing/indexing.ts
  packages/events/src/service/users/users.ts
  packages/events/src/tests/generators.ts
  packages/events/tsconfig.json
  packages/gateway/tsconfig.json
Labels: 🚀 Ready to deploy

#8521 perf: only forward the questionnaire resource
  packages/workflow/src/records/handler/update-field.ts
Labels: 🚀 Ready to deploy
