Repository opencrvs/opencrvs-core, pull requests merged in 2025-04, with the labels that each got.

#9127 v2 assign unassign (backend)
  packages/commons/src/events/ActionInput.ts
  packages/commons/src/events/test.utils.ts
  packages/events/src/router/event/event.actions.assign.test.ts
  packages/events/src/router/event/event.actions.unassign.test.ts
  packages/events/src/router/event/index.ts
  packages/events/src/router/middleware/authorization/index.ts
  packages/events/src/router/middleware/utils.ts
  packages/events/src/router/middleware/validate/index.ts
  packages/events/src/service/events/actions/assign.ts
  packages/events/src/service/events/actions/unassign.ts
  packages/events/src/service/events/utils.test.ts
  packages/events/src/service/events/utils.ts
  packages/events/src/tests/utils.ts
Labels: 💅 Waiting For Review

#9089 feat: Memoize generating locations as it was causing re-renders and slowing search
  packages/client/src/utils/locationUtils.ts
Labels: 💅 Waiting For Review

#9168 fix: checkout branch before building images
  .github/workflows/build-images-from-branch.yml
Labels: 💅 Waiting For Review

#9193 Cleanup on unassign
  packages/client/.storybook/default-request-handlers.ts
  packages/client/src/v2-events/features/events/useEvents/api.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
  packages/client/src/v2-events/features/files/cache.ts
  packages/client/src/v2-events/features/files/useFileUpload.ts
Labels: 💅 Waiting For Review

#9208 fix: ensure user create/update is allowed only in jurisdiction
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/gateway/src/features/user/utils/index.ts
  packages/gateway/src/location.ts
  packages/workflow/src/utils/location.ts
Labels: 💅 Waiting For Review, 🔒 Keep e2e, 🚀 Ready to deploy

#9178 perf: use useMemo to cache expensive function call
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/utils/locationUtils.ts
Labels: 💅 Waiting For Review

#9222 feat: Replace Redis with Valkey
  CHANGELOG.md
  docker-compose.deps.yml
Labels: 🏥 Failing Tests, Enhancement

#9207 Ocrvs-9053
  packages/client/src/v2-events/features/events/actions/declare/Pages.interaction.stories.tsx
  packages/client/src/v2-events/features/events/fixtures.ts
  packages/client/src/v2-events/features/events/useEvents/api.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistoryModal.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/utils.ts
  packages/commons/eslint.events.config.js
  packages/commons/src/events/ActionType.ts
  packages/commons/src/events/utils.test.ts
  packages/commons/src/events/utils.ts
  packages/events/src/router/event/event.actions.assign.test.ts
  packages/events/src/router/event/event.actions.declare.test.ts
  packages/events/src/router/event/event.actions.test.ts
  packages/events/src/router/event/event.actions.unassign.test.ts
  packages/events/src/router/event/event.actions.validate.test.ts
  packages/events/src/router/event/event.create.test.ts
  packages/events/src/router/event/event.delete.test.ts
  packages/events/src/service/events/actions/assign.ts
  packages/events/src/service/events/actions/unassign.ts
  packages/events/src/service/events/events.ts
  packages/events/src/service/events/utils.ts
Labels: 💅 Waiting For Review

#9280 Automatically unassign user when submitting an action
  packages/client/src/v2-events/custom-api/index.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx
  packages/client/src/v2-events/utils.ts
  packages/commons/src/events/ActionDocument.ts
  packages/commons/src/events/ActionInput.ts
  packages/commons/src/events/ActionType.ts
  packages/commons/src/events/test.utils.ts
  packages/commons/src/events/utils.test.ts
  packages/commons/src/events/utils.ts
  packages/events/src/router/event/event.actions.archive.test.ts
  packages/events/src/router/event/event.actions.correction.test.ts
  packages/events/src/router/event/event.actions.declare.test.ts
  packages/events/src/router/event/event.actions.printCertificate.test.ts
  packages/events/src/router/event/event.actions.reject.test.ts
  packages/events/src/router/event/event.actions.test.ts
  packages/events/src/router/event/event.actions.validate.test.ts
  packages/events/src/router/event/event.delete.test.ts
  packages/events/src/service/events/events.ts
Labels: 💅 Waiting For Review

#9308 fix: use closest role entry when none available
  CHANGELOG.md
  packages/commons/src/fhir/practitioner.ts
  packages/gateway/src/features/registration/recordHistory.test.ts
Labels: ✅ Ready for merging

#9398 Fix migration issue discovered when restoring an OpenCRVS instace with a large number of records
  CHANGELOG.md
  packages/search/src/features/records/service.ts
Labels: 💅 Waiting For Review
