Repository opencrvs/opencrvs-core, pull requests merged in 2025-08, with the labels that each got.

#10126 fix: tweak email & name field analyzers in elasticsearch
  packages/commons/src/conditionals/conditionals.test.ts
  packages/commons/src/conditionals/conditionals.ts
  packages/events/src/router/event/event.search.test.ts
  packages/events/src/service/indexing/indexing.ts
Labels: 💅 Waiting For Review

#10144 perf: reduce events service restart churning
  packages/events/nodemon.json
  packages/events/package.json
  packages/events/src/index.ts
  yarn.lock
Labels: 💅 Waiting For Review

#10174 feat: introduce typescript references in commons
  packages/commons/eslint.events.config.js
  packages/commons/package.json
  packages/commons/tsconfig-base.json
  packages/commons/tsconfig-commonjs.json
  packages/commons/tsconfig-esm.json
  packages/commons/tsconfig-tests.json
  packages/commons/tsconfig.build.json
  packages/commons/tsconfig.esm.build.json
  packages/commons/tsconfig.json
  packages/toolkit/tsconfig.json
Labels: 💅 Waiting For Review

#10158 (Events v2) Set a limit for action retry
  packages/client/src/v2-events/components/RetryButton.tsx
  packages/client/src/v2-events/custom-api/index.ts
  packages/client/src/v2-events/features/events/Search/SearchResult.tsx
  packages/client/src/v2-events/features/events/useEvents/outbox.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
  packages/client/src/v2-events/features/workqueues/Outbox.tsx
  packages/client/src/v2-events/routes/Toaster.tsx
Labels: 💅 Waiting For Review, Phase 3 (Events v2)

#10201 Add "Verify ID" fields in summary page and make `Correction Request` button have full width
  packages/client/src/i18n/messages/views/correction.ts
  packages/client/src/v2-events/features/events/actions/correct/request/CorrectionRequest.stories.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/ReviewCorrection.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Summary/CorrectionDetails.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Summary/Summary.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistoryDialog/EventHistoryDialog.stories.tsx
  packages/commons/src/events/test.utils.ts
  packages/commons/src/fixtures/tennis-club-membership-event.ts
Labels: 💅 Waiting For Review, Phase 3 (Events v2)

#10250 chore: update history role label
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.stories.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistory.tsx
Labels: ✅ Ready for merging

#10262 Fix aborting correct record process.
  packages/client/src/v2-events/features/events/actions/correct/request/Onboarding/Onboarding.stories.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Onboarding/Onboarding.tsx
  packages/client/src/v2-events/features/events/useEventFormNavigation.tsx
  packages/components/src/ActionPageLight/ActionPageLight.tsx
Labels: 💅 Waiting For Review

#10302 perf: give FieldConfig an explicit type
  packages/client/src/v2-events/features/events/registered-fields/Address.tsx
  packages/client/src/v2-events/features/events/registered-fields/AdministrativeArea.tsx
  packages/client/src/v2-events/features/events/registered-fields/Checkbox.tsx
  packages/client/src/v2-events/features/events/registered-fields/LocationSearch.tsx
  packages/client/src/v2-events/features/events/registered-fields/RadioGroup.tsx
  packages/client/src/v2-events/features/events/registered-fields/Select.tsx
  packages/client/src/v2-events/features/events/registered-fields/SelectCountry.tsx
  packages/commons/src/events/FieldConfig.ts
Labels: 💅 Waiting For Review

#10305 [HOTFIX] Fix broken FrameHeader
  packages/components/src/AppBar/AppBar.tsx
  packages/components/src/Frame/Frame.tsx
Labels: 💅 Waiting For Review, 💥 Hot Fixes

#10310 fix: change dependency of parent field
  packages/client/.storybook/preview.tsx
  packages/client/src/v2-events/components/forms/FormFieldGenerator/FormSectionComponent.tsx
  packages/client/src/v2-events/features/events/ReadOnlyView.stories.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/CorrectionRequest.stories.tsx
  packages/commons/src/fixtures/forms.ts
  packages/events/src/router/event/__snapshots__/event.actions.declare.test.ts.snap
  packages/events/src/router/event/event.actions.declare.test.ts
Labels: ✅ Ready for merging

#10246 feat: Trigger notification for events
  packages/auth/src/features/refresh/handler.test.ts
  packages/auth/src/features/resend/handler.test.ts
  packages/auth/src/features/retrievalSteps/sendUserName/handler.ts
  packages/auth/src/features/retrievalSteps/verifyNumber/handler.test.ts
  packages/auth/src/features/verifyCode/service.ts
  packages/client/src/v2-events/features/events/actions/correct/request/Review.tsx
  packages/client/src/v2-events/features/events/actions/correct/useActionForHistory.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistory.tsx
  packages/commons/src/countryconfig/index.ts
  packages/commons/src/events/index.ts
  packages/commons/src/events/state/index.ts
  packages/commons/src/events/utils.ts
  packages/commons/src/notification/UserNotifications.ts
  packages/commons/src/utils.ts
  packages/events/src/router/event/__snapshots__/event.actions.register.test.ts.snap
  packages/events/src/router/event/__snapshots__/event.actions.test.ts.snap
  packages/events/src/router/event/actions/actionConfirmationRequest.ts
  packages/events/src/router/event/actions/index.ts
  packages/events/src/router/event/event.actions.correction-2.test.ts
  packages/events/src/router/event/event.actions.correction.test.ts
  packages/events/src/router/event/event.actions.declare.test.ts
  packages/events/src/router/event/event.actions.notify.test.ts
  packages/events/src/router/event/event.actions.register.test.ts
  packages/events/src/router/event/event.actions.test.ts
  packages/events/src/router/event/event.actions.validate.test.ts
  packages/events/src/router/event/event.delete.test.ts
  packages/events/src/router/event/event.index.flag.test.ts
  packages/events/src/service/events/events.ts
  packages/events/src/storage/postgres/events/events.ts
  packages/events/src/tests/msw.ts
  packages/events/src/tests/postgres-migrations.sql
  packages/events/src/tests/utils.ts
  packages/migration/src/migrations/events/1755506672116_add-status-to-unique-constraint-in-event-actions.sql
  packages/user-mgnt/src/features/createUser/service.ts
  packages/user-mgnt/src/features/resetPassword/handler.ts
  packages/user-mgnt/src/features/updateUser/handler.ts
  packages/user-mgnt/src/features/usernameSMSReminderInvite/handler.ts
Labels: 💅 Waiting For Review

#10323 fix: give checkbox fields a default value
  packages/client/src/v2-events/components/forms/FormFieldGenerator/FormFieldGenerator.interaction.stories.tsx
  packages/client/src/v2-events/features/events/components/Output.stories.tsx
  packages/client/src/v2-events/features/events/registered-fields/Checkbox.stories.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistoryDialog/actionTypeSpecificContent/PrintCertificate.tsx
  packages/commons/src/events/FieldConfig.ts
  packages/events/src/router/event/event.config.test.ts
  packages/events/src/router/middleware/validate/validate.test.ts
Labels: ✅ Ready for merging
