Repository opencrvs/opencrvs-core, pull requests merged in 2025-07, with the labels that each got.

#9905 use database dump in tests
  packages/events/DATABASE.md
  packages/events/package.json
  packages/events/src/tests/postgres-migrations.sql
  packages/events/src/tests/postgres.ts
  packages/events/src/tests/setup.ts
Labels: 💅 Waiting For Review

#9881 [OCRVS-9839] Fix total number of corrections in performance dashboard updates when request correction event occurs
  packages/metrics/src/features/registration/handler.ts
Labels: 💅 Waiting For Review

#9925 fix: Enabled download button in my draft workqueue for different browser
  packages/client/src/v2-events/components/DownloadButton.tsx
  packages/client/src/v2-events/features/events/Search/SearchResult.tsx
Labels: 🔒 Keep e2e

#9845 (Events V2) Ensure advanced search scope is respected in search API
  docker-compose.yml
  packages/client/src/tests/__snapshots__/token-generator.test.ts.snap
  packages/client/src/tests/test-data-generators.ts
  packages/client/src/v2-events/features/events/Search/AdvancedSearch.tsx
  packages/client/src/v2-events/features/events/Search/utils.ts
  packages/commons/src/events/EventIndex.ts
  packages/commons/src/scopes.test.ts
  packages/commons/src/scopes.ts
  packages/data-seeder/src/users.ts
  packages/events/src/router/event/__snapshots__/event.search.test.ts.snap
  packages/events/src/router/event/event.search.test.ts
  packages/events/src/router/event/index.ts
  packages/events/src/router/middleware/authorization/index.ts
  packages/events/src/router/workqueue/index.ts
  packages/events/src/router/workqueue/workqueue.count.test.ts
  packages/events/src/service/indexing/indexing.test.ts
  packages/events/src/service/indexing/indexing.ts
  packages/events/src/service/indexing/query.ts
  packages/events/src/tests/utils.ts
Labels: ✅ Ready for merging, 🔒 Keep e2e, Phase 2 (Events v2)

#9911 fix: resolve dateOfEvent in outbox
  packages/client/src/v2-events/features/events/Search/SearchResult.tsx
  packages/client/src/v2-events/features/events/useEvents/outbox.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/create.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx
  packages/client/src/v2-events/layouts/EventOverview/index.tsx
  packages/commons/src/events/state/index.ts
Labels: 💅 Waiting For Review

#9932 fix: amend registration no in query param for quick search
  packages/client/src/v2-events/features/events/Search/utils.test.ts
  packages/client/src/v2-events/features/events/Search/utils.ts
  packages/client/src/v2-events/features/events/components/SearchToolbar.tsx
  packages/events/src/service/indexing/indexing.ts
Labels: 💅 Waiting For Review, Phase 2 (Events v2)

#9752 (Events v2) fix: remove draft status from when searching for all status
  packages/client/src/v2-events/features/events/Search/utils.test.ts
  packages/client/src/v2-events/features/events/Search/utils.ts
Labels: 💅 Waiting For Review, Phase 2 (Events v2)

#9973 fix: ignore health user when calculating certificate
  packages/client/src/v2-events/features/events/actions/print-certificate/Review.tsx
  packages/client/src/v2-events/utils.ts
Labels: 👌 LGTM, Phase 2 (Events v2)

#9984 Ocrvs 9311
  CHANGELOG.md
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/offline/reducer.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/tests/util.tsx
  packages/client/src/utils/validate.ts
Labels: 💅 Waiting For Review

#10017 fix: hide action menu buttons for correction-requested records
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenuStories/LocalRegistrarInteraction/CorrectionRequested.stories.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenuStories/RegistrationAgentInteraction/CorrectionRequested.stories.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/useActionMenuItems.ts
Labels: 💅 Waiting For Review, Phase 3 (Events v2)

#9997 chore: implement default action procedure on correction actions
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/commons/src/events/ActionType.ts
  packages/commons/src/events/state/availableActions.ts
  packages/commons/src/events/test.utils.ts
  packages/events/src/router/event/actions/index.ts
  packages/events/src/router/event/event.actions.correction.test.ts
  packages/events/src/router/event/event.get.test.ts
  packages/events/src/router/event/event.index.flag.test.ts
  packages/events/src/router/event/index.ts
  packages/events/src/router/middleware/validate/index.ts
  packages/events/src/tests/utils.ts
Labels: 💅 Waiting For Review, Phase 3 (Events v2)

#10047 Update migrations to remove special characters from role ids on generation
  CHANGELOG.md
  packages/migration/src/migrations/user-mgnt/20240628124653-remove-userroles.ts
  packages/migration/src/utils/role-helper.ts
Labels: 💅 Waiting For Review

#10084 fix(ocrvs-10029): date range selection for declaration fields
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/features/events/Search/SearchCriteriaPanel.stories.tsx
  packages/client/src/v2-events/features/events/Search/SearchCriteriaPanel.tsx
  packages/client/src/v2-events/features/events/Search/SearchResultIndex.tsx
  packages/client/src/v2-events/features/events/Search/TabSearch.tsx
  packages/client/src/v2-events/features/events/Search/utils.test.ts
  packages/client/src/v2-events/features/events/Search/utils.ts
  packages/client/src/v2-events/features/events/registered-fields/Data.tsx
  packages/client/src/v2-events/features/events/registered-fields/DateRangeField.tsx
  packages/commons/src/event-config/event-configuration.ts
  packages/commons/src/events/AdvancedSearchConfig.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/event.ts
  packages/events/src/router/middleware/validate/index.ts
  packages/events/src/service/indexing/query.ts
Labels: 💅 Waiting For Review
