Repository opencrvs/opencrvs-core, pull requests merged in 2025-03, with the labels that each got.

#8784 fix: set default value for QA_ENV
  packages/webhooks/src/environment.ts
Labels: ✅ Ready for merging

#8818 fix(ocrvs-8270): hide upload button in correction
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Labels: 💅 Waiting For Review

#8762 fix(ocrvs-8434): reset credentials flow
  packages/login/src/views/ResetCredentialsForm/SecurityQuestionForm.tsx
  packages/user-mgnt/src/features/verifyUser/handler.ts
Labels: 👌 LGTM, ✅ Ready for merging

#8765 fix(ocrvs-8688): consider CorrectionRequested as correction
  packages/client/src/views/CorrectionForm/utils.ts
Labels: 👌 LGTM, ✅ Ready for merging

#8787 fix(ocrvs-8586-2): set office location in all navigation
  packages/client/src/hooks/useHomePage.ts
  packages/client/src/views/Performance/Dashboard.tsx
  packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
Labels: ✅ Ready for merging

#8807 fix(ocrvs-8601): update minio regex to include full URL
  packages/commons/src/documents.ts
Labels: 💅 Waiting For Review, ✅ Ready for merging

#8806 fix(ocrvs-8516): disable workqueue actions when assigned to others
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
Labels: 💅 Waiting For Review, ✅ Ready for merging

#8430 fix: Add the isAgeInYearsBetween validator
  CHANGELOG.md
  packages/client/src/i18n/messages/validations.ts
  packages/client/src/utils/constants.ts
  packages/client/src/utils/validate.ts
Labels: 👌 LGTM

#8826 Tracking ID saved for events
  packages/client/src/v2-events/components/forms/inputs/FileInput/fixtures.ts
  packages/client/src/v2-events/features/events/actions/declare/Review.stories.tsx
  packages/client/src/v2-events/features/events/fixtures.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/create.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.test.tsx
  packages/commons/src/conditionals/conditionals.test.ts
  packages/commons/src/events/EventDocument.ts
  packages/commons/src/events/EventMetadata.ts
  packages/commons/src/events/state/index.test.ts
  packages/commons/src/events/state/index.ts
  packages/events/src/router/event/event.create.test.ts
  packages/events/src/service/deduplication/deduplication.test.ts
  packages/events/src/service/events/events.ts
  packages/events/src/service/indexing/indexing.ts
Labels: 🚀 Ready to deploy

#8825 fix(ocrvs-8505): create a new id field for corrections
  packages/config/src/handlers/dashboardQueries/defaultQueries.ts
  packages/migration/src/migrations/hearth/20250303113723-create-id-field-for-corrections.ts
Labels: 💅 Waiting For Review

#8794 fix(ocrvs-8615): allow deletion of attachments when updating
  packages/commons/src/fhir/transformers/index.ts
  packages/workflow/src/records/handler/update.test.ts
Labels: 💅 Waiting For Review, 👌 LGTM

#8810 v2 simplify workqueue
  packages/client/src/v2-events/components/forms/inputs/FileInput/fixtures.ts
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/utils.ts
  packages/commons/src/events/WorkqueueConfig.ts
  packages/commons/src/events/utils.ts
  packages/commons/src/fixtures/tennis-club-membership-event.ts
  packages/toolkit/package.json
Labels: 💅 Waiting For Review

#8814 Feat/scope based actions on declare
  packages/client/src/v2-events/README.md
  packages/client/src/v2-events/custom-api/index.ts
  packages/client/src/v2-events/features/events/EventSelection.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/AdditionalDetails/AdditionalDetails.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Onboarding/Onboarding.tsx
  packages/client/src/v2-events/features/events/actions/declare/Pages.tsx
  packages/client/src/v2-events/features/events/actions/declare/Review.interaction.stories.tsx
  packages/client/src/v2-events/features/events/actions/declare/Review.stories.tsx
  packages/client/src/v2-events/features/events/actions/declare/Review.tsx
  packages/client/src/v2-events/features/events/actions/declare/useReviewActionConfig.tsx
  packages/client/src/v2-events/features/events/actions/validate/index.tsx
  packages/client/src/v2-events/features/events/components/Pages.tsx
  packages/client/src/v2-events/features/events/components/Review.tsx
  packages/client/src/v2-events/features/events/useEvents/README.md
  packages/client/src/v2-events/features/events/useEvents/api.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/action.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/utils.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/create.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/delete.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/get.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/utils.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.test.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/layouts/form/FormHeader.tsx
  packages/client/src/v2-events/routes/config.tsx
  packages/client/src/v2-events/trpc.tsx
  packages/client/src/v2-events/utils.ts
  packages/commons/src/events/ActionDocument.ts
  packages/commons/src/events/test.utils.ts
  packages/events/src/service/events/events.ts
  packages/events/src/service/files/index.ts
Labels: 🚀 Ready to deploy

#8838 fix(ocrvs-8434-2): remove scope check for retrieveUserName
  packages/notification/src/config/routes.ts
Labels: 💅 Waiting For Review

#8837 fix(ocrvs-5350): ui issues
  packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
  packages/components/src/ComparisonListView/RowView.tsx
  packages/components/src/ListUser/ListUser.tsx
  packages/components/src/Table/Table.tsx
Labels: 💅 Waiting For Review

#8856 fix: add configurable date format
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/features/events/components/Output.tsx
  packages/client/src/v2-events/features/events/registered-fields/DateField.tsx
  packages/client/src/v2-events/features/events/registered-fields/index.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistory.tsx
Labels: 🚀 Ready to deploy

#8775 fix: disabled color in text input and dropdowns
  CHANGELOG.md
  packages/components/src/Select/Select.tsx
  packages/components/src/TextInput/TextInput.tsx
Labels: 💅 Waiting For Review

#8817 V2 rejection flow
  packages/client/src/v2-events/features/events/actions/declare/Review.rejection.stories.tsx
  packages/client/src/v2-events/features/events/actions/declare/Review.tsx
  packages/client/src/v2-events/features/events/actions/declare/useReviewActionConfig.tsx
  packages/client/src/v2-events/features/events/actions/register/Review.tsx
  packages/client/src/v2-events/features/events/components/Review.stories.tsx
  packages/client/src/v2-events/features/events/components/Review.tsx
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistoryModal.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/commons/src/events/ActionConfig.ts
  packages/commons/src/events/ActionDocument.ts
  packages/commons/src/events/ActionInput.ts
  packages/commons/src/events/ActionType.ts
  packages/commons/src/events/EventMetadata.ts
  packages/commons/src/events/state/index.ts
  packages/commons/src/events/test.utils.ts
  packages/events/src/router/event/event.actions.archive.test.ts
  packages/events/src/router/event/event.actions.reject.test.ts
  packages/events/src/router/event/index.ts
  packages/events/src/service/events/events.ts
  packages/events/src/tests/utils.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#8715 (Events V2) Extract search result
  packages/client/src/v2-events/features/events/AdvancedSearch/AdvancedSearch.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchModifier.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchResult.stories.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchResult.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchResultIndex.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/TabSearch.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/utils.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/routes/config.tsx
  packages/client/src/v2-events/routes/routes.ts
  packages/commons/src/conditionals/validate.ts
  packages/commons/src/events/AdvancedSearchConfig.ts
  packages/commons/src/events/EventIndex.ts
  packages/commons/src/events/test.utils.ts
  packages/commons/src/fixtures/tennis-club-membership-event.ts
  packages/events/src/router/event/event.search.test.ts
  packages/events/src/router/event/index.ts
  packages/events/src/service/indexing/indexing.ts
  packages/events/src/service/indexing/utils.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#8863 fix(v1.6.3) Fix mongo client connection errors and other performance enhancements
  packages/config/src/config/hearthClient.ts
  packages/config/src/handlers/locations/locationTreeSolver.test.ts
  packages/config/src/handlers/locations/locationTreeSolver.ts
  packages/config/src/server.ts
  packages/metrics/src/config/hearthClient.ts
  packages/metrics/src/features/certifications/service.ts
  packages/metrics/src/features/corrections/service.ts
  packages/metrics/src/features/locationStatistics/service.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/payments/service.ts
  packages/metrics/src/features/performance/viewRefresher.ts
  packages/metrics/src/features/registration/handler.test.ts
  packages/metrics/src/server.ts
  packages/metrics/src/utils/batchHelpers.ts
  packages/search/src/config/hearthClient.ts
  packages/search/src/features/records/service.ts
  packages/search/src/server.ts
Labels: 💅 Waiting For Review

#8852 fix(ocrvs-8516): prioritize downloaded assignment
  packages/client/graphql.schema.json
  packages/client/src/declarations/index.ts
  packages/client/src/search/queries.ts
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
  packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx
  packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx
  packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
  packages/client/src/views/PrintCertificate/utils.ts
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/queries.ts
  packages/client/src/views/SearchResult/SearchResult.tsx
  packages/commons/src/assignment.ts
  packages/commons/src/search.ts
  packages/gateway/src/features/registration/root-resolvers.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/assignment/service.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
Labels: 💅 Waiting For Review

#8844 feat: new menu icons
  packages/client/src/components/interface/Navigation.tsx
  packages/components/src/Icon/all-icons.ts
  packages/components/src/SideNavigation/LeftNavigation.stories.tsx
Labels: ✋ On Hold, [DONT USE] 🚀 Ready to deploy

#8910 feat: allow sending incomplete declaration based on proper scope
  packages/client/src/v2-events/features/events/actions/declare/Review.tsx
  packages/client/src/v2-events/features/events/actions/declare/useReviewActionConfig.tsx
  packages/client/src/v2-events/features/events/components/Review.tsx
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistory.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistoryModal.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/commons/src/events/ActionInput.ts
  packages/commons/src/events/state/index.ts
  packages/events/src/router/event/event.delete.test.ts
  packages/events/src/router/event/index.ts
Labels: 💅 Waiting For Review

#8975 fix: Filter metrics locations by office as other types cant have stats
  packages/config/src/handlers/locations/children.ts
  packages/config/src/handlers/locations/locationTreeSolver.ts
  packages/metrics/src/configApi.ts
  packages/metrics/src/features/certifications/service.ts
  packages/metrics/src/features/corrections/service.ts
  packages/metrics/src/features/declarationsStarted/service.ts
  packages/metrics/src/features/getTimeLogged/utils.ts
  packages/metrics/src/features/metrics/metricsGenerator.ts
  packages/metrics/src/features/payments/service.ts
Labels: 💅 Waiting For Review

#8977 printing pdf only if printCertificate action is successful
  packages/client/src/v2-events/features/events/actions/print-certificate/Pages.tsx
  packages/client/src/v2-events/features/events/actions/print-certificate/Review.tsx
  packages/client/src/v2-events/features/events/useCertificateTemplateSelectorFieldConfig.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
Labels: ✅ Ready for merging

#8951 (Events v2) chore: update event overview page
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/features/events/registered-fields/AdministrativeArea.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventSummary.tsx
  packages/client/src/v2-events/hooks/useFormDataStringifier.ts
  packages/client/src/v2-events/messages/utils.tsx
  packages/commons/src/events/FieldTypeMapping.ts
  packages/commons/src/events/state/index.ts
Labels: 💅 Waiting For Review

#9001 fix: filter out inactive locations in the Organisations menu
  CHANGELOG.md
  packages/client/src/views/Organisation/AdministrativeLevels.tsx
Labels: 💅 Waiting For Review

#8993 fix: separate fields for Farajaland and other countries
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/features/events/actions/declare/Pages.interaction.stories.tsx
  packages/client/src/v2-events/features/events/components/Review.stories.tsx
  packages/client/src/v2-events/features/events/registered-fields/Address.interaction.stories.tsx
  packages/client/src/v2-events/features/events/registered-fields/Address.stories.tsx
  packages/client/src/v2-events/features/events/registered-fields/Address.tsx
  packages/client/src/v2-events/features/events/registered-fields/SelectCountry.tsx
  packages/client/src/v2-events/utils.test.ts
  packages/commons/src/conditionals/validate-address.test.ts
  packages/commons/src/conditionals/validate.ts
  packages/commons/src/events/CompositeFieldValue.ts
  packages/commons/src/events/FieldTypeMapping.ts
  packages/commons/src/events/FieldValue.ts
  packages/commons/src/events/state/index.test.ts
  packages/events/src/router/event/event.actions.correction.test.ts
  packages/events/src/router/event/event.actions.declare.test.ts
  packages/events/src/router/event/event.actions.register.test.ts
  packages/events/src/router/event/event.actions.test.ts
  packages/events/src/router/event/event.actions.validate.test.ts
  packages/events/src/router/event/event.list.test.ts
  packages/events/src/router/event/event.search.test.ts
  packages/events/src/service/indexing/indexing.ts
Labels: 💅 Waiting For Review

#9034 fix: explicitly handle plain dates in certificate date handler
  CHANGELOG.md
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: ✅ Ready for merging

#9035 Fix typo in getLocationsByIdentifier() hearth url
  CHANGELOG.md
  packages/config/src/handlers/locations/utils.ts
Labels: 💅 Waiting For Review

#9072 Merge changes from pr 9035
  CHANGELOG.md
  packages/config/src/handlers/locations/utils.ts
Labels: 💅 Waiting For Review

#9073 Merge changes from pr 9034
  CHANGELOG.md
  packages/client/src/views/PrintCertificate/PDFUtils.ts
Labels: 💅 Waiting For Review

#9086 chore: add matches validator for a matching regex
  packages/commons/src/conditionals/conditionals.test.ts
  packages/commons/src/conditionals/conditionals.ts
Labels: 💅 Waiting For Review

#8865 ID Reader and QR Dialog Reader UI fixes
  packages/client/src/views/RecordAudit/History.tsx
  packages/client/src/views/Unlock/Unlock.tsx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/Dialog/Dialog.tsx
  packages/components/src/IDReader/readers/QRReader/InfoBox.tsx
  packages/components/src/IDReader/readers/QRReader/QRReader.tsx
  packages/components/src/LoadingBar/LoadingBar.tsx
  packages/components/src/PINKeypad/PINKeypad.tsx
  packages/components/src/SideNavigation/NavigationItem.tsx
  packages/components/src/fonts.ts
  packages/login/src/views/Common.tsx
  packages/login/src/views/StepOne/StepOneContainer.tsx
  packages/login/src/views/StepTwo/StepTwoContainer.tsx
Labels: 🔧Waiting for fixes, MOSIP

#8163 fix: multiple UI fixes in Action Menu / Dropdown
  packages/client/src/views/RecordAudit/ActionMenu.test.tsx
  packages/client/src/views/RecordAudit/ActionMenu.tsx
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/Button/Button.tsx
  packages/components/src/Dropdown/Dropdown.tsx
  packages/components/src/Spinner/Spinner.tsx
Labels: 🏥 Failing Tests, MOSIP
