Repository opencrvs/opencrvs-core, pull requests merged in 2025-02, with the labels that each got.

#8557 Events v2: use V2 events as default events when config.FEATURES.V2_EVENTS config variable is enabled
  packages/client/src/App.tsx
  packages/client/src/v2-events/README.md
  packages/client/src/v2-events/layouts/workqueues/index.tsx
  packages/client/src/v2-events/routes/config.tsx
  packages/client/src/v2-events/routes/routes.ts
  packages/client/typings/window.d.ts
Labels: 🚀 Ready to deploy

#8554 fix(ocrvs-8542): remove extra slash
  packages/gateway/src/features/fhir/service.ts
Labels: 💅 Waiting For Review

#8321 Events v2 collect certificate workflow boilerplate code
  debug-service-in-chrome.sh
  packages/client/.storybook/default-request-handlers.ts
  packages/client/.storybook/tennisClubMembershipCertifiedCertificateTemplate.ts
  packages/client/src/offline/selectors.ts
  packages/client/src/v2-events/STYLEGUIDE.md
  packages/client/src/v2-events/features/events/actions/correct/request/AdditionalDetails/AdditionalDetails.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Onboarding/Onboarding.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Pages.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Review.tsx
  packages/client/src/v2-events/features/events/actions/declare/Pages.tsx
  packages/client/src/v2-events/features/events/actions/declare/Review.tsx
  packages/client/src/v2-events/features/events/actions/print-certificate/Pages.tsx
  packages/client/src/v2-events/features/events/actions/print-certificate/PrintCertificate.stories.tsx
  packages/client/src/v2-events/features/events/actions/print-certificate/Review.tsx
  packages/client/src/v2-events/features/events/actions/print-certificate/index.ts
  packages/client/src/v2-events/features/events/actions/print-certificate/pdfUtils.ts
  packages/client/src/v2-events/features/events/actions/register/Pages.tsx
  packages/client/src/v2-events/features/events/components/Pages.tsx
  packages/client/src/v2-events/features/events/components/Review.tsx
  packages/client/src/v2-events/features/events/fixtures.ts
  packages/client/src/v2-events/features/events/useCertificateTemplateSelectorFieldConfig.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/action.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistory.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/hooks/useAppConfig.ts
  packages/client/src/v2-events/hooks/useLocations.ts
  packages/client/src/v2-events/hooks/usePrintableCertificate.ts
  packages/client/src/v2-events/layouts/form/FormHeader.tsx
  packages/client/src/v2-events/layouts/form/index.tsx
  packages/client/src/v2-events/layouts/form/utils.ts
  packages/client/src/v2-events/routes/config.tsx
  packages/client/src/v2-events/routes/routes.ts
  packages/client/tsconfig.json
  packages/commons/src/events/ActionConfig.ts
  packages/commons/src/events/ActionDocument.ts
  packages/commons/src/events/ActionInput.ts
  packages/commons/src/events/User.ts
  packages/commons/src/events/index.ts
  packages/commons/src/events/offline/CertificateConfig.ts
  packages/commons/src/events/offline/LanguageConfig.ts
  packages/commons/src/events/offline/index.ts
  packages/commons/src/events/state/index.ts
  packages/events/src/router/event/event.print.test.ts
  packages/events/src/router/event/index.ts
  packages/events/src/tests/generators.ts
  packages/toolkit/build.sh
Labels: 💅 Waiting For Review

#8536 fix(ocrvs-8340): provide unique keys to ToggleMenu
  packages/client/src/views/SysAdmin/Config/Systems/Systems.test.tsx
  packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
Labels: 👌 LGTM

#8548 fix(ocrvs-8526): add scopes to form data
  packages/client/src/tests/util.tsx
  packages/client/src/user/userReducer.ts
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx
  packages/commons/src/authentication.ts
Labels: 💅 Waiting For Review

#8551 fix(ocrvs-8525): sentForReview pagination mapping
  packages/client/src/views/OfficeHome/OfficeHome.tsx
Labels: 👌 LGTM, 🚀 Ready to deploy

#8562 fix: slow render of location options
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/forms/utils.ts
Labels: Tech, 💅 Waiting For Review, Team IET, Team CORE

#8618 Events v2: implement useStringifier for Address, Location and RadioGroup
  .eslintrc.js
  packages/client/.storybook/default-request-handlers.ts
  packages/client/src/v2-events/STYLEGUIDE.md
  packages/client/src/v2-events/components/forms/FormFieldGenerator.stories.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Summary/Summary.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/useCorrectionRequestData.ts
  packages/client/src/v2-events/features/events/components/Output.tsx
  packages/client/src/v2-events/features/events/fixtures.ts
  packages/client/src/v2-events/features/events/registered-fields/Address.stories.tsx
  packages/client/src/v2-events/features/events/registered-fields/Address.tsx
  packages/client/src/v2-events/features/events/registered-fields/Location.tsx
  packages/client/src/v2-events/features/events/registered-fields/RadioGroup.tsx
  packages/client/src/v2-events/features/events/useEventFormData.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx
  packages/client/src/v2-events/features/workqueues/utils.tsx
  packages/client/src/v2-events/hooks/useFormDataStringifier.ts
  packages/client/src/v2-events/hooks/useTransformer.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/utils.ts
Labels: 🚀 Ready to deploy

#8627 Feat/validation with zod
  packages/client/package.json
  packages/client/src/offline/actions.ts
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/components/forms/validation.ts
  packages/client/src/v2-events/features/events/components/Output.tsx
  packages/client/src/v2-events/features/events/fixtures.ts
  packages/commons/src/client.ts
  packages/commons/src/conditionals/conditionals.ts
  packages/commons/src/conditionals/validate.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/FieldType.ts
  packages/commons/src/events/FieldTypeMapping.ts
  packages/commons/src/events/FieldValue.ts
  packages/commons/src/events/TranslationConfig.ts
  packages/commons/src/events/index.ts
  packages/commons/src/fixtures/tennis-club-membership-event.ts
  packages/events/src/router/event/__snapshots__/event.actions.correction.test.ts.snap
  packages/events/src/router/event/__snapshots__/event.actions.declare.test.ts.snap
  packages/events/src/router/event/__snapshots__/event.actions.printCertificate.test.ts.snap
  packages/events/src/router/event/__snapshots__/event.actions.register.test.ts.snap
  packages/events/src/router/event/__snapshots__/event.actions.validate.test.ts.snap
  packages/events/src/router/event/event.actions.correction.test.ts
  packages/events/src/router/event/event.actions.declare.test.ts
  packages/events/src/router/event/event.actions.printCertificate.test.ts
  packages/events/src/router/event/event.actions.register.test.ts
  packages/events/src/router/event/event.actions.validate.test.ts
  packages/events/src/router/middleware/validate/index.ts
  packages/events/src/service/indexing/indexing.ts
  packages/toolkit/build.sh
  packages/toolkit/package.json
  packages/toolkit/src/conditionals/index.ts
Labels: 🚀 Ready to deploy

#8630 Events v2: add country name and logo on review page
  development-environment/summary.sh
  packages/client/.storybook/default-request-handlers.ts
  packages/client/src/offline/selectors.ts
  packages/client/src/tests/mock-offline-data.ts
  packages/client/src/v2-events/.eslintrc.js
  packages/client/src/v2-events/features/events/actions/correct/request/CorrectionRequest.stories.tsx
  packages/client/src/v2-events/features/events/components/Review.stories.tsx
  packages/client/src/v2-events/features/events/components/Review.tsx
  packages/client/src/v2-events/features/events/fixtures.ts
  setup.sh
Labels: 🚀 Ready to deploy

#8626 feat: upsert fields in workflow
  packages/commons/src/fhir/index.ts
  packages/workflow/src/records/handler/update-field.ts
Labels: 💅 Waiting For Review, 🚀 Ready to deploy

#8648 chore: Upgrade runners to Ubuntu 24.04 as latest LTS release (#7045)
  .github/workflows/auto-pr-to-release.yml
  .github/workflows/build-images-from-branch.yml
  .github/workflows/cd-manual-e2e.yml
  .github/workflows/close-stale-prs-after-30-days.yml
  .github/workflows/create-backup-data-action.yml
  .github/workflows/deploy-to-feature-environment.yml
  .github/workflows/lint-and-test.yml
  .github/workflows/mirror-trivy-db.yml
  .github/workflows/on-label-added-for-pr.yml
  .github/workflows/publish-release.yml
  .github/workflows/publish-toolkit-to-npm.yml
  .github/workflows/reset-env-action.yml
  .github/workflows/security-scans.yml
  .github/workflows/storybook-deploy.yml
  .github/workflows/trigger-e2e.yml
  CHANGELOG.md
Labels: 🚀 Ready to deploy

#8656 fix: review page crashing checking .verified status
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/workflow/src/records/handler/update-field.test.ts
  packages/workflow/src/records/handler/update-field.ts
Labels: 🚀 Ready to deploy

#8110 Colour refactored to use Alta's
  packages/client/index.html
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/components/form/IDVerification/StatusIcon.tsx
  packages/client/src/views/PrintRecord/Header.tsx
  packages/client/src/views/PrintRecord/PrintRecord.tsx
  packages/client/src/views/PrintRecord/utils.ts
  packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
  packages/components/package.json
  packages/components/src/Alert/Alert.tsx
  packages/components/src/Bar/Bar.tsx
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/Button/Button.styles.ts
  packages/components/src/CopyButton/CopyButton.tsx
  packages/components/src/Legend/Legend.tsx
  packages/components/src/Legend/index.ts
  packages/components/src/LoadingBar/LoadingBar.tsx
  packages/components/src/Pill/Pill.tsx
  packages/components/src/Table/Table.tsx
  packages/components/src/ToggleIcon/ToggleIcon.stories.tsx
  packages/components/src/VerticalBar/VerticalBar.tsx
  packages/components/src/VerticalBar/components/AxisTick.tsx
  packages/components/src/buttons/Action.tsx
  packages/components/src/buttons/LinkButton.tsx
  packages/components/src/buttons/SecondaryButton.tsx
  packages/components/src/chart-datapoint-types.ts
  packages/components/src/colors.ts
  packages/components/src/index.ts
  packages/components/stories/colors.stories.mdx
  packages/login/src/common/LoginBackgroundWrapper.tsx
Labels: 🚀 Ready to deploy

#8553 feat: file uplaod with options
  packages/client/.storybook/default-request-handlers.ts
  packages/client/.storybook/main.ts
  packages/client/.storybook/preview.tsx
  packages/client/package.json
  packages/client/public/mockServiceWorker.js
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/DocumentListPreview.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/DocumentPreview.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/DocumentUploaderWithOption.stories.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/DocumentUploaderWithOption.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/File.stories.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/FileInput.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/SimpleDocumentUploader.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/SingleDocumentPreview.tsx
  packages/client/src/v2-events/components/forms/inputs/FileInput/fixtures.ts
  packages/client/src/v2-events/features/events/actions/print-certificate/pdfUtils.ts
  packages/client/src/v2-events/features/events/registered-fields/Select.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.test.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/features/files/cache.ts
  packages/client/src/v2-events/features/files/useFileUpload.ts
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/features/workqueues/utils.tsx
  packages/client/src/v2-events/trpc.tsx
  packages/commons/src/documents.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/FieldType.ts
  packages/commons/src/events/FieldTypeMapping.ts
  packages/commons/src/events/FieldValue.ts
  packages/commons/src/events/utils.ts
  packages/documents/src/config/routes.ts
  packages/events/src/service/indexing/indexing.ts
  packages/events/src/storage/elasticsearch.ts
  packages/gateway/src/config/routes.ts
  packages/toolkit/package.json
Labels: 💅 Waiting For Review

#8664 feat: implement file exlporer
  packages/client/.storybook/default-request-handlers.ts
  packages/client/src/v2-events/components/forms/inputs/FileInput/File.stories.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Review.tsx
  packages/client/src/v2-events/features/events/actions/declare/Review.tsx
  packages/client/src/v2-events/features/events/actions/register/Review.tsx
  packages/client/src/v2-events/features/events/components/Review.tsx
Labels: 💅 Waiting For Review

#8671 Chore: Improve CI error scenarios
  .github/workflows/deploy-to-feature-environment.yml
  .github/workflows/lint-and-test.yml
  packages/client/.storybook/default-request-handlers.ts
  packages/client/.storybook/main.ts
  packages/client/package.json
  packages/client/src/v2-events/features/events/actions/correct/request/CorrectionRequest.stories.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Onboarding/Onboarding.stories.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/Onboarding/Onboarding.tsx
  packages/client/src/v2-events/features/events/actions/correct/request/index.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.stories.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/features/workqueues/router.tsx
  yarn.lock
Labels: 🚀 Ready to deploy

#8685 Events v2: apply dot to underscore separator formatting to messages from client.csv
  packages/client/.storybook/default-request-handlers.ts
  packages/client/src/v2-events/components/forms/inputs/FileInput/File.stories.tsx
  packages/client/src/v2-events/features/events/actions/register/index.ts
  packages/client/src/v2-events/features/workqueues/utils.test.tsx
  packages/client/src/v2-events/features/workqueues/utils.tsx
  packages/events/src/environment.ts
  packages/events/src/storage/elasticsearch.ts
Labels: 🚀 Ready to deploy

#8717 Events v2: client-side feature flag for showing Events v2 as the default view
  packages/client/src/App.tsx
  packages/client/src/config.ts
  packages/client/src/v2-events/.eslintrc.js
  packages/client/src/v2-events/routes/routes.ts
Labels: 🚀 Ready to deploy

#8541 fix(ocrvs-8437): explicitly check for code
  packages/gateway/src/graphql/data-source.ts
Labels: 👌 LGTM

#8576 fix(ocrvs-8505): sync dashboard queries from countryconfig
  packages/config/src/handlers/dashboardQueries/dashboardQueries.ts
  packages/config/src/handlers/dashboardQueries/defaultQueries.ts
Labels: 👌 LGTM

#8581 fix(ocrvs-8568): make subject name optional for notification
  packages/notification/src/features/sentForUpdates/handler.ts
  packages/notification/src/features/utilsForPartiallyCompletedRecord.ts
Labels: 👌 LGTM

#8643 fix(ocrvs-8444): make signature required
  packages/client/src/forms/user/fieldDefinitions/createUser.ts
Labels: 💅 Waiting For Review

#8713 fix(ocrvs-8678): show title on mobile
  packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
Labels: ✅ Ready for merging

#8718 fix: notify country config about the event `sent-for-approval`
  packages/workflow/src/records/handler/validate.test.ts
  packages/workflow/src/records/handler/validate.ts
Labels: 💅 Waiting For Review

#8591 fix(ocrvs-8582): correction flow back button
  packages/client/src/components/DraftLoadingSpinner.tsx
  packages/client/src/views/CorrectionForm/CorrectionForm.tsx
  packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
  packages/client/src/views/CorrectionForm/VerifyCorrector.tsx
  packages/client/src/views/PrintCertificate/usePrintableCertificate.ts
  packages/client/src/views/RegisterForm/RegisterForm.tsx
Labels: ✅ Ready for merging, 🚀 Ready to deploy

#8594 fix(ocrvs-8587): stats block in performance page
  docker-compose.yml
  packages/metrics/src/api.ts
  packages/user-mgnt/src/config/routes.ts
  packages/user-mgnt/src/environment.ts
  packages/user-mgnt/src/features/countUsersByLocation/service.ts
Labels: ✅ Ready for merging

#8597 fix(ocrvs-8586): use primary office as the default locationId
  packages/client/src/components/interface/Navigation.tsx
Labels: ✅ Ready for merging

#8603 fix(ocrvs-8561): only show field level errors in print forms
  packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx
  packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
Labels: ✅ Ready for merging

#8633 fix(ocrvs-8598): cater sources of registrations to scopes
  packages/client/src/views/SysAdmin/Performance/ApplicationSourcesReport.tsx
  packages/gateway/src/features/user/root-resolvers.ts
Labels: ✅ Ready for merging

#8647 fix(ocrvs-8566): only store certificateTemplateId
  packages/client/src/forms/register/mappings/event-specific-fields/birth/query/registration-mappings.ts
  packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueFormForOthers.tsx
Labels: ✅ Ready for merging

#8659 fix(ocrvs-8640): add fallback options for anchor position
  packages/components/src/Dropdown/Dropdown.tsx
Labels: ✅ Ready for merging

#8660 fix(ocrvs-8650): disable unassign action when offline
  packages/client/src/views/RecordAudit/ActionMenu.tsx
Labels: ✅ Ready for merging

#8696 fix(ocrvs-8365): handle correcting informant relationship
  packages/commons/src/fhir/transformers/index.ts
  packages/workflow/src/records/handler/correction/correction.test.ts
  packages/workflow/test/mocks/correctBirthRecord.ts
Labels: ✅ Ready for merging

#8708 fix(ocrvs-8602): check flag before sending notification
  packages/workflow/src/records/handler/reject.ts
  packages/workflow/src/server.ts
Labels: ✅ Ready for merging

#8710 fix(ocrvs-8516): determine assignment based on creation time
  packages/client/graphql.schema.json
  packages/client/src/search/queries.ts
  packages/client/src/utils/gateway-deprecated-do-not-use.d.ts
  packages/client/src/utils/gateway.ts
  packages/client/src/views/DataProvider/birth/queries.ts
  packages/client/src/views/DataProvider/death/queries.ts
  packages/client/src/views/DataProvider/marriage/queries.ts
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/PrintCertificate/utils.ts
  packages/client/src/views/RecordAudit/RecordAudit.tsx
  packages/client/src/views/RecordAudit/queries.ts
  packages/commons/src/assignment.ts
  packages/commons/src/search.ts
  packages/gateway/src/features/registration/type-resolvers.ts
  packages/gateway/src/features/search/schema.graphql
  packages/gateway/src/features/search/type-resolvers.ts
  packages/gateway/src/graphql/schema.d.ts
  packages/gateway/src/graphql/schema.graphql
  packages/search/src/elasticsearch/utils.ts
  packages/search/src/features/registration/assignment/service.ts
  packages/search/src/features/registration/birth/service.ts
  packages/search/src/features/registration/death/service.ts
  packages/search/src/features/registration/marriage/service.ts
Labels: ✅ Ready for merging

#8711 fix(ocrvs-8550): make location fields optional
  packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
Labels: ✅ Ready for merging

#8599 🍒 Merge changes from PR #8562 to develop
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/register/mappings/query/field-mappings.ts
  packages/client/src/forms/utils.ts
Labels: ✅ Ready for merging

#8702 Implement default value for simple fields (string, number, boolean fields), add FieldType.NUMBER
  packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx
  packages/client/src/v2-events/components/forms/utils.ts
  packages/client/src/v2-events/features/events/components/Output.tsx
  packages/client/src/v2-events/features/events/fixtures.ts
  packages/client/src/v2-events/features/events/registered-fields/Address.stories.tsx
  packages/client/src/v2-events/features/events/registered-fields/Address.tsx
  packages/client/src/v2-events/features/events/registered-fields/Checkbox.tsx
  packages/client/src/v2-events/features/events/registered-fields/Number.tsx
  packages/client/src/v2-events/features/events/registered-fields/index.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/action.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/FieldType.ts
  packages/commons/src/events/FieldTypeMapping.ts
  packages/commons/src/events/FieldValue.ts
  packages/commons/src/fixtures/tennis-club-membership-event.ts
  packages/events/src/service/indexing/indexing.ts
  packages/toolkit/package.json
Labels: ✅ Ready for merging, 🚀 Ready to deploy

#8703 fix: console warnings and errors
  packages/client/src/App.tsx
  packages/client/src/components/form/FormFieldGenerator.test.tsx
  packages/client/src/index.tsx
  packages/client/src/tests/util.tsx
  packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx
  packages/client/src/views/RecordAudit/ActionMenu.tsx
  packages/components/package.json
  packages/components/src/Dropdown/Dropdown.tsx
  packages/components/src/buttons/Button.tsx
  packages/components/src/icons/Cross.tsx
  packages/login/src/App.tsx
  packages/login/src/index.tsx
  yarn.lock
Labels: ✅ Ready for merging

#8770 fix(ocrvs-8743): check if array before reducing
  packages/migration/src/migrations/hearth/20250225173145-align-family-prop-in-name.ts
Labels: 💅 Waiting For Review

#8786 fix(ocrvs-8778): update translation for no drafts
  packages/client/src/i18n/messages/workQueue.ts
Labels: 💅 Waiting For Review

#8744 fix: link button redirect issue
  packages/client/src/components/form/http.ts
Labels: 👌 LGTM, ✅ Ready for merging

#8790 Disable react-router v7_startTransition, to fix problems with routing
  packages/client/package.json
  packages/client/src/App.tsx
  yarn.lock
Labels: 🚀 Ready to deploy

#8761 Events v2 demo environment
  packages/client/nginx.conf
  packages/client/src/v2-events/features/events/actions/delete/index.tsx
  packages/client/src/v2-events/features/events/actions/validate/index.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
Labels: 🚀 Ready to deploy

#8667 fix(v1.6.3): Improve performance when location level numbers are high
  docker-compose.yml
  packages/commons/src/fhir/location.ts
  packages/config/package.json
  packages/config/src/environment.ts
  packages/config/src/handlers/locations/children.test.ts
  packages/config/src/handlers/locations/children.ts
  packages/config/src/handlers/locations/hierarchy.test.ts
  packages/config/src/handlers/locations/hierarchy.ts
  packages/config/src/handlers/locations/locationTreeSolver.test.ts
  packages/config/src/handlers/locations/locationTreeSolver.ts
  packages/config/src/services/hearth.ts
  yarn.lock
Labels: 💅 Waiting For Review

#8772 Events v2: Update tRPC
  packages/client/package.json
  packages/client/src/v2-events/README.md
  packages/client/src/v2-events/features/events/actions/delete/index.tsx
  packages/client/src/v2-events/features/events/useEventConfiguration.ts
  packages/client/src/v2-events/features/events/useEventFormNavigation.tsx
  packages/client/src/v2-events/features/events/useEvents/api.ts
  packages/client/src/v2-events/features/events/useEvents/outbox.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/action.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/create.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/delete.ts
  packages/client/src/v2-events/features/events/useEvents/procedures/get.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.test.tsx
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/hooks/useLocations.ts
  packages/client/src/v2-events/hooks/useUsers.ts
  packages/client/src/v2-events/routes/config.tsx
  packages/client/src/v2-events/trpc.tsx
  packages/events/package.json
  yarn.lock
Labels: 🚀 Ready to deploy
