Repository opencrvs/opencrvs-core, pull requests merged in 2025-05, with the labels that each got.

#9357 Redirect user from advanced search to advanced search result page
  packages/client/src/v2-events/features/events/AdvancedSearch/AdvancedSearch.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchModifier.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchResult.stories.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchResult.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchResultIndex.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/TabSearch.tsx
  packages/client/src/v2-events/features/events/actions/register/Review.interaction.stories.tsx
  packages/client/src/v2-events/features/events/registered-fields/DateField.stories.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/client/src/v2-events/routes/config.tsx
  packages/client/src/v2-events/utils.ts
  packages/commons/src/conditionals/validate.ts
  packages/commons/src/fixtures/tennis-club-membership-event.ts
  packages/commons/src/workqueues/WorkqueueConfig.ts
  packages/commons/src/workqueues/defaultColumns.ts
  packages/commons/src/workqueues/index.ts
Labels: 💅 Waiting For Review

#9343 Improve relevance of quick searches using name
  CHANGELOG.md
  packages/search/src/features/search/search.test.ts
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/utils.test.ts
  packages/search/src/features/search/utils.ts
Labels: 💅 Waiting For Review

#9161 (Events V2) Create endpoint for advanced search #8427
  packages/client/src/v2-events/components/forms/FormFieldGenerator/utils.ts
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchResult.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/SearchResultIndex.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/TabSearch.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/utils.ts
  packages/client/src/v2-events/features/events/fixtures.ts
  packages/client/src/v2-events/features/events/useEvents/useEvents.ts
  packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistory.tsx
  packages/client/src/v2-events/features/workqueues/Workqueue.tsx
  packages/commons/src/conditionals/conditionals.test.ts
  packages/commons/src/conditionals/conditionals.ts
  packages/commons/src/event-config/event-configuration.ts
  packages/commons/src/events/ActionDocument.ts
  packages/commons/src/events/AdvancedSearchConfig.ts
  packages/commons/src/events/EventConfig.ts
  packages/commons/src/events/EventIndex.ts
  packages/commons/src/events/EventMetadata.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/event.ts
  packages/commons/src/events/field.ts
  packages/commons/src/events/index.ts
  packages/commons/src/events/scopes.ts
  packages/commons/src/events/state/index.ts
  packages/commons/src/events/test.utils.ts
  packages/commons/src/events/utils.test.ts
  packages/commons/src/events/utils.ts
  packages/commons/src/field-config/field-configuration.test.ts
  packages/commons/src/field-config/field-configuration.ts
  packages/commons/src/fixtures/tennis-club-membership-event.ts
  packages/events/src/router/event/actions/index.ts
  packages/events/src/router/event/event.actions.test.ts
  packages/events/src/router/event/event.search.test.ts
  packages/events/src/router/event/index.ts
  packages/events/src/service/deduplication/deduplication.test.ts
  packages/events/src/service/events/actions/approve-correction.ts
  packages/events/src/service/events/actions/assign.ts
  packages/events/src/service/events/actions/reject-correction.ts
  packages/events/src/service/events/actions/unassign.ts
  packages/events/src/service/events/actions/validate.ts
  packages/events/src/service/events/events.ts
  packages/events/src/service/indexing/indexing.test.ts
  packages/events/src/service/indexing/indexing.ts
  packages/events/src/service/indexing/query.ts
  packages/events/src/service/indexing/utils.ts
Labels: 💅 Waiting For Review

#9417 Release automation: automation pipeline for bootstrapping a new release(ocrvs-9396)
  .github/workflows/init-release.yml
Labels: 🛣️ Infrastructure

#9491 fix: Remove PractitionerRole from Hearth bundle on every view and download
  CHANGELOG.md
  packages/migration/src/migrations/hearth/20250508091242-remove-duplicate-practitioner-role.ts
  packages/workflow/src/records/state-transitions.ts
Labels: 🚀 Ready to deploy

#9326 refactor: remove the dob limit under death declaration form
  CHANGELOG.md
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/utils/validate.ts
  packages/components/src/DateField/DateField.tsx
  yarn.lock
Labels: 💅 Waiting For Review

#9389 Add warning/error message on search for less than one parameter
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/views/SearchResult/AdvancedSearch.test.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
Labels: 💅 Waiting For Review

#9474 Extend advanced search configuration for new input kinds
  packages/client/src/v2-events/components/forms/FormFieldGenerator/GeneratedInputField.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/TabSearch.tsx
  packages/client/src/v2-events/features/events/AdvancedSearch/utils.ts
  packages/client/src/v2-events/features/events/registered-fields/DateRangeField.stories.tsx
  packages/client/src/v2-events/features/events/registered-fields/DateRangeField.tsx
  packages/client/src/v2-events/messages/utils.tsx
  packages/commons/src/client.ts
  packages/commons/src/event-config/event-configuration.ts
  packages/commons/src/events/AdvancedSearchConfig.ts
  packages/commons/src/events/FieldConfig.ts
  packages/commons/src/events/FieldType.ts
  packages/commons/src/events/FieldTypeMapping.ts
  packages/commons/src/events/FieldValue.ts
  packages/commons/src/events/state/index.ts
  packages/commons/src/field-config/field-configuration.test.ts
  packages/commons/src/field-config/field-configuration.ts
  packages/events/src/service/indexing/indexing.ts
Labels: 💅 Waiting For Review

#9408 Merge release v1.7.2 into 1.8.0
  CHANGELOG.md
  packages/client/src/components/DateRangePicker.tsx
  packages/client/src/components/form/FormFieldGenerator.tsx
  packages/client/src/forms/index.ts
  packages/client/src/forms/utils.ts
  packages/client/src/i18n/messages/errors.ts
  packages/client/src/tests/languages.json
  packages/client/src/user/userReducer.ts
  packages/client/src/utils/validate.ts
  packages/client/src/views/CorrectionForm/utils.ts
  packages/client/src/views/OfficeHome/myDrafts/MyDrafts.test.tsx
  packages/client/src/views/OfficeHome/queries.ts
  packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx
  packages/client/src/views/OfficeHome/sentForReview/SentForReview.test.tsx
  packages/client/src/views/Organisation/AdministrativeLevels.tsx
  packages/client/src/views/RecordAudit/RecordAudit.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx
  packages/client/src/views/RegisterForm/review/ReviewSection.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.test.tsx
  packages/client/src/views/SearchResult/AdvancedSearch.tsx
  packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx
  packages/commons/src/authentication.ts
  packages/commons/src/scopes.ts
  packages/components/src/DateField/DateField.tsx
  packages/components/src/TimeField/TimeField.tsx
  packages/config/src/handlers/forms/validation.ts
  packages/config/src/handlers/locations/hierarchy.test.ts
  packages/data-seeder/src/users.ts
  packages/gateway/src/features/user/root-resolvers.test.ts
  packages/gateway/src/features/user/root-resolvers.ts
  packages/migration/src/migrations/hearth/20250508091242-remove-duplicate-practitioner-role.ts
  packages/search/src/features/search/search.test.ts
  packages/search/src/features/search/service.test.ts
  packages/search/src/features/search/service.ts
  packages/search/src/features/search/utils.test.ts
  packages/search/src/features/search/utils.ts
  packages/toolkit/package.json
  packages/workflow/src/records/state-transitions.ts
  packages/workflow/src/test/utils.ts
  yarn.lock
Labels: ✅ Ready for merging

#9649 fix: use helper to find the role
  CHANGELOG.md
  packages/gateway/src/features/registration/type-resolvers.ts
Labels: 💅 Waiting For Review

#9662 fix: Add Elasticsearch images to our own registry
  .github/workflows/mirror-docker-images.yml
Labels: Bug
